video-dev/hls.js

API.md
src/controller/buffer-controller.js
src/hls.js

Here's a fix proposal for issue #31, to be used as a basis for discussion (need a little bit of cleaning if this approach is accepted)

Proposal for issue #31

---

package.json
src/loader/playlist-loader.js
src/utils/url.js
tests/unit/util/url.js

Improved playlist url parsing

---

package.json
src/controller/buffer-controller.js
src/utils/binary-search.js
tests/unit/utils/binary-search.js

Also added unit tests for the `BinarySearch.search()` helper.

Implemented dichotomic fragment search

---

src/controller/buffer-controller.js
src/controller/level-controller.js
src/demux/demuxer-inline.js
src/demux/demuxer-worker.js
src/demux/demuxer.js
src/demux/tsdemuxer.js
src/errors.js
src/events.js
src/hls.js
src/loader/fragment-loader.js
src/loader/key-loader.js
src/loader/playlist-loader.js
src/utils/xhr-loader.js

Finally, I have implemented support for AES-128 decrypt. It also works in web worker. Final solution solves Decrypting data before the probe() function. More features/fix at commits comments.

Add support for AES-128 decrypting

---

README.md

It is only "cosmetic" change at README.md :-)

Add tag #EXT-X-KEY to "Supported M3U8 tags"

---

src/controller/abr-controller.js

Currently, it stays on the level indefinitely.

reset nextAutoLevel once level has been loaded

---

.jshintrc
src/crypt/aes128-decrypter.js
src/crypt/decrypter.js
src/demux/demuxer.js

See individual commits for actual changes.

Improve decryption implementation

---

src/demux/aacdemuxer.js
src/demux/demuxer-inline.js
src/demux/id3.js

successfully tested on one playlist
need more coverage, and sample playlists, but merging upstream should speed up AAC ES support

AAC elementary stream demuxer

---

src/demux/aacdemuxer.js
src/demux/tsdemuxer.js

Only "small" fix of audio sample rate units :-)

Fix audio sample rate units (kHz -> Hz)

---

API.md
src/controller/mse-media-controller.js
src/errors.js

Added BUFFER_STALLED_ERROR

---

README.md

Noticed that my editor also removed trailing whitespace, if that is not alright then let me know and I will update the PR.

Added npm badge so we know what version is published

---

README.md

As quick reference, as this comes up in the bug tracker quite often.

Document CORS requirement

---

package.json
src/hls.js

Set to the package.json version at build time.
Closes #348

Add "version" property

---

API.md

Use jsdelivr url in docs

---

src/demux/tsdemuxer.js

This is how existing video players such as VLC and ffplay work.

Choose the first video stream in multi stream containers.

---

src/utils/url.js
tests/unit/utils/url.js

And also the case where the base url doesn't contain a protocol.
Refs: #424

URL parser now handles base urls which don't contain a domain

---

src/controller/buffer-controller.js
src/controller/stream-controller.js

check for pending seek command after having loaded last fragment + Additional log lines for seeking and media dettaching

Fix possible infinite buffering + log lines

---

src/controller/buffer-controller.js

Same as https://github.com/dailymotion/hls.js/pull/451 but cherry picked onto 0.5 branch.

Update mediaelement.duration with duration from manifest (v0.5.x)

---

API.md
src/loader/playlist-loader.js
tests/unit/loader/playlist-loader.js

Add "version" and "type" to level object (master)

---

API.md
src/loader/playlist-loader.js
tests/unit/loader/playlist-loader.js

Add type and version to level object

---

package.json

Update package.json 'main' to './dist/hls.js'

---

API.md

Plus some rudimentary punctuation etc. corrections in their
documentation.

List Ewma abr config params directly under Fine Tuning

---

API.md

document second param to xhrSetup callback function

update docs for xhrSetup

---

demo/index.html

Add a dropdown-list to change the version of hls.js in the demo-page

---

API.md
src/controller/stream-controller.js
src/hls.js

please refer to issue https://github.com/dailymotion/hls.js/issues/630

compute and store actual live position

---

src/controller/abr-controller.js

Add additional check for maxAutoLevel not to exceed available levels.

Fix for #672

---

.travis.yml
package.json
tests/functional/auto/hlsjs.html
tests/functional/auto/hlsjs.js

setup Travis CI using Sauce Labs and Sauce Connect.

---

tests/functional/auto/hlsjs.html
tests/functional/auto/hlsjs.js

Also use promises with assertion library.
This makes creating more tests with different stream urls easier and keeps the tests in the same file.

Make html more boilerplate and move test logic to js test file

---

.travis.yml
tests/functional/auto/hlsjs.js
tests/functional/streams.json

Add travis job per functional test stream

---

src/controller/stream-controller.js

When main has audio drops to main audio when seeking.
note: this.audioTrackType on onFragParsingData is undefined

763-Alternative_audio_with_main_with_audio

---

API.md
src/controller/abr-controller.js
src/hls.js

Introducing minAutoBitrate variable that is preventing AutoBitrate
calculator from dropping lower than a minimal value in bytes.

[Feature] Adding minimal auto-bitrate value #775

---

src/hls.js

It is possible that window.MediaSource does not exist. Instead should also check for window.WebKitMediaSource

check for window.WebKitMediaSource

---

scripts/travis.sh

If sauce labs has an error hopefully waiting a bit before retrying might help.

functional tests: add delay between attempts

---

src/utils/cea-608-parser.js

Fix for "Cannot read property 'cueStartTime' of undefined" error after PR https://github.com/dailymotion/hls.js/pull/802

Fix cueStartTime error

---

src/loader/playlist-loader.js
src/utils/attr-list.js

Extract regex to constants

---

src/controller/buffer-controller.js

Fix MPEG audio only media source duration.

Fix audio mpeg duration

---

package.json
tests/functional/auto/hlsjs.html
tests/functional/auto/hlsjs.js

Attempts to fix errors like https://saucelabs.com/jobs/9d1712e8df32462889cc8686a0038e61 where I think the web server hasn't initialised in time, by reloading the page until it gets the proper one.

functional tests: try reloading page on error

---

tests/functional/auto/hlsjs.js

Add name to capabilities to make it easier to browse on sauce labs

---

.travis.yml

Hopefully will help with debugging

Output sauce connect log on travis

---

.travis.yml
src/crypt/decrypter.js
src/demux/demuxer-inline.js
src/demux/demuxer-worker.js
src/demux/demuxer.js

as its name state, perform AES decryption in webworker

decrypt in webworker

---

src/controller/buffer-controller.js

Right now this doesn't provide helpful info. Just making the object inspectable.

improving debug message

---

.jshintrc
package.json
src/controller/subtitle-stream-controller.js
src/controller/subtitle-track-controller.js
src/controller/timeline-controller.js
src/errors.js
src/events.js
src/hls.js
src/loader/playlist-loader.js
src/utils/cea-608-parser.js
src/utils/cues.js
src/utils/vttcue.js
src/utils/vttparser.js
src/utils/webvtt-parser.js

Although this PR is large, it makes sense to bundle because several changes to 608/708 were made in response to webVTT.
7d8d55d 913e965 5699e6b 1bacc5b 6af63bd 4f40977 15dadc2 7b3fda0 200de62 8e9bde8 df21e32 5c64a10 7b2d20d f71d208 a798f74

Webvtt support, along with 608/708 enhancements & bugfixes

---

.gitignore
doc/API.md

- Add more information about loader use
- Add table of contents

Improve API Documentation

---

doc/API.md

Add `js` lang type to example code in API.md

API.md : add syntax highlighting to example code

---

package.json
src/loader/playlist-loader.js

See https://github.com/tjenkinson/url-toolkit/releases/tag/v2.0.0

Update url-toolkit to v2

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
LICENSE
README.md
bower.json
demo/index.html
package.json
src/controller/audio-stream-controller.js
src/controller/buffer-controller.js
src/controller/stream-controller.js
src/loader/playlist-loader.js

Updates following hls.js transfer from dailymotion to video-dev organization

---

src/controller/timeline-controller.js

https://github.com/dailymotion/hls.js/issues/1032

Fix for issue 1032: clear outdated text tracks on manifest loading

---

README.md

looks like the links syntax is incorrect

fix links on README

---

README.md
src/controller/stream-controller.js
src/hls.js

Ensure url is absolute in `loadSource()`. Fixes #1063
~~[] new unit / functional tests have been added (whenever applicable)~~
~~[] API or design changes are documented in API.md~~

Convert to absolute url in loadSource()

---

doc/API.md
src/controller/abr-controller.js
src/controller/stream-controller.js

Bandwidth estimate added to FRAG_BUFFERED event as data.stats.bwEstimate

Bandwidth estimate added to FRAG_BUFFERED event data stats

---

doc/design.md

Recently, GitHub update own Markdown rendering engine and the spec.
- [A formal spec for GitHub Flavored Markdown | GitHub Engineering](https://githubengineering.com/a-formal-spec-for-github-markdown/ "A formal spec for GitHub Flavored Markdown | GitHub Engineering")
This PR follow up the spec.

Format design.md

---

doc/API.md

`startFragPrefech` -> `startFragPrefetch`

Fix typo in API.md

---

README.md

added declaration file info to readme

---

doc/API.md
src/events.js

Added missing events to `Runtime Events` section of API.md.  Cleaned up punctuation and spacing in events.js.

Updated API documentation

---

src/remux/mp4-remuxer.js

This PR implements a check to ensure we do not insert a silent audio gap larger than the length of a segment. If the gap would exceed this length, it is not added -  large differences can lead to gaps so large they crash the browser or inflate duration by hours.
Test stream: //playertest.longtailvideo.com/adaptive/id3-timestamp-addition/test_list.m3u8

Implement a maximum silent frame duration of 10 seconds

---

src/event-handler.js

Hi, 
I'm trying to learn the code-base so I'm going through it, I'm opening some PRs for some code clean up if that's OK :) 
(That's what I recommend to people who contribute to projects I'm involved in like Node or bluebird)

Replace `.bind` with forEach arg

---

src/controller/subtitle-track-controller.js

Hello.   I was noticing over time the SubtitleTrackController building up quite a bit of memory usage.  In looking at the code I have noticed a TODO to remove event listeners on the textTrack objects.  This merge request is to handle that TODO.
I am fairly new to this project so I apologize if anything is off here.  Please do let me know if this can be improved in any way and I will certainly do so.  Thanks!
- [X ] changes have been done against master branch, and PR does not conflict

handled TODO: Remove event listeners

---

src/controller/abr-controller.js

Declare class variables ahead of time, which is more friendly to VMs. It's not a big deal in this case since creating abr instances isn't particularly "hot" code - but it's still good practice and helps debugging since less hidden classes are created.
Remove redundant conditional check for clearing the timer, since clearing invalid timeouts is valid and common practice.
Again, baby steps for learning the project.

forward declare object properties

---

.gitignore
package.json

**Done:** Add coverage to hls.js. 
1) add `nyc` for coverage
2) add `coverage` task to package.json
**Next step:** Integrate coverage with Travis via [coveralls](https://coveralls.io/sign-up).
1) Sign up with coveralls. 
2) Follow remaining integration [steps](https://github.com/istanbuljs/nyc#integrating-with-coveralls).
I purposely didn't add coveralls until I get guidance from one of the maintainers on the approach to take. 
Please let me know what steps to take to integrate coverage into hls.js. 👍

add nyc for coverage purposes

---

package.json

chore(package): update uglify-js to version 3.0.20

---

package.json

chore(package): update parallelshell to version 3.0.1

---

package.json

chore(package): update uglify-js to version 3.0.23

---

README.md

Syntax highlighting of HTML to html instead of js

---

tests/functional/streams.json

-Updates
http://level3cdn.screen9.com/M/V/e/X/eXLpum-4HGEg67ECxUnqWQ_720p_hls/playlist.m3u8?token=089899b60a6e85dd2239a 
to
http://cdn3.screen9.com/media/c/W/cW87csHkxsgu5TV1qs78aA_auto_hls.m3u8?auth=qlUjeCtbVdtkDfZYrtveTIVUXX1yuSqgF8wfWabzKpX72r-d5upW88-FHuyRRdnZA_1PKRTGAtTt_6Z-aj22kw

Use new stream link for issue #649 test

---

doc/API.md
src/errors.js

Fixes #1134.
* Update Errors section of `API.md` with all errors from `src/errors.js`
* Segment errors by type
* Update some typos
* Remove `WEBVTT_EXCEPTION` from `src/errors.js` as it appears to be unused

Update errors documentation in API.md

---

doc/design.md

* Update description in `design.md` to say bundling is done by webpack instead of browserify
* Fix a few typos

link to webpack in design.md

---

doc/API.md

Add `enableWebVTT` config documentation.

API: add enableWebVTT documentation

---

src/controller/subtitle-track-controller.js

Modified this file header comment

---

demo/index.html

This PR simple logs media error message when this one is available (Chrome & FF). 
See https://googlechrome.github.io/samples/media/error-message.html and https://www.chromestatus.com/feature/4996058069336064

Demo: Log media error message when available

---

src/controller/stream-controller.js

Additional checks for PR https://github.com/video-dev/hls.js/pull/1295

fix frag loading loop detection

---

README.md

Sorry, I just couldn't leave it as is. It didn't match the other badges :)
Now its the same style.
- [x ] no commits have been done in dist folder (we will take care of updating it)
- [x ] new unit / functional tests have been added (whenever applicable)
- [ x] Travis tests are passing (or test results are not worse than on master branch :))
- [x ] API or design changes are documented in API.md

Fixed badge style

---

src/config.js

restore correct maxFragLookUpTolerance value

---

doc/API.md

ignore protocol part in url

---

doc/design.md
src/controller/level-controller.js

It’s an improvement for Media Zigzagging to handle the case when we reach lowest level. With this change, we potentially will check every available level (primary + backup).

Improve Media Zigzagging

---

package.json

Update url-toolkit to a version which is a bit stricter parsing the scheme.
See https://github.com/tjenkinson/url-toolkit/releases/tag/v2.1.2
fixes https://github.com/video-dev/hls.js/issues/1478

update url-toolkit to 2.1.2

---

README.md

closes #1254
Added a few lines of code (@bmalehorn originally wrote in #1254) that show the basics of how to support use of hls.js on iOS.

Added iOS support snippet to README

---

src/config.js

- add comments
- comment out `fetchSetup` because fetch-loader is not used

Add comments to config.js

---

src/remux/mp4-remuxer.js

Fixes missing brace lint complains aout
- [x ] no commits have been done in dist folder (we will take care of updating it)
- [x ] new unit / functional tests have been added (whenever applicable)
- [x ] Travis tests are passing (or test results are not worse than on master branch :))
- [x ] API or design changes are documented in API.md

fixes lint style error; travis: 42 passing

---

.babelrc
README.md
demo/basic-usage.html
demo/canvas.js
demo/index.html
demo/index.js
demo/main.js
demo/metrics.js
demo/style.css
package.json
tests/functional/auto/hlsjs.js
tests/test-streams.js
webpack.config.js

* Allows having test-streams with custom config attached, applied in demo code
* Adds Widevine demo stream with license-server-config
* Allows to enter Widevine license server config in demo
* Demo code quality/readability/maintenance improvements
* Many visual/UX improvements
* Links to an additional super-simple demo page for plain basic usage

Improve the demo 2

---

src/controller/buffer-controller.js
src/helper/fragment-tracker.js
tests/unit/helper/fragment-tracker.js

There was an issue with the fragment tracker feature with webpack and IE11 where Map iterators had some issues. I've converted the Maps into Objects.

Refactor Maps to Objects

---

doc/design.md

Fix missing link in design.md

---

src/controller/stream-controller.js
src/task-loop.js
tests/unit/controller/stream-controller.js

This PR add basic tests for `StreamController`.
This PR will not includes tests for all methods. 
I will add other tests in other PR by little and little.
`StreamController` has important logic for playing.
I will improve coverage and stability.
This PR fix a bit of `stream-controller.js` and `task-loop.js`.
I've tested hls.js demo manually.

Add StreamController unit tests

---

src/controller/stream-controller.js

Currently, failt to jump buffer hole.
```
////: Buffered
buffer  hole
|             |                   
vvvv       vvvvvvvvvvvvvvvv
|____|/////|________________|//////////////.....//////| 
0   0.005  0.501      ^     2.011                    22.000
|
Current Time(`1.510666`)
```
This PR fix that jump over the buffer hole correctly.
Fore more details, See #1537 
fix  #1537

fix monitor playback progress on StreamController

---

README.md

README: example below > example above

---

tests/unit/crypt/aes-decryptor.js

Fix typo in aes-decryptor.js tests
Fix what looks to be a small typo in tests/unit/crypt/aes-decryptor.js

Fix typo in aes-decryptor.js tests

---

src/controller/timeline-controller.js

Get right language code from config like 'Label' parameter (https://github.com/video-dev/hls.js/issues/1552)

---

tests/test-streams.js

Firefox is always failed on TravisCI + SauceLab.
I've added "firefox" to `blacklist_ua` of `angelOneShakaWidevine` func test
**Failure Example**: https://travis-ci.org/video-dev/hls.js/jobs/343204352
> hlsjs fatal error :keySystemNoKeys"
```
should receive video loadeddata event for Shaka-packager Widevine DRM (EME) HLS-fMP4 - Angel One Demo[0m
Retrieving web driver session...
travis_fold:start:debug_logs
logs
2018-02-19 03:43:18.888: 
2018-02-19 03:43:18.913: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0"
2018-02-19 03:43:18.914: "[log] > loadSource:https://storage.googleapis.com/shaka-demo-assets/angel-one-widevine-hls/hls.m3u8"
2018-02-19 03:43:18.917: "[log] > trigger BUFFER_RESET"
2018-02-19 03:43:18.918: "[log] > attachMedia"
2018-02-19 …
```

fix(func-test): add "firefox" to blacklist of angelOneShakaWidevine

---

tests/unit/controller/eme-controller.js
tests/unit/controller/level-controller.js

- Add Level Controller unit test: level switching, manifest parsing, manifest loading.
- Update EME Controller unit test: key system errors

add level controller unit test, update eme controller unit test

---

tests/functional/auto/hlsjs.html

Hope this will fix flakiness of testbench even more and explain a few issues we had here and there with it in the past :D 
Figured this while working on the linting.
We should also have this code linted, just put it in a js file next to the HTML instead of embedding it.
Or eslint also has a plugin that lints js in html tags :)

Testbench: Fix missing argument in switchToHighestLevel function

---

demo/demo-utils.js
demo/index.html
demo/main.js
demo/metrics.js
demo/style.css
package.json

* Make demo config passed in permalink as Base64-serialized JSON (except `src`) 
* Allow to extend demo configuration more easily
* Tabbed tool panes (metrics, buffer stats, quality/track controls etc)
* Visual fixes in HTML
* Add lint command for demo code (not applied yet, too many errors yet)
* Move general purpose helper functions into a `demo-utils` module
This work is part of two tracks
1) Allow our amazing metrics events recoding and rendering system to be cut out of the demo and introduce as a "plugin" or "extension" of our lib. For this, we will have to come up with the concept of Hlsjs extensions (or plugins) in the first place :)
2) Improve our demo itself, but also the maintainability and readability of the code. Allow to make it more fancy will also need to make parts of it …

Demo config parameters serialized B64/JSON

---

package-lock.json
package.json
tests/functional/auto/setup.js
tests/test-streams.js

Fix functional test failing on chrome 66+
Because functional tests fail and I want to ✅ on my PRs
No

Fixed chrome not autoplaying when performing functional tests

---

README.md

Add Fluid Player to the Player Integration list.
Informational purposes.
No.
N/A

Add Fluid Player to Player Integrations

---

karma.conf.js
tests/mocks/hls.mock.js
tests/tests.webpack.js
tests/unit/controller/eme-controller.js

Make source-maps work conveniently in unit tests (actually mapping down to actual source file and line number).
Easier to debug tests.
We could probably improve on the config still. Not sure why inline-source-map doesn't work as well.
Maybe upgrade on version of the karma stuff?
Cryptic source-mapping in unit testing console.

Improve unit tests sourcemaps

---

.github/stale.yml

Add stale bot config. See https://github.com/apps/stale
Too many issues stay open but inactive :) 
;)

Add stale-bot config

---

.github/PULL_REQUEST_TEMPLATE.md
.travis.yml
package.json
scripts/travis.sh

Automate release

---

src/controller/abr-controller.js

there are a null exception
https://gist.github.com/senaev/a9237c53543b0f7f13b8dbb136cd636e

do not throw error if level details is not defined

---

src/loader/fragment-loader.js

Fix the broken cleanup of loaders in `FragmentLoader` on timeout/error
To cleanup `FragmentLoader` properly on timeout/error
no

Fixed `FragmentLoader` not cleaning up on timeout/error

---

demo/index.html
scripts/travis.sh

Make the demo page load the build from the cdn when not running locally.
Because otherwise when running on github it fails to load, as there is no dist dir anymore.

Use demo build from cdn

---

.travis.yml

to make the builds quicker.
Opening this PR will determine if it actually works

disable sauce labs when not needed

---

webpack.config.js

speed up our build, quite a bit.
we were not excluding node_modules from the compiler webpack-loader, which was causing a lot of the webpack-hooks (especially in the dev-server env) to be run through the compiler, which is a lot and was causing our builds to be much slower than they should have been.

Speed up build by avoiding to compile node_modules things

---

package-lock.json
package.json

update url-toolkit
fixes a bug that was reported
see https://github.com/tjenkinson/url-toolkit/releases/tag/v2.1.5
cc @spodlecki

update url-toolkit to v2.1.5

---

docs/design.md

This fix can help developers understand the design and duty of each module better.
No.
No.

Fix design document event typo

---

demo/index.html

Fix a broken link
To avoid the user getting a 404 error when clicking on the link "API"
nop
- [N/A] new unit / functional tests have been added (whenever applicable)
- [N/A] API or design changes are documented in API.md

Fix broken link on the demo page

---

.github/ISSUE_TEMPLATE/bug_report.md

These links were not updated after we moved the demos to `/stable` and `/latest`, and 404 when navigated to.
No

Update broken demo links in the bug_report template

---

README.md

This PR lists a new player that integrates seamlessly `hls.js`, to the continuously increasing list of players that support it

Added OpenPlayerJS to the list of players that support HLS.js

---

README.md

1.  Fix spelling of interdependent and environment
2. Correct the agreement in the phrase: 'imported/required by each other.'

NIT: fix typos in readme

---

src/config.js
src/controller/abr-controller.js
src/hls.js
src/utils/logger.js
tests/functional/auto/setup.js
tests/functional/auto/testbench.js

Reduce eslint issues from 389 -> 334.
Green marks in editor makes it harder to read code. Why lint if it isn't enforced?

Lint fixes

---

docs/API.md

Fixed some typos for API docs.
This Pull Request needed to understand API correctly for developers that use hls.js.

Fixed some typos

---

scripts/deploy-netlify.sh

fix error in deploy script

---

README.md

Add netlify's badge to the readme
So that we qualify for the open source plan: https://www.netlify.com/legal/open-source-policy/

add netlify badge to readme

---

src/controller/subtitle-track-controller.js

Fix subtitles default track autoselect.
`if (this.queuedDefaultTrack)` check doesn't work correctly if default track is first in the list (`this.queuedDefaultTrack = 0`)

fix subtitle default track autoselect

---

webpack.config.js

This PR removes unnecessary option from webpack.
This PR needs to simplify webpack config.
https://github.com/video-dev/hls.js/issues/2251

fix: Remove unnecessary option

---

src/errors.ts

convert errors.js to typescript
#2070

convert errors to typescript

---

src/demux/tsdemuxer.js

Just a simple logging typo change.

Fix typo: unkown -> unknown

---

tests/test-streams.js
tests/unit/controller/level-controller.js

Change hosting of test streams to mux
Github has asked us to stop using that repo for hosting media because it is using too much bandwidth.

fix: change test streams hosting to mux

---

package.json
webpack.config.js

- Allow building multiple configs via webpack env
- Build demo page for `npm run build:debug`, `npm run build:watch`, `npm run dev`
demo page is not builded for local debug builds
nope

build demo page in debug, watch && dev scripts

---

tests/functional/auto/setup.js

Hopefully make retries work if we initially get an error page through the sauce connect tunnel
Because the promise was incorrectly resolving by default.
No

fix break in promise chain

---

package-lock.json
package.json
tests/functional/auto/setup.js

Update chromedriver to a version that works with chrome today, and increase the timeout for the beforeEach, because it seems sometimes connecting and getting the web driver session with saucelabs is taking longer than the current 40 second timeout.
builds on https://github.com/video-dev/hls.js/pull/2352

Increase before each timeout

---

package-lock.json
package.json
src/controller/timeline-controller.ts
src/is-supported.ts
src/utils/fetch-loader.ts
src/utils/mediasource-helper.ts

the newer typescript includes more type definitions meaning that more stuff on `self` is typed

update typescript and remove `(self as any)`

---

src/crypt/decrypter.ts
src/demux/transmuxer.ts

**This is based off the v1 branch**
Remove all the ts-ignores
It's better to not disable typescript completely when possible.

remove all ts-ignore flags

---

package-lock.json
package.json
scripts/precommit.sh
scripts/travis.sh

Make sure we run the type check and build the types on CI. It also sets `types` in the package.json so that users of the library also get the types.
It also sneaks in a husky update

Include types in build and type check on CI

---

src/crypt/aes-decryptor.ts
src/crypt/decrypter.ts
src/demux/base-audio-demuxer.ts
src/demux/transmuxer-worker.ts
src/demux/tsdemuxer.ts
src/hls.ts
src/polyfills/runtime-polyfills.ts
src/utils/chunker.ts
src/utils/mp4-tools.ts
src/utils/typed-array.ts

https://github.com/video-dev/hls.js/pull/2370#discussion_r324418422

remove slice pollyfill

---

README.md

Adds the specific version of ID3 that the demuxer supports.
Closes a question about what ID3 version is supported, and does it hopefully more permanently.
Is v2.3.0 correct?
Closes #2413

Add ID3 supported version to README.

---

package-lock.json
package.json
tests/functional/auto/setup.js
tests/functional/auto/testbench.js

- Mute video when required to auto play functional tests
- Update chromedriver to v78
- `npm audit fix`
Mute the video to allow playback without interactions when running functional tests.

Mute video when required to auto play functional tests

---

demo/index.html

Fix link to API docs
This Pull Request needed to link to API doc.
No
No

Fix demo errors

---

src/remux/aac-helper.ts
src/remux/mp4-remuxer.ts

Convert aac-helper.js to typescript and add typing to some mp4-remuxer methods

Convert aac-helper.js to typescript and add typing to some mp4-remuxer methods

---

README.md

This PR will add supported M3U8 tags to README and tweaks
This PR is needed to v1.0.0
N/A

Add supported M3U8 tags

---

src/remux/mp4-generator.ts

Convert mp4-generator to TypeScript
Progress towards #2070
NO
N/A

Convert mp4-generator to TypeScript

---

README.md

Fix formatting of the example in the readme.
Looks better. 🤓 
No
No

Fix formatting of example

---

.vscode/tasks.json

This gives the ability to get lint errors as problems in Visual Studio Code. Rather than only seeing errors as you have the file open, you are able to approach the project holistically.
Adds a problem matcher definition for running ESLint in VSCode.
This makes it easier to find and fix linting errors in Visual Studio Code.
No.
N/A

Add a VSCode task: "lint".

---

docs/API.md

Hey, this is my first contribution, so decided to go for a simple docs change in the "good first issues list" to test the ropes. Let me know if I've done anything wrong this time around!
Add a docs entry for the capLevelOnFPSDrop config option.
Description of this config option is currently missing.
Don't think so
#1744 
- [ :heavy_check_mark:  ] changes have been done against master branch, and PR does not conflict
- [ n/a ] new unit / functional tests have been added (whenever applicable)
- [ n/a ] API or design changes are documented in API.md

adds docs for capLevelOnFPSDrop config option

---

docs/API.md

Based on the notes from #2449 this updates the documentation with further clarification
update the API about 2 likely scenarios
Reduce confusion around an existing API
No
#2449

Update API.md about BUFFER_NUDGE_ON_STALL fatal flag

---

docs/API.md

Add missing events to API docs.
I mentioned in the [v0.14.0-beta.1 release notes](https://github.com/video-dev/hls.js/releases/tag/v0.14.0-beta.1) that these were missing from the docs.

Add NON_NATIVE_TEXT_TRACKS_FOUND and CUES_PARSED events to API docs

---

README.md

Word wrap the comments in the Getting Started code example. There are no changes to the wording.
Improve readability, remove need for scrolling to read the comments.
No
None

Word wrap code comments for readability

---

src/remux/mp4-remuxer.js

fix a trivial copy-pasta for when the mp4 muxer detects audio being ahead of video
fix a warning message
because it might confuse developers like /myself
no

log message fix

---

src/controller/abr-controller.js

Add guard for ABR controller check on missing level
Levels can be removed while abr-controller timer is running resulting in #2685
#2685

Add guard for ABR controller check on missing level

---

src/controller/gap-controller.js

Simple logging improvement to provide more details when encountering the "playback stalling" warning message.
More visibility into the underlying state.

Include buffer size in playback stall warnings

---

docs/API.md

Several properties shown in API.md were undocumented. 
Feel free to suggest improvements to the descriptions. I'm also open to removing items if we want to keep them undocumented.

Fill gaps in documentation

---

tests/functional/auto/setup.js
tests/functional/auto/testbench.js

Testing the behaviour on SauceLabs to see if single browser session is
more reliable on SauceLabs.
Potentially improve the behaviour for functional tests on SauceLabs by decreasing the amount of sessions created.
Functional tests are failing a lot, but succeeding without code changes if run again. Timeouts appear to be an issue. (40000ms waiting).

refactor(tests): Functional tests run in a single browser session.

---

src/controller/base-stream-controller.ts
src/types/general.ts
src/utils/discontinuities.ts

Convert discontinuities.js to TypeScript
Progress towards #2070

Convert discontinuities.js to TypeScript

---

docs/design.md
src/controller/id3-track-controller.ts
src/demux/aacdemuxer.ts
src/demux/base-audio-demuxer.ts
src/demux/id3.ts
src/demux/mp3demuxer.ts
src/demux/tsdemuxer.ts
tests/unit/demuxer/base-audio-demuxer.ts
tests/unit/demuxer/id3.ts

Migrate `demux/id3.js` to typescript: `demux/id3.ts` 
Introduce `ID3Frame` object type: `{key: string, data: ArrayBuffer | string, info?: any}`
https://github.com/video-dev/hls.js/projects/5#card-37707235
Yes but I'll add github comments where relevant.
contributes to: https://github.com/video-dev/hls.js/issues/2070

Demux id3.js to typescript

---

demo/main.js
webpack.config.js

Fix the branch link on branch builds.
We can't always properly get the branch name from the semver string because we replace invalid semver characters, so now we inject it from the environment in the build instead.

fix branch link on demo

---

src/controller/stream-controller.js

Prevent immediate level switch from performing unnecessary pause and seeks.
Media element pause and seeking events can interfere with 3rd party application state.

Prevent immediate level switch unnecessary pause and seek

---

src/remux/mp4-remuxer.js

Add method to find start pts

---

src/controller/id3-track-controller.js

Merge #2960 
That PR was made against a patch branch for releasing recent remuxer fixed in v0.14.8

Merge patch/v0.14.8

---

src/remux/mp4-remuxer.js

Fill audio gaps at the beginning of VOD streams, and align silence with the first sample to prevent sliding.
Filling large audio gaps at the start ensures that the combined media buffer is close enough to 0 for the browser to autostart and trigger "loadeddata" without a seek from hls.js's gap-controller.
Aligning the silence to the first available sample, prevents the samples with audio from being moved. Moving samples with audio each time a gap if found could lead to audio becoming out of sync with the video if applied repeatedly.  
#2948

Fill audio gaps at start of stream with silence

---

.travis.yml
package-lock.json
package.json
scripts/travis.sh
tests/functional/auto/setup.js

- Add `npm run test:func:sauce` task
- Separate test runner travis and saucelabs concerns
- Use sauce-connect-launcher dev dependency for creating tunnel in all test runs using sauce labs
1. Run tests locally against remote browsers on saucelabs (just latest chrome for now).
2. Troubleshoot and fix issues with travis sauce-connect

Functional test runner updates and tasks

---

src/utils/imsc1-ttml-parser.ts
src/utils/vttcue.ts

convert vttcue.js to vttcue.ts as designated in [project-5](https://github.com/video-dev/hls.js/projects/5#card-37706880)
I cannot seem to compile this on localhost, because of a babel/webpack issue as discussed in Slack, opening the PR here for review/comments
no, changes are done from `feature/v1.0.0` branch
there are no API changes, this is meant to be a 1-to-1 translation with as narrow types as possible

chore: convert vttcue.js -> vttcue.ts;

---

src/controller/stream-controller.ts

Fix live playback list not sync issue.
Bugfix.
No.
https://github.com/video-dev/hls.js/issues/3091

fix: fix live playlist not sync

---

.github/workflows/automerge.yml

Update the automerge action.
Previously it timed out after 1 hour, which was too short. The new one keeps checking for 6 hours.

update automerge action

---

.github/workflows/codeql-analysis.yml

Configure codeql scanning on PR's and pushes, and once a week.
It's free, and it will help find any security issues.
More info: https://github.com/github/codeql-action

Configure CodeQL Scanning

---

demo/benchmark.html
demo/main.js
demo/metrics.html

Fix some of the codeql issues.
Make the demo a bit safer

Fix some issues found by codeql

---

.github/workflows/codeql-analysis.yml

Remove the typescript lauguage from the codeql action.
Docs are vague, but it looks like typescript is included as part of the javascript language after reading https://help.semmle.com/QL/learn-ql/javascript/introduce-libraries-ts.html
Verified on https://github.com/video-dev/hls.js/pull/3154

remove typescript language from codeql action

---

.github/workflows/build.yml

Also trigger the action on pull request events.
Because it looks like the push event is not triggered for PR's opened from a fork.

also trigger action on pull request events

---

.github/workflows/automerge.yml

Update the auto merge action to a version that handles rate limits.
https://github.com/video-dev/hls.js/pull/3194#issuecomment-720687766

update automerge action to version which handles rate limit

---

src/utils/xhr-loader.js

fixbug vuejs production build error "cannot read property 'readyState' of null" when loadSource, then cannot load video
Vuejs production build cannot load video

Update xhr-loader.js - fixbug vuejs production build cannot load video

---

src/demux/aacdemuxer.ts
src/demux/adts.ts
src/demux/base-audio-demuxer.ts
src/demux/mpegaudio.ts
src/demux/tsdemuxer.ts
src/types/demuxer.ts

Convert adts.js to TypeScript using work from #2504 
Progress towards #2070
Squash and merge

Convert adts.js to TypeScript

---

README.md

(has changed with https://github.com/video-dev/hls.js/pull/3207)

Fix documentation on --env usage with webpack command

---

README.md

Following discussions in video-dev#3345 this emphasizes where hls.js is supported and that for multi-platform support adherence to RFC8216 is required.
No code changes.
#3345

Emphasize where hls.js works and RFC adherence

---

src/loader/m3u8-parser.ts

The format is the same as in the other sections.

Fix comments adding [*]

---

LICENSE
src/demux/exp-golomb.ts

Convert src/demux/exp-golomb.js to typescript.
Because src/demux/exp-golomb.js is not typescript.
No
Related to #2070

Convert src/demux/exp-golomb.js to typescript.

---

src/utils/vttparser.ts
src/utils/webvtt-parser.ts

Convert vttparser.js to TypeScript.
This is the last untyped module.
Closes #2070

Type vttparser

---

lint-staged.config.js

Fix a hang that can occur when making a commit if there are no staged files for prettier.
If `prettier --write` runs with no file it hangs (for some reason).

fix bug if there are no files for prettier on commit

---

src/loader/m3u8-parser.ts
tests/unit/loader/playlist-loader.js

Handle a comment in the master playlist on a line before the URL.
Spotted when I was playing around with [mock-hls-server](https://github.com/tjenkinson/mock-hls-server). 0.1.0 of that using the link in the example will cause the issue.
Currently if there's a comment there it ends up in an infinte loop, possibly becase it's treating it as a url which becomes relative to the playlist url with the anchor added.

handle comment in master playlist before url

---

.github/workflows/build.yml
README.md
api-extractor/report/hls.js.api.md
demo/index-light.html
package.json
src/config.ts
src/utils/cues.ts
tests/functional/auto/index-light.html
tests/functional/auto/setup.js

- Fix Cues export for the light build
- Run a very small subset of functional tests for the light build as part of the required functional test build step
Fix and prevent regressions like #3493
Fixes #3493

Fix Cues export and add functional test for the light build 

---

docs/design.md

Fix broken links in design.md

---

README.md

Update the alpha references to canary.
We changed from alpha to canary a while ago and forgot to update this.

point at canary not alpha in the readme

---

src/hls.ts

- Apply the Hls API instance context to event listeners instead of using the default event emitter
- Add non-debug flag callback try-catch guard to trigger rather than wrap listeners
- event listeners can be added and removed explicitly
- `on(event, fn)` / `off(event, fn)`
- fixes `once`
- added listeners are not modified
- listeners are invoked with the API object as their context by default, not `this._emitter`
- `hls.on(event, function() { this === hls })`
#3535

API instance event emitter fixes

---

src/controller/audio-stream-controller.ts
src/controller/base-stream-controller.ts
src/controller/cap-level-controller.ts
src/controller/level-helper.ts
src/controller/timeline-controller.ts
src/crypt/aes-decryptor.ts
src/remux/mp4-remuxer.ts
src/types/remuxer.ts
src/utils/cea-608-parser.ts
src/utils/mp4-tools.ts
tools/mp4-inspect.js

Cleanup unused vars, assignments and expressions
Based on issues listed on https://lgtm.com/projects/g/video-dev/hls.js?mode=list

Cleanup unused vars, assignments and expressions

---

CONTRIBUTING.md
MIGRATING.md
README.md

Created some rough drafts of CONTRIBUTING and MIGRATING documents.
The CONTRIBUTING is very incomplete. I could use help from other project maintainers who have good suggestions, like linking to CODE_OF_CONDUCT, pointing to roadmap project, labels, etc...
MIGRATING.md covers everything in recent release notes for moving to v1.0 from v.0.14. I would like to have more input from users moving their apps over. I haven't had time to start over with a new migration to verify every point of this doc or find gaps as I am still working on incoming issues.

Add CONTRIBUTING and MIGRATING rough drafts

---

api-extractor/report/hls.js.api.md
src/types/events.ts

Use SourceBufferName for elements

---

api-extractor/report/hls.js.api.md
src/controller/base-playlist-controller.ts
src/types/level.ts

Add support for delta playlist updates without blocking reload.
Delta playlist updates can be used without LL-HLS and/or blocking playlist requests.
Resolves #3644

Add support for delta playlist updates without blocking reload

---

docs/API.md

1. Explain `liveSyncPosition`'s relationship to `liveMaxLatencyDuration` and how it's the moving target for syncing with a live stream.

Update live API details in API.md

---

src/demux/transmuxer.ts
src/demux/tsdemuxer.ts
src/types/demuxer.ts
src/utils/fetch-loader.ts

Fixes https://github.com/video-dev/hls.js/issues/3747

Fix Video Glitches with Fetch Loader

---

README.md
docs/API.md

- Make the "Features" section front and center
- Cleanup "Getting Started with development" and move it up making it easier for newcomers to pull down the project and run it locally
- Cleanup "Using HLS.js" combining installation and embedding in one section
- Fix links to deployments list
- Put integrations and license at the bottom of the README
- Added example `licenseXhrSetup` usage

Updated README to highlight "Features" and "Getting started with development"

---

src/controller/subtitle-stream-controller.ts

Use `BaseStreamController` methods in `SubtitleStreamController` to handle seeking properly.
When a subtitle track playlist contains #EXT-X-PROGRAM-DATE-TIME, subtitle-stream-controller would load all segments sequentially based on date time of `fragPrevious`. `fragPrevious` should be cleared when seeking away from the current fragment, but it never was because `SubtitleStreamController` was not using the base implementation of `onMediaAttached` which adds the seeking listener that performs this logic.
Now subtitle-stream-controller handles fragment loading selection after a seek just like the audio and main stream controllers.
These changes also remove useless overrides and code that is redundant in `SubtitleStreamController` since it extends `BaseStreamController`.
Fixes #3813

Fix subtitle loading after seeking in tracks with PDT

---

.github/release-drafter.yml
.github/workflows/release-drafter.yml

Use https://github.com/release-drafter/release-drafter to generate draft release notes for project releases.

Add Release Drafter to project workflows

---

api-extractor/report/hls.js.api.md
src/config.ts
src/utils/logger.ts

Allow passing an `ILogger` to `config.debug`.  The documentation says you can do this, but the typescript types say you can only pass a boolean.
To make typescript happy.  :)
No
Doesn't resolve it, but this was pointed out in #2701.

Fix type for 'debug' field in config.

---

demo/main.js

Add space before version in demo page title.
The space was missing.

add space before version in demo page title

---

src/controller/subtitle-stream-controller.ts

Fix subtitle loading after switching subtitles off and then on to a new track
Fixes #4345

Fix subtitle loading after switching subtitles off and on

---

docs/design.md

Ensure design.md shows up all the markdown file
To fix https://github.com/video-dev/hls.js/issues/4460
Check that all markdown file is shown and that ~~FRAG_DECRYPT_ERROR~~ error and comments are `strikedthrough` 
&nbsp;&nbsp;<img src="https://user-images.githubusercontent.com/7487579/146243883-9cef71d8-eda9-405f-96e5-5bf349800907.png" width="500px" />
Fixes https://github.com/video-dev/hls.js/issues/4460

Fix design.md comments problem

---

package.json

Fixes #4441 
This PR fixes exposing the `demo` site on the dev build.
#4441

Bugfix: Added `--static .` in order to fix `demo` page

---

docs/API.md

Update the documentation for testBandwidth to accurately represent what occurs when this value is left on the default, including what needs to be set for it to have the impact described.
Also added what happens in the default case.

Update documentation on testBandwidth.

---

src/controller/stream-controller.ts

- Only preemptively select earlier segments when the selected segment is not tracked as buffered
- Do not preemptively select earlier segments over discontinuity (cc) boundaries
- Use the forward buffer target load time to determine if we need to backtrack rather than currentTime
These changes prevent the loop loading or reloading of segments when the stream is known to have segments with missing keyframes and when a segment is loaded with dropped samples because it does not start with a keyframe and the previous segment was not just appended. I also prevents this logic from reloading the segments at the end of a stream when a user seeks within the buffer after the stream has ended.
Fixes #4378 #3986

Fix loop loading of segments caused by backtracking logic

---

docs/design.md

this is to fix the typo in the design doc
NA
NA

chore: fix typos in design doc

---

src/controller/audio-stream-controller.ts
src/controller/stream-controller.ts

Use stream controller instance for logger log and warn calls.
Adds [_controller-name_] prefix to log statements and removes logger import from base-stream-controller sub classes.

Cleanup stream controller logger statements

---

docs/API.md

Update Loader Composition code example with code that does not produce runtime errors
Using the current code example to override the loader produces runtime errors (and compile time error if you are using Typescript).
Would it be helpful to include an `async` code example with a "Use at your own risk" warning?
#4410, #4411. Possibly #1354, #4840, #4803.

Update Loader Composition code example with code that does not produce runtime errors

---

src/demux/adts.ts

just fix the spellings of sampling and channel.
It makes readability better and does grep easily with less confusion.
nothing special.
N/A
- [-] new unit / functional tests have been added (whenever applicable)
- [-] API or design changes are documented in API.md

fix the sampling and channel spellings.

---

src/controller/timeline-controller.ts

Disable 608 captions on variants with CLOSED-CAPTIONS=NONE attribute and value pair
Spec compliance and Safari parity
Resolves #4913

Disable 608 captions on levels with CLOSED-CAPTIONS=NONE

---

docs/API.md

Fix broken loader link in table of contents
The previous "Loader Composition" sections was renamed, but the link was not updated.
No

Fix broken loader link in table of contents

---

src/controller/base-stream-controller.ts

Try to fix this issue: https://github.com/video-dev/hls.js/issues/4950

compare fragmet sn instead of object equality

---

src/utils/discontinuities.ts

Apply a fixed delta in alignMediaPlaylistByPDT - the delta is calculated based on the first fragment of each playlist, and applied to all fragments. Using a fixed delta avoids changing the implicit duration of fragments when there are gaps in fragment PDTs.
Need to consider the impact on synchronizing audio - is this change ok for audio? the function alignMediaPlaylistByPDT is called from audio-stream-controller as well.
#4984

alignMediaPlaylistByPDT: use a fixed delta

---

src/controller/audio-stream-controller.ts
src/controller/base-stream-controller.ts
src/controller/subtitle-stream-controller.ts

Clone of #5095 for v1.2.9 patch.
- See #5095 for details.
Fixes #5083

Fix audio and subtitle controller loading before player seeks to startPosition (for v1.2.9)

---

README.md

add another example player that demonstrates IPTV streaming with m3u-playlists using the hls.js
Because there are not many IPTV related players available.
Nope
No issue - just adds another example to README

Added another modern IPTV player example

---

src/controller/buffer-controller.ts

Fix an issue where SourceBuffer `timestampOffset` is not updated for MP3 appends when first chunk loaded cannot be decrypted using software decrypter.
This situation results in the first append having a ChunkMetadata id of 2 instead of 1. Rather than depending only on the chunk id which is derived from the number of loading progress callback and transmuxer passes for a segment, keep track of the last mp3 ChunkMetadata so that `timestampOffset` is updated whenever the segment sequence number changes.
Closes #4543

Prevent missed software decrypt from skipping MP3 segment timestamp offset from being set

---

src/controller/id3-track-controller.ts

Add cue id for date-range cues

add cue id for date-range cues

---

.github/workflows/build.yml

Switch back to official saucelabs action
My fix for retries been broken is merged in now

switch back to official saucelabs action

---

src/utils/attr-list.ts

Response to CodeQL feedback:
https://github.com/video-dev/hls.js/security/code-scanning/69

Cleanup Attribute RegEx

---

src/controller/base-stream-controller.ts
src/crypt/decrypter.ts
src/demux/transmuxer.ts
src/loader/m3u8-parser.ts

Add support for AES-128 encrypted Low-Latency HLS.
Fixes #5212

Support AES-128 Encrypted Low-Latency HLS Parts

---

src/controller/audio-stream-controller.ts
src/controller/base-stream-controller.ts
src/controller/buffer-controller.ts
src/controller/buffer-operation-queue.ts
src/controller/cap-level-controller.ts
src/controller/level-helper.ts
src/controller/stream-controller.ts
src/demux/mp4demuxer.ts
src/remux/passthrough-remuxer.ts
src/utils/cues.ts
src/utils/fetch-loader.ts
src/utils/vttparser.ts
tests/functional/auto/setup.js
tests/functional/auto/testbench.js
tests/mocks/time-ranges.mock.js

Use optional chaining operator in more places.
cc @itsjamie as looks like you added this rule
To unblock https://github.com/video-dev/hls.js/pull/5039 which updates eslint, which has made the `@typescript-eslint/prefer-optional-chain rule` more sensitive.

use optional chaining operator in more places

---

src/remux/mp4-remuxer.ts
src/remux/passthrough-remuxer.ts

Update base timestamp offset (initPTS) when timescale changes or new base time would cause variant timing to be unplayable or not aligned with other assets.
HLS Authors have trouble packaging HLS assets that share the same base timestamp across variants when the segment types do not match (TS and fmp4).
Based on changes that add timescale tracking in feature/content-steering
Fixes #5195

Handle misaligned variant timestamps

---

src/loader/key-loader.ts

Fix [5244](https://github.com/video-dev/hls.js/issues/5244)

Play AES-128 stream failed sometimes

---

README.md

Add a link to Media Chrome for users to build custom UI with hls.js

docs: add Media Chrome for custom UI

---

build-config.js

Add a light ESM build.
See https://github.com/video-dev/hls.js/issues/5484
Fixes https://github.com/video-dev/hls.js/issues/5484

Provide light ESM dist file

---

src/demux/tsdemuxer.ts

Fix TS probing by requiring 2-3 packet start bytes to be matched
Scanning for only one packet with PID was matching AAC content.
Fixes #5501

Fix TS probing by requiring 2-3 packet start bytes to be matched

---

.github/ISSUE_TEMPLATE/question.yaml

Update question.yaml template description
Users should not file questions when there issue merits a Bug Report or Feature Request.

Update question.yaml template description

---

src/demux/video/base-video-parser.ts

Fixes a lint error impacting new PRs

Remove unused import from base-video-parser.ts

---

.gitignore

Add Visual Studio folder exclusions to `.gitignore`
To make it easier to work with this code with Visual Studio
Not at all.
In case of interest, I could submit the `.njsproj` and `.sln` files I'm using.

Add Visual Studio Exclusions to `.gitignore`

---

src/controller/buffer-controller.ts

Remove SourceBuffers on "updateend" when MediaSource is closed
Fixes errors accessing buffers after media error ("bufferAppendError" in #5481) 
#5481

Remove SourceBuffers on "updateend" when MediaSource is closed

---

MIGRATING.md
docs/API.md

Add additional documentation around the `workerPath` config and the ESM distribution.
- Adds a section to MIRATING.md mentioning that workerPath should be included when using the ESM distribution and wanting web workers to be enabled.
- Adds a comment to the code example in API.md about the above
- Adds a note in the workerPath documentation in API.md about the above
See the comments on #5757 
No, this is just a small documentation change
None. Related to #5757, but does not resolve the actual issue.

Add additional documentation for workerPath config

---

api-extractor/report/hls.js.api.md
src/controller/audio-stream-controller.ts
src/controller/base-playlist-controller.ts
src/controller/base-stream-controller.ts
src/controller/fragment-tracker.ts
src/controller/level-helper.ts
src/controller/stream-controller.ts
src/loader/level-details.ts

Merge bugfix/live-append-only-endlist into patch v1.4.x branch
Changes from https://github.com/video-dev/hls.js/pull/5778 needs to be applied asap.
Fixes https://github.com/video-dev/hls.js/issues/5777

Merge bugfix/live-append-only-endlist into patch v1.4.x branch

---

docs/API.md

I didn't know this and found myself getting confused when trying to access buffered data. Perhaps this will help others.
Docs only, so grammar checks would be appreciated. Also anything else to be noted?
- [N/A] new unit / functional tests have been added (whenever applicable)

API docs: add more info around backBufferLength

---

package.json

This PR updates the serve command in package.json to fix the issue with the http-server command opening the page incorrectly. The command parameter is modified to ensure the page opens correctly.
The current configuration in package.json causes the http-server command to open the page incorrectly, resulting in a failed page load. This pull request updates the serve command to fix this issue and open the page correctly.
Please review the modifications in the serve command to ensure that the page is opened correctly and that there are no unintended side effects.
N/A

Fix http-server path in package.json

---

src/utils/mp4-tools.ts

In mp4-tools.ts
* Fixed parsing for sei_message, by always consuming the entire message, before parsing the message according to payload_type
* Fixed payloadType / payloadSize parsing to ensure they never exceed 255, as the field is restricted to 8 bytes.
Resolve 608 caption issues.
To fix issues described in  #5952 
Automated tests?
#5952 

Fix issues with long cea608 captions. #5952

---

build-config.js
src/controller/id3-track-controller.ts
src/polyfills/number.ts
src/utils/mp4-tools.ts

Cherry-pick fixes for legacy WebKit UAs:
- #6021
- #6022

Cherry-pick fixes for v1.4.13

---

src/controller/id3-track-controller.ts

Fix handling of the DATERANGE END-ON-NEXT attribute
I noticed that we could do away with sorting to find the next DateRange after one with END-ON-NEXT, only to find that `candidate.id !== id` was always false meaning that we would never find the next DateRange.
This change fixes the id comparison and handles all logic in the reduce method so that we don't need to sort.
I'm not adding tests for this fix. The plan is to break out this code and add tests as part of Interstitial work for v1.6.

Fix handling of the DATERANGE END-ON-NEXT attribute

---

src/controller/abr-controller.ts
src/controller/level-controller.ts

Pulls in v1.5.2 patch from #6135 into development.
Fixes #6122

Use average for level sorting and abandon rules check (#6135)

---

src/controller/abr-controller.ts
tests/functional/auto/setup.js

Fix regression in hls.light.js selection (Cherry picked from #6155)
Fixes #6151

Fix regression in hls.light.js selection

---

tests/test-streams.js

Reverts video-dev/hls.js#6176
Stream is fixed

Re-enable `AppleAdvancedHevcAvcHls` stream

---

docs/API.md

Adds missing docs for `cmcd.includeKeys`.

Update API.md for CMCD `includeKeys`

---

src/controller/base-stream-controller.ts

Clean up base-stream-controller
Small followup to #6227
- #6227

Clean up base-stream-controller

---

src/types/general.ts
src/utils/hash.ts
src/utils/webvtt-parser.ts

- Move hash function into utils
- Remove unused type and types/general.ts
This hash function will be used to create IDs for Interstitial assets and CMCD player content in #5730

Move hash function into utils

---

src/controller/buffer-controller.ts

Fix access of media src value with non-source children (#6611)

---

src/controller/eme-controller.ts

Fix Tizen 2017 Widevine playback
https://github.com/video-dev/hls.js/issues/4962

fix: tizen 2017 widevine playback

---

README.md

add documentation on time offset introduced by HLS transcoding (kudos to @robwalch for providing the code in issue [6649](https://github.com/video-dev/hls.js/issues/6649))
This information would be very useful for users who create e.g. video timeline annotations on an original video and needs the HLS stream to be in sync with that.
This is purely a documentation PR.

Document time offset in HLS

---

src/controller/interstitials-controller.ts
tests/unit/controller/interstitials-controller.ts

Handle Interstitials with empty asset-lists
If the asset list returns an empty `ASSETS` array, the client SHOULD apply the resume offset without playing any interstitial content.
This case is not being handled gracefully. Playback gets stuck waiting for the asset list.

Handle Interstitials with empty asset-lists

---

src/controller/stream-controller.ts

Handle alternate audio switching and switched states.
Prevents main audio from being appended while switching to alternate (#6812).
Fixes #6812

Handle alternate audio switching and switched states

---

README.md

Update the `README.md`, add [ArtPlayer](https://artplayer.org/?libs=https://cdnjs.cloudflare.com/ajax/libs/hls.js/1.5.17/hls.min.js&example=hls) Integration
Currently ArtPlayer is also a popular web player. Hope more people will know it.

Add ArtPlayer Integration

---

src/controller/audio-stream-controller.ts

Ignore main playlist loading when loading audio rendition in audio-only asset.
Ensures audio-only renditions are not blocked from loading.

Unblock audio-only rendition loading

---

package.json

Add shortcat for `light` version
Light way to connect light version
`import HLSLight from 'hls.js/light';`

Add shortcat for `light` version

---

src/demux/video/hevc-video-parser.ts

[6895](https://github.com/video-dev/hls.js/issues/6895)

Support HEVC VPS coming after SPS

---

src/controller/eme-controller.ts
src/loader/key-loader.ts
src/loader/level-key.ts
src/utils/mediakeys-helper.ts
tests/unit/controller/eme-controller.ts

Cherry-pick #6946 and #6644 into v1.5.x patch
Support for encrypted event with PlayReady when Widevine pssh are also present.
#6947

Fix assumptions in Multi-DRM cases where only PlayReady is available

---

src/utils/level-helper.ts
tests/unit/controller/level-helper.ts

Fix delta updates with discontinuity tags (v1.5.x patch)
Cherry-picked from #6950
Fixes #6949

Fix delta updates with discontinuity tags (v1.5.x patch)

---

api-extractor/report/hls.js.api.md
src/loader/level-details.ts
src/loader/m3u8-parser.ts
src/utils/level-helper.ts
tests/unit/controller/cmcd-controller.ts
tests/unit/controller/level-helper.ts

Update segment discontinuity sequence numbers (`Fragment.cc`) correctly when merging delta playlist updates.
#6949

Fix delta updates with discontinuity tags

---

src/controller/audio-stream-controller.ts

Fix a bug where buffered audio with different characteristics are not flushed when audio track switch has the same name and language.
Removed `mediaAttributesIdentical` and the old case that caused the problem in favor of `matchesOption` rendition-helper which does characteristics array comparison (just in case multiple characteristics are present but not in the same order).
Fixes #6962

Fix audio track switch where only characteristics differ

---

api-extractor/report/hls.js.api.md
src/controller/buffer-controller.ts
src/controller/level-controller.ts
src/controller/stream-controller.ts
src/demux/mp4demuxer.ts
src/hls.ts
src/loader/m3u8-parser.ts
src/remux/passthrough-remuxer.ts
src/types/buffer.ts
src/types/demuxer.ts
src/types/level.ts
src/utils/attr-list.ts
src/utils/codecs.ts
src/utils/mediacapabilities-helper.ts
src/utils/mp4-tools.ts
tests/index.js
tests/unit/controller/buffer-controller.ts
tests/unit/controller/error-controller.ts
tests/unit/loader/m3u8-parser.ts

Parse supplemental codecs and skip auto selection when support check fails
#5558

Supplemental codecs support

---

src/utils/mp4-tools.ts

Parse all init segment track headers so that all track base decode timestamps are updated. This fixes timestamp alignment of in-band metadata and captions with fmp4 "pass-through" remuxer.
Prevents errors in cases where track metadata is required for enhanced media playback.

Fix fmp4 track timestamp alignment for non-av tracks

---

src/controller/abr-controller.ts
src/controller/base-stream-controller.ts
src/controller/interstitials-controller.ts
src/controller/interstitials-schedule.ts

- Manage interstitial stalls (nudge on asset player stall)
- Improve jagged discontinuity fragment selection at interstitial boundaries
- Fix issue with allowing append-in-place for interstitial at end of program

Manage interstitial stalls

---

src/controller/buffer-controller.ts

Make appendBuffer error fatal when HTMLMediaElement.error is present.
There is no point in retrying appends when the media element in in an error state.
Related to #7116

Make appendBuffer error fatal when HTMLMediaElement.error is present

---

src/controller/buffer-controller.ts

Catch errors in SourceBuffer blocked callbacks
Prevents out-of-sequence invalid state errors or exceptions in `BUFFERED_TO_END` and `FRAG_BUFFERED` event handlers from interrupting execution of the buffer operation queue.
Resolves #7138

Fix streaming interruption by exception thrown setting MediaSource duration

---

src/utils/mp4-tools.ts

Guard against exceptions when parsing incomplete 'avcC', 'hvcC', 'vpcC', and 'av1C' boxes.
Internal exceptions are not helpful in troubleshooting bad media.
Resolves #7142

Guard against exceptions when parsing incomplete codec boxes

---

.eslintrc.js
package-lock.json
package.json
src/controller/cmcd-controller.ts
tests/functional/auto/.eslintrc.js

This pull request is being created with reference to [this conversation ](https://github.com/video-dev/hls.js/pull/7184#discussion_r2051185512)as below where we discussed that it will be better that we setup this eslint rule so that it automatically gives error for using for of loops, maintaining code consistency.
- Conversation link - https://github.com/video-dev/hls.js/pull/7184#discussion_r2051185512
I have updated at once place where for of loop was being used and I have replace it with `forEach` so we can check that part once.

Setup eslint no for loops rule

---

src/utils/mp4-tools.ts

Fix mp4 parsing regression introduced into development with #7199
Fixes streaming of full segments in MUX Low-Latency HLS asset. config: `"lowLatencyMode": false`:
https://hlsjs-dev.video-dev.org/demo/?src=https%3A%2F%2Fstream.mux.com%2Fv69RSHhFelSm4701snP22dYz2jICy4E4FUyk02rW4gxRM.m3u8&demoConfig=eyJlbmFibGVTdHJlYW1pbmciOnRydWUsImF1dG9SZWNvdmVyRXJyb3IiOmZhbHNlLCJzdG9wT25TdGFsbCI6ZmFsc2UsImR1bXBmTVA0IjpmYWxzZSwibGV2ZWxDYXBwaW5nIjotMSwibGltaXRNZXRyaWNzIjotMX0=

Fix mp4 parsing regression

---

src/controller/interstitials-controller.ts

Trim buffered assets past X-PLAYOUT-LIMIT on late schedule update.
Support live HLS updates of playout limit after buffering or playing of assets past the limit. Prior to these changes, if an interstitial was set to append in place, and it buffered past a new X-PLAYOUT-LIMIT, the buffered content may still play through.
Fixes #7239

Support late X-PLAYOUT-LIMIT update with append-in-place interstitials

---

src/utils/mp4-tools.ts

Fix regression in audio sample duration calculation introduced in v16.3 with #7199
#7199 introduced a bug where duration of mp4 segments without a default sample duration were treated as 0, blocking streaming of these segments.
Fixes #7289

Fix mp4 audio sample duration calculation regression

---

src/utils/mp4-tools.ts

Parse PSSH box when 'version' is 1. PSSH box defines as follows:
```
aligned(8) class ProtectionSystemSpecificHeaderBox extends FullBox('pssh', version, flags=0)
{
unsigned int(8)[16]                SystemID;
if (version > 0)
{
unsigned int(32)              KID_count;
{
unsigned int(8)[16]       KID;
} [KID_count];
}
unsigned int(32)                   DataSize;
unsigned int(8)[DataSize]          Data;
}
```
When version of PSSH box is 1, parsing value is an error.

fix: parse PSSH box error

---

api-extractor/report/hls.js.api.md
src/controller/base-playlist-controller.ts
src/controller/base-stream-controller.ts
src/controller/interstitials-schedule.ts
src/loader/level-details.ts
src/utils/level-helper.ts
tests/unit/controller/level-helper.ts

- Remove unnecessary conditionals
- Use instance logger in level-helper functions
- Detect and warn on large segment timestamp changes
General maintenance made by strengthening TypeScript checks in local development (@typescript-eslint/no-unnecessary-condition will be added later).

Remove unnecessary conditionals

---

tests/functional/auto/setup.js

Improve functional test logs
