video-dev/hls.js

- src/controller/buffer-controller.ts
- tests/unit/controller/buffer-controller-operations.ts
Clear muxed "audiovideo" SourceBuffer on BUFFER_FLUSHING without SourceBufferName type
Operations are now queued based on which SourceBuffers have been created. This allows HLS.js to remove content from the forward buffer when switching qualities, as well as clear the back buffer.
Prior to these changes, "audio" and "video" remove operations were queued regardless of which buffers were present. This meant media with only one "audiovideo" SourceBuffer would not have its buffer ejected by the browser, preventing immediate or next segment quality switching and back-buffer removal from working as expected. 
Resolves #3850
> Clear muxed "audiovideo" SourceBuffer on BUFFER_FLUSHING 

- src/controller/base-stream-controller.ts
- src/task-loop.ts
- tests/unit/controller/subtitle-stream-controller.js
- Yield before calling `tick` on seek so that async abort behavior can complete before loading the next fragment
- Don't abort forward buffer fragment requests on seek since this can abort the next fragment at buffer end
- Exit from `flushMainBuffer` when the range is invalid (length of `0`)
Prevents HLS.js from looping on fragment load and abort when seeking to or starting on a segment with a gap. This occurs mostly in streams that drop frames from segments that do not start with a keyframe.
Fixes #3811 #3847
> Prevent async abort handler from causing current fragment to be reloaded

- src/controller/stream-controller.ts
- src/remux/mp4-remuxer.ts
- src/types/remuxer.ts
Perform preemptive backtracking in streams with segments that do not start with a video keyframe.
If a seek or level switch moves buffering to a non-contiguous point in the stream, and the segment meant to fill the buffer at that position cannot, because it does not start with a keyframe, the player needs to backtrack. This happens when video samples are dropped due to keyframes being located after the start of a segment, and media can only be appended ahead of the play-head.
Backtracking is inefficient in the current player architecture. Side-effects include:
- Reloading of segments that require backtracking to an earlier segment (since data is neutered once sent to the worker, and backtracking resets the transmuxer-worker)
- Removal of content from the buffer for backtrack loading
- …
> Preemptive backtracking

- src/controller/level-controller.ts
- tests/unit/controller/level-controller.ts
Use RESOLUTION and CODECS attributes in addition to BANDWIDTH to group levels (STREAM-INF variants) for redundant fallback.
A stream might have two variants with the same RESOLUTION and BANDWIDTH, but alternative CODECS (like HEVC and H.264) not intended for redundant fallback.
Resolves #3888
> Require redundant levels to have matching RESOLUTION and CODECS attributes

- demo/chart/timeline-chart.ts
- src/demux/transmuxer-interface.ts
- src/demux/transmuxer-worker.ts
- src/demux/transmuxer.ts
- src/remux/mp4-remuxer.ts
- src/types/remuxer.ts
- Pass transmuxer-interface id (playlist type) into transmuxer so that when remuxing alt-audio, samples are aligned with video based on PTS.
- Remux overlapping AAC samples so that they are appended over earlier samples segment rather than dropping them. 
- Remove redundant audio drop/backfill code in remuxer.
[This mp4-remuxer workaround](https://github.com/video-dev/hls.js/commit/e478757a62e02681e87f34479593962a93601945#diff-fccedeec0ef12b083f3e18534af86e02cecca386bce4d9f328048b5423f2e9e3R756-R763) was disabled in transmuxers for audio-only streams to prioritize segment timing over PTS. This had the side-effect of appending overlapping samples in alt audio-tracks. This is something that happens a lot in certain DAI live streams leading to audio drift.
To keep alt-audio in sync with the …
> Fix audio drift in DAI streams with overlapping AAC samples

- src/demux/aacdemuxer.ts
- src/demux/adts.ts
- src/demux/base-audio-demuxer.ts
- src/demux/mpegaudio.ts
- src/demux/tsdemuxer.ts
- src/remux/mp4-remuxer.ts
- src/types/demuxer.ts
- tests/unit/demuxer/adts.js
Store the entire parsed `AudioFrame` and partial sample in tsdemuxer `aacOverFlow`. This includes the frame's original PTS, and how many bytes are missing. The remainder is taken from the following AAC PES, added to the sample, and appended to the track. Then that PES's PTS is applied to the following sample.
This avoids the `[tsdemuxer]: AAC: align PTS for overlapping frames by N` warning logs that were really not needed because all this was saying was that we should be using `aacLastPTS` rather than the current PTS for the samples following the remainder of the ACC overflow bytes.
Overflowing samples are only parsed and allocated once, so PES data remains constant resulting in less memory allocation.
Resolves #3920
> Handle AAC overflow with error message

- src/controller/audio-stream-controller.ts
Use `startPosition` to determine if audio-stream-controller waiting fragment should be cleared.
While waiting for init PTS from the stream-controller's first video segment, the audio-stream-controller will prefetch a segment, and then on tick, check if that `waitingFragment` is correct for the current loading context. If not it is cleared so that it can prefetch a better match.
The logic for this used the initial `video.currentTime` of `0` which doesn't match `startPosition`. The player only seeks after media has been buffered to avoid multiple seeks or stalls so it's important that this check use `this.getLoadPosition()` instead. That way  `startPosition` is honored until media is buffered and `video.currentTime` has been adjusted to start playback at the start position.
Fixes #3950
> Fix incorrect audio track segments loaded before video segment with > 0 startPosition

- src/controller/audio-stream-controller.ts
- src/controller/base-stream-controller.ts
- src/controller/buffer-operation-queue.ts
- src/controller/stream-controller.ts
- src/controller/subtitle-stream-controller.ts
- src/utils/buffer-helper.ts
- Fix forward buffer length estimation when in a gap not spanned by `maxBufferHole` (#3914)
- Fix buffer controller blocked after "SourceBuffer is full" append error
- Cleanup fragment-tracker with `afterBufferFlushed` on tick with audio-stream-controller to prevent the player from clearing audio segments not yet shown in the buffer after `onBufferFlushed` 
Prevents hls.js from over-buffering because of incorrect estimation at a gap. Recovers correctly when buffering does fail because of a SourceBuffer full error.
Resolves #3914
> Fix forward buffer length estimation and error handling

- src/controller/base-stream-controller.ts
Apply and clamp `EXT-X-START: TIME-OFFSET` according to spec with regards to live window
The sliding window start was not accounted for TIME-OFFSET is a positive value. This resulted in  `startPosition` being set to `TIME-OFFSET` when resetting the start position after a live sliding window playlist refresh.
#3913
> Fix application of EXT-X-START: TIME-OFFSET in live after refresh

- src/controller/base-playlist-controller.ts
- src/controller/base-stream-controller.ts
- src/controller/level-helper.ts
Fix "The loading context changed while buffering fragment" in live streams loading removed fragment
When the transmuxer completes work on a segment, the stream controller looks for the fragment with a matching sn matching the transmuxer's context. If the fragment was removed from the live sliding window, the fragment was not found and the media would not be appended.
Instead, use the stream controller's `fragCurrent` in this case to complete buffering of the fragment.
#3913
> Fix last segment in live removed "context changed" error

- src/controller/base-stream-controller.ts
Cleanup `alignPlaylists` in base-stream-controller. This makes it clear why `alignStream` is being called. Logging is only performed after a call to `alignStream` with pertinent information.
Warnings were being logged on stream start that did not merit that level of logging. The three different logger messages were not always very helpful or informative.
With these changes we'll only see logs when:
1. There are not fragments (this does merit a warning if an error hasn't already occurred)
2. Action was taken to align the stream after a refresh or first switch to a new level    
Resolves #3933
> Replace live playlist sliding warnings with improved logging

- src/controller/fragment-tracker.ts
- src/controller/subtitle-stream-controller.ts
- src/controller/timeline-controller.ts
- Clear subtitle cues from the back-buffer
- Remove loaded subtitle data from the fragment-tracker
Longform VOD and live streams with VTT or IMSC1 subtitles should have data and cues cleared with the back-buffer to free up memory. The fragment-tracker was particularly leaky with memory as the loaded data was being added and never removed for each subtitle fragment loaded.
> Remove subtitle cues and data with the back-buffer

- src/remux/mp4-remuxer.ts
Fix mid-stream insertion of missing AAC audio frames
TS streams with missing AAC samples ended up with bad sample times after frames were inserted after 74ac1002ef60ffd81f515899f63debca961e3369. This happened when earlier samples were pushed forward more than a sample duration, and the remaining samples were not retimed properly.
Resolves #3976
> Fix mid-stream insertion of missing AAC audio frames

- api-extractor/report/hls.js.api.md
- src/controller/audio-stream-controller.ts
- src/controller/level-helper.ts
- src/controller/subtitle-stream-controller.ts
- src/controller/subtitle-track-controller.ts
- src/controller/timeline-controller.ts
- src/types/events.ts
- src/utils/texttrack-utils.ts
- tests/unit/controller/subtitle-stream-controller.js
- Align live WebVTT subtitle playlists with main variant using media-sequence when program-date-time is unavailable/
- Fix a regression in v1.0.5 where a subtitle track is enabled after back-buffer removal sets a track's mode to "hidden"
- Update audio-stream alignment with main to be simpler. Both subtitle and audio live playlists will wait for main before being aligned and loading fragments
- Subtitle playlists will be realigned with main if they get into a state where a loading fragment candidate cannot be found
Subtitle tracks should be aligned when enabled with the main playlist based on Program-Date-Time when available. Otherwise, aligning on SN may work as is the case with the test stream in #3987
Resolves #3987
> Align live WebVTT subtitle playlists with main playlist

- src/utils/buffer-helper.ts
Fix regression introduced in v1.0.6 with #3993 where subtitle track segment loading at a position less than target duration only loads the first segment.
(only appears in streams with irregularly large target durations compared to segment duration)
The position argument passed to `bufferedInfo` should never be less than 0 as that is almost certain to not intersect with any buffered time range. subtitle-stream-controller passes in the current time - target duration so that it loads all subtitles at and adjacent to the current time. That resulted in negative values being passes to our buffer util which resulted in misses getting the end of the subtitle stream buffer.
> Fix subtitle segment loading with current time less than target-duration

- .github/release-drafter.yml
- .github/workflows/build.yml
- docs/release-process.md
Only create the draft release when a tag is pushed instead of keeping one up to date all the time.
I'm not sure the 'live' one is useful, and having it might result in accidentally publishing a release without the build attached if the tag build hasn't completed yet.
If you think the live one is useful we can close this.
> Only draft release on tag

- src/utils/xhr-loader.ts
Move the call to set the headers (added in https://github.com/video-dev/hls.js/pull/4346) to after the `XMLHttpRequest` is opened.
Without this you get an error when enabling CMCD with `useHeaders: true`.
Otherwise if the `XMLHttpRequest` is not open it throws an exception.
fixes #4422
> set headers after XMLHttpRequest OPEN

- src/controller/level-helper.ts
- tests/unit/controller/level-helper.ts
Prevent unnecessary requests for the same initialization segment. For live video, merging playlists did not updated non-overlapping fragments. Now, the level-helper will update any non-overlapping fragmentHint or fragments to reference existing initSegment fragments.
When multiple EXT-X-MAP support was included https://github.com/video-dev/hls.js/pull/3859, live playlists that include EXT-X-MAP may unnecessarily request the same initialization segment multiple times.
I'm not super familiar with LL-HLS so it took me a while to figure out I needed to also include the `fragmentHint` in the update check. If there's something else missing with LL-HLS integration let me know and I can work through those issues. I've tested with the LL-HLS test stream
I've verified the behavior with some …
> Fix repeated requests for initialization segments

- src/controller/timeline-controller.ts
Fix issue of CC of low latency streams not displayed correctly
cea608parser will be reset when sn of currently loaded fragment is not as same as last sn + 1, which is wrong for low latency streams. For low latency case, parts of a segment is loaded with same sn, cea608parser shouldn't be reset.
https://github.com/video-dev/hls.js/blob/1ea75a236151c1ce4ee0cdf6829b571465a75c3f/src/controller/timeline-controller.ts#L429-L433
No.
https://github.com/video-dev/hls.js/issues/4297
> Bugfix: CC of low latency streams not displayed correctly

- src/controller/subtitle-stream-controller.ts
This PR resets the `fragPrevious` on the subtitle stream controller.
After switching subtitle tracks, it doesn't load new subtitle frags (`webvtt` files).
In my particular case, the subtitle playlist is very long. When a subtitle track is switched, instead of loading current time's frags, it loads the one that continue from previous subtitle track. In my specific case, I had to wait like a minute in order to reach the loaded frags of the new track.
Please some help in order to introduce functional tests :).
- #4403
> bugfix: Reset fragPrevious when there is a subtitle track switch

- src/demux/tsdemuxer.ts
Improve error reporting
In order to improve error reporting we want to report only one `FRAG_PARSING_ERROR` per parsed `TS`.
&nbsp;-&nbsp;
https://github.com/video-dev/hls.js/issues/4469
> Report only 1 FRAG_PARSING_ERROR per parsed TS file

- src/utils/output-filter.ts
Fix cues for 608 live captions having a wrong start time after seek.
608 cues can have a wrong start time after seek back>forward>back, which causes captions to be shown at the wrong time position.
Whether this can have any side effects on 608 captions behavior.
https://github.com/video-dev/hls.js/issues/4466
> clear cue start time on reset

- src/controller/gap-controller.ts
- tests/unit/controller/gap-controller.js
Fix nudge retries happening one time fewer than `nudgeRetry` config
It's one off.
I'm wondering if we should treat this as a breaking change and maybe just update the docs instead?
Or we could change the default from value from 3 to 2 so there's no behaviour change for people who haven't set the config option.
Or maybe it's fine. My concern is if people are expecting there to be X events and now there will be X + 1.
> Fix nudge retries happening one time fewer than `nudgeRetry` config

- README.md
- src/demux/mp4demuxer.ts
- src/remux/mp4-remuxer.ts
- src/remux/passthrough-remuxer.ts
- src/utils/mp4-tools.ts
Add support for emsg timed metadata within fragmented MP4. 
These changes allow for timed metadata delivery (ID3 via emsg) for use cases such as content labeling and advertising in CMAF streams in the same way HLS.js currently supports ID3 in other container formats. 
`HTMLMediaElement` text track and cues generated by HLS.js are similar in timing and content to those added with native HLS playback in Safari. 
Supported schemas include any url containing "/emsg/ID3" or "/emsg-id3" (case insensitive).
Sample test streams from #2360: 
- https://d24rwxnt7vw9qb.cloudfront.net/out/v1/62a7ec8a0f3b4f19ad76eac54f2f2dce/cmaf-clear/index.m3u8
- http://db2.indexcom.com/bucket/ram/00/01x/256k/program.m3u8 
- https://storage.googleapis.com/dlevin/tmp/fmp4-emsg-id3/1567191409/master.m3u8
Closes #2360
> Add support for emsg ID3 metadata in fmp4 segments

- src/loader/m3u8-parser.ts
- tests/unit/loader/playlist-loader.js
Fix level playlist parse error when `#EXT-X-PROGRAM-DATE-TIME` appear before `#EXT-X-MAP`
When `#EXT-X-PROGRAM-DATE-TIME` appear before `#EXT-X-MAP`, `rawProgramDateTime` of currentInitSegment will be set:
https://github.com/video-dev/hls.js/blob/116e7cd4b93b4adf45159e3684c9ec3d2cfd8f80/src/loader/m3u8-parser.ts#L274
Then `rawProgramDateTime` of the following fragments will be set to same `rawProgramDateTime`:
https://github.com/video-dev/hls.js/blob/116e7cd4b93b4adf45159e3684c9ec3d2cfd8f80/src/loader/m3u8-parser.ts#L228-L231
Thus, `programDateTime` will be set to wrong value in function `assignProgramDateTime`:
https://github.com/video-dev/hls.js/blob/116e7cd4b93b4adf45159e3684c9ec3d2cfd8f80/src/loader/m3u8-parser.ts#L613-L615
So `currentInitSegment.rawProgramDateTime` need to be cleared …
> fix: level playlist parse error of ProgramDateTime

- README.md
- api-extractor/report/hls.js.api.md
- src/controller/timeline-controller.ts
- src/demux/aacdemuxer.ts
- src/demux/base-audio-demuxer.ts
- src/demux/dummy-demuxed-track.ts
- src/demux/mp3demuxer.ts
- src/demux/mp4demuxer.ts
- src/demux/transmuxer.ts
- src/demux/tsdemuxer.ts
- src/loader/fragment-loader.ts
- src/remux/passthrough-remuxer.ts
- src/types/demuxer.ts
- src/utils/imsc1-ttml-parser.ts
- src/utils/mp4-tools.ts
Add extraction of 608 captions from fragmented MP4 segments. HLS.js will handle captions found in MP4 segments, as it does for MPEG-2 TS segments.
- Add support for CMAF SEI 608 captions in AVC and HEVC video tracks - Resolves #2623
- Optimize SEI and CEA608 caption extraction
- Remove `Mp4BoxData` from mp4-tools and replace it with `Uint8Array[]` views for all results from `findBox`
- Replace use of `ExpGolomb` decoder with mp4-tools data methods for reading bytes from SEI NALu packets
- Parse all unregistered SEI messages so that they are present in `FRAG_PARSING_USERDATA` API events - Resolves #4242
- Rename the DemuxerResult field `avcTrack` to `videoTrack` since this track carries video of any codec (not just AVC) and rename its interface from `PassthroughVideoTrack` to …
> Add support for CMAF SEI Captions

- src/utils/webvtt-parser.ts
Removes unnecessary code, 1.x.x versions do not need this code, they already have the cueOffset calculation fixed
subtitle stream without X-TIMESTAMP-MAP, has incorrect cue start/end time 
#4500
> Bugfix/webvtt-parse: cue offset (subtitle stream without X-TIMESTAMP-MAP)

- src/controller/latency-controller.ts
Fix bug of forwardBufferLength calculation.
I think forwardBufferLength should be buffered.end - this.currentTime or levelDetails.edge - this.currentTime, so the statement should be:
```
(bufferedRanges ? media.buffered.end(bufferedRanges - 1) : levelDetails.edge) - this.currentTime
```
While current statement will return media.buffered.end(bufferedRanges - 1) instead.
No.
N/A
> Bugfix: forwardBufferLength calculation

- src/hls.ts
Resolves #4628 
`minAutoLevel` API returns the wrong value when an exact bitrate is used for `player.config.minAutoBitrate`.
#4628
> Allow exact bitrate matches for minAutoLevel getter

- src/controller/audio-stream-controller.ts
- tests/unit/controller/audio-stream-controller.js
The problem is that sometimes the onLevelLoaded event comes just after onAudioTrackLoaded, and then everything has to wait around for the entire segment time before it finally gets going.
A very simple workaround looks like this, but that has some rather obvious downsides:
```diff
diff --git a/src/controller/audio-stream-controller.ts b/src/controller/audio-stream-controller.ts
index e9fa2d1c..91e16dc9 100644
--- a/src/controller/audio-stream-controller.ts
+++ b/src/controller/audio-stream-controller.ts
@@ -433,7 +436,14 @@ class AudioStreamController
if (!newDetails.fragments[0]) {
newDetails.deltaUpdateFailed = true;
}
if (newDetails.deltaUpdateFailed || !mainDetails) {
+        setTimeout(() => {
+          this.hls.trigger(Events.AUDIO_TRACK_LOADED, data)
+        }, 100)
return;
}
if …
```
> Retry aligning audio playlist with main playlist if levelloaded came too early

- src/controller/eme-controller.ts
Fix several uncaught drm exceptions when call load/unload frequently.
`keySession.update` is called in a callback. And it will raise exception when trying to update keys which belong to closed key session:
```
Uncaught (in promise) DOMException: Failed to execute 'update' on 'MediaKeySession': The session is already closed.
at https://hls-js.netlify.app/dist/hls.js:6259:18
at EMEController._onLicenseRequestReadyStageChange (https://hls-js.netlify.app/dist/hls.js:6457:11)
```
No
https://github.com/video-dev/hls.js/issues/4576
> Bugfix: Failed to execute 'update' on 'MediaKeySession

- README.md
Update jsdelivr urls in readme to point at canary and v1. People should probably use `v1` not `latest` so that they don't accidentally get a version with breaking changes in the future, which might not match the example they copied the url from.
refs https://github.com/video-dev/hls.js/discussions/4714
> update jsdelivr urls in readme to point at canary and v1

- src/utils/fetch-loader.ts
when destroying, 'error' itself can be undefined
> Fix exception in fetch-loader error handler

- src/controller/stream-controller.ts
**Summary:**
Bug fix:
Segment loading may stop when level switching while using the fetch loader.
**Steps To Reproduce:**
1. Add `"progressive": true` to the config to use the fetch loader to stream segments
2. Switch current/next/loadingLevel while playing
**Results:**
If the streaming fragment is aborted while the stream controller’s state is loading or parsing, the state is not reset to IDLE and no more segments are loaded.
This Pull Request fixes the issue described above.
> Bugfix: Network hangs on streaming level switch using fetch loader

- api-extractor/report/hls.js.api.md
- docs/API.md
- src/controller/audio-stream-controller.ts
- src/controller/id3-track-controller.ts
- src/controller/stream-controller.ts
- src/types/events.ts
Update ID3 cues in timed metadata text tracks to span until the playlist end or until the start of the next cue with the same frame type. 
This change improves the handling of ID3 metadata for applications using metadata TextTrack active cues. Since ID3v2 frames have no duration or end time, cues should remain active until the HLS playlist's end or until another cue with the same ID3 frame type begins. 
In Safari, DataCues are assigned an endTime of Infinity, but since HLS.js may use VTTCues, which must have finite start and end times, the current playlist end time was chosen to keep the number of active cues manageable. Applications wishing to modify the default endTime of new cues may do so on "cuechange". 
Resolves #3879
> Update ID3 cues to span until playlist end, or next cue with same tag type (value.key) on cue append

- README.md
- api-extractor/report/hls.js.api.md
- docs/API.md
- src/controller/id3-track-controller.ts
- src/controller/level-helper.ts
- src/controller/stream-controller.ts
- src/demux/base-audio-demuxer.ts
- src/demux/mp4demuxer.ts
- src/demux/tsdemuxer.ts
- src/hls.ts
- src/loader/date-range.ts
- src/loader/level-details.ts
- src/loader/m3u8-parser.ts
- src/types/demuxer.ts
- src/utils/texttrack-utils.ts
- tests/unit/loader/date-range.ts
Parse and validate Date Range tags in HLS playlists on playlist load. Date Range tags are converted to cues on the HTMLMediaElement's metadata text track on level update. In addition, the presence and duration of Date Range cues (as well as inband ID3 and emsg metadata cues already supported by HLS.js) are updated to reflect the Date Range content of the active playlist and inband metadata found in buffered audio/video tracks.
These updates should more closely match the metadata text track cues produced by Safari when playing the same HLS stream natively in Safari. 
- Add `hls.playingDate` to API: gets program date time at media playhead (`video.currentTime`) 
- Fixed build regression by formatting code with prettier
Resolves #2218
> Add Support for EXT-X-DATERANGE Metadata

- api-extractor/report/hls.js.api.md
- docs/API.md
- src/config.ts
- src/controller/id3-track-controller.ts
- src/hls.ts
Add configuration options to disable metadata TextTrack Cue processing by type.
With the additional support for new types of metadata parsing being added in v1.2.0 (emsg #4458, DATERANGE #4720), the performance and functionality of existing implementations could be impacted by upgrading to the new version. Developers will benefit from being able to disable cue processing at player instantiation when their app does not intend to use TextTracks for specific types of metadata. Their app may already parse certain types of metadata using HLS.js events. Avoiding cycles used to parse and update unused cues and overlap with cues they add outside of HLS.js will allow for a more straightforward transition to v1.2.0.
HLS.js events such as `FRAG_PARSING_METADATA` (signals ID3/emsg parsed) and …
> Config options to disable metadata TextTrack Cue processing

- src/demux/transmuxer-interface.ts
Fixes bug of playback stuck after BUFFER_FULL_ERROR when maxBufferSize set to a very big value.
###Why is this Pull Request needed?
Per design, contiguous will be true when:
- track not switched
- sn in sequence
- or same sn but part sn in sequence (low latency mode)
But partDiff is always 1 in current implementation for non-low-latency streams, so contiguous will be true even sn is same, which is not correct.
No.
> Bugfix: freeze after buffer full error occur

- src/remux/mp4-remuxer.ts
Prevent us from using negative DTS values in AVC moof atoms in Panasonic Smart TVs.
Some new Panasonic Smart TVs have a `navigator.userAgent` string like this one:
`HbbTV/1.4.1 (;Panasonic;VIERA 2020;a.393;4301-0003 0008-0000;) PanasonicSDK/2017`
These Smart TVs use an old version of Chrome like Chrome 51, and this browser needs the positive DTS gate. It's like the following pull requests for Panasonic Smart TVs:
https://github.com/video-dev/hls.js/pull/3224
https://github.com/video-dev/hls.js/pull/2995
> Include Panasonic Smart TVs and other old browsers in positive DTS gate

- src/demux/adts.ts
- src/demux/tsdemuxer.ts
- tests/unit/demuxer/adts.js
Fix playback of HLS streams with MPEGTS segments when AAC overflow occurs within the ADTS header.
Without this fix data is dropped before being appended which can lead to buffer/decoder corruption (see #4732).
Fixes #4732
Relates to #4506
> Fix AAC overflow when it occurs at ADTS header

- src/controller/subtitle-track-controller.ts
Set track mode of active subtitle track when `hls.subtitleDisplay` is set.
Fixes #4530
> Bugfix: `hls.subtitleDisplay` doesn't toggle visibility until track selection

- src/controller/gap-controller.ts
- tests/unit/controller/gap-controller.js
Guard against exceptions caused by destroying player in buffer stall error callbacks.
The `media` property of GapController is cleared when the player is destroyed. Some applications choose to do this on BUFFER_STALLED_ERROR events. Improved type handling and some early returns correct this behavior.
Prior to triggering BUFFER_STALLED_ERROR, log the full `BufferInfo` object rather than just the buffer length from currentTime. This will help identify stalls in Chrome that occur ~1s after playing through buffer gaps (a new buffered range "start"). This is for issues like #4470.
Fixes #4525
Related to #4478
> Guard against exceptions caused by destroying player in buffer stall error callbacks

- src/demux/tsdemuxer.ts
When demuxing MPEG2 transport streams, include NAL unit type 12 filler data in output samples.
Prevents decode playback errors on ARM hardware. 
Fixes #4787
> Include NAL filler data in AVC samples

- src/controller/base-stream-controller.ts
Skip part tune-in when there is no part target.
Streams with blocking reload can be made to reload indefinitely without picking a start position when this method incorrectly returns true. In this case this method expects a part target or part holdback but the stream played does not use parts and has neither tags/attributes.
Fixes #4766
> Bugfix: Slow start on stream with CAN-BLOCK-RELOAD=YES

- src/remux/mp4-remuxer.ts
Keep track of last or average video sample duration in TS->MP4 remuxer, and use this value (or a default of 1/30s) when remuxing a single sample. Also allow a single video sample on remuxer flush to ensure all video samples in a segment are processed even if there is only one sample.
Without this change HLS.js will not process single sample segments. We can encounter streams or discontinuity sequences that end with a single video sample or frame.
There is no way in the demuxer currently to determine duration of single sample or fps of media in a TS segment without comparing samples.
Fixes: #4783
> Bugfix: Handle single sample MPEG2-TS video segments

- src/controller/base-stream-controller.ts
- src/controller/buffer-controller.ts
- src/demux/transmuxer-worker.ts
- src/loader/fragment.ts
- Emit FRAG_PARSED when parsed fragment has no media. This will update the fragment tracker state so that the stream controller is not stuck on empty fragments and can load the next segment.
- Fix the early return and unblock case in the buffer controller. The empty parsed result is sent here and no append occurs so we should run the `onUnblocked` callback immediately. (Fixed `Promise.resolve(onUnblocked)` which does not invoke `onUnblocked`).
- Reset transmuxer any time a result comes back with no media or the duration of all tracks could not be determined
- Always post at least one "transmuxComplete" message from transmuxer-worker to update stream-controller state from FRAG_LOADING to PARSING so that we do not return early from `_handleTransmuxerFlush` and ultimately emit FRAG_PARSED. …
> Emit FRAG_PARSED when parsed fragment has no media

- src/controller/gap-controller.ts
This PR will enabled the "seeked" event to complete on paused videos that are seeking to a new timepoint, by supporting buffer hold gap jumps videos that have occasional gaps.
Both the UPV Paella Player and the Jellyfin Web players `pause` the video prior to doing a seek.  Both players are experiencing frozen seek events with HLS.js 1.1.3-1.1.5
Videos are freezing up when seeking and in paused state (when they hit a bad buffer that needs a gap jump).
Please verify that it makes sense that the playhead is indeed moving, or needs to move, when the video is actively seeking to a new time point, although the video is in paused state, the playhead still needs to jump for the seek to succeed.
It resolves  Issue #4367
Here is an example log
```
[log] > [stream-controller]: Loaded fragment 240 of …
```
> Paused-but-seeking video buffer hole gap jump support

- .github/workflows/build.yml
- README.md
- package.json
- tests/test-streams.js
- webpack.config.js
Remove IE from test configs and build targets.
IE 11 EOL was in June of 2022. We shouldn't waste resources running functional tests against it.
It _should_ be safe to remove from the webpack target, although I have not looked at whether this impacts dist/*.js output in any way that could adversely impact uncommon JS runtimes leveraging HLS.js.
> Remove Internet Explorer 11 support

- src/controller/base-stream-controller.ts
- src/controller/fragment-tracker.ts
- src/controller/stream-controller.ts
- src/remux/mp4-remuxer.ts
- src/types/fragment-tracker.ts
- src/types/remuxer.ts
- Replace older backtracking logic with a simpler solution that can continue loading earlier segments until it finds one with a keyframe suitable for the target buffer position.
- Avoid backtracking when the parsed segment's first IDR frame comes before or is at target buffer position (~currentTime).
After testing #4801 against streams with non-independent segments I found that the older backtracking logic was still loop loading when the previous segment was unusable because it had no keyframes. This resolves that issue.
Fixes untracked regressions in backtracking through HLS streams. The test stream with segments missing keyframes was produced using ffmpeg options that produce segments which are shorter than the minimum keyframe distance:
`-r 30 -keyint_min 150 -g 150 -f hls -hls_time 2 …
> Simplify backtracking logic to handle segments without keyframes

- src/remux/mp4-remuxer.ts
Align audio to video rather than trusting playlist offsets when remuxing MPEG2-TS audio and video samples at the same time.  
Long playlists with inaccurate durations can result in incorrect fragment start times. The mp4-remuxer was always using video timestamps in these cases, but for audio was not, leading to cases where appended AV did not even overlap after seeking hours into a playlist with this kind of drift (#4418).
With this fix, the media is appended correctly, even if it's not where it was expected to be based on playlist content.
Fixes #4418
> Bugfix: Use audio PTS over playlist time when aligned with video

- .github/workflows/build.yml
- tests/test-streams.js
- Remove remaining internet explorer targets missed in #4802
- Exclude Chrome 79 from Widevine test
Improve the usefulness of functional test results by excluding a test that should fail (Widevine no longer supported in older versions of Chrome).
> Update functional test targets

- src/controller/gap-controller.ts
- src/controller/stream-controller.ts
- tests/unit/controller/gap-controller.js
Make the gap controller wait for active fragments that start before current position while seeking.
When seeking to a point with 2 seconds (`MAX_START_GAP_JUMP`) before a buffered range, the gap-controller will seek to the start of that range without waiting for fragments to be loaded and appended that would fill the buffer. This change makes the gap controller wait so that rather than skipping ahead, it seeks to and plays the media from the main playlist at the initial seek point.
Only active fragments from the stream-controller (main playlist) are considered. Alternate audio track fragments are not included in the check. Generally audio segments are smaller and are delivered ahead of video, but this might not always be the case, so passing in both could be a good future enhancement …
> Make gap controller wait for active fragments while seeking

- src/controller/audio-stream-controller.ts
- Buffer audio up to one target duration ahead of main buffer
- Wait for main buffer after buffing some audio
Improve efficiency for better start, seek, and adaptation times in HLS streams with alt-audio playlists.
> Throttle audio stream controller based on main buffer state

- .github/workflows/build.yml
- Update workflows to use Node.js v16.
Testing functional test hosting in updated Node.js
> Functional test fixes

- .github/workflows/automerge.yml
- .github/workflows/build.yml
- package-lock.json
- package.json
- tests/functional/auto/setup.js
- tests/test-streams.js
Switch to W3C WebDriver protocol for functional tests.
See https://docs.saucelabs.com/dev/w3c-webdriver-capabilities/ and https://saucelabs.com/platform/platform-configurator
The JWP protocol is now deprecated, and switching fixes the issue we had where newer versions of `selenium-webdriver` didn't work with MacOS 10.15 (#4827).
> sauce labs: switch to W3C WebDriver protocol

- src/controller/audio-stream-controller.ts
Sync the audio-stream-controller with the stream-controller after reattaching the media element.
When calling `hls.recoverMediaError()` or `hls.detachMedia()` followed by `hls.attacheMedia(video)`, the audio-stream-controller should start loading media from the last known currentTime like the stream-controller, so that the player can resume playback by seeking to a buffered starting point. 
Without this fix, after reattaching, alt-audio tracks begin streaming from 0, rather than observed currentTime before media was detached. This can result in audio and video buffered ranges which do not overlap, preventing the combined buffer from growing in length so the `seekToStartPos()` is called to resume playback.
```
// Check combined buffer
const buffered = BufferHelper.getBuffered(media);
if …
```
> Fix attach/detach and recoverMediaError resume with alt audio

- src/controller/base-stream-controller.ts
- src/controller/subtitle-stream-controller.ts
- src/controller/timeline-controller.ts
- Load subtitle playlist EXT-X-MAP segments
- Prepend WebVTT segment payload with init segment payload prior to parsing
HLS spec compliance and support of WebVTT segments with header(s) in init segment(s).
Fixes #4836
> WebVTT EXT-X-MAP support

- api-extractor/report/hls.js.api.md
- src/controller/timeline-controller.ts
- src/types/level.ts
- tests/unit/controller/timeline-controller.js
will set the text track kind to either `captions` or `subtitles` based on CHARACTERISTICS attribute in the MediaPlaylist for the track.
If a text tracks has `CHARACTERISTICS="public.accessibility.transcribes-spoken-dialog,public.accessibility.describes-music-and-sound`, the native video element in Safari will set the `kind` property of the textTrack to `captions` instead of `subtitles`.  
1.  I wasn't sure here if there was any MediaPlaylist information here to analyze to make the distinction between captions and subtitles when making a native text track. https://github.com/video-dev/hls.js/blob/79895a477800147e0b64008e3d01b9f6216453a9/src/controller/timeline-controller.ts#L225-L245.
1. The same goes for a non-native textTrack. I wasn't sure if I should be adding CHARACTERISTICS …
> Feature/determine text track kind based on CHARACTERISTICS

- src/controller/audio-stream-controller.ts
- src/demux/aacdemuxer.ts
- src/demux/base-audio-demuxer.ts
- src/demux/mp3demuxer.ts
- src/demux/transmuxer-interface.ts
- tests/unit/demuxer/base-audio-demuxer.ts
1. Fix audio demuxer contiguity with segments not carrying ID3 timestamps
1. Clear audio stream controller waiting for init PTS data when loading state is reset
1. Fix progressive mode contiguity mux flag
1. Audio segments missing ID3 timestamps were assigned incorrect start times and not appended correctly. 
1. When seeking in streams with discontinuities while waiting for video to load in the previous discontinuity for the first time, processing of audio segments was not handled correctly.
1. When "progressive" mode was enabled, the transmuxer was reset on each chunk loaded leading to gaps in appended video.
Fixes #4835
> Fix audio demuxer contiguity with segments not carrying ID3 timestamps

- src/demux/aacdemuxer.ts
- src/demux/mp3demuxer.ts
- src/demux/mp4demuxer.ts
- src/demux/transmuxer.ts
- src/demux/tsdemuxer.ts
- Update transmux state before decryption which can return early
- Prune dead code from demux stack
Fixes a case where init data is not reset because a partial segment could not be decrypted
Closes #4586
> Update transmux state before decryption which can return early

- src/controller/audio-stream-controller.ts
- src/controller/base-stream-controller.ts
- src/controller/stream-controller.ts
- src/controller/subtitle-stream-controller.ts
- tests/unit/controller/stream-controller.ts
Fix an issue where `BufferHelper.bufferInfo` throws when it is passed an array of `TimeRange` objects from the subtitle-stream-controller. 
`BufferHelper.bufferInfo` and `getBuffered` expect an `HTMLMediaElement` or `SourceBuffer` (or something implementing the `Bufferable` interface) and not an array of TimeRanges, which subtitle-stream-controller was setting on `mediaBuffer`.
The stronger typing on `media`, `mediaBuffer`, and `videoBuffer` informed all of the changes in this PR, which will prevent exceptions when checking if subtitles are buffered while seeking or when the player is detached in certain event loops.
While the exception in `BufferHelper.bufferInfo` is caught, it can be reproduced by enabling "Pause on caught exceptions" and seeking outside the buffered range on any HLS …
> Fix subtitle buffered check

- src/controller/base-stream-controller.ts
- src/remux/passthrough-remuxer.ts
Stop using `nextLoadPosition` to find fragments as soon as the first media segment is appended. Use media timecode when fragmented MP4 mux input has audio and video.
Prevents stream controllers from skipping segments and appending media at the wrong time when the first playlist segment duration is longer than the parsed media segment. This could happen when an audio encoder drops out leaving a large gap which is then added to the segment duration without splitting it into a new segment or marking it with a GAP tag.
#4828
> Bugfix: segment loading order with gaps

- src/controller/abr-controller.ts
- src/controller/stream-controller.ts
- tests/unit/controller/stream-controller.ts
1. Fix a bug where the bitrate test depended on a [buffer full error workaround](https://github.com/video-dev/hls.js/blob/v1.2.1/src/controller/stream-controller.ts#L355-L358) to resume loading.
2. Always skip the bitrate test when only one level is available.
The bitrate test fragment should never be added to the fragment tracker or set to "APPENDING" state. The abr controller cleared the fragment's `bitrateTest` flag before the event was received by the fragment tracker.
Fixes #4865
> Resume streaming after bitrate test with low max buffer

- src/controller/abr-controller.ts
- src/controller/audio-stream-controller.ts
- src/controller/base-stream-controller.ts
- src/controller/level-controller.ts
- src/controller/stream-controller.ts
- src/hls.ts
- src/loader/key-loader.ts
- src/loader/playlist-loader.ts
- Fix fragment error handling with live streams
- Fix level fail over on alt-audio fragment request errors
- Stop playlist and key loading when `stopLoad` is called 
Prevents looping error requests on segment assets in live streams. Live stream fragment errors should observe retry rules, switching levels in ABR mode after retries are exhausted, eventually resulting in the player erroring out if retry rules do not succeed for each level.
Fragment retry counts apply across all media options before a level switch is performed. On the last level to error each playlist's (main, audio, subs) fragments will get the full number of retries.
`hls.stopLoad` should abort active playlist and key loading to prevent activity after `stopLoad` is called or after a fatal player error. 
Fixes #4312
Related …
> Fix segment error handling with live streams

- src/controller/stream-controller.ts
- src/remux/mp4-generator.ts
- src/remux/mp4-remuxer.ts
- tests/unit/controller/stream-controller.ts
Fix handling of negative composition timestamps in MPEG-2 TS remuxing.
Remove loading of "partial" segments. If MSE doesn't append the full segment duration this is likely an issue with the media. This avoids loop loading. Reloading of ejected media is still covered by the fragment tracker.
This change eliminates the "PTS < DTS" warnings and workarounds. The mp4 "trun" box version is set to 1 to signal that composition timestamps are signed.
Fixes #4878
> Fix handling of negative composition timestamps

- package-lock.json
- package.json
- scripts/check-already-published.js
Make `check-already-published` hit api directly.
Because https://github.com/npm/cli/issues/2740 broke the npm `--json` flag meaning the json output is mixed with standard text output (😱). Hopefully the api itself will be stable. With this current bug no npm publishes are happening given the check says they are already there.
We should skip the publish stage if the package is already published so that the rest of the pipeline can run and go green if the pipeline needs to be retried after a publish already succeeded.
Alternative to https://github.com/video-dev/hls.js/pull/4890
> fix npm publishes not happening

- src/remux/mp4-remuxer.ts
Never use negative start times in m2ts remuxer.
The remuxed mp4 output includes a tfdt box with base media decode timestamp which is expected to be an unsigned int(64) based on the box version of 1. This does not allow for negative values. The UA checks are not reliable enough to prevent us from using negative values in places where they could break playback.
Fixes #4893 #4899
> Initial timestamps must be unsigned for tfdt v1 box

- src/controller/subtitle-stream-controller.ts
Improves checking if a fragment of subtitles needs to be loaded.
Fixes a bug causing the same subtitle fragments to load. 
No
#4898
> Bugfix: load one fragment in infinite loop (WebVTT AES-128) 

- api-extractor/report/hls.js.api.md
- src/controller/abr-controller.ts
- src/controller/base-stream-controller.ts
- src/controller/stream-controller.ts
- src/hls.ts
Fix estimates and assumptions in `_abandonRulesCheck` that occur before first byte loaded.
These changes are a subset #4825 intended improve stability until a later release focused on ABR and Low-Latency HLS improvements.
> Patch for abandonRulesCheck sudden quality drops

- api-extractor/report/hls.js.api.md
- src/controller/abr-controller.ts
- src/controller/audio-stream-controller.ts
- src/controller/base-stream-controller.ts
- src/controller/stream-controller.ts
- src/controller/subtitle-stream-controller.ts
- src/demux/mp4demuxer.ts
- src/hls.ts
- src/loader/fragment-loader.ts
- src/loader/fragment.ts
- src/loader/key-loader.ts
- src/types/loader.ts
Load keys and encrypted segments at the same time when not loading parts or progressively.
Reduce time to buffer encrypted content.
> Parallelize key and segment requests

- src/utils/imsc1-ttml-parser.ts
Remove predefined values for cue.size and cue.position
If the subtitles do not contain styles, the subtitles are shifted to the left.
No
#4914
> Bugfix: IMSC subtitles default formatting

- src/controller/base-stream-controller.ts
- src/controller/subtitle-stream-controller.ts
- src/crypt/aes-crypto.ts
- src/crypt/decrypter.ts
- src/demux/sample-aes.ts
- src/demux/transmuxer.ts
Perform needed cleanup on the Decrypter interface:
- Do not modify `config.enableSoftwareAES` outside of "progressive" check (each instance has its own `useSoftware` property and can fallback from Web crypto to software independently)
- Make `decrypter.decrypt` async so that it can be used in stream controllers in place of `webCryptoDecrypt`
- Removed unused `observer` from `Decrypter`
- Check `decrypter.isSync()` after calling `decrypt` so that it reflects correct state after webCryptoDecrypt error fallback
Follow up to #4902
> Decrypter cleanup

- src/controller/audio-track-controller.ts
- src/controller/base-playlist-controller.ts
- src/controller/level-controller.ts
- src/controller/level-helper.ts
- src/controller/subtitle-track-controller.ts
- tests/unit/controller/level-helper.ts
- Schedule live reload time measuring from the last _scheduled_ time the client began loading the Playlist file
- Use last fragment duration rather than target duration when playhead is less than three target durations from the live edge
- Eliminate any latency in refresh interval added by `setTimeout` or JavaScript execution
- Move clock logic out of `computeReloadInterval` and into `playlistLoaded` where timer is set and last request request time (`requestScheduled`) is maintained
- Fix blocking reload schedule when low latency mode is disabled to start one part duration or one second from when an update is expected (Improves upon #3792)
Prevent saw-tooth forward buffer length pattern as playlist refreshes drift from playlist update interval or target duration. 
Data provided by @wilaw …
> Schedule live reload based on start of last update request

- src/utils/codecs.ts
This commit violates RFC6381 + MP4RA ISO code list for compatibility with browsers and other players.
Chrome and Firefox accept `opus` codec only as lowercase despite ISO code has a capital O:
No player plays an M3U8 with `CODECS="Opus"`, but some players do play an M3U8 with `CODECS="opus"`.
`codecs="opus"` is also playable in DASH.
Opus is modern open audio codec already used in Internet communications and it has a potential use in video streaming.
Browsers (I checked Firefox and Chrome) violate some specs and accept only lowercase codec for Opus:
```
> MediaSource.isTypeSupported('audio/mp4; codecs="opus"')
true
> MediaSource.isTypeSupported('audio/mp4; codecs="Opus"')
false
```
no
#4527
> Make Opus sample entry lowercase

- src/demux/sample-aes.ts
- src/demux/tsdemuxer.ts
- src/utils/mp4-tools.ts
no need to call discardEPB on the data passed to parseSEIMessageFromNALu since it's performed inside function.
removed the duplicate implementation discardEPB from tsdemuxer, and exported the mp4-tools implementation instead.
> tsdemuxer: remove redundant discardEPB call & impl

- src/remux/mp4-remuxer.ts
Avoid adjusting TS media timestamps when a dts overlap is found that does not overlap pts 
Fixes #4976
> TS->MP4 Remuxer Fix

- src/demux/tsdemuxer.ts
Restore TS demuxer code that scans for Transport Stream packets.
Users reporting issues with streaming containing TS segments that do not start with mp2t packet sync byte. These bytes should be skipped.
Fixes #4922 #5002
Address comment https://github.com/video-dev/hls.js/issues/5001#issuecomment-1297933802
> Fix MPEG-2 TS packet scanning regression

- api-extractor/report/hls.js.api.md
- src/controller/id3-track-controller.ts
- src/demux/base-audio-demuxer.ts
- src/demux/mp4demuxer.ts
- src/demux/tsdemuxer.ts
- src/types/demuxer.ts
* Add a duration field to Metadata Samples.
* Set the duration to Infinite from sources that don't carry a duration.
* Set the duration to Infinite from fragmented MP4 files with an `event_duration` of 0xffffffff or <= .001 seconds.
* Create Cues from ID3 tags with an Infinite duration (where possible), or `Number.MAX_VALUE` as a fallback.
* On new ID3 tags, update any existing, unbounded Cues
On Safari, when an ID3 track is present, unbounded cues are initially created with an Infinite endTime. As new ID3 tags come in, all previous cues have the endTime updated. Cues may also have a valid endTime, if the underlying source supports it (fragmented mp4).
The current implementation is tracking for changes on the individual ID3 frame level, but Safari will update all existing, unbounded Cues, …
> id3: add duration to metadata samples, mimic Safari behavior on unbounded cues

- src/utils/xhr-loader.ts
catch exception when `data.byteLength` is null and won't stop the video from playing.
(solution was made by [shnjp](https://github.com/video-dev/hls.js/issues/1723#issuecomment-990782845))
https://github.com/video-dev/hls.js/issues/1723
> Catches exception when byteLength is null

- MIGRATING.md
- docs/API.md
Added deprecated event descriptions to API.md and MIGRATING.md
Some events has been deprecated but not updated in documents.
https://github.com/video-dev/hls.js/issues/4969
> Added deprecated event descriptions to API.md and MIGRATING.md

- src/demux/base-audio-demuxer.ts
* Add a new field to the base audio demuxer (`lastPTS`), which tracks the PTS of the most recently added audio frame.
* Use lastPTS as the PTS time when adding ID3 frames
Changes in #4847 (to fix #4835) caused the basePTS value to only update on discontinuity events, which causes ID3 frames to all have the same PTS.
This tracks the PTS of added frames in a new field, which is then used when adding ID3 frames. This field is reset anytime on discontinuities and defaults to the basePTS value when no other value is available (first sample, etc).
Not that I'm aware of
#4963
Additional note, I also tested with the test video in #4835 and confirmed it still plays correctly as well.
> base audio demuxer: track PTS of last sample for ID3 frames

- src/controller/base-stream-controller.ts
- src/controller/stream-controller.ts
Fix https://github.com/video-dev/hls.js/issues/5012
When we use `maxFragLookUpTolerance: 0` and the range that's currently buffering catches up to a previously buffered range the stream-controller may get stuck in a loop trying to load a previously loaded fragment. 
This adjusts the logic in the stream-controller so that if an attempt is made to load a fragment that was already successfully downloaded, the `fragPrevious` field is updated as if the fragment had just been downloaded. 
In the case of small `maxFragLookUpTolerance` this will allow the logic in [`getFragmentAtPosition`](https://github.com/video-dev/hls.js/blob/98d4ab329827bfb2104a882cd13a4df8e983cbe8/src/controller/base-stream-controller.ts#L1039-L1057) to move past the already downloaded fragment. …
> Update fragPrevious when attempting to load an already-buffered fragment

- src/demux/transmuxer-interface.ts
Fallback to demuxing on the main runtime look when an error event is received from the Worker.
Worker errors can occur as a result of webworkify JS injection issues like #5015 or other runtime issues. Disabling the worker to continue streaming playback is better that emitting a fatal error.
We already have a try-catch block to fallback in case the worker could not be instantiated, so why not fallback in the case of an exception.
Helps with builds that break webworkify like #5015
> Fallback to inline demuxing on Worker error

- src/demux/webworkify-webpack.js
Handle a case that breaks worker js injection where rebundled module js is formatted:
```
"function.name"(_) {
}
```
#5015
> Improve webworkify handling of named functions where name is in quotes

- api-extractor/report/hls.js.api.md
- src/controller/audio-stream-controller.ts
- src/controller/base-stream-controller.ts
- src/controller/level-controller.ts
- src/controller/stream-controller.ts
- src/demux/transmuxer-interface.ts
- src/demux/transmuxer-worker.ts
- src/demux/transmuxer.ts
- src/types/events.ts
- Make `transmuxer.flush` results async each time that  `transmuxer.push` returns a promise so that they push->flush results are received in order
- Handle Uncaught Promise Exceptions in transmuxer push and flush by emitting FRAG_PARSING_ERROR event (Example: `MP4Demuxer.demuxSampleAes` returns rejected Promise throwing `"The MP4 demuxer does not support SAMPLE-AES decryption"`
- Route FRAG_PARSING_ERROR (and KEY errors) through level-controller `levelSwitch` error handling and escalate to fatal when switching is not possible
These changes are on top of #4930
Related to #5011 (does not yet handle fall-through probe and empty transmux response flows)
> Emit and handle FRAG_PARSING_ERROR from transmuxers

- MIGRATING.md
Document on the migration documentation that  what seems to be unexpected / buggy behaviour is intentional. We no longer skip start gaps of any size, limiting it to a maximum of a 2s gap.
https://github.com/video-dev/hls.js/issues/4066
It appears based on some googling that default FFmpeg output should now begin somewhere around ~0.7s, so our gap of 2 should work for any defaults well.
```
-muxdelay seconds (output)
Set the maximum demux-decode delay.
```
https://github.com/FFmpeg/FFmpeg/blob/master/fftools/ffmpeg_opt.c#L141
```
-muxpreload seconds (output)
Set the initial demux-decode delay.
```
Is there any additional information that should be added to the README.md for folks as generalized advice to handle this case as it seems to be a common stream issue?
Is anything said here …
> Document new gap controller behaviour on v1.x

- src/is-supported.ts
This is a type and should be imported as type.
When importing from nodejs, I get the following error: `The requested module '/node_modules/hls.js/src/types/buffer.ts' does not provide an export named 'ExtendedSourceBuffer'`
> import ExtendedSourceBuffer as type

- src/controller/cap-level-controller.ts
- tests/unit/controller/cap-level-controller.js
Fix an issue where `capLevelToPlayerSize` is not applied when `attachMedia` is called after the `MANIFEST_LOADED` event is fired.
#4522
> Reset the cached clientRect when media is attached

- src/controller/fragment-tracker.ts
- src/controller/level-helper.ts
- src/controller/stream-controller.ts
Fix consistency of FRAG_CHANGED and LEVEL_SWITCHED events after seeking back (#5077)
and update source of `currentLevel` getter prior to emitting these events (#5082)
The player uses the fragment-tracker's `activeFragment.appendedPTS` in `getAppendedFrag` to determine which fragment (and level) is currently playing. The method for updating `appendedPTS` only worked when playing and buffering media forward; If segments were appended ahead of the current one, `appendedPTS` would be assigned a value outside the segment's range. The method also used TimeRanges from alternate buffers, and  `appendedPTS` was being set on alt audio segments even though it is never used on them.
Fixes #5077
> Fix consistency of FRAG_CHANGED and LEVEL_SWITCHED events

- src/controller/audio-stream-controller.ts
- src/controller/base-stream-controller.ts
- src/controller/subtitle-stream-controller.ts
1. Set `loadedmetadata` on stream controllers such that:
- stream-controller `loadedmetadata` is set to `true` first, after which it seeks to `startPosition` (when not `0`)
- audio and subtitle stream controllers `loadedmetadata` is set to `true` after stream-controller media is buffered (this assumes the previous step is complete)
2. Make the subtitle stream controller fragment selection and max buffer length logic more closely match the audio stream controller
`loadedmetadata` determines whether stream controllers use `media.currentTime` or `nextLoadPosition` to find the next segment to load. If set to true before seeking to `startPosition`, audio and subtitle stream controllers would load media at `media.currentTime` (`0`) instead of `startPosition`.
This change prevents the player …
> Fix audio and subtitle controller loading before player seeks to startPosition (VOD)

- src/controller/fragment-finders.ts
- tests/unit/controller/fragment-finders.js
Make `fragmentWithinToleranceTest` eagerly return a match on an exact match before checking for a match with tolerance.
This is needed to not skip over small segments or segments adjacent to small segments.
Fixes #4919
> Eagerly match segments without tolerance offset

- .github/workflows/automerge.yml
- package-lock.json
- package.json
Downgrade netlify-cli for now as it [breaks netlify](https://app.netlify.com/sites/hls-js-dev/deploys/639c37ede360b50008f95739).
```
9:18:39 AM: build-image version: 524714d1a66d1a967316f5c39465e22c77fdd56c (focal)
9:18:39 AM: build-image tag: v4.16.0
9:18:39 AM: buildbot version: 2956156cff73cc91029b26e56f43b4bf895eefff
9:18:39 AM: Fetching cached dependencies
9:18:39 AM: Starting to download cache of 372.8MB
9:18:42 AM: Finished downloading cache in 3.41719096s
9:18:42 AM: Starting to extract cache
9:18:45 AM: Finished extracting cache in 2.574730015s
9:18:45 AM: Finished fetching cache in 6.063038567s
9:18:45 AM: Starting to prepare the repo for build
9:18:45 AM: Preparing Git Reference pull/5112/head
9:18:46 AM: Parsing package.json dependencies
9:18:47 AM: Different publish path …
```
> downgrade `netlify-cli` for now as it breaks netlify

- src/controller/base-stream-controller.ts
Fix an issue in `nextPartIndex` where the first independent part index is returned after newer parts have been loaded, but the next part needed is not yet listed.
Instead of waiting for the next needed part, the player was selecting the first part, then skipping the ones that were loaded, leading to freezing of video or stalling of playback.
No
Fixes #5111
> Fix Low-Latency HLS next part selection when switching mid segment

- src/controller/base-playlist-controller.ts
- src/types/level.ts
Add support for Rendition Report switching when their relative urls contain dot segments
Rendition Report URLs can be absolute or relative to the playlist they are in. When the relative URLs contain dot segments (../) then the comparison to the selected level fails and the Rendition Report is not used.
Fixes #3572
> Fix: Rendition Report switching with unnormalized relative URLs

- src/controller/audio-stream-controller.ts
- src/controller/base-stream-controller.ts
- src/controller/buffer-controller.ts
- src/controller/stream-controller.ts
- tests/functional/auto/setup.js
- Log additional information for EOS test
- Move up `_streamEnded` checks for `BUFFER_EOS` event triggers in stream-controllers to ensure they run event after max buffer length conditions are met
The HTMLMediaElement "ended" event intermittently does not fire or does not fire at all in certain browsers with certain streams.
The info added to our CI tests will help determine if it is an issue with audio and video buffer alignment, MediaSource readyState, stream-controller state re-opening MediaSource, or something else.
#5000
> Log additional information for EOS test

- docs/release-process.md
Mention that you need to be an admin or maintainer to push version tag. I’ve updated the setting already for `v*` tags. If we don’t want this can switch it off again.
It restricts the group of people that can publish releases to those with a specific maintainer or admin role to reduce the chance of a compromised account being able to get a package update onto npm.
Also prevents version tags being deleted by anyone other than admins.
> mention that you need to be an admin or maintainer to push version tag

- .github/stale.yml
Update GitHub stale bot rules to exempt more labels and remove "Question" label from the list since once "Needs Triage" is removed from a question, it should be answered.
Answered "Question" issues often don't get confirmation and are not closed by originators of the issues so we should let the stale bot take care of them.
> Update GitHub stale bot rules

- api-extractor/report/hls.js.api.md
- src/controller/audio-stream-controller.ts
- src/controller/base-stream-controller.ts
- src/controller/buffer-controller.ts
- src/controller/fragment-tracker.ts
- src/controller/stream-controller.ts
- src/loader/fragment.ts
- src/loader/m3u8-parser.ts
- src/types/buffer.ts
- tests/unit/controller/base-stream-controller.js
The HTMLMediaElement "ended" event intermittently does not fire. A common cause for this is the back buffer removal resetting the buffer ended state just before playback reaches the end. Seeking back to append segments after the last segment is appended also resets the stream controller and MediaSource state. Afterwards the EOS is not set again and "ended" will not fire.
#5000
> Manage End of Stream state after flushing buffer

- docs/API.md
Clarify that `LEVEL_LOADING` is not called for media playlists loaded via loadSource in API.md
Closes #4851
> Clarify when `LEVEL_LOADING` is not called

- api-extractor/report/hls.js.api.md
- src/loader/level-details.ts
- src/loader/m3u8-parser.ts
- src/loader/playlist-loader.ts
- src/types/loader.ts
Remove code that makes additional byte-range requests when media playlists are missing a MAP tag and have file extensions that suggest MP4 container format.
Segment file extensions should not impact player behavior. EXT-X-MAP tags are required by fMP4 segments in HLS media playlists. 
The code being removed was added in #1442. It is not needed for the stream in the description. This suggests it was added to support an early version of shaka-packager or DASH streams ported to HLS without the required MAP tags.
Is anyone depending on the code being removed?
Are there such HLS streams and are they supported in other HLS clients?
I am assuming no to both and if wrong then would prefer to see an fmp4 specific demuxer error which included sidx data so that this fix could be applied as a …
> Remove SIDX playlist MAP patching

- api-extractor/report/hls.js.api.md
- docs/API.md
- src/controller/level-controller.ts
- src/hls.ts
- src/types/level.ts
- Implement `hls.maxHdcpLevel` getter/setter API for HDCP-LEVEL capping and EME error handling.
- Sort levels primarily by HDCP level, followed by `bitrate` (AVERAGE-BANDWIDTH or BANDWIDTH - this is the current behavior), followed by SCORE, followed by RESOLUTION (height).
Allows for playback of DRM protected streams with HDCP restriction to recover from output-restricted EME Key errors (`ErrorDetails.KEY_SYSTEM_STATUS_OUTPUT_RESTRICTED`).
1. Setting `hls.maxHdcpLevel` does not prevent levels from being manually selected by setting one of the manual level selection setters. Use `hls.removeLevel()` to remove all levels of a particular HDCP-LEVEL as selection options.
2. Setting `hls.maxHdcpLevel` does not immediately force a level change.  To do do, set `hls.currentLevel` to `-1` after …
> Implement `maxHdcpLevel` HDCP-LEVEL capping and EME error handling

- src/demux/transmuxer.ts
Prioritize MP4 demux probe over MPEG-TS.
I found MP4 segments containing 2 TS sync bytes (0x47) exactly one TS packet apart (188 bytes). They're not at the start of the stream but since we allow for some scanning of segment bytes this could make HLS.js treat mp4 segments as TS segment resulting in playback failure.
HLS.js should start with the more robust mp4 probe that looks for a moov atom before looking for TS packets.
> Prioritize MP4 demux probe over MPEG-TS

- docs/API.md
- src/controller/abr-controller.ts
- src/types/component-api.ts
Create a type interface for the AbrController
Users can implement their own Custom AbrController. Having a typed interface for Abr Controllers will help developers understand what properties and methods their Custom AbrControllers must implement to operate with hls.js
re: https://github.com/video-dev/hls.js/issues/4824#issuecomment-1208530220
> If you could define an interface for abr controller classes to implement in src/types and link to it in the docs, that would be most helpful
I didn't see any prior art for linking directly to src/types in the API documentation, so I just updated the API.md file directly, but am willing to link directly to src/types if that's preferred. 
---
It wasn't specified in the above comment, but because the [docs also …
> Documentation - Add interface for AbrController

- src/config.ts
- src/controller/buffer-controller.ts
- src/loader/level-key.ts
- tests/functional/auto/setup.js
- webpack.config.js
- Reduce hls.light build size by removing level-key,  mediakeys-helper and `requestMediaKeySystemAccess` code
- Fix: Allow hls.light to play Variant Playlist content while ignoring audio Media Playlists (buffer-controller expected 2 bufferCodec events, preventing playback from starting)
- Increase number of functional tests for hls.light build to cover this case
> Light build optimizations and fixes

- src/loader/m3u8-parser.ts
- tests/unit/loader/playlist-loader.ts
Parse TARGETDURATION as a decimal-integer assigned a minimum value of 1.
TARGETDURATION is defined as an upper bound on the duration of all Media Segments in the Playlist. HLS.js already only matches the decimal-integer portion of this tags value [here](https://github.com/video-dev/hls.js/blob/v1.3.0/src/loader/m3u8-parser.ts#L47) (`TARGETDURATION|VERSION): *(\d+)/`).
If an Media Playlist provides a sub-second value, HLS.js should use a value of 1 to avoid any errors in handling live playlist reload (#4464).
`computeReloadInterval` already uses the last segment duration when shorter than target duration and near live edge. 
Follow up on #4464
> Parse TARGETDURATION as a decimal-integer assigned a minimum value of 1

- api-extractor/report/hls.js.api.md
- src/controller/fragment-tracker.ts
- src/controller/level-helper.ts
- src/loader/fragment.ts
- src/types/fragment-tracker.ts
- Track buffered fragments in Low-Latency HLS so that `currentLevel`, `LEVEL_SWITCHED` and `FRAG_CHANGED` fire when seeking back from edge in Low-Latency streams
- Move `appendedPTS` from Fragment to fragment-tracker's FragmentEntity
When streaming Low-latency parts, the fragment-tracker uses activeParts to determine the `currentLevel` and fragment/level change events. FragmentEntity objects are not stored in the tracker when parts are being loaded as this can interfere with fragment selection and subsequent part loading.
This change stores the last active `mainFragEntity` FragmentEntity into the fargment-tracker's list of fragments so that when seeking back, `getBufferedFrag([at position])` can return the fragment (and its level) for part(s) appended in that range of the buffer.
There …
> Fix current quality reporting when seeking back from edge in Low-Latency streams

- api-extractor/report/hls.js.api.md
- demo/main.js
- src/controller/abr-controller.ts
- src/controller/audio-stream-controller.ts
- src/controller/base-stream-controller.ts
- src/controller/level-helper.ts
- src/controller/stream-controller.ts
- src/controller/subtitle-stream-controller.ts
- src/hls.ts
- src/utils/ewma-bandwidth-estimator.ts
- tests/unit/controller/stream-controller.ts
Improve bandwidth estimation and adaptive switching with smaller segments and higher TTFB
Estimating time-to-first-byte exclusive from the time used to estimate bandwidth, allows us to more accurately predict the time it takes to load segments, especially those with shorter durations closer to the average round trip time of a request.
There were also several issues with loading stats, combined vs main video buffer observation, and calculation of inflight BW performed before bytes were loaded that all contributed to bad emergency down-switch and BWE corruption in `_abandonRulesCheck`. Thanks to @Pri12890 for pointing many of these out.
There are two new public methods on the player instance that I have left undocumented:
1. `get mainForwardBufferInfo(): BufferInfo | null` Allows the ABR …
> Improve bandwidth estimation and adaptive switching

- src/controller/base-playlist-controller.ts
- tests/unit/controller/base-stream-controller.ts
- tests/unit/controller/level-controller.ts
When performing a switch, if no exact URI match to a RENDITION-REPORT is found, use the last RENDITION-REPORT URI that matches the target Playlist URI from start to Rendition URI length.
Switches will be performed using RENDITION-REPORT Delivery Directives when Media Playlist URI has a query string, and the RENDITION-REPORT URI does not.
It could be worth considering simply using the current Playlist's last msn and part index when a matching RENDITION-REPORT cannot be found. A failed attempt would fall back to a request without Delivery Directives. However, the player should avoid making requests that could cause errors to get cached on edge servers.
Fixes #5174
> Support partial RENDITION-REPORT URI matches fallback

- package.json
- scripts/build-netlify.sh
Fix Netlify root redirect. The problem was the second line to setup the api-docs redirect was replacing the file contents instead of appending (`>>`).
Second reason it wasn't working is because netlify won't redirect by default if a file already exists, so now we delete the index file.
New commit deployments and https://hls-js-dev.netlify.com/ go to a 404 at the root and api docs redirect doesn’t work
> fix Netlify redirects

- src/controller/base-stream-controller.ts
- src/controller/level-controller.ts
- src/controller/stream-controller.ts
- src/utils/time-ranges.ts
Remove the `hls.nextLoadLevel` check that blocks bitrate test fragment loading from completing.
Also improves log lines:
- `Attempt loading level index` (removes LL-HLS msn and part directives when none are added)
- `stream-controller]: Buffered` (includes fragment time range as compared to buffered time range `(frag:[210.001-220.066] > buffer:[100.066-220.009])`)
When HLS Playlists include Variants under ~500kbps, a value higher than `0` for `hls.nextLoadLevel` is returned blocking the bitrate test from completing. 
The purpose of the check was lost after https://github.com/video-dev/hls.js/blame/5d532bde70f188263bef2661090ecd7d740d8910/src/controller/stream-controller.js#L847 and likely went unchecked because a `hls.nextLoadLevel` of `0` is expected if the second lowest bitrate is …
> Fix bitrate test with variants under ~500kbps

- src/demux/tsdemuxer.ts
To prevent false positives in TSDemuxer probe check that all packets in scan window begin with start byte, and confirm that PAT PID is found.
Audio files may contain 0x47 byte 188 bytes apart within scan window.
Fixes #5183
> MPEG-TS probe improvement

- src/controller/buffer-controller.ts
- tests/unit/controller/buffer-controller-operations.ts
Listen for "emptied" event on media element while attaching MediaSource. If the media `src` attribute does not match the  object URL being attached log an error and detach the media element (this will emit MEDIA_DETACHING).
#4952 Users are unsure why calling `hls.attachMedia(HTMLMediaElement)` does not always resolve with the player emitting `MEDIA_ATTACHED` after MediaSource is attached and open. My best guess is that something is changing the video.src externally while attaching, which interrupts the MediaSource from dispatching the 'sourceopen' event HLS.js depends on to complete the attachMedia operation. 
With this change-set, `detachMedia` will be called if attaching the MediaSource is interrupted ("emptied" event with src change detected). The detaching event following an attach …
> Log error and detach if MediaSource 'sourceopen' is interrupted

- .github/workflows/build.yml
- tests/functional/auto/setup.js
- tests/functional/auto/testbench.js
Stop using the optional chain operator for functional tests, and move the older chrome browser tests to the required list given they have been more stable recently, and would have caught this bug introduced in #5243 
Because they need to be es5 for older chrome.
> do not use optional chain operator for functional tests

- scripts/deploy-netlify.sh
Set the git user email when updating deployments file
Without this it tries to come up with a sensible default but recently this failed in https://github.com/video-dev/hls.js/actions/runs/4217828503/jobs/7321920416 with
```
Author identity unknown
*** Please tell me who you are.
Run
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
fatal: unable to auto-detect email address (got 'runner@fv-az581-156.(none)')
Error: Process completed with exit code 128.
```
I've set it to the email of the CI user it's actually using.
> set the git user email when updating deployments file

- src/controller/base-stream-controller.ts
- src/demux/tsdemuxer.ts
Fix MPEG2-TS probing when PAT packet is not found in the first three packets.
Sometimes HLS assets with segmented M2TS streams have segments that do not begin with PAT and PMT packets. Despite this not being spec compliant it is widely supported. Recent changes to TS probing in v1.3 broke support for segments like this (#5251). 
As long as we find a sync byte and every following 188 byte packet starts with the same sync byte, keep looking for the PAT packet before passing the probe test. TS segments without a PAT (and no MAP in the Playlist to provide it) are not usable. It's worth noting that HLS.js does not support M2TS MAP init segments or implicit init segments when byteranges are used, but this is only commonly found in I-FRAME Playlists which also remain unsupported.
Fixes …
> Fix M2TS probing when PAT packet is not found in first three packets

- README.md
- src/controller/content-steering-controller.ts
- src/loader/m3u8-parser.ts
- src/utils/variable-substitution.ts
- tests/unit/loader/playlist-loader.ts
- webpack.config.js
Implement EXT-X-DEFINE QUERYPARAM support
The EXT-X-DEFINE QUERYPARAM attribute is a new HLS feature that allows the definition of HLS variables based on URL search parameter key value pairs. A URL param from the playlist's parent URL can used as a variable to substitute variable declarations (`{$var-name}`) inside URI strings and quoted string attributes anywhere in an HLS playlist following the variable definition, just like variables defined by the EXT-X-DEFINE NAME/VALUE or IMPORT attribute(s) (#5161).
Resolves #5240
> Support QUERYPARAM Variable Substitution

- api-extractor/report/hls.js.api.md
- src/controller/audio-stream-controller.ts
- src/controller/base-stream-controller.ts
- src/controller/stream-controller.ts
- src/demux/transmuxer-interface.ts
Fix fallback to inline worker when exception is thrown in worker
When the injected worker fails,`worker.onerror` callback triggers an internal error event that is not handled properly. These changes set config.enableWorker to false and resets the stream controller loading state and transmuxer instance so that audio and main stream controllers can retry with inline transmuxer.
Related to #5107
> Fix fallback to inline worker when exception is thrown in worker

- api-extractor/report/hls.js.api.md
- src/controller/base-playlist-controller.ts
- src/controller/base-stream-controller.ts
- src/controller/cmcd-controller.ts
- src/controller/content-steering-controller.ts
- src/controller/error-controller.ts
- src/controller/fragment-tracker.ts
- src/controller/id3-track-controller.ts
- src/errors.ts
- src/hls.ts
- src/loader/date-range.ts
- src/loader/fragment.ts
- src/types/cmcd.ts
- src/types/demuxer.ts
- src/types/events.ts
- src/types/level.ts
- src/types/loader.ts
- src/utils/cea-608-parser.ts
- src/utils/mediakeys-helper.ts
- webpack.config.js
Inline existing enums as much as possible by using const enums and limiting export scope.
Reduces bundle size and module complexity.
See babel's [babel-preset-typescript `optimizeConstEnums`](https://babeljs.io/docs/babel-preset-typescript#optimizeconstenums) for optimizations. Many of the enums in the library are exported as types and thus are not completely inlined. This change at least replaces IFFE output with object literals and inlines where possible.
> TypeScript enum optimizations

- src/controller/eme-controller.ts
- src/hls.ts
Cleanup config on destroy /
Callbacks can have references to the player instance or other objects in their scope.
> Cleanup config on destroy 

- README.md
Add a link that loads the repo in stackblitz with the demo running.
At the moment it initially loads `/` not `/demo` so you get an index of the files in the root. We can improve this but I think it would make sense to get the rollup switch done first than keep messing with webpack things.
It's a quick way of getting a dev env running and allows running the demo locally in the browser.
> add a link to open in stackblitz to the readme

- src/controller/subtitle-track-controller.ts
- tests/unit/controller/subtitle-track-controller.js
fix #5292
I did not test on Edge, which is part of the comments in filterSubtitleTracks.. 
So I guess just make sure this is still working on different agents/devices as originally intended?
* Can be added to this PR if needed
* N/A
> fix for #5292 - push to filterSubtitleTracks output if kind is captions

- src/controller/base-stream-controller.ts
`MediaAttachedData` is the right type for `base-stram-controller.ts` and his child class use it.
There is a spell type error; And I fix it;
Don't need;
> fix: type name error

- src/controller/base-playlist-controller.ts
- src/utils/error-helper.ts
- Maintain live reload pace after level switch
- Only define deliveryDirectives when when blocking reload is available (correct error handling)
- Retry main playlist on status 0 when `navigator.onLine` is false (this policy is not extended to audio and subtitle track media playlists)
On level switch the reload interval was being added to the already scheduled time for next reload, which could skip reloads after level switch.
#5282
#5306
> Live reload level switch and error handling improvements

- README.md
- api-extractor/report/hls.js.api.md
- docs/API.md
- src/controller/audio-stream-controller.ts
- src/controller/base-stream-controller.ts
- src/controller/eme-controller.ts
- src/controller/error-controller.ts
- src/controller/fragment-tracker.ts
- src/controller/gap-controller.ts
- src/controller/latency-controller.ts
- src/controller/level-controller.ts
- src/controller/stream-controller.ts
- src/controller/subtitle-stream-controller.ts
- src/errors.ts
- src/loader/fragment-loader.ts
- src/loader/fragment.ts
- src/loader/m3u8-parser.ts
- src/types/level.ts
- tests/unit/controller/audio-track-controller.ts
- tests/unit/controller/error-controller.ts
- tests/unit/loader/playlist-loader.ts
Do not load GAP segments or parts. Error when encountering a segment with a GAP in a level to trigger a level switch (clients are expected to look for alternate segments to load when a GAP is encountered). Track segments with a GAP as partially buffered in fragment-tracker to avoid reload looping and expedite finding of the next available fragment. Allow the gap-controller to skip over unbufferable gaps (when level switch is not an option).
- Segments with a GAP tag are not requested
- Parts with a GAP=YES attribute are not requested
- The first time a stream-controller goes to select a GAP segment for loading in a level a FRAG_GAP Error will be emitted
- The FRAG_GAP error is handled by switching variants when possible
- When no alternates are available, the next segment/part is selected …
> GAP Tag/Attribute Support with FRAG_GAP Error

- src/controller/audio-stream-controller.ts
- src/controller/base-stream-controller.ts
Manage appendBuffer SourceBuffer full errors correctly when audio bitrate is higher than video..
When the audio bitrate is higher than the video bitrate, SourceBuffer full errors can occur on the audio buffer as the audio-stream-controller tries to keep up with the video buffer length.
The audio-stream-controller was going past `maxMaxBufferLength` when the video buffer exceeded that length prior to its value being reduced after the first buffer full error. Further more, the max length was not being reduced more than the current buffer length on the second error at which point the entire buffer was flushed. The entire buffer should only be flushed when the buffer that errored is starved (to remove back and forward buffer not used for playback). 
Fixes #5328
> Fix for SourceBuffer full error handling

- src/remux/passthrough-remuxer.ts
- src/utils/mp4-tools.ts
Live to VOD streams from some vendors contain invalid CMAF tfdt (track fragment decode time). We suspect they tried writing a negative value to what is defines as an unsigned 64-bit integer. Assume that is the case when a value above 63-bit is found, and ignore it. Continuing to parse the remaining tfdt atoms if present, or returning null should ensure that the player uses a valid value or fallback to playlist time/passthrough, and prevents the invalid media timecode from shifting the playlist it is found in.
If the first fmp4 segment loaded for a playlist has an invalid tfdt base media time the `initPTS` is assigned a bad value and the playlist is shifted. This can cause CMAF audio and video to be completely de-synced (the segments in the playlist affected can no longer be found). …
> Handle invalid signed "tfdt" decode time values

- .gitignore
- build-config.js
- karma.conf.js
- src/demux/inject-worker.ts
Remove the temporary output name for karma because the karma rollup plugin _shouldn't_ be writing anything to disc. It seems fine locally but maybe I'm missing something?
And then remove the need for the wrapping function for the worker build by just replacing the `__IN_WORKER__` var
> More rollup PR tweaks

- src/controller/audio-stream-controller.ts
- src/controller/stream-controller.ts
Fix #5349
Fix #5349
-
Issue #5349
> [Fixes #5349] Remove fragments from FragmentTracker after transmux complete if fragment context changed

- api-extractor/report/hls.js.api.md
- src/controller/subtitle-stream-controller.ts
Display subtitles that have been loaded before detaching and reattaching the media element (or using `recoverMediaError`).
The subtitle-stream-controller keeps track of which subtitle segments have been loaded using  `tracksBuffered`. This data must be cleared on detach since the cues containing the loaded subtitles are removed at the same time. If we do not do this then subtitles that have been loaded previously will not be reloaded or displayed after reattaching the media element (#5353).
Fixes #5353
> Clear subtitle-stream-controller buffered list on detach

- src/controller/subtitle-stream-controller.ts
- src/controller/timeline-controller.ts
- src/utils/media-option-attributes.ts
- tests/unit/controller/subtitle-stream-controller.js
- tests/unit/controller/timeline-controller.js
Do not clear subtitle cues or tracked fragments when updating subtitle tracks with identical tracks.
When Content Steering forces a Pathway change, the player updates levels and tracks. Content from matching playlists (where STABLE-RENDITION-ID match) should not be cleared as these playlists are bit-identical.
This change also covers tracks with matching attributes. The assumptions is a new list with the exact same languages and characteristics should match the current list for the same Multivariant Playlist.
Fixes #5361
> Content-Steering fix: Keep bit identical subtitle content

- api-extractor/report/hls.js.api.md
- src/controller/abr-controller.ts
- src/controller/audio-stream-controller.ts
- src/controller/base-stream-controller.ts
- src/controller/error-controller.ts
- src/controller/fragment-tracker.ts
- src/controller/gap-controller.ts
- src/controller/level-helper.ts
- src/controller/stream-controller.ts
- src/controller/subtitle-stream-controller.ts
- src/types/level.ts
- tests/unit/controller/error-controller.ts
Only allow large gaps to be skipped if start gap or all fragments in range are partial
Prevents large gap jumps introduced in v1.4.0-beta with the exception of start gaps and spans containing tracked fragments with GAP tags.
Fixes #5360
> Only allow large gaps to be skipped if start gap or all fragments in range are partial

- .github/workflows/build.yml
- scripts/publish-npm.sh
Setup npm provenance statements.
Easiest way to test it will be with the canary release when this is merged
Adds a signature to the package in npm that lets users verify the package was built and published from this action.
see https://docs.npmjs.com/generating-provenance-statements/
> Setup npm provenance statements

- src/demux/mp4demuxer.ts
Reset `remainingData` in order to ensure we don't continue appending new fragments on top of old incomplete fragments stored in `remainingData`.
On seek, with progressive mode on, the segmentedData can end up with an empty valid segment and large remainder segment. The remainder segment consists of an incomplete moof+mdat from the fragment pre-seek and the complete fragment post-seek. This gets output when flush() is called, triggering an error as the buffer appended to the MediaSource is invalid.
#5409
> Bugfix: reset remainderData in resetContiguity

- src/controller/base-playlist-controller.ts
Make playlist controllers (level-controller, audio-track-controller, subtitle-track-controller) retry playlist loading on loading error or timeout, before attempting a redundant failover or level switch.
This fixes a regression where no retries were performed at all for alt-audio and subtitle playlist loading errors, which could resolve issues when no pathways or failover variants are available.
When an audio or subtitle track load error or timeout occurs, the error controller flags the error so that a Content Steering Pathway change or redundant variant fallback action can be taken. While the `errorAction` retains the `retryConfig` settings, they are ignored because the error action is no longer set to `NetworkErrorAction.RetryRequest`. 
Content Steering Pathway changes are still …
> Retry audio and subtitle media playlist loading when alternate is not found

- src/controller/audio-track-controller.ts
Sometimes STABLE-RENDITION_ID of tracks is undefined. Adding a guard for it, otherwise audio track doesn't switch.
Fix the initial audio track selection issue by guarding for `undefined` value. It will allow us to set initial audio track.
See [issue/5430](https://github.com/video-dev/hls.js/issues/5430)
> bugfix: Check for undefined audio track attribute in findTrackId()

- src/remux/passthrough-remuxer.ts
As HEVC Spec A.3.2 defined, when `general_profile_compatibility_flag[1]` is equal to 1, `general_profile_compatibility_flag[2]` should be equal to 1 as well, thus a valid HEVC 
main profile codec id should be: `hvc1.1.6.L120.90` instead of `hvc1.1.c.L120.90`.
> Fix incorrect HEVC main profile codec id

- api-extractor/report/hls.js.api.md
- src/controller/audio-stream-controller.ts
- src/controller/base-stream-controller.ts
- src/controller/buffer-controller.ts
- src/controller/eme-controller.ts
- src/controller/fragment-tracker.ts
- src/controller/stream-controller.ts
- src/hls.ts
- src/loader/key-loader.ts
- tests/unit/controller/fragment-tracker.ts
- tests/unit/controller/stream-controller.ts
- tests/unit/controller/subtitle-stream-controller.js
Fix Low-Latency part and fragment tracking issues introduced in v1.3.5 with #5102
- #5102
- Introduced regression: stalling when playing back over segment where some parts were loaded seeking back
- Introduced regression: unnecessary loading of fragments over parts during Low-Latency playback
Additional enhancements:
- Prevents flushing the forward buffer on smooth switch in live playback when buffer conditions are low
- Fixes loading of live streams with alt-audio using an `Hls` instance that is already playing an asset with alt-audio
- Return MAP segment (when present) for event `frag` value in `FRAG_PARSING_INIT_SEGMENT` events
- Prevents fragment and part requests from being unnecessarily aborted on seeking events
- Fix issues with reuse of player instance when loading additional …
> Fix Low-Latency part and fragment tracking

- src/utils/codecs.ts
- tests/unit/controller/content-steering-controller.ts
- tests/unit/controller/level-controller.ts
Always use `MediaSource` returned by utils module.
`isTypeSupported` should use the same `MediaSource` object returned by `getMediaSource` used in other parts of the player.
> Always use MediaSource returned by utils module

- src/controller/fragment-tracker.ts
Fragments which contain both audio and video also need to be checked if they are partial. We check for them individually, but there are cases when only the one flag is set.
Fix an edge case with the fragment loader
Bug fix on an edge case.
Not really.
> fix: partial audiovideo fragments not being treated as partial

- src/remux/passthrough-remuxer.ts
Fix AV desync regression in v1.4.0 when mp4 audio track timestamps start before video track timestamps. Log a warning when initPTS is updated this way.
#5235 introduced a change to the passthrough-remuxer which resets initPTS if the current initPTS would result in negative timestamps or appends. The de-sync is a result of the initPTS reset only applying to audio appends. The change made for #5235 was intended to allow de-synchronized initPTS when the tracks themselves do no have valid alignment, using playlist alignment as a fallback. It should not be applied to mp4 segments within reasonable distance to there HLS Playlist program time.
Initial segments that would have been assigned negative decode timestamps in v1.3.5 start at 0 in v1.4. So while there may be some misalignment on the …
> Fix AV desync regression in v1.4.0 with misaligned mp4 audio

- docs/API.md
Remove `startLoad()` as recovery method from API.md doc
`startLoad()` makes the player reload files as needed. Calling it after a network error is likely to trigger the same network error, resulting in loop loading. This should only be used for very specific scenarios, with timers to prevent excessive requests from being made for files that are not being served.
#5476
> Remove startLoad() as recovery method from API.md doc

- src/controller/fragment-tracker.ts
Fix reloading of first fragment after ejected.
Fixes v1.4.1 regression with seeking back to 0 (loop) when first media sequence number is 0 after buffer has been ejected by user agent.
Fixes #5482
> Fix long VOD looping or seeking back to 0 after buffer ejection

- src/controller/audio-stream-controller.ts
- src/controller/base-playlist-controller.ts
- src/controller/error-controller.ts
- Reset playlist loading error count when handling error with level switch and on level updated
- Do not mark errors as resolved by playlist controller if retries are maxed out 
- Use buffered helper in audio-stream-controller to prevent exceptions when source buffer is detached because of error
Playlist loading errors must be fatal after all levels and retries exhausted.
Fixes #5488
> Bugfix: Playlist loading errors must be fatal after all levels and retries exhausted

- src/remux/mp4-remuxer.ts
Adjust parsed TS AVC samples when start PTS overlaps with last DTS
Resolves user reported buffer gaps in Chrome for TS streams produced from Cloudflare with overlapping video samples between the first and second segment (#5477).
Older releases of the player made this adjustment, but the change was dialed back in 1.2.5. This change makes a slight adjustment to allow the timestamp adjustment that works for the samples provided in #5477.
Resolves #5477
> Adjust parsed TS AVC samples when start PTS overlaps with last DTS

- src/remux/mp4-remuxer.ts
Use input timescale when normalizing metadata cue timestamps
v1.4.0 introduced rational timestamps (basetime, timescale) for initPTS, and with that a regression in emsg metadata cue timestamp normalization.
Fixes #5504
> Use input timescale when normalizing metadata cue timestamps

- api-extractor/report/hls.js.api.md
- docs/API.md
- src/controller/content-steering-controller.ts
- src/events.ts
- src/hls.ts
- src/types/events.ts
- tests/unit/controller/content-steering-controller.ts
Fire a new event (`STEERING_MANIFEST_LOADED`) when the Steering Manifest is loaded and expose on it the content of the received steering manifest.
We may need the application loading the player to react when receiving Content Steering Manifests. In our case and for now, we are using the steering params for debugging purposes, so it was handy to expose them.
Please check the unit tests are enough. As I was using already existing interfaces, I didn't extend much the checks over the event contents. I can do it if I needed.
> Fire STEERING_MANIFEST_LOADED event when loading a Content Steering Manifest

- src/controller/gap-controller.ts
Prevent gap-controller from jumping start gaps when paused
So that small backward seeks can be performed along segment boundaries whose buffered content does not match playlist times can be performed without seeking forward to buffered start.
Resolves #5499
> Do not jump start gaps when paused

- src/controller/audio-stream-controller.ts
- src/controller/base-stream-controller.ts
- src/controller/buffer-controller.ts
- src/controller/buffer-operation-queue.ts
- src/controller/error-controller.ts
- src/controller/level-controller.ts
- src/controller/stream-controller.ts
- tests/unit/controller/buffer-controller-operations.ts
Error and switch on SourceBuffer append requests for non-existing tracks.
Prevents the player from stalling when encountering muxed "audiovideo" (mp4) after setting up with unmuxed "video" and "audio" SourceBuffers (TS or unmuxed main and alt-audio mp4)
There may be cases where muxed mp4 content could be appended into either a "video" or "audio" SourceBuffer (but not both). Only some MSE implementations handle this, ignoring the unrecognized tracks, but some devices do not (iPad for example). Either way, that is not correct behavior, or behavior we should support. Mixing content in HLS this way is not the best for compatibility an should not be supported.
Feature requests for unmuxing muxed mp4 when needed could be entertained (file an issue). There also may be future work that involves …
> Error and switch on SourceBuffer append requests for non-existing tracks

- src/remux/passthrough-remuxer.ts
- src/utils/mp4-tools.ts
Add codec string parsing for avc, hevc, and mp4a.
When testing the new HEVC playback on using hls.js on Chrome 107 for Windows, I noticed that some playlists were failing. These playlists have been working fine with hls.js on MS Edge on the same machine for quite some time, and they continue to work there. They also previously worked fine using hls.js on Chrome 104 for Windows also on the same machine (with the `PlatformHEVCDecoderSupport` flag set). Additionally, the playlists work fine on MacOS and on Android Webview 107 using hls.js.
After poking around a bit it seems that this regression seems to be due to a change in Chrome's MSE (of which I know very little) - it looks like the default `hvc1.1.c.L120.90` codec string hls.js uses for HEVC is getting rejected.
To reproduce, try …
> Add codec string parsing for h264, h265, and mp4a

- src/controller/buffer-controller.ts
- src/controller/level-controller.ts
- src/controller/stream-controller.ts
- src/remux/passthrough-remuxer.ts
- src/utils/codecs.ts
Allow hls.js to demux and decode FLAC and Opus audio, regardless of whether the browser accepts the MP4-Registered codec entries (`fLaC` and `Opus`, respectively), or if they use a fallback legacy codec entry (`flac`, `FLAC`, and `opus`).
See https://developer.apple.com/documentation/http-live-streaming/hls-authoring-specification-for-apple-devices - which lists FLAC as a supported codec.
Opus is not listed for Apple devices, but adding Opus support is about the same as adding FLAC support.
In `stream-controller.ts` - this file contains fallback logic for browsers which aren't able to change the codec type (Safari on iPhone is the only browser with this issue, as far as I know). I'm unsure what should happen there, if anything.
See #4387 - it works in the browsers I've tested that support …
> Add FLAC support

- README.md
- src/demux/transmuxer-interface.ts
- src/demux/tsdemuxer.ts
- src/remux/mp4-generator.ts
- src/remux/mp4-remuxer.ts
Add support for AC-3 codec in MPEG-TS
> Add support for AC-3 codec in MPEG-TS

- src/controller/audio-stream-controller.ts
- src/controller/buffer-controller.ts
- src/controller/error-controller.ts
- src/remux/passthrough-remuxer.ts
- src/utils/mp4-tools.ts
- Add mp4 "stsd" codec parsing for Dolby Vision, VP9, AV1, and audio codec passthrough
- Update contributed mp4a, avc, and hevc mp4 "stsd" codec parsing
- Clean up mp4 init segment track parsed codec handling
- Clean up SourceBuffer `changeType` detection and appends
- Allows for Media Playlist playback with MSE SourceBuffer creation using media parsed codec strings
- Allows player to compare/correct issues in Multivariant Playlist Variant CODECS attribute values
- Allows for proper handling of codec changes between mp4 init segments
Resolves #4744
Related to #5378
Related to #5162
> MP4 Sample Description CODEC Parsing

- src/controller/audio-stream-controller.ts
- src/controller/level-controller.ts
- src/controller/stream-controller.ts
- src/loader/m3u8-parser.ts
- src/utils/codecs.ts
Filter variants with multiple audio or video codecs where any of the codecs are unsupported by MSE.
All codecs in the CODECS attribute must be supported for a client to select and play a variant.
Multiple video or audio codecs separated by a comma typically indicate codec changes at discontinuities in the stream (common with digital ad insertion). Multiple audio codecs can also indicate a variety of codecs across playlists within the same audio group. However, since the client can not determine which tracks contain which of the codecs, if any of them are unsupported, the client should not use the variant which could require all of them. For this reason using different audio groups for each audio codec is recommended. 
#5378
> Filter variants with any unsupported codecs

- src/controller/stream-controller.ts
Resume fragment loading after level switch follows level error
The stream-controller gets stuck in WAITING_LEVEL state waiting for the first level that failed to load. The stream-controller's idle tick needs to run to update its level property to match `hls.nextLoadLevel` so that it will attempt to fetch segments from the current level if available or go back to WAITING_LEVEL for the active level that has yet to load.
Fixes #5498
> Resume fragment loading after level switch follows level error

- src/controller/id3-track-controller.ts
Prevent adjusting the end time of metadata cues that overlap with cues of another type (id3, emsg, daterange)
DateRange cue duration is independent of other cues on the timeline. ID3 and emsg cues should span until the next cue of the the same type.
Fixes #5531
> Fix DateRange metadata cue duration with ID3 cues that overlap

- api-extractor/report/hls.js.api.md
- src/types/loader.ts
Correcting usage of extended generic type `LoaderContext` in type `Loader`
Better typing when submmiting custom loaders into HLS instance.
No
#5487
> Correcting usage of extended generic type `LoaderContext` in type `Loader` (#5487)

- api-extractor/report/hls.js.api.md
- src/controller/buffer-controller.ts
Improve buffer-controller logging
Log seekable range start and end when using `liveDurationInfinity` to help with debugging live stream catchup and stalls. Also optimizes log statements by binding module name to the start of each statement instead of repeating it.
Related to #5536
> Improve buffer-controller logging

- src/hls.ts
- Prevent recursion in error event handlers that throw
- Internal exception events from other error events where the handler throws are fatal
The player should handle flaws in event callbacks as best it can. Preventing recursion avoids locking up the browser because of a flawed integration of hls.js, and making these error events fatal when processing of an error was flawed in the first place hopefully helps with debugging and encourages better coding practices.
Fixes #5497
> Prevent recursion in error event handlers that throw

- src/controller/error-controller.ts
Keep level switch error actions within player constraints
The player will not switch to suggested level indexes outside the bounds of `hls.minAutoLevel` and `hls.maxAutoLevel`. Working within these constraints is a condition to reaching a fatal error when all viable level loading attempts have failed.
Fixes #5566
> Keep level switch error actions within player constraints

- api-extractor/report/hls.js.api.md
- src/loader/key-loader.ts
- src/types/loader.ts
- src/utils/fetch-loader.ts
- src/utils/xhr-loader.ts
Make loader context nullable and cleanup loader cleanup
`context` is undefined before `load()` is called. Making it nullable and clearing it on destroy makes it easier to deal with loader usage after the end of its lifecycle.
Do apps currently use these loader properties after loaders are destroyed (`context` or `stats`)? At the very least we should clear `(xhr|fetch)Setup` callbacks on destroy to remove any references hoisted into the scope of these functions.
Followup to #5494
> Make loader context nullable and cleanup loader cleanup

- .eslintrc.js
- build-config.js
- src/controller/audio-track-controller.ts
- src/define-plugin.d.ts
- src/demux/ac3-demuxer.ts
- src/demux/transmuxer-interface.ts
- src/demux/transmuxer.ts
- src/demux/tsdemuxer.ts
- src/remux/mp4-generator.ts
- src/types/demuxer.ts
- Add AC3 file support 
- Exclude AC3 parsing from hls.light builds
With #5167 bringing support for parsing AC3 in M2TS, support for unwrapped AC3 segments is also needed so that support checks can be trusted regardless of container type.
This is a follow up from this comment and sample https://github.com/video-dev/hls.js/pull/1102#issuecomment-358754920, which aligns AC3 with AAC/ADTS and MP3 handling.  
This also brings AC3 support inline with Safari.
In the light build, with AC3 probing disabled, the MP3 probe passes for some AC3 content. Not too concerned about this, but it does prevent the player from going down the desired error path. I don't have a solution for making the existing MP3 probing less prone to false positives.
Follow up to #5167
> Add AC3 file support and exclude AC3 parsing from hls.light builds

- src/controller/base-stream-controller.ts
- src/utils/xhr-loader.ts
Fix Multivariant Playlist and Key XHR loader retries.
**XHR Loader Issue:**
Loader was marking its state as aborted when timeouts execute while xhr.readystate is low. This was not reset on internal retries so on subsequent completes (retries), the loader exited, treating the retry request as aborted.
**Base Stream Controller Frag/Key Load Error Handler Issue:**
The stream controller state was set to ERROR On Frag/Key errors without a retry configuration. This caused the stream controller to stall after a `SendAlternateToPenaltyBox` (level switch) error action.
Fixes #5588
> Fix Multivariant Playlist and Key XHR loader retries

- src/controller/subtitle-stream-controller.ts
- src/controller/timeline-controller.ts
- src/utils/webvtt-parser.ts
Remove the use of target duration in ensuring subtitle segment N-1 is loaded. Instead, find best match for position, then ensure N-1 is loaded.
Improve handling of MPEGTS VTT syncing. Rather than always require initPTS for the subtitle discontinuity sequence, only require it when parsed subtitles include an MPEGTS map value, log when it's missing, and trigger a non-fatal error only when only AV initPTS from lower sequence numbers have been loaded.
Since target duration is an upper bound of playlist segment durations, and subtitle segments can be very long, using target duration to ensure the last subtitle segment is loaded can lead to subtitle loading starting several segments back. Loading can then idle before reaching the playhead as the subtitle-stream-controller tries to match the …
> Bugfix: large subtitle target duration can result in subtitles not loading as needed

- src/controller/stream-controller.ts
Skip backtracking on first segment.
Calling `this.backtrack` on first segment can cause loop loading because the loaded media is rejected in favor of loading an earlier segment in hopes of finding an IDR frame that begins before the playhead position.
Fixes #5609
> Never back-track on first fragment to avoid loop loading

- src/controller/base-stream-controller.ts
Fixes #5617
When worker setup errors, stream-controller `nextLoadPosition` is not reset, leading to the player skipping any segments loaded while attempting worker setup. This leads to initial segment appends being performed out of order, after the skipped segments are reloaded, which can produce gaps.
Fixes #5617
> Reset loading start on worker setup error

- src/controller/cap-level-controller.ts
- Continue to poll player size when not displayed with `capLevelToPlayerSize`
- Fixes #5611
- Prevent changes in aspect-ratio from causing capping to toggle back and forth
Makes cap-level-controller continue to detect player size changes after it has been hidden and shown again.
Also prevents `autoLevelCapping` from bouncing back and forth when aspect ratio changes slightly between renditions because of rounded height values. To repro set player size to 426px with first BBB test stream.
The first issue (#5611) can be worked around by toggling capping after displaying the media element again:
```
hls.capLevelToPlayerSize = false;
hls.capLevelToPlayerSize = true;
```
This could be done at any time the size/layout of the media element is changed to perform a timely update of …
> Fix capLevelToPlayerSize after hiding player and maintain stable selection when aspect ratio changes

- api-extractor/report/hls.js.api.md
- src/controller/buffer-controller.ts
- src/types/events.ts
- tests/unit/controller/buffer-controller-operations.ts
Handle mixed SourceBuffer append errors, up to `appendErrorMaxRetry` consecutive errors per SourceBuffer type ('audio', 'video', and 'audiovideo').
Allows append errors across SourceBuffers until the limit of consecutive errors is reached for a single type. The error count is reset for a particular type after a successful append. This prevents some sequences of append errors from being escalated to fatal, which may be recoverable. This also helps to deal with or identify append errors caused by unsupported mixed segment types, such as unmuxed and muxed 'video' and  'audiovideo' segments (#5369). 
Related to #5369, #1510
> Handle mixed sourcebuffer errors

- src/demux/tsdemuxer.ts
This is a version of #5652 based on `patch/v.1.4.x`
As requested here: https://github.com/video-dev/hls.js/pull/5652#issuecomment-1635147020
This was kept as close to the other PR as possible, with the only real differences being variable names and file that contains the change.
#5632
> Fix issue #5632, where missing AUD units for keyframes causes them to be merged with their preceding frame

- src/controller/stream-controller.ts
- src/loader/fragment-loader.ts
- Prevent backtracking on first segment in discontinuity
- Use gap skipping to handle gap jumping prevent loop loading when large gaps are present in segment/disco start
- Marks bad segments as GAP segments to avoid loop loading
- Clears the `gap` property if the fragment loader later needs to reload the fragment after the buffer was cleared and the fragment had no 'GAP' tag.
Streams with segments at discontinuity sequence starts that are missing keyframes result in large gaps. HLS.js should not loop load when encountering this scenario.
Fixes #5629
> Fix handling of segments at the discontinuities that do not start with a keyframe

- src/demux/tsdemuxer.ts
Fix a regression in AC3 PES parsing
The PR https://github.com/video-dev/hls.js/pull/5562 introduced a regression by dropping this line in the `parseAC3PES` function:  https://github.com/video-dev/hls.js/pull/5562/files#diff-4a467ddfe2310c97c29aac6fda61c534714123a1b68c7f198b0f8ddd0598c611L1007
No
> Fix AC3 PES parsing

- src/demux/tsdemuxer.ts
Add support for AC-3 audio in DVB streams
The newly added AC-3 decoding assumes embedding with stream_type 0x81 according to the ATSC standard.
In DVB streams, AC-3 audio is broadcast as stream_type 0x06 (which is used for multiple purposes) with an AC-3 descriptor of type 0x6A.
Because AC-3 support is not complete yet.
No. The code is proven to work with the now-merged AC-3 PR for a long time.
> Add support for AC-3 audio in DVB streams

- src/remux/mp4-remuxer.ts
- src/utils/texttrack-utils.ts
- Use input timescale when remuxing inband captions
- Catch exceptions attempting to create TextTrackCue instances and adding them to TextTracks
The start time of 608 captions was not being remuxed from mp4 segments correctly. Negative start times resulted in `addCueToTrack` throwing, and then the fallback also threw because the constructor for `TextTrackCue` has changed in latest Safari (document fragments in cues is not to be supported until a later date).
Fixes #5669
> Use input timescale when remuxing inband captions

- src/controller/base-stream-controller.ts
- src/controller/error-controller.ts
- src/controller/fragment-tracker.ts
Treat the odd empty segment FRAG_PARSING_ERROR as a gap. The stream controller will advance to the next segment without loop loading. If subsequent errors occur, a level switch will be attempted, up to `maxRetry` count.
Fixes regression of #4799 in v1.3 and v1.4 that introduced loop loading, and fatal errors after parsing errors accumulated beyond `maxRetry` count.
Some care was taken not to regress frag parsing error handling and gap jumping:
- #5011 CC @mattzucker
- #2940 CC @mtoczko
For the sample streams provided in #5674 the empty segments are not needed and once the following segments are appended there are not gaps. The player does not recognize this to the case, and proceeds naively. In most cases we would want to switch variants when an error like this occurs to find an …
> Allow the odd empty segment to be skipped like a gap segment

- src/controller/timeline-controller.ts
Push back the initialization of 608 parsers until `FRAG_PARSING_USERDATA`.
Improved script eval and player setup setup performance. This can improve page load and time to request initial HLS Playlist.
> Lazy init CEA608 parsers

- src/demux/video/avc-video-parser.ts
- src/remux/mp4-remuxer.ts
Push AUD units to fix decode errors with some TS segments
Found TS playlists that produce a decode error in HLS.js but not in other MSE based players that push AUD units to the data they remux into fmp4.
Example decoding error:
| |
| :------------- |
| Selected VDAVideoDecoder for video decoding, config: codec: h264, profile: h264 baseline, level: not available, alpha_mode: is_opaque, coded size: [640,360], visible rect: [0,0,640,360], natural size: [640,360], has extra data: false, encryption scheme: Unencrypted, rotation: 0°, flipped: 0, color space: {primaries:BT709, transfer:BT709, matrix:BT709, range:LIMITED} |
| VDA Error 4 |
| video decode error! | 
```
Error Group: DecoderStatus
Error Code: 1
Stacktrace: media/gpu/ipc/service/vda_video_decoder.cc:919
```
```
Error Group: …
```
> Push AUD units to fix decode errors with some TS segments

- src/demux/audio/aacdemuxer.ts
- src/demux/audio/ac3-demuxer.ts
- src/demux/audio/dolby.ts
- src/demux/audio/mp3demuxer.ts
Check for AC3 and EC3 before passing MP3 probe. 
Unwrapped EC3 in #4958 sample media was passing the MP3 probe test. It doesn't take much to find MP3 sync bytes in a file after all other probed types fail.
This change moves the bsid check into a dolby module and runs in before passing the MP3 probe test regardless of the `__USE_M2TS_ADVANCED_CODECS__` build constant so that HLS.js does not get false positives for MP3 demuxing when scanning ac3 and ec3 files. This allows HLS.js to go down the correct path (`"[transmuxer] Failed to find demuxer by probing fragment data") for unwrapped/unsupported EC3 files, and the same for AC3 files in the light build where the build constant strips support.
BSID for EC3 is 16, for AC3 < 16. While HLS.js does not support unwrapped EC3 or EC3 in TS, if it …
> Fail MP3 probe if AC3 or EC3 detected

- src/controller/audio-stream-controller.ts
- src/utils/discontinuities.ts
- tests/unit/utils/discontinuities.ts
Use last discontinuity bounds when aligning playlists on PDT.
Realigns audio playlist when waiting for initPTS, and removes redundant alignPDT method.
Ensures proper alignment of live streams which do not carry contiguous PDT values across discontinuities.
When the middle reference fragments from the audio and main playlists do not share the same discontinuity sequence, this method could fail to align the playlists correctly because of differences in the PDT between segments.
> Use last discontinuity bounds when aligning playlists on PDT

- src/remux/mp4-remuxer.ts
Increase m2ts->fmp4 remuxed sample dts to prevent decode artifacts and errors in Safari. 
Samples with negative DTS after aligning on PTS can cause decode artifacts and errors when hls.js sets those initial samples' DTS to 0.
It's not ideal that hls.js has to modify the decode timeline in order to align the media presentation to 0. This is done to remove large video starting gaps that result from MSE implementations not accounting for or reflecting composition time in the media elements timeline.
In the future, HLS.js could improve by setting SourceBuffer `timestampOffset` before appending, without shifting sample timestamps. That would be a much more involved change as it could impact fragment timing properties and append positions across browsers, so for these reasons this intermediate …
> Fix Safari decode errors with DTS not increasing when PTS decreases

- src/controller/fragment-tracker.ts
Fix loop loading in fmp4 sample with gaps
Gap at sn 13 causes loop loading in https://efa8a4bc.hls-js-dev.pages.dev/demo/?src=https%3A%2F%2Fbitmovin-a.akamaihd.net%2Fcontent%2Fdataset%2Fmulti-codec%2Fhevc%2Fstream_fmp4.m3u8&demoConfig=eyJlbmFibGVTdHJlYW1pbmciOnRydWUsImF1dG9SZWNvdmVyRXJyb3IiOmZhbHNlLCJzdG9wT25TdGFsbCI6ZmFsc2UsImR1bXBmTVA0IjpmYWxzZSwibGV2ZWxDYXBwaW5nIjotMSwibGltaXRNZXRyaWNzIjotMX0=
The range detected as "partial" which results in additional frag load attempts is invalid because the `bufferPadding` added. The gap actually starts and ends before sn 13, and since the range has an end time which is less than the start it can be ignored.
Not sure if overlapping appends are causing the gaps. Could be an issue with the decode timestamps found in the media - haven't checked or …
> Fix loop loading in fmp4 sample with gaps

- src/controller/base-stream-controller.ts
When looking for the next fragment to load, if the target position is less than the start of the playlist, reset `startPosition` and `nextLoadPosition` to `liveSyncPosition`. Setting `nextLoadPosition` ensures that the audio-stream-controller can properly evaluate the main buffer before SourceBuffers have been added to the MediaSource.
audio-stream-controller exits before loading anything when main's `nextLoadPosition`  is incorrect in some cases.
Fixes #5741
> Fix live frag finding after detach and re-attach past live window

- src/controller/eme-controller.ts
On Edge, the raw license message is an UTF-16-encoded XML. It needs to be unpacked. The Challenge element is and base64 encoded xml string (the actual license challenge). Any HttpHeader elements need to be added to the xhr.
Same code can be found in shaka-player: https://github.com/shaka-project/shaka-player/blob/d6d5b155ff38428e96808094a341694d353ba289/lib/media/drm_engine.js#L1608
Code works and builds without warnings. I'm not primarily a JS developer. Check if everything is fine.
PlayReady playback not working in Edge browser.
Before:
After:
> Fix PlayReady DRM in Edge browser

- api-extractor/report/hls.js.api.md
- docs/API.md
- src/config.ts
- src/utils/error-helper.ts
- tests/index.js
- tests/unit/utils/error-helper.js
Adds the ability to set a custom function `shouldRetry` via `retryConfig`, which overrides default
Was recommended to add this improvement in #5647 in cases when user need to have possibility to override default `shouldRetry`
#5647
> Custom shouldRetry in retryConfig

- api-extractor/report/hls.js.api.md
- src/config.ts
- src/controller/buffer-controller.ts
- src/controller/eme-controller.ts
- src/controller/level-controller.ts
- src/demux/transmuxer-interface.ts
- src/hls.ts
- src/remux/passthrough-remuxer.ts
- src/types/events.ts
- src/utils/codecs.ts
- src/utils/mediasource-helper.ts
- tests/unit/controller/content-steering-controller.ts
- tests/unit/controller/level-controller.ts
1. Use ManagedMediaSource (MMS) when available rather than MediaSource for MSE based playback
- Adds `preferManagedMediaSource` config option which defaults to `true`. Set to `false` to use standard `MediaSource` when available even if MMS is present.
1. Start and stop loading of media segments with MMS "startstreaming" and "endstreaming" events
- Adds new new player API methods `pauseBuffering()` and `resumeBuffering()`
(unlike `startLoad()` and `stopLoad()`, these methods do not interrupt Playlist loading)
1. Cap max quality based on MMS quality:
1. low = ABR selection limited to 1280x720p max
1. medium = 1920x1080p max
1. (other) = no limit
1. Use HTMLSourceElements for MediaSource blob URL and set `media.disableRemotePlayback` to `true` to allow ManagedMediaSource to open (users can …
> ManagedMediaSource Support

- src/controller/gap-controller.ts
Allow stalls to be reported when playhead at the edge or outside a buffered range.
Playback doesn't always stall inside a buffered range. Typically it stalls at the end of one.
The code being moved is to prevent stalls from being reported and stall nudges from being performed while seeking. The issue _was_ that some clients resolve seeking before media is buffered.
Resolves part of #5759
> Do not exit from stall detection when playhead is at or past end of buffer

- src/utils/mp4-tools.ts
Do not modify fmp4 bytes when there is no offset
Minor enhancement to improve performance of fmp4 playback for media that does not require timestamp modification (until HLS.js can adopt MSE `SourceBuffer.timestampOffset`).
> Do not modify fmp4 bytes when there is no offset

- src/controller/buffer-controller.ts
- src/demux/audio/aacdemuxer.ts
- src/utils/codecs.ts
Prevent ADTS probe false positives when bytes following ID3 are a match for MPEG audio
TS/ADTS/MP3 probe methods scan through all or most bytes to find a sync word, and as a result sometimes find a false positive. We tried removing this in v1.2.x, but users with malformed content (media segments starting with JPEG bytes) reported that they depended on it this functionality so it was kept in (#5002).
Fixes #5782
> Prevent ADTS probe false positives when bytes following ID3 are a match for MPEG audio

- api-extractor/report/hls.js.api.md
- src/controller/audio-stream-controller.ts
- src/controller/base-playlist-controller.ts
- src/controller/base-stream-controller.ts
- src/controller/fragment-tracker.ts
- src/controller/stream-controller.ts
- src/loader/level-details.ts
- src/utils/level-helper.ts
Treat LevelDetails as `updated` when #EXT-X-ENDLIST is appended to live playlist without new segment. Mark the corresponding segment in the previous details object with `endList = true` so that the fragment-tracker can add it to `endListFragments`.
`endListFragments` is used to determine that everything from the playhead to the end of the playlist has been buffered so that the MediaSource and SourceBuffer(s) can be marked as ended.
Fixes #5777
> Handle #EXT-X-ENDLIST appended to live playlist without new segment

- MIGRATING.md
- api-extractor/report/hls.js.api.md
- docs/API.md
- src/config.ts
- src/controller/buffer-controller.ts
- tests/unit/controller/buffer-controller-operations.ts
Allow users to specify a maximum forward buffer to give control of media buffer memory usage.
Some devices have poor MSE buffer cleanup and run out of memory instead of evicting segments far ahead of the playhead.
Fixes #5479
Fixes #5587
@iamboorrito
> Add config flag for maximum front buffer `frontBufferFlushThreshold`

- api-extractor/report/hls.js.api.md
- src/controller/level-controller.ts
- src/events.ts
- src/hls.ts
- src/types/events.ts
Implement `MAX_AUTO_LEVEL_UPDATED` event for maxAutoLevel change.
Used when presenting selection options and those options change based on supported HDCP levels, or `hls.autoLevelCapping` is set by fps/cap-level controller.
Resolves #4521
> Implement event for maxAutoLevel change

- src/controller/base-playlist-controller.ts
Fix support of skip directive without block reload.
Playlist request directives are only being added when SERVER-CONTROL contains CAN-BLOCK-RELOAD=YES.
Regressed in v1.4.0 with:
- #5317
https://github.com/video-dev/hls.js/issues/3644#issuecomment-1700656757
> Fix support of skip directive without block reload

- src/utils/mp4-tools.ts
Fix two AV1 parsing issues that make Firefox fails to play HLS stream
- fix(mp4-tools): Fix AV1 profile parsing
Profile: unsigned right shift 5-bits for the 2nd av1CBox
Level: bitwise AND the 2nd av1CBox with 0b11111(0x1f)
Without this, Main `av01.0.15M.08` is parsed as High `av01.1.15M.08`.
In this case the High profile is not supprted in Firefox.
- fix(mp4-tools): set default color descriptions to satisfy Firefox
In Firefox either you omit the chroma values, or you have to complete the rest of the color descriptions.
Otherwise even the most basic AV1 Main 4:2:0 8-bit video will be reported as unsupported in HTMLMediaElement.canPlayType and MediaSource.isTypeSupported. Chromium is not affected by this.
See also
- https://aomediacodec.github.io/av1-isobmff/#av1codecconfigurationbox-syntax …
> fix(mp4-tools): Fix two AV1 parsing issues

- src/controller/abr-controller.ts
- src/demux/video/avc-video-parser.ts
- src/remux/mp4-remuxer.ts
Reset init segment when M2TS video configuration changes
Some MSE implementations do not handle video configuration (resolution) changes without appending a new init segment or changeType append to prepare the decoder for the change.
Resolves #2062 (and stale duplicates #1842 #967)
> Reset init segment when M2TS video configuration changes

- src/controller/fragment-finders.ts
- src/controller/stream-controller.ts
- tests/unit/controller/fragment-finders.js
Switch on smaller fmp4 segments that align with buffered segment boundaries
Prevents vide buffer gaps from being produced on append in Chrome with HLS assets with fmp4 segments of different durations as in #5743.
Fixes #5743
> Switch on smaller fmp4 segments that align with buffered segment boundaries

- src/demux/video/avc-video-parser.ts
- src/remux/mp4-remuxer.ts
Prevents vide buffer gaps from being produced on append in Chrome with HLS assets with m2ts segments containing overlapping AVC samples at segment boundaries.
Resolves #5759 #4470
> Adjust overlapping M2TS AVC timestamps of sample that overlap with previous segment

- src/controller/stream-controller.ts
Skip large video start gaps using the Fragment gap flag.
The gap-controller only skips start gaps less than two seconds in length. HLS.js can jump larger gaps and will for any fragment marked with a gap flag. There are already cases where this flag is added when segments are found to be _a)_ completely missing all video samples or _b)_ dropping initial samples because of not starting with a key-frame. This change adds the case where nothing is dropped from the segment, but it still starts more than 2 seconds after the start of the audio track.
Fixes #4975
> Skip large video start gaps using GAP flag

- api-extractor/report/hls.js.api.md
- src/controller/audio-stream-controller.ts
- src/controller/base-stream-controller.ts
- src/controller/stream-controller.ts
- src/controller/subtitle-stream-controller.ts
- src/utils/discontinuities.ts
- tests/unit/utils/discontinuities.ts
Keep a reference to the last loaded level or track playlist object, and use it when aligning live playlists without PDT.
Track group id changes replace track list, making it impossible to access the level or details object used prior to the switch using `level[index]`.
Resolves #5802
> Fix for aligning live alt audio and subtitle playlists on msn without PDT

- src/controller/audio-track-controller.ts
Exit gracefully when switching to an audio group with no (supported) tracks
Users report receiving a fatal error in streams with no audio tracks (but audio groups?)
Related to #4602
> Exit gracefully when switching to an audio group with no tracks

- docs/API.md
- src/controller/buffer-controller.ts
- Add `preferManagedMediaSource` API.md doc entry
- Only emit BUFFER_FLUSHED with removed ranges in ManagedMediaSource "bufferedchange" event
ManagedMediaSource dispatches "bufferedchange" on append and when ejecting media independent of appends. The event includes `removedRanges` when media is ejected from the buffer.
> Add `preferManagedMediaSource` API.md doc entry for ManagedMediaSource usage

- MIGRATING.md
Corrects default details and additional demo setting of `backBufferLength`.
> Update MIGRATING doc back buffer length details

- src/controller/error-controller.ts
Fix selection of levels with alternate audio codecs on frag parsing error of audio segment.
Fixes handing of frag parsing error of containerless EC-3 segments when HLS asset has other audio codec renditions.
Related to #4958
> Fix audio codec alternate error fallback

- src/demux/mp4demuxer.ts
- src/utils/mp4-tools.ts
Remove 16kB constraint on "moof" offset when probing segments to detect fmp4.
Segments with large or many emsg boxes can push the moof box offset to much further out in the segment. This is not uncommon for media carrying image data over id3 emsg.
Added a new method optimized to exit on the first moof box found and skip quickly over others. When testing how this worked with TS and unwrapped audio the method tended to exit after first iteration because `size` was out of bounds (which is good).
> MP4Demuxer probe fix for large "emsg" payloads

- api-extractor/report/hls.js.api.md
- src/loader/fragment-loader.ts
- src/loader/fragment.ts
- src/loader/m3u8-parser.ts
- tests/unit/loader/playlist-loader.ts
- Support #EXT-X-BYTERANGE before #EXT-X-MAP tag
- Update Fragment `byteRange`, `byteRangeEndOffset`, `byteRangeStartOffset` typing to reflect actual return types.
-  `fragment.byteRange` returns a number tuple or an empty array
- `byteRangeEndOffset` and `byteRangeStartOffset` both return numbers or both return undefined
Handle odd tag order in media playlists and better reflect data types.
> Support #EXT-X-BYTERANGE before #EXT-X-MAP tag

- src/controller/stream-controller.ts
- src/demux/audio/adts.ts
- src/demux/tsdemuxer.ts
- tests/unit/demuxer/adts.js
- Avoid false positive in M2TS probe where sync byte is not either followed by another sync byte at packet length or is at packet length from the end of the payload
- Reset item related properties in stream-controller `onManifestLoading` not handled by `stopLoad`, `startLoad`, or `onManifestLoaded` in base controller
- Fix ADTS error handling and tests
Fixes case where M2TS probe incorrectly exits early
Closes #5857
> Fix regression in M2TS probe introduced in #5503

- api-extractor/report/hls.js.api.md
- src/controller/abr-controller.ts
- src/controller/audio-stream-controller.ts
- src/controller/audio-track-controller.ts
- src/controller/content-steering-controller.ts
- src/controller/level-controller.ts
- src/controller/subtitle-stream-controller.ts
- src/controller/subtitle-track-controller.ts
- src/controller/timeline-controller.ts
- src/hls.ts
- src/loader/m3u8-parser.ts
- src/types/level.ts
- src/types/media-playlist.ts
- src/utils/media-option-attributes.ts
- src/utils/mediacapabilities-helper.ts
- src/utils/rendition-helper.ts
- tests/unit/controller/audio-track-controller.ts
- tests/unit/controller/level-controller.ts
- tests/unit/controller/subtitle-track-controller.js
- tests/unit/controller/timeline-controller.js
- Treat STREAM-INFs with the same attributes and URL as a single Level AND:
- List `audioTracks` and `subtitleTracks` across multiple GroupIDs that share the same Variant (#5302)
- Add VIDEO_RANGE and HDCP attribute values to Redundant Stream group splitting
- Add `channels` and `characteristics` to `MediaPlaylist` objects (`hls.audioTracks` and `hls.subtitleTracks`)
- Improve selection of matching alternate tracks (audio and subtitles) when switching variants
> - Treat STREAM-INFs with the same attributes and URL as a single Level AND:
>  - List `audioTracks` and `subtitleTracks` across multiple GroupIDs that share the same Variant (#5302)
> - Add VIDEO_RANGE and HDCP attribute values to Redundant Stream group splitting
HLS assets can have audio or subtitle groups with different sets of …
> Redundant Stream grouping enhancements

- src/controller/audio-track-controller.ts
- src/controller/subtitle-track-controller.ts
- src/controller/timeline-controller.ts
- src/utils/media-option-attributes.ts
- src/utils/texttrack-utils.ts
- tests/unit/controller/timeline-controller.js
Use subtitle track name and language to find and match subtitle/captions TextTrack rather than subtitleTrack index.
Logs a warning when loading a new source with subtitle options that do not completely overlap with the attached media element's existing TextTracks:
```
Media element contains unused subtitle tracks: {TRACK LABEL CSVs}.
Replace media element for each source to clear TextTracks and captions menu.
```
Default subtitle track selection is updated to pick first default | forced | autoselect track to more closely match default behavior with Safari HLS playback.
If the user sets `hls.audioTrack` to a valid index on AUDIO_TRACKS_UPDATED, that selection will not be replaced with the default audio track immediately after (similar to existing initial subtitle track selection logic). …
> Fix subtitle track selection when reusing media element with mismatched TextTracks

- src/controller/gap-controller.ts
Reset gap-controller nudgeRetry count after playhead moves, pauses, or ends while not seeking.
When `nudgeRetry` reaches `nudgeMaxRetry`, the error is escalated to fatal (expected):
https://github.com/video-dev/hls.js/blob/46a7ca29bec3453bf39bc9919aba5ce189d17895/src/controller/gap-controller.ts#L334-L365
`nudgeRetry` is reset when polling `currentTime`. The expectation is that this runs after currentTime has advanced naturally. Note that `stalled` must not be `null` - the think here is that this is reset when exiting a stall, but this does not work if stalled is reset before reaching this point:
https://github.com/video-dev/hls.js/blob/46a7ca29bec3453bf39bc9919aba5ce189d17895/src/controller/gap-controller.ts#L47-L73
And here we see that `stalled` is reset to null before nudging, so …
> Bugfix: Reset gap-controller `nudgeRetry`

- src/controller/buffer-controller.ts
- tests/functional/auto/setup.js
- Handle muxed ("audiovideo") fmp4 main playlist setup (enabling audio tracks will fail without "audio" buffer, but at lest muxed main variant will start)
- Cleanup MMS setup and source children removal
Supports playback of main variants in unsupported muxed fmp4 audvideo with alt audio tracks. Fixes caught exception in MMS setup. Prevents removal of TextTrack or other non `<source>` video element children in Safari. 
Muxed TS main with alt-audio is supported because TS is always demuxed. Make sure that and similar SourceBuffer setups continue to work as expected.
> SourceBuffer controller cleanup

- api-extractor/report/hls.js.api.md
- src/utils/attr-list.ts
Replace the `AttrList` class `clientAttrs` property with a getter so that the `DateRange` constructor does not confuse the property with other attributes when merging DATERANGE tags with the same ID.
Fixes logger warning `DATERANGE tag attribute: "clientAttrs" does not match for tags with ID: "${DATERANGE ID}"`.
https://github.com/video-dev/hls.js/blob/470a29f47d2cd2155afadfb7d97b19e4e3e1cc2a/src/loader/date-range.ts#L41-L50
It also improves Typing since `clientAttrs` was treated as `any` but could have been `string[] | undefined`. Now it is always `string[]` as it was expected to be in the m3u8-parser:
https://github.com/video-dev/hls.js/blob/470a29f47d2cd2155afadfb7d97b19e4e3e1cc2a/src/loader/m3u8-parser.ts#L551-L554
`clientAttrs` is only read in one place (above when parsing a new …
> Fix DATERANGE parser handling of `clientAttrs` property

- src/controller/buffer-controller.ts
Check ManagedMediaSource `removedRanges` length on "bufferedchange" event.
`removedRanges` should be defined and have a positive length before it is assumed that media was ejected from the buffer.
> Check ManagedMediaSource removedRanges length on "bufferedchange" event

- build-config.js
- src/controller/buffer-controller.ts
- src/controller/error-controller.ts
- src/exports-default.ts
- src/exports-named.ts
- tsconfig.json
Include named exports in ESM output for classes and enums in addition to the default export.
Allows import and use of classes and enums in the public API with ESM output. UMD output continues to use default Hls class export only for backwards compatibility.
Resolves #5630
> Use named exports in ESM output

- src/controller/buffer-controller.ts
Fix SourceBuffer reset regression introduced in dev with #5911 (not reproducible in v1.14.x).
`_bufferCodecEventsTotal` should not be reset on BUFFER_CODECS. It is only set once on manifest parsed and its value is needed to reset SourceBuffers on detach/attach or recoverMediaError with unmuxed HLS assets.
We may want to replace `_bufferCodecEventsTotal` and `bufferCodecEventsExpected` with a map of tracks/SourceBuffer types ('audio' and/or 'video' or 'audiovideo') to manage SourceBuffer creation on init segment parsed. If you have trouble with MSE setup/reset or an irregular stream like #1510 leave a comment or file an issue mentioning this note.
> Fix detach attach behavior dropping one of two SourceBuffers

- api-extractor/report/hls.js.api.md
- build-config.js
- src/controller/base-stream-controller.ts
- src/controller/content-steering-controller.ts
- src/controller/error-controller.ts
- src/controller/fragment-tracker.ts
- src/controller/level-controller.ts
- src/controller/stream-controller.ts
- src/hls.ts
- src/loader/fragment.ts
- src/loader/m3u8-parser.ts
- src/loader/playlist-loader.ts
- src/types/events.ts
- src/types/level.ts
- src/types/loader.ts
- src/types/media-playlist.ts
- src/utils/codecs.ts
- src/utils/level-helper.ts
- tests/unit/controller/abr-controller.ts
- tests/unit/controller/audio-track-controller.ts
- tests/unit/controller/content-steering-controller.ts
- tests/unit/controller/error-controller.ts
- tests/unit/controller/level-controller.ts
- Use Content Steering Pathways to manage Redundant Streams and resolve their errors.
- Deprecates Level `urlId` indexes and related Level fields and removes redundant failover error handling.
Content Steering error handling is used in place by assigning Redundant Streams a Pathway ID.
Where the default Pathway ID is ".", each Redundant Stream is assigned a Pathway ID based on the number of similar variants encountered: "..", "...", and so on. The Pathway ID assigned is based on the order found in the Multivariant Playlist.
These improvements will help to simplify switching logic with upcoming audio preference API changes (#5532).
> Use Content Steering Pathways to manage Redundant Streams

- src/utils/logger.ts
Remove use of `self` from `enableLogger`
Fixes #5905
> Remove use of `self` from `enableLogger`

- src/controller/timeline-controller.ts
Fix regression introduced with #5689 to lazily instantiate CEA608 parsers (issue found in #5953).
Changes to instantiate CEA608 parsers on FRAG_PARSING_USERDATA introduced side-effects in timeline-controller's FRAG_LOADING handler by skipping the setting of properties used to track continuity.
> Fix regression in dev with CEA608 parser setup

- package-lock.json
- package.json
Update `karma-rollup-preprocessor` to version that works in watch mode
See https://github.com/jlmakes/karma-rollup-preprocessor/issues/78
To fix watch mode for tests. Currently it gets slower and slower before crashing.
> Update `karma-rollup-preprocessor` to version that works in watch mode

- src/utils/mp4-tools.ts
In mp4-tools.ts
* Fixed parsing for sei_message to remove the incorrect masking to 8 bits for the sei message size.
Removes an incorrect masking of payloadSize to 8 bits, allowing payloadSize to be larger than 256, as per the spec.
My previous pull request added an incorrect masking to the payloadSize, and this removes that.
Not in the code. I am curious about thoughts on masking the payloadType. The spec doesn't have any values over 255 that are parsed, however according the spec's parsing logic, it should be permitted to be larger than 255.  I left the mask in, as I doubt it really matters either way.
- [x ] new unit / functional tests have been added (whenever applicable)
- [x ] API or design changes are …
> Fix issues parsing sei_messages

- api-extractor/report/hls.js.api.md
- docs/API.md
- src/config.ts
- src/controller/abr-controller.ts
- src/controller/audio-track-controller.ts
- src/controller/base-stream-controller.ts
- src/controller/content-steering-controller.ts
- src/controller/stream-controller.ts
- src/controller/subtitle-track-controller.ts
- src/hls.ts
- src/loader/level-details.ts
- src/loader/m3u8-parser.ts
- src/types/component-api.ts
- src/types/level.ts
- src/types/media-playlist.ts
- src/utils/mediacapabilities-helper.ts
- src/utils/rendition-helper.ts
- tests/unit/controller/abr-controller.ts
Adds config options and API methods for selecting audio and subtitles based on the attributes of media options (language, characteristics, associated language, channels, codec, name, group).
The primary goal of this feature is to simplify the initial selection of audio and subtitles on startup.
By default, the player will attempt to start playback using default audio (stereo) and default subtitle options. These options and methods allow for the selection of audio and subtitles on startup and during playback, both with and without specific knowledge of the renditions available in an HLS asset.
Since the change from one audio group to another can necessitate a level switch, this API performs these changes when needed. This API allows for switching between change sets, which is impossible …
> API enhancements for audio and subtitle selection

- api-extractor/report/hls.js.api.md
- docs/API.md
- src/config.ts
- src/controller/abr-controller.ts
- src/controller/buffer-controller.ts
- src/controller/error-controller.ts
- src/hls.ts
- src/types/media-playlist.ts
- src/utils/hdr.ts
- src/utils/mediacapabilities-helper.ts
- src/utils/rendition-helper.ts
- tests/unit/controller/buffer-controller-operations.ts
- Add `videoPreference` config option for HDR/SDR VIDEO-RANGE selection preference and priority.
- Query high dynamic-range capability and use result to select from `allowedVideoRanges` when specified.
- Fix an exception on platforms where MediaCapabilities is undefined
These settings determine whether HDR video should be selected before SDR video. Which VIDEO-RANGE values are allowed, and in what order of priority can also be specified.
By default, when `videoPreference` is undefined, SDR will always preferred for maximum backwards compatibility. To enable HDR selection using the media query results without changing `allowedVideoRanges`, include an empty `videoPreference` object in the player config at setup.
Resolves #2489
> HDR/SDR VIDEO-RANGE selection and priority

- api-extractor/report/hls.js.api.md
- docs/API.md
- src/exports-named.ts
- src/hls.ts
- src/is-supported.ts
- Expand `isSupported` check to test alternate baseline codecs. At least one `isTypeSupported` check must pass for `isSupported` to return true
- (Resolves #6004)
- Add `isMSESupported` check (checks for MediaSource API without `isTypeSupported` checks)
- Add named exports for and expose statically: `isSupported`, `isMSESupported`, and `getMediaSource`
- (Resolves #5593)
Not all platforms support AVC/AAC via MSE.
Applications needing more fine grained support checks based on expected delivery formats can implement those checks in their app layer using `isMSESupported` and `getMediaSource().isTypeSupported(mimeType)`.
Ideally the list of codecs checked will be kept short. It should only contain the most widely supported codecs required for compatibility. Changes can be contributed given …
> Expand isSupported check to allow alternative codecs

- src/controller/id3-track-controller.ts
- Remove the use of deprecated `WebKitDataCue`
- If setting custom properties on a VTTCue or TextTrackCue throws, create a new instance with the data fields serialized as JSON in the cue text 
PlayStation4 throws when using `undefined` result from `new Cue`.
Fixes #6020
> ID3 TextTrack Cue fixes for PlayStation4

- build-config.js
- src/polyfills/number.ts
- src/utils/mp4-tools.ts
Add a polyfill for `isSafeInteger`
`Number.isSafeInteger` (like `isFiniteNumber` which is also polyfilled) is missing from older platforms
https://caniuse.com/mdn-javascript_builtins_number_issafeinteger
> Add polyfill for isSafeInteger

- api-extractor/report/hls.js.api.md
- src/controller/eme-controller.ts
- tests/unit/controller/eme-controller.ts
Use `addEventListener` for `MediaKeySession` events
It appears that legacy versions of Chrome (53) do no support the `onmessage` and `onkeystatuseschange` callback handlers.
Fixes #6034
> Use addEventListener for MediaKeySession events

- src/controller/latency-controller.ts
`maxLiveSyncPlaybackRate` should only work for live stream.
I'm using same config (`{ maxLiveSyncPlaybackRate: 1.2 }`) to play normal playback and live stream.
When playing playback, we hope users can change playback rate as needed. However, things work not quiet well.
**When user changes playback rate to 2, the player will reset to 1 quickly.**
To figure out what happen, I have debugged the `latency-controller.ts` file.
It seems that we want to listen 'timeupdate' event when receive **MEDIA_ATTACHED**(https://github.com/video-dev/hls.js/blob/master/src/controller/latency-controller.ts#L153), and remove 'timeupdate' event when receive **LEVEL_UPDATED**(https://github.com/video-dev/hls.js/blob/master/src/controller/latency-controller.ts#L177).
Since the **MEDIA_ATTACHED** is triggered by …
> fix(latency-controller): only sync live stream

- src/loader/m3u8-parser.ts
Ignore #EXT-X-INDEPENDENT-SEGMENTS so that it is not added to Fragment tagList.
INDEPENDENT-SEGMENTS is global to the Playlist and should not be associated with any specific fragment.
HLS.js does not use INDEPENDENT-SEGMENTS because there is no advantage to knowing that all segments have at least one key-frame somewhere. For best performance, HLS.js needs each segment to begin with a key-frame (not just have at least one somewhere). Only streams that have segments that do not start with a key-frame get flagged for backtracking which impacts fragment selection on switch and seek.
> Ignore #EXT-X-INDEPENDENT-SEGMENTS

- scripts/build-deployments-readme.js
- scripts/deploy-cloudflare.sh
- tsconfig.json
Update the deployments readme to only contain the most recent 100 deployments in reverse order. The rest will be contained in a new "deployments.txt" file.
"deployments.json" will be a new file on the deployments branch and be the source of truth.
The readme is getting truncated by github due to the size.
> Store deployments in json file, and generate md and txt file from that

- src/demux/id3.ts
On PS4, TextDecoder is defined but it is partially implemented and does not function properly. This will force manual decoding approach for PS4 platform in `utf8ArrayToStr` function.
It is necessary for private id3s to be correctly decoded and converted on Play Station 4 platform.
> Bugfix/ID3 Decoding On Play Station 4

- src/demux/id3.ts
On PS4, TextDecoder is defined but it is partially implemented and does not function properly. This will force manual decoding approach for PS4 platform in utf8ArrayToStr function.
It is necessary for private id3s to be correctly decoded and converted on Play Station 4 platform.
**Are there any points in the code the reviewer needs to double check?**
**Resolves issues**: https://github.com/video-dev/hls.js/issues/6041
**Checklist**
changes have been done against master branch, and PR does not conflict
new unit / functional tests have been added (whenever applicable)
API or design changes are documented in API.md
> Bugfix/ID3 Decoding On Play Station 4 (1.4.x cherry pick)

- src/controller/audio-stream-controller.ts
- src/controller/base-stream-controller.ts
- src/controller/buffer-controller.ts
- src/controller/stream-controller.ts
- src/controller/subtitle-stream-controller.ts
- tests/unit/hls.js
- Fix base-stream-controller onHandlerDestroying callback evocation
- Remove circular references left after destroying player
Fixes potential for leaks caused by unremoved media event handlers and circular references.
> Fix base-stream-controller onHandlerDestroying callback evocation

- src/utils/fetch-loader.ts
Abort fetch loader as long as loading has not ended.
Fetch response.ok is true as soon as status 200 is returned. In progressive mode, this is set and can be read before all data is loaded and the handling the response is complete.
Instead of checking the response status, `!stats.loading.end` indicates that loading is incomplete and it is OK to abort. `stats.loading.end` is only set after receiving all data and handling the final response before invoking the loader `onSuccess` callback.
Fixes #6054
> Fix fetch loader abort in progressive mode

- src/utils/mp4-tools.ts
Fix the `codec` parsing for MP4 AVC streams.
Previously the codec was wrongly parsed (the extraction of profile + compatibility + level) at a wrong offset.
From a certain version, the source buffer started to get created based on codecs present in init segment instead of the playlist's codecs, resulting in an error since e.g. profile was zero.
> Fix codec parsing for AVC streams

- src/controller/abr-controller.ts
- src/utils/level-helper.ts
- Force auto level on emergency switch down
- Update estimates on frag load timeout
- Do not abort frag load on abandon rules check (wait for new frag request after playlist is loaded to abort)
- Remove two segment forward buffer length limit on abandon rules
- Reset estimate when candidate bitrate is lower than adjusted estimate
In low bandwidth conditions where level loading can take several ticks, setting `hls.nextLoadLevel` on emergency switch down gets overridden by new evaluation of `hls.nextAutoLevel`. Setting `hls.nextAutoLevel` forces abr-controller to wait for the playlist to load.
Since low bandwidth conditions can result in frag loading timeouts, especially when the timeout limits are lowered in setup, updating estimates based on the available stats on timeout will help …
> Fix regression in emergency switch down

- src/controller/cmcd-controller.ts
Null CMCD callbacks on destroy
Inline callback properties like the ones in cmcd-controller are a great alternative to using bind. However, since they end up being declared in the constructor and referencing `this`, they create circular references that can cause leaks when disposing of hls.js player instances. Setting properties these to `null` on destroy removes circular references.
src:
```ts
private onPlaying = () => {
if (!this.initialized) {
```
dist/hls.js:
```js
function CMCDController(hls) {
var _this = this;
this.onPlaying = function () {
if (_this.initialized) {
```
> Null CMCD callbacks on destroy

- .github/workflows/build.yml
Update the artifact actions together because they depend on each other.
The upload and download got a _lot_ quicker! Looks like now it downloads the compressed zip instead of each file individually.
> Update artifact actions

- .github/workflows/build.yml
- tests/functional/auto/setup.js
Update functional tests to run on Safari using MacOS 13 rather than 10.15.
Older versions of Safari are lower in usage and have issue with the "ended" event making functional test run fail. The hope is to get more stable results so that we can rely on auto-merge.
> Update functional tests to run on Safari using MacOS 13

- src/demux/audio/adts.ts
Apply the Firefox AAC SBR (HE-AAC) workaround to Pale Moon (confirmed working on my end).
Without this change, Pale Moon plays sound on some streams at an extremely low pitch with crackling.
Correct regex?
- I've unsuccessfully tried creating a test for Pale Moon in particular (adapting the Firefox low-frequency sound test for Pale Moon did not result in a failing test, even before this change is implemented), although existing tests continue to pass.
> Use AAC SBR (HE-AAC) workaround on Pale Moon

- src/crypt/decrypter.ts
Use the WebCrypto API by default and only use software decryption as a fallback if enabled (default behavior).
This fixes the use of  `enableSoftwareAES` to match the docs and the intended behavior when added in #99.
> Use WebCrypto by default for AES decryption

- api-extractor/report/hls.js.api.md
- src/controller/base-stream-controller.ts
- src/controller/buffer-controller.ts
- src/controller/eme-controller.ts
- src/controller/latency-controller.ts
- src/controller/stream-controller.ts
- src/controller/subtitle-track-controller.ts
- tests/unit/controller/latency-controller.ts
Prefer inline callback properties to binding methods to new properties, and null referenced on destroy.
Reduce retained references after destroying the player in UAs that cannot remove circular references to class instance "_this" hoisted into callbacks defined in the constructor (Follows up on #6098).
> Null inline class JavaScript Event callback properties on destroy

- src/controller/level-controller.ts
- src/demux/transmuxer-interface.ts
- src/demux/transmuxer.ts
- src/demux/tsdemuxer.ts
- src/remux/mp4-remuxer.ts
- src/utils/codecs.ts
Replace user-agent check for "mp4a.40.34" to "mp3" and "audio/mpeg" fallback with support checks,
MSE support checks fail for ISO BMFF "MP3"  identifier for codecs parameter "mp4a.40.34". HLS.js works around this by using "mp3" as the identifier, or by checking support for "audio/mpeg" SourceBuffers. It only does this when the user-agent contains "chrome" or "firefox", but this issue affects other browsers. Removing the UA check and using support checks like we do for the many casings of 'fLaC' is a more elegant solution.
Fixes #6125
> Fix filtering of "mp4a.40.34" variants in Safari

- src/controller/base-stream-controller.ts
- src/controller/subtitle-stream-controller.ts
- src/crypt/aes-crypto.ts
- src/crypt/decrypter-aes-mode.ts
- src/crypt/decrypter.ts
- src/crypt/fast-aes-key.ts
- src/demux/sample-aes.ts
- src/demux/transmuxer.ts
- src/loader/fragment-loader.ts
- src/loader/key-loader.ts
- src/loader/level-key.ts
- src/utils/encryption-methods-util.ts
- tests/index.js
- tests/test-streams.js
- tests/unit/crypt/decrypter.js
- tests/unit/loader/playlist-loader.ts
Adding AES-256 and AES-256-CTR encryption methods (full segment, as AES-128)
Need stronger encryption scheme than AES-128 for CCTV scenario, in the short-mid term.
See more context & informal addendum to rfc8216 at :
https://mailarchive.ietf.org/arch/msg/hls-interest/RZBgatOvI4W0M0J5cShuXWzdigg/
- I have very little experience in JavaScript/TypeScript, please assume that everything is wrong language wise :-)
- Error handling
- Everything crypto related
- Does not enforce the presence of explicit IV in AES-256 & AES-256-CTR (when the rfc informal proposal stated they SHALL be present, and different for each segment).
- AES-256 & AES-256-CTR will only work with WebCrypto, not the JavaScript implementation.
- Range access ‘adjustment’ is not implemented for CTR mode (don’t re-compute nonce …
> Adding AES-256 and AES-256-CTR encryption methods

- src/demux/audio/adts.ts
- src/remux/mp4-remuxer.ts
- src/types/demuxer.ts
- tests/unit/demuxer/adts.js
Prefer to use originalCodec when generating silent aac frame.
As https://github.com/video-dev/hls.js/blob/master/src/demux/audio/adts.ts#L87 mentioned, audio type will always force to be HE-AAC SBR in some browsers.
When I play {codec: mp4a.40.2, channelCount: 2} stream with gaps in Chrome, MP4Remuxer will inject mp4a.40.5 frame, which sounds noisy.
> fix: generate silent aac frame based on original codec

- src/controller/abr-controller.ts
- src/controller/level-controller.ts
Fixes a regression where using max bitrate to estimate time to load a segment could result in more emergency aborts and less stable playback when the the max is unusually larger than the average and/or larger than that of some upper tiers.
Fixes #6122
> Use average for level sorting and abandon rules check

- api-extractor/report/hls.js.api.md
- src/config.ts
- src/controller/abr-controller.ts
- src/controller/audio-stream-controller.ts
- src/controller/audio-track-controller.ts
- src/controller/base-playlist-controller.ts
- src/controller/base-stream-controller.ts
- src/controller/buffer-controller.ts
- src/controller/cap-level-controller.ts
- src/controller/content-steering-controller.ts
- src/controller/eme-controller.ts
- src/controller/error-controller.ts
- src/controller/fps-controller.ts
- src/controller/gap-controller.ts
- src/controller/latency-controller.ts
- src/controller/level-controller.ts
- src/controller/stream-controller.ts
- src/controller/subtitle-stream-controller.ts
- src/controller/subtitle-track-controller.ts
- src/controller/timeline-controller.ts
- src/demux/transmuxer-worker.ts
- src/hls.ts
- src/task-loop.ts
- src/utils/logger.ts
- tests/mocks/hls.mock.ts
- tests/unit/controller/subtitle-stream-controller.js
- tests/unit/loader/fragment-loader.ts
- Retrieve a new logger configuration from `enableLogs ` for each `Hls` instance and for external contexts (transmuxer-worker)
- Extend controller classes with instance logger configuration 
- Add a read-only `logger` property to `Hls` instances (used in places where instance is available and extending a class is impossible or impractical)
This allows each player instance to maintain the logging configuration it was given. It also allows for custom logger configs and future updates to add labelling to distinct player instances on the page in a single log file.
Resolves #2461
> Use unique logger configurations across instances

- api-extractor/report/hls.js.api.md
- src/controller/base-stream-controller.ts
- src/controller/gap-controller.ts
- src/controller/level-controller.ts
- src/controller/stream-controller.ts
- src/events.ts
- src/hls.ts
- src/types/events.ts
- tests/functional/auto/setup.js
Add a MEDIA_ENDED event. This event emits when the media element dispatches its "ended" event or when stalling has begun near end of VOD.
This event is useful in apps that need to do something when VOD playback has ended, but the user-agent does not dispatch "ended" reliably (common on older WebKit UAs).
Note that Safari 17 significantly improves the handling of "ended" event dispatching at the end of VODs, so the issues this resolved may be more difficult to reproduce than it was in past versions with most HLS assets.
Resolves #5274
- #5274
Related to:
- #5703
- #5168
> MEDIA_ENDED event

- src/remux/mp4-remuxer.ts
Ensure PTS order while remuxing an overlapping segments.
We are experiencing the following scenario
_GIVEN_
Variable frame rate stream where we have:
- Two contiguous segments (SegA and SegB) which have an overlap
- mp4SampleDuration of the last sample of SegA is 7508 
- delta of -4505 with SegB
- SegB has initial couple of samples with duration of 3003
- timebase of 90000
_WHEN_
The remuxVideo gets invoked AND the overlap logic triggers
_THEN_
the PTS becomes misaligned and Safari throws a **_Media failed to decode_** error code 3 (MEDIA_ERR_DECODE) on the DOM Node
Chrome handles this scenario well and has no issues, but seems Safari is quite strict about things like this.
```
// inputSamples before PTS/DTS adjustments:
// [
//    {key: true, frame: true, pts: 270270, dts: 270270, units: …
```
> fix(Remuxer): Safari segment overlap ensure PTS order

- src/controller/abr-controller.ts
- tests/functional/auto/setup.js
- Fix regression in hls.light.js selection
- Enable smooth switch functional tests for light build
Changes in 1.5 use MediaCapabilities to filter adaptive qualities. When using this feature is disabled (like in the light build by default) all variants are filtered out, resulting in a downswitch to 0.
This also impacts the standard build with config option `useMediaCapabilities: false`.
Fixes #6151
> Fix regression in hls.light.js selection

- tests/test-streams.js
Disable `AppleAdvancedHevcAvcHls` stream for now due to cors errors. It's causing a build up of dependency updates.
`https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_adv_example_hevc/master.m3u8` currently fails because cors headers are missing 😢 
@robwalch maybe you could get this fixed? :)
> Disable `AppleAdvancedHevcAvcHls` stream for now due to cors errors

- src/controller/audio-stream-controller.ts
- src/controller/subtitle-stream-controller.ts
Use main playlist details to determine start position of audio and subtitle streaming controllers
Startup worked (corrected itself) in 1.4 but regressed in 1.5 to only load live edge on live media playlists (audio) and first segment in vod media playlists (main) which results in playback not starting (no combined buffer) until a seek.
How does this impact live start? So far looks like a more aligned start time results in fast start times when initial live playlist are not perfectly aligned. Not sure if there are some edge cases where the main start time presents a problem for audio or sub playlists abnormal starts or alignment.
Fixes #6126
> Align playlists streaming start position with mismatched end-list tags

- docs/API.md
- src/controller/abr-controller.ts
- src/controller/stream-controller.ts
Fix regression that removed (unofficial) support for `startLevel` above max level index. Update docs to note that `startLevel`  _should_ be set to a valid level index.
Setting `startLevel` to Infinity is used to start on max level index even though the player emits a non-fatal error. Since the error is non-fatal playback and streaming should not fail.
Changing stream-controller `startLoad` logic can have side-effects. This change is an improvement that will keep the stream-controller's level index aligned with the level controllers load level index.
Fixes #6172
> Support `startLevel` above max level index

- src/utils/mp4-tools.ts
Account for overlapping sidx subsegment durations by parsing earlierstPresentationTime
Summing up all sidx box subsegment durations to get segment duration will add muxed audio and video track durations together without accounting for overlap. This bug was introduced with #4849 because earlierstPresentationTime was never parsed and potential for overlap was never taken into account.
I found overlapping sidx boxes in media from #1510 but had to change mp4-tools `getDuration` temporarily to ignore trun durations to see the impact that using overlapping durations from sidx boxes would have. This fix has not been verified against #6191 because a sample that reproduces the issue has not been provided.
Fixes #6191
> Account for overlapping sidx subsegment durations by parsing earlierstPresentationTime

- api-extractor/report/hls.js.api.md
- src/controller/audio-stream-controller.ts
- src/controller/base-stream-controller.ts
- src/controller/buffer-controller.ts
- src/controller/stream-controller.ts
- src/hls.ts
- src/types/component-api.ts
Handle ManagedMediaSource "endStreaming" events without aborting requests.
Using start/stopLoad to throttle buffering aborts active requests which can make the use of ManagedMediaSource less efficient when resources must be re-requested.
This change is against development and will go into v1.6.0. Leave a comment if you would like it picked into patch/v1.5.x.
Related to #6181
> Handle ManagedMediaSource endStreaming events without aborting requests

- build-config.js
- src/demux/tsdemuxer.ts
Remove HEVC in TS support in hls.light.js
The light build has AC-3 in TS and other features removed using build consts. HEVC in TS support adds roughly 7kB to the minified hls(.light).js library payload which should not be included in the light build.
Excluded from light build using __USE_M2TS_ADVANCED_CODECS__ build const same as AC-3 in TS.
Follow up to #5847
> Do not include HEVC in TS support in hls.light

- src/controller/cmcd-controller.ts
- src/loader/playlist-loader.ts
- src/utils/logger.ts
Make global exported logger uses the log methods from last call to `enableLogs`
Changes to logger ts failed to update the exported logger object methods from `noop` to latest enabled settings. For the log messages still not scoped to a player instance, these logs should behave as they did in earlier releases.
Follow up to #6131
> Restore global logger logs in dev

- src/controller/base-playlist-controller.ts
- src/controller/level-controller.ts
- Skip segment and part directives when last LL-HLS response is older than three target durations
- Fix Media Playlist 'advanced' state when no Multivariant Playlist is provided Related to #6076
Prevents requests for stale playlists.
Related to #6076
> Skip Low-Latency HLS segment and part directives after long delay

- src/controller/abr-controller.ts
- src/controller/stream-controller.ts
- Set buffer starvation delay to Infinity when media is detached
- Exit early from MediaCapabilities decodingInfo Promise callback after player has been destroyed
- Limit polling of next level when detached to start frag prefetch
- Prevents excessive logging from selection fallback when buffer is deemed empty because media is detached
- Prevents exception on resolving decodingInfo after player is destroyed
- Reduce redundant logs in detached prefetch or loading state
> Fix issues with detached and destroyed level selection

- src/utils/mp4-tools.ts
fix parsing of earliestPresentationTime in sidx atom.
Because earliestPresentationTime and firstOffset are not parsed correctly, the offset arg passed to `readUintXX` is wrong, since `index += Y` is evaluated before the call to `readUintXX`. Reading the value of earliestPresentationTime should be done with an offset of 12, but its actually done with an offset of 16.
- [-] changes have been done against master branch, and PR does not conflict
> fix sidx parsing

- api-extractor/report/hls.js.api.md
- src/controller/abr-controller.ts
- src/controller/audio-stream-controller.ts
- src/controller/base-stream-controller.ts
- src/controller/buffer-controller.ts
- src/controller/buffer-operation-queue.ts
- src/controller/fragment-tracker.ts
- src/controller/stream-controller.ts
- src/controller/subtitle-stream-controller.ts
- src/hls.ts
- src/utils/codecs.ts
- tests/unit/controller/buffer-controller-operations.ts
Block audio append queue to keep AV appends in lock-step
Keeping audio and video appends in sync can improve streaming performance by throttles audio requests that are not yet required, and allow stalls to occur when video is not loading fast enough.
This change will also help in buffering media up to an Interstitial break, although additional work is needed to set boundaries on active Interstitial timeline segments.
> Block audio append queue to keep AV appends in lock-step

- src/utils/buffer-helper.ts
Cleanup buffer-helper functions and remove nesting try-catch statements
- Fixes case where `getBuffered` can return undefined (`media.buffered` if not defined should fallthough to empty TimeRange)
- `isBuffered` and `bufferInfo` no longer need try-catch blocks because they don't throw and neither do their sub-routines
> Cleanup buffer-helper functions and remove nested try-catch statements

- src/controller/buffer-controller.ts
Fix compatibility of ManagedMediaSource implementation with Edge 18. Gate all ManagedMediaSource logic, including appending child source element by the presence of the ManagedMediaSource API.
SourceBuffers get stuck in "updating" state assigning MediaSource to a child `source` element of HTMLMediaElement in Edge 18.
Fixes #6243
> Fix compatibility of ManagedMediaSource implementation with Edge 18

- src/utils/logger.ts
When updating the exported singleton logger, don't copy new logger functions with player ids.
In places where `logger` is used without player context (Hls instance) the id of the last player to call `enableLogs` should not be prefixed to log messages.
> Don't pass log functions with player id to global logger

- docs/API.md
Update API.md removeLevel description
removeLevel description is outdated
- [ - ] changes have been done against master branch, and PR does not conflict
- [ - ] API or design changes are documented in API.md
> API.md update removeLevel

- .github/workflows/automerge.yml
Update dependency update auto merge action and use GitHub auto merge.
Our CI user has been suspended and I think it may be automated due to the number of repeated merge calls the action was making. With these changes the action will now enable the native GitHub auto merge feature which should be much more efficient. 
Note the CI user is still disabled so this still won't actually work right now. I'm waiting to hear back from support.
> Update dependency update auto merge action and use GitHub auto merge

- src/controller/base-playlist-controller.ts
- src/controller/cmcd-controller.ts
- src/controller/level-controller.ts
- src/demux/audio/base-audio-demuxer.ts
- src/demux/audio/mpegaudio.ts
- src/demux/mp4demuxer.ts
- src/demux/video/hevc-video-parser.ts
- src/events.ts
- src/exports-named.ts
- src/loader/fragment-loader.ts
- src/loader/key-loader.ts
- src/remux/mp4-remuxer.ts
- src/types/component-api.ts
- src/types/remuxer.ts
- src/utils/fetch-loader.ts
Refactor TypeScript type imports to consistently only use `type` keyword with the imports.
Improves tooling identification of type vs. non-type imports.
> chore: update all type imports to explicitly use the type keyword.

- src/controller/buffer-controller.ts
- src/utils/mediasource-helper.ts
Flip the **BufferController.appendSource** flag, in cases where **_preferManagedMediaSource_** config is set to **_false_** but MSE is not present.
The API Docs state:
```
preferManagedMediaSource
...
Setting this to false will only use ManagedMediaSource when MediaSource is undefined.
```
This is indeed the case but the  **appendSource** flag is never updated to handle the scenario as it's only set within the constructor:
```
this.appendSource =
hls.config.preferManagedMediaSource &&
typeof self !== 'undefined' &&
(self as any).ManagedMediaSource;
```
, thus blocks like:
```
if (this.appendSource) {
ms.addEventListener('startstreaming', this._onStartStreaming);
ms.addEventListener('endstreaming', this._onEndStreaming);
}
```
and 
```
if (this.appendSource) {
try { …
```
> Bugfix: preferManagedMediaSource:false when MSE is not present 

- src/controller/buffer-controller.ts
- src/utils/codecs.ts
Avoid using "levelCodec" to instantiate the audio SourceBuffer when multiple audio codec strings are present in the Multivariant Playlist CODECS attribute for muxed content (TS segment without alt-audio).
SourceBuffer creation fails with invalid mime-time.
Fixes #6337
> Bugfix: Handle duplicate audio codec in CODECS

- api-extractor/report/hls.js.api.md
- src/controller/content-steering-controller.ts
- src/controller/level-controller.ts
- src/hls.ts
Add public API for pathwayPriority
To be able to manage pathwayPriority when we working with redundant streams
- [+] changes have been done against master branch, and PR does not conflict
> pathwayPriority getter/setter added

- src/demux/video/avc-video-parser.ts
- src/demux/video/base-video-parser.ts
- src/demux/video/hevc-video-parser.ts
- src/types/demuxer.ts
- tests/test-streams.js
It prevents error "Malformed SEI payload. X is too small, only Y bytes left to parse" in case when SEI overflows PES. It also adds new test stream, HEVC in MPEG-TS, with variety of such NAL units of different types.
Test stream: mpegTsBitmovinHevc (see `test-streams.js`)
PS
In spite of the error video track can be played. Therefore if this PR is approved, the changes can be merged right before 1.6.0 release in order to avoid inconvenience with `patch` branch.
> Fix extraction of NALu overflowing PES packet

- src/controller/cmcd-controller.ts
- src/hls.ts
- tests/unit/controller/cmcd-controller.ts
Resolves #6388 
CMCD data is improperly constructed for part requests.
#6388
> Bugfix: use part details to construct CMCD data when available

- src/loader/m3u8-parser.ts
- tests/unit/loader/playlist-loader.ts
- Update parser pattern to not terminate segment URIs on irregular white-space
- Add test for unicode (\u3000) white-space in segment URIs
Someone put \u3000 chars in their segment URIs and the regular expression to match segment URIs ends on any white-space character instead of only newline or return like the pattern used for media playlist URIs.
Fixes #6381
> Bugfix: Handle irregular white-space in segment URIs

- docs/API.md
Adjust the API documentation for property capLevelToPlayerSize.
Without this clarification anyone using a modern high resolution display will have to figure out the additionally required config themselves.
- https://github.com/video-dev/hls.js/issues/5594
> Clarify capLevelToPlayerSize docs in API.md

- src/controller/subtitle-stream-controller.ts
- tests/unit/controller/subtitle-track-controller.ts
Fix issue where changing subtitle before onLoaded is called drops the details from the track
Resolves https://github.com/video-dev/hls.js/issues/6402
https://github.com/video-dev/hls.js/issues/6402
> Fix missing details if subtitle changed synchronously after loaded and before onLoaded callback

- src/controller/base-stream-controller.ts
Clear backtracking fragments stuck in "APPENDING" state without reducing max buffer length.
Reducing the max buffer length and skipping fragment tracker removal is done to address BUFFER_FULL errors (#5354).
Fixes #6428
> Fix backtracking when an appended segment has no buffered timerange

- src/controller/timeline-controller.ts
- src/utils/cea-608-parser.ts
- Fix 608 parser handling of redundant control codes
- Fix 608 caption TextTrack Cue seek/discontinuity timing regression introduced in v1.5.0 with #5557
- Lazily evaluate all 608 parser logger message statements
> Fix 608 parser handling of redundant control codes
The 608 parser was not ignoring redundant control codes for special characters, resulting in the display of duplicate special characters in streams that carried redundant entries.
> Fix 608 caption TextTrack Cue seek/discontinuity timing regression introduced in v1.5.0 with #5557
The 608 parser was not being reset on seek within the same discontinuity since v1.5.0 resulting in captions undrawn before seek to be added to the TextTrack with incorrect durations.
> Lazily evaluate all 608 parser logger message statements
To avoid …
> Fix 608 parser handling of redundant special chars and cue timing after seek

- src/demux/transmuxer-interface.ts
- src/demux/tsdemuxer.ts
Emit FRAG_PARSING_ERROR on unsupported M2TS codec. Include `frag` reference in error event when `enableWorker` is `false`.
When EC-3 is encountered in MPEG-2 TS segments a warning is logged, but the result is handled like an empty segment (gap) rather than a standard FRAG_PARSING_ERROR error which calls for a variant or rendition change. 
Throwing from the demuxer is handled by emitting FRAG_PARSING_ERROR. The error is handled as an audio codec error provided the `frag` reference is present in the error event payload.
Fixes #6445
> Emit FRAG_PARSING_ERROR on unsupported M2TS codec

- src/controller/timeline-controller.ts
Do not allow subtitles TextTracks with labels matching captions options names to be reused by timeline-controller.
Handles edge case where subtitle and captions media options are assigned the same NAME attribute value.
Fixes #6392
> Fix duplicate subtitle/captions with same NAME edge-case

- build-config.js
- src/empty-es.js
ESM build needs a special empty file that exports an object to prevent property access of "undefined"
Fix `hls.light.mjs` script crash (`TypeError: Cannot read properties of undefined (reading 'KeySystemFormats')`
ESM bundle imports `empty` as an object. So we must export an empty object instead of `undefined` to prevent a crash.
> Fix light ESM build

- src/controller/base-stream-controller.ts
- src/demux/transmuxer-interface.ts
- src/demux/transmuxer-worker.ts
- src/demux/tsdemuxer.ts
- Emit FRAG_PARSING_ERROR rather than throw in TSDemuxer
- Add type safety to worker message handling
- Warn with error message when available
Throwing in transmuxers was handled correctly in worker and async (WebCrypto Promise wrapped) execution paths, but not in sync paths (transmuxer-interface `handleTransmuxComplete`, `handleFlushResult`).
This is only an issue when delivering codecs unsupported in TS. 
Resolves #6445
> Fix TSDemuxer parsing error handling in sync path

- src/controller/stream-controller.ts
Fix exception reading metadata.channelCount with HE-AAC when changeType is not supported.
`audio.metadata` is undefined after parsing mp4 init segments.
Fixes #6470
> Fix HE-AACv1 and v2 in fMP4 on iOS

- src/controller/base-stream-controller.ts
- src/controller/fragment-finders.ts
Don't append over first fragment when next fragment aligns with playlist within 1/200s tolerance.
Fixes edge-case starting in v1.5 that causes #6441
The 1/200s magic number is a temporary workaround. We may make this configurable in future releases, but it can be masked completely by `maxFragLookupTolerance`.
> Prevent overlapping appends on start not present in v1.4.x

- src/controller/error-controller.ts
- src/controller/subtitle-stream-controller.ts
Fix default error handling of GAP tags always treated as error in MAIN playlist.
`getLevelSwitchAction` ignores candidates with the same group ID, but this was being short-circuited by the `errorDetails === ErrorDetails.FRAG_GAP && data.frag` check.
Adding the subtitle fragment with a gap to the fragment tracker prevents loop loading with repeated gap tag error events.
Resolves #6475
> Fix error handling for GAP tags in subtitles or audio

- api-extractor/report/hls.js.api.md
- src/controller/abr-controller.ts
- src/hls.ts
- src/types/media-playlist.ts
- src/utils/hdr.ts
- src/utils/rendition-helper.ts
- Add `videoCodec` field to `config.videoPreference`
- Improve SDR/HDR initial selection results
- Don't narrow allowed video-ranges to one that is not available
- Pick lowest in start tier regardless of "skip candidate" rules as long as "can switch within tolerance" check passes
- Fix return value for `setSubtitleOption` and undefined->null type for `setAudioOption`
- #5730 with child player instances that match primary player SourceBuffer configuration
> Add videoCodec field to videoPreference options

- src/demux/video/avc-video-parser.ts
- src/demux/video/base-video-parser.ts
- src/demux/video/hevc-video-parser.ts
- src/types/demuxer.ts
Revert NALu overflow handling change introduced in #6268 that results in a decode error at 30s w/ https://playertest.longtailvideo.com/adaptive/elephants_dream_v4/media/b2962000-video.m3u8 
`PIPELINE_ERROR_DECODE: Error Domain=NSOSStatusErrorDomain Code=-12909 "(null)" (-12909): VTDecompressionOutputCallback`
The above asset produces a decode error when playback reaches 29-30s in Chrome using the latest from dev:
https://hlsjs-dev.video-dev.org/demo/?src=https%3A%2F%2Fbitmovin-a.akamaihd.net%2Fcontent%2Fdataset%2Fmulti-codec%2Fhevc%2Fv720p_ts.m3u8&demoConfig=eyJlbmFibGVTdHJlYW1pbmciOnRydWUsImF1dG9SZWNvdmVyRXJyb3IiOmZhbHNlLCJzdG9wT25TdGFsbCI6ZmFsc2UsImR1bXBmTVA0Ijp0cnVlLCJsZXZlbENhcHBpbmciOi0xLCJsaW1pdE1ldHJpY3MiOi0xfQ==
The escape can be tracked back to #6268.
This PR removes the …
> Fix decode error escape in dev

- src/controller/abr-controller.ts
Fixes regression in dev introduced in #6483 where variant with alternate codec can be selected.
Audio and video codec should not be changed without manual intervention.
> Fix selection codec contstraint

- api-extractor/report/hls.js.api.md
- src/controller/abr-controller.ts
- src/controller/audio-stream-controller.ts
- src/controller/base-stream-controller.ts
- src/controller/buffer-controller.ts
- src/controller/error-controller.ts
- src/controller/fragment-finders.ts
- src/controller/fragment-tracker.ts
- src/controller/stream-controller.ts
- src/controller/subtitle-stream-controller.ts
- src/controller/timeline-controller.ts
- src/hls.ts
- src/loader/fragment-loader.ts
- src/loader/fragment.ts
- src/loader/level-details.ts
- src/loader/playlist-loader.ts
- src/remux/mp4-remuxer.ts
- src/remux/passthrough-remuxer.ts
- src/types/events.ts
- src/utils/level-helper.ts
- src/utils/rendition-helper.ts
- tests/unit/controller/stream-controller.ts
Ensure that audio-stream-controller loads segments from the same discontinuity domain (`cc`) as the main stream-controller.
Sync max audio buffer target with main playlist loading fragment (rather than video SourceBuffer end).
Properties defined in the base stream controller class are now set and reset there where possible.
This PR improves Live start and VOD resume at offset by selecting audio segments that align with selected video segments.
> Sync audio fragment loading with main discontinuity and time

- api-extractor/report/hls.js.api.md
- src/controller/base-stream-controller.ts
Reduce max buffer length in response to buffer full errors using the duration of the fragment that caused the error .
- Max buffer length is reduced by three fragment durations or half (whichever result is greater)
- The minimum value for max buffer length is constrained between `maxBufferLength` and fragment duration
`reduceMaxBufferLength` was a no-op when its input was greater than half `maxMaxBufferLength`.
Fixes #6529
> Fix: Reduce max buffer length

- api-extractor/report/hls.js.api.md
- src/controller/base-stream-controller.ts
Use strict tolerance when picking fragments when paused and seeking backward.
Support seeking back step-by-step without requiring additional configuration that sacrifices performance when seeking forward while playing.
This cannot address rendering of buffered media near an unbuffered playhead or rendering subsequently buffered media while paused. I consider these MSE flaws that HLS.js cannot or should not workaround (at least not with this change). For more detail see https://github.com/video-dev/hls.js/issues/6511#issuecomment-2191450440.
Does anyone question whether this enhancement should only apply when media is paused (and not when seeking backwards)? When not paused the _max frag lookup and buffer hole_ tolerances allow skipping loading of a whole segment that would only contribute …
> Paused and backward seeking enhancement

- demo/main.js
Fix a XSS vulnerability by validating user input stream URL.
XSS Proof:  https://hlsjs-dev.video-dev.org/demo/?src=%3Cimg%20src%3D%22x%22%20onerror%3D%22alert(%27XSS%27)%22%3E&demoConfig=eyJlbmFibGVTdHJlYW1pbmciOnRydWUsImF1dG9SZWNvdmVyRXJyb3IiOnRydWUsInN0b3BPblN0YWxsIjpmYWxzZSwiZHVtcGZNUDQiOmZhbHNlLCJsZXZlbENhcHBpbmciOi0xLCJsaW1pdE1ldHJpY3MiOi0xfQ==
No.
XSS vulnerability (Snoatype Nexus IQ `sonatype-2018-0455`)
> Fix XSS vulnerability by validating user input stream URL.

- src/remux/mp4-remuxer.ts
Remove `remuxEmptyAudio`.
This method is no longer used.
If HLS.js is to support silent audio insertion beyond what is currently present in `remuxAudio`, then it should be done for a wider array of supported audio formats and should be done for both muxed TS and unmuxed sources.
Informed by #6528
> Remove unused method

- src/utils/codecs.ts
- tests/index.js
- tests/unit/utils/codecs.ts
Fix the parse of multiple value codecs (CODECS="avc1.64001E,avc1.64001f,mp4a.40.2") on `convertAVC1ToAVCOTI` function.
Before this MR, the codec value was converted from "avc1.64001E,avc1.64001f" to "avc1.fa01fa01" leading to the "no level with compatible codecs found in manifest" error.
Now, it is keeping the "avc1.64001E,avc1.64001f" value.
It fixes media with multiple video codecs broken on `1.5.x` hls.js versions.
Ex.: 
`#EXT-X-STREAM-INF:BANDWIDTH=1199000,RESOLUTION=854x480,CODECS="avc1.64001E,avc1.64001f,mp4a.40.2",AUDIO="audio",SUBTITLES="subs"`
Related to https://github.com/video-dev/hls.js/issues/5378
> Fix parsing of multiple video codecs when converting from AVC1 to AVCOTI

- src/controller/base-stream-controller.ts
Make sure `reduceMaxBufferLength` can reach a min length of fragment duration resulting in buffer full error.
With under-reported bitrate the player may try to reload media that cannot be appended after reducing max buffer length close to but not all the way to the needed minimum.
Resolves #6535
> Fix `reduceMaxBufferLength` with under-reported bitrate

- api-extractor/report/hls.js.api.md
- src/controller/audio-stream-controller.ts
- src/controller/base-stream-controller.ts
Fixes a shortcoming in #6491 that assumes the last fragment of the main playlist to be loaded is nearest to the end of the buffer.
Prevents audio from not loading up to a previously appended video buffer range after appended audio was ejected.
This was a regression in dev discovered while testing #6529.
> Fix audio segment loading when main segments loaded out of sequence

- src/controller/base-stream-controller.ts
- Add fragment "Parsed" log line that reports start and end PTS before append
- Add frag.start and frag.end to fragment "Loading" log lines
- Make fragment Loading > Loaded > Parsed > Buffered log lines more consistent
This will help in cases where appends fail as well as make it easier to find all lines relevant to a particular segment ("main" or "audio" sn of "level" or "track").
```
[log] > [stream-controller]: Loading main sn: 4 of level 17 (frag:[23.650-31.533]) cc: 0 [1-77], target: 23.65
[log] > [stream-controller]: Loaded main sn: 4 of level 17
[log] > [stream-controller]: Parsed main sn: 4 of level 17 (frag:[23.650-31.533])
[log] > [stream-controller]: Buffered main sn: 4 of level 17 (frag:[23.650-31.533] > buffer:[0.000-31.533])
```
Related to #6191
> Log parsed segment timestamps ahead of append

- src/utils/discontinuities.ts
- tests/unit/utils/discontinuities.ts
Improve playlist alignment based on discontinuity sequence change
`alignDiscontinuities` did not always align on discontinuity sequence change between two different parsed playlists (`LevelDetails`) as it should (as pointed out in #4416).
This removes the need for the `lastFrag` argument in `alignStream`. I'll address cleanup in base-stream-controller in another PR.
Resolves #4416
> Improve playlist alignment based on discontinuity sequence change

- src/controller/base-stream-controller.ts
- src/demux/audio/aacdemuxer.ts
- src/demux/audio/ac3-demuxer.ts
- src/demux/inject-worker.ts
- src/demux/transmuxer-interface.ts
- src/demux/transmuxer-worker.ts
- src/demux/transmuxer.ts
- src/demux/tsdemuxer.ts
- src/hls.ts
- src/remux/mp4-remuxer.ts
- src/remux/passthrough-remuxer.ts
- src/version.ts
- tests/unit/demuxer/transmuxer.ts
- Usa a single Web Worker by path and by player version across instances of transmux-interface and `Hls`
- Use the configured logger in remuxer and demuxer instances and static calls to probe
Creating and tearing down workers is costly. Avoiding this should improve performance and avoid leaks where `resetTransmuxer` is run in stream controllers.
Workers are torn down only once all clients using them are destroyed. Worker load is fairly light so managing all transmuxers in a single worker should not have any negative impact on performance.
- Resolves #5402
- Related to #2461
> Reduce workers across instances

- api-extractor/report/hls.js.api.md
- src/controller/base-stream-controller.ts
- src/errors.ts
- src/hls.ts
- tests/unit/hls.ts
Improves error handling in `hls.attachMedia(media)` when `null` is passed as a parameter. 
Logging error to the console will benefit users when when attachMedia is called with a null parameter and this feedback will also help avoid potential confusion.
https://github.com/video-dev/hls.js/issues/6463
> Trigger `ATTACH_MEDIA_ERROR` when calling `attachMedia` with falsey `media` argument

- docs/API.md
Update API.md to reflect `maxBufferHole` v1.0 default.
This issue was mentioned in #6576
> Update API.md to reflect `maxBufferHole` v1.0 default

- src/controller/buffer-controller.ts
Fix the access to retrieve the `src` value from current media.
The problem happens when there is a video element child which is not a `source` element. Other children could be `track` or any other element.
Now, instead of retrieving the `src` from `firstChild`, it is retrieved from the `source` element if it exists.
The cleanup when detaching media is being skipped and an error is wrongly logged due to this problem.
> Fix access of mediaSrc value

- MIGRATING.md
- api-extractor.json
- package.json
Let TypeScript find the corresponding TypeScript definition file (.d.mts and.d.ts) by extension substitution for ESM and UMD library exports.
This is to satisfy https://arethetypeswrong.github.io/?p=hls.js
Resolves #6612
> Support TypeScript Node16/NodeNext module resolution

- tests/test-streams.js
Update the source URL for a test asset
We're moving away from S3 buckets for this use case, and have instead hosted this file on github actions
Just confirming the test still runs as expected.
> Update test case to use Github Pages url

- src/utils/discontinuities.ts
- src/utils/level-helper.ts
- tests/unit/controller/level-helper.ts
Align live playlist updates to end of last when there is no media-sequence overlap and no PDT.
When really short live playlists with sliding windows fail to update for longer than the duration of the sliding window, fragment times will slide back to 0 when there is no overlapping media-sequence, no overlapping discontinuity-sequence, and no program date time to sync on.
Keeping the sliding window moving forward, ahead of the playhead, ensures that streaming can continue and playback can resume when conditions are favorable and playback can resync with the live edge.
Resolves #6685
(duplicate of #5282)
> Align live playlist updates to end of last when there is no overlap

- src/controller/eme-controller.ts
Removes duplicate `catch()` handlers added to `keySessionContextPromise`.
Only handle license renewal error if no longer listening to license status as part of `keyUsablePromise`.
Removes duplicate `catch()` handlers added to `keySessionContextPromise` and prevents error handling from running before `licenseStatus` error is caught emitting the error again. 
- Resolves #6701
- Replaces #6703
> Prevent key errors from being emitted twice

- src/exports-named.ts
- src/loader/fragment-loader.ts
- Export FetchLoader, fetchSupported, XhrLoader, Cues, SubtitleStreamController, requestMediaKeySystemAccess in ESM output (hls.mjs)
- Fix: Disable progressive callbacks in fLoader when progressive mode is disabled Resolves #6707
Allows config options `fLoader`, `pLoader`, and `loader` to be set to imported Loader class, or a custom loader sub-class.
Fixes a bug with setting `fLoader` to `FetchLoader` with default `progressive: false`: data was empty on complete and onProgress was a no-op. Now onProgress no-op is not passed in to fLoader when not in progressive mode so that the correct more direct path is taken to returning data on complete.
Resolves #6707
> Add loaders and other modules used in config to ESM output

- api-extractor/report/hls.js.api.md
- src/controller/buffer-controller.ts
- src/controller/level-controller.ts
- src/controller/stream-controller.ts
- src/hls.ts
- src/remux/passthrough-remuxer.ts
- src/utils/codecs.ts
- src/utils/mediacapabilities-helper.ts
- src/utils/mediakeys-helper.ts
- tests/unit/utils/codecs.ts
- Support unknown codec as video or audio with passing `isTypeSupported` checks
- Use multivariant playlist CODECS when mp4 parsed codec is incomplete
- Add `getMediaDecodingInfo` to public API (undocumented) and fix issues with video and audio only input
- Add codecs-helper to fill in AV1 codec string missing parameters required by MediaCapabilities decodingInfo checks
Adds support for playback of audio and video codecs not indexed in utils/codecs or not parsed completely from mp4 init segment so long as a supported CODECS value is provided.
> Improve support of unknown CODECS

- src/demux/video/hevc-video-parser.ts
This is a fix of track's PPS array growth and related memory leak in HEVC TS parser.
[#6683](https://github.com/video-dev/hls.js/issues/6683)
> Fix PPS array growth in HEVC TS parser

- api-extractor/report/hls.js.api.md
- src/config.ts
- src/utils/fetch-loader.ts
- support promise in `fetchSetup` config
```ts
const hls = new Hls({
progressive: true,
async fetchSetup (ctx, init) {
const signature = await sign(ctx.url)
init.headers = { ...init.headers, 'x-signature': signature }
return new Request(ctx.url, init)
}
})
```
This will be more friendly to users using `progressive` mode.
Currently only xhrSetup supports promises
> feat: `fetchSetup` config support promise

- src/controller/stream-controller.ts
It will iron logic for dropping a level fragment after resetting the details.
It fixes TypeError: Cannot read properties of undefined (reading 'details') which sometimes happens on mobile devices.
Especially on Android 10. 
No idea.
I don't think someone reported an issue.
> fix: drop fragment when currentLevel is undefined

- src/controller/content-steering-controller.ts
- tests/unit/controller/content-steering-controller.ts
Fix content-steering when starting with a single pathway and cloning another without a pathway change
If there aren't pathways to filter out other than the default, or the pathway is not explicitly changed on start, then the levels array in the level controller remain the same as that in the content-steering controller.
Fixes #6759
> Bugfix: content-steering start with one pathway

- src/controller/audio-stream-controller.ts
Fix unregister listener typo in audio-stream-controller
`onFragLoading` should be removed not added again in `unregisterListeners`.
Regression introduced in dev and 1.6.0-beta.1 only. Listeners are still removed on destroy with removeAllListeners.
Resolves #6773
> Fix unregister listener typo in audio-stream-controller

- src/controller/buffer-controller.ts
- tests/unit/controller/buffer-controller-operations.ts
Update `trimBuffers()` to flush the back buffer when `backBufferLength` is set to 0.
To be consistent with the documentation of the `backBufferLength` setting at https://github.com/video-dev/hls.js/blob/master/docs/API.md#backbufferlength , which states that this value can be set to 0 to keep the minimum amount.
Resolves https://github.com/video-dev/hls.js/issues/6781
> Fix back buffer not being flushed when backBufferLength is set to 0 (#6781)

- src/controller/abr-controller.ts
- src/controller/level-controller.ts
Check-in on abandon rules check and abort in-flight frag when stuck on playlist loading
Switches down to a variant that should load at line speed when the higher bitrate in-flight fragment is late. If the playlist of the lower variant still hasn't arrived by the time estimated, and the original in-flight fragment is still active, abort it and switch down further if needed.
Fixes redundant switching level / level loading events that occur for VOD when playlist loading is significantly delays. These events cancel the fallback abandon rules check playlist timeout.
Resolves #6689 (provided throttled requests do not timeout)
> Check-in on abandon rules check and abort in-flight frag when stuck on playlist loading

- api-extractor/report/hls.js.api.md
- docs/API.md
- src/config.ts
- src/controller/cap-level-controller.ts
We have more and more devices with high `devicePixelRatio` values. For example, a new iPhone today has a `devicePixelRatio` of 3. If a high-density browser (usually mobile phones) requests the video, a level with high resolution is requested. In the past, to avoid this, `ignoreDevicePixelRatio` was implemented. However, this results in videos that are sometimes visually detectably low-res. This option provides a granular value to adjust this.
For example, if a video on an iPhone loaded before with `{ capLevelToPlayerSize: true }` 10 MB, it would now take about 4.5 MB with `{ capLevelToPlayerSize: true, maxDevicePixelRatio: 2 }` (10 MB ÷ (3 × 3) * (2 × 2)) with almost no visual degradation (assuming, of course, the levels are available).
no
use case with hight density devices.
> feat: `maxDevicePixelRatio` limits the browser's value

- README.md
- api-extractor/report/hls.js.api.md
- src/controller/abr-controller.ts
- src/loader/fragment-loader.ts
- src/loader/fragment.ts
- src/loader/m3u8-parser.ts
- tests/unit/loader/playlist-loader.ts
Use segment #EXT-X-BITRATE tag value where applicable. Adds Fragment byteLength getter and bitrate getter/setter.
Improves `_abandonRulesCheck` calculations when #EXT-X-BITRATE tags provide more accurate bitrate values than those found in the MVP.
> #EXT-X-BITRATE support

- src/utils/xhr-loader.ts
Fix null XHR response handling
Prevents an Invalid State exception thrown by reading `xhr.responseText` when `xhr.response` is null and `xhr.responseType` is not "text" or empty.
> Fix null XHR response handling

- src/controller/audio-track-controller.ts
Prevent loading of audio media options with the same URI as the current level.
Resolves #6783
> Prevent loading of audio media options with the same URI as the current level

- api-extractor/report/hls.js.api.md
- src/controller/abr-controller.ts
- src/controller/audio-track-controller.ts
- src/controller/level-controller.ts
- src/controller/stream-controller.ts
- src/controller/subtitle-track-controller.ts
- src/loader/playlist-loader.ts
- src/types/events.ts
- src/types/loader.ts
- tests/unit/controller/audio-stream-controller.ts
- tests/unit/controller/audio-track-controller.ts
- tests/unit/controller/stream-controller.ts
- tests/unit/controller/subtitle-track-controller.ts
Force media capabilities check for HEVC to decode errors from HEVC selection on Windows Firefox.
`MediaSource.isTypeSupported('')` reports true, but MediaCapabilities `decodingInfo` tests return false and appending media results in a decode error.
Failed test results: https://github.com/video-dev/hls.js/actions/runs/11844914912/job/33012913783?pr=6845
> `The video playback was aborted due to a corruption problem or because the video used features your browser did not support - NS_ERROR_DOM_MEDIA_NOT_SUPPORTED_ERR (0x806e0003) - Utility MF Media Engine CDM only support for media engine playback`
> Force media capabilities check for HEVC to avoid failure on Windows

- src/controller/audio-stream-controller.ts
- src/controller/base-stream-controller.ts
- src/controller/stream-controller.ts
- src/controller/subtitle-stream-controller.ts
- src/loader/fragment.ts
- Skip errored fragments with no alternate
- Fix fragment retry delay when there are no alternates
Error handling of fragment 4xx errors skips retry, expecting a switch to an alternate selection or pathway. When there is none, the error was reset, but then the stream controller would request the fragment again on next IDLE tick.
This change skips fragments that 4xx when there are no alternate pathways or media options, treating them as gaps, unless the segment is the last segment in a VOD playlist (#5153, #6171). An init segment or the last segment in a playlist will be retried using retry rules even if the network error is a 4xx (#5647, #6741).
- Resolves #6741
- Resolves #5647
- Resolves #5153
- Closes/Replaces #6171
> Fragment 4xx network error handling improvements

- api-extractor/report/hls.js.api.md
- src/controller/audio-stream-controller.ts
- src/controller/audio-track-controller.ts
- src/controller/base-stream-controller.ts
- src/controller/level-controller.ts
- src/controller/stream-controller.ts
- src/controller/subtitle-stream-controller.ts
- src/controller/subtitle-track-controller.ts
- src/loader/level-details.ts
- src/loader/playlist-loader.ts
Avoid requesting expired playlist segments when resuming live playback.
HLS.js should wait for live (not EVENT) playlists to refresh before loading segments if they have not been updated in enough time for the last segment to be older than three target duration past the start of the playlist.
Resolves #6854
> Make stream controllers wait for playlist updates before requesting segments from expired playlists

- src/controller/audio-stream-controller.ts
- src/controller/base-stream-controller.ts
- src/loader/m3u8-parser.ts
- src/utils/discontinuities.ts
- src/utils/level-helper.ts
- tests/unit/controller/level-helper.ts
- Attempt to realign audio with main when `alignPlaylists` finds no overlap in live playlist updates.
- Wait for audio rendition playlist update when ending discontinuity is not matched in main playlist.
- `startCC` of LevelDetails will be set to DISCONTINUITY-SEQUENCE when playlists begin with a DISCONTINUITY tag instead of the sequence number of the first fragment (starting sequence +1), allowing alignment on first segment with new discontinuity.  
- Prevent audio-stream-controller state changes to "WAITING..." when loading is stopped.
- Realigns live main and audio playlists after media sequence sync is lost.
- Prioritizes discontinuity sequence alignment over program date time.
- Prevents audio segment fetching of new discontinuity until main discontinuity sequence is avaiable.
Audio …
> Re-align audio playlist with main when there is no overlap between audio playlist updates

- src/utils/level-helper.ts
- tests/unit/controller/level-helper.ts
Fix regressions in live playlist advancement introduces in #6692 and not fixed in #6857.
Ensure that main playlist keeps up with audio playlist on level switch after old details have no overlap with reload. Switching back to a level that was loaded a long time ago was being merged at the end of the old details, way behind audio and the more up-to-date level switched from.
- #6692
- #6857
- #6823
- #6685
- #5282
> Fix regressions in live playlist advancement 

- api-extractor/report/hls.js.api.md
- src/controller/audio-track-controller.ts
- src/controller/base-playlist-controller.ts
- src/controller/base-stream-controller.ts
- src/controller/level-controller.ts
- src/controller/subtitle-track-controller.ts
- src/loader/level-details.ts
- src/utils/level-helper.ts
- tests/unit/controller/subtitle-track-controller.ts
Schedule each playlists earliest reload time based on last request. Do not start loading until scheduled time is reached. 
Prevents automatic reloading of playlists on variant and rendition switch when playlist is recent or inflight.
Fixes #6858
> Limit live playlist reloading to scheduled updates

- api-extractor/report/hls.js.api.md
- src/controller/abr-controller.ts
- src/controller/base-playlist-controller.ts
- src/controller/base-stream-controller.ts
- src/controller/interstitials-controller.ts
- src/controller/level-controller.ts
- src/controller/stream-controller.ts
- src/hls.ts
- src/loader/level-details.ts
- src/loader/playlist-loader.ts
- src/types/events.ts
- src/utils/level-helper.ts
- tests/unit/controller/error-controller.ts
- tests/unit/controller/interstitials-controller.ts
- tests/unit/controller/stream-controller.ts
- Improve live reload scheduling (and fix a regression in dev)
- Improve blocking requests with parts and low-latency mode disabled
- Defer autostart until after manifest loasded and level loaded when media playlist is source
- Added `hls.loadingEnabled` getter
- Prevent Interstitial controller from calling startLoad when stopped and do not resume primary on first item 
Prevents redundant playlist request on startup and fixes autostart behavior in development.
- Fixes #6858
- Fixes #6839
> Live reload throttling per level details schedule

- .eslintrc.js
- src/controller/audio-stream-controller.ts
- src/controller/eme-controller.ts
- src/controller/timeline-controller.ts
- src/crypt/decrypter.ts
- src/demux/chunk-cache.ts
- src/demux/transmuxer.ts
- src/types/buffer.ts
- src/utils/fetch-loader.ts
- tests/unit/demuxer/transmuxer.ts
- Add strict type checking for Uint8Array/ArrayBuffer and fix errors.
- Include tsconfig in eslint settings.
Enforce the use of ArrayBuffers vs Uint8Array so that we pass the correct type to user-agents that may be strict about the type provided.
This should also help avoid unnecessary copying of data by creating new views from typed arrays (`copy = new Uint8Array(uint8Arr)`).
> Add strict type checking for Uint8Array/ArrayBuffer

- src/controller/audio-track-controller.ts
- src/controller/interstitials-controller.ts
- src/controller/stream-controller.ts
- src/utils/rendition-helper.ts
Only load audio via the stream-controller (main playlist / active level) when the alternate audio rendition has the same URL.
The stream-controller was not loading audio for audio-only streams when there were alternate audio options. It assumed that the main variant was inactive or represented by another alternate. However, if the current alternate has a (redundant) URL matching that of the main variant, instead of opting to omit the URL attribute, that alternate should not handled by the the audio-track and audio-stream-controllers.
Resolves #6859
Resolves #6783 (Fixed with #6785 but regressed with #6845)
> Fix loading of audio media options with the same URI as the current level

- src/remux/mp4-remuxer.ts
- tests/index.js
- tests/unit/remux/mp4-remuxer.ts
Fix `getVideoStartPts` when timestamps wrap at MPEG-2 33-bit boundary
The arguments used to normalized timestamps in `getVideoStartPts` where provided backwards, and the normalized wrapped value was always used to update the minimum, even though wrapped values are generally are wrapped because timestamp values are advancing.
This issue had little to no effect because the value returned by `getVideoStartPts` is only used to determine the difference between audio and video samples at the start of TS segments, the result for which was not off by much if anything when wrapping occurred near the start of a TS segment.
> Fix `getVideoStartPts` when timestamps wrap at MPEG-2 33-bit boundary

- api-extractor/report/hls.js.api.md
- src/hls.ts
- src/loader/playlist-loader.ts
- src/types/events.ts
Maintain startup event order using autoStartLoad for expected level and audioTrack getter results on MANIFEST_LOADING
Moving the `startLoad()` call evoked when `autoStartLoad` is `true` in MANIFEST_LOADING to after MANIFEST_LOADING caused loadLevel and hls.audioTracks to not be populated in app callback to the MANIFEST_LOADING event - because level switching and associated media selection is not performed until loading is started.
Fixes a regression in dev in apps that expect these getters to be populated rather that using events associated with track updates and level selection (caused by #6879).
Resolves #6891
> Maintain startup event order with autoStartLoad

- api-extractor/report/hls.js.api.md
- src/controller/interstitials-controller.ts
- src/loader/playlist-loader.ts
- src/types/events.ts
- Fallback to primary when Interstitial DateRange is removed while playing
- Resolve regression in dev starting live interstitials from media playlist (revert autostart load after playlist populated when no multivariant playlist is provided)
Prevents playback from stalling when the Interstitial DateRange of the currently playing Interstitial is removed in a live playlist update. Removal of active events should terminate event playback and resume primary (#6765).
Resolves #6765
Resolves regression in dev starting live interstitials from media playlist (no multivariant playlist loaded startup sequence changed)
> Fallback to primary when Interstitial DateRange is removed while playing

- src/controller/base-stream-controller.ts
Do not apply interstitial buffering bounds to subtitle fragments. Always allow subtitle fragments to be loaded while interstitials are buffering.
Buffer boundaries applied before loading fragments is only meant to apply to audio and video fragments.
Fixes #6768
> Fix: Subtitles not loaded while buffering Interstitials

- api-extractor/report/hls.js.api.md
- src/controller/id3-track-controller.ts
- src/controller/interstitials-controller.ts
- src/events.ts
- src/utils/texttrack-utils.ts
- Use TextTrackCue "enter" event to improve Interstitial playback timing
- Restore DateRange metadata TextTrack cues when re-attaching media
TextTrackCue "enter" events provide more precision for Interstitial timing than HTMLMediaElement "timeupdate" events.
An "enter" event listener is added to TextTrackCues created for interstitial date range asset-list and asset-url attributes. When dispatched, a new hls.js `EVENT_CUE_ENTER` event is triggered. The interstitial-controller uses `EVENT_CUE_ENTER` to run its "timeupdate" handler at a more precise start time.
The logic to advance the program is unchanged and still depends on the HTMLMediaElement `currentTime`.
> Use TextTrackCue "enter" event to improve Interstitial playback timing

- src/controller/buffer-controller.ts
Fix transfer media failing when MediaSource readyState is "ended".
Transferring SourceBuffers between primary and asset players failed to complete when MediaSource was in "ended" state (buffer had reached EoS). This change ensures that we can seek back to an Interstitial event time range that was appended "in place" on the same SourceBuffer(s) after playback and buffering have reached the end of the VOD and buffer from the event was ejected.
> Fix transfer media (source) failing when MediaSource readyState is "ended"

- src/controller/interstitials-controller.ts
Don't resume playback on interstital transition after player is paused.
Player should remain paused after seeking into a different interstitial schedule segment.
> Don't resume playback on interstitial transition after player is paused

- src/controller/base-stream-controller.ts
- tests/unit/controller/base-stream-controller.ts
Fix stream ended check for interstitial asset players sharing a media-source timeline when there is another buffered range in the future for other content.
When seeking back to an unbuffered event, asset players fail to recognize that the stream has ended (buffered to end) when another buffered range is detected. Ranges outside the asset program must be ignored.
> Fix Interstitial asset inline buffering with other items buffered ahead

- src/controller/interstitials-controller.ts
- Fix additional asset player creation between assets at start 
- Update interstitial controller item references when the schedule is updated
Fixes cases where additional unexpected Interstitial events fire during playback. 
Ensures that the `bufferingItem` and `playingItem` in `hls.interstitialsManager` always match items in its `schedule`.
> Interstitials: Fix additional asset player creation between assets at start 

- src/controller/buffer-controller.ts
- src/controller/stream-controller.ts
- Run `afterBufferFlushed` on stream-controller when main audio is flushed
- Resolves  #6919 by allowing the stream-controller to re-enter "ENDED" state when only audio back-buffer is flushed by HLS.js (because video was already auto-ejected on append)
- Ignore back buffer removal requests in ended state and remove front buffer removal ended check
Fixes https://github.com/video-dev/hls.js/issues/6919
Fixes a case where EOS is removed by HLS.js back-buffer removal logic flush operation, and never reset. Preventing the removal in ended state will make ending more reliable. There is no need to do so for front-buffer removal.
Fixes #6919
> Fix reset of "ended" state after main muxed audio flush

- src/controller/interstitials-controller.ts
Trigger `INTERSTITIALS_PRIMARY_RESUMED` after ending interstitial with CUE ONCE
The handling of CUE ONCE involved removal of current (ended) interstitial from the schedule followed by a recursive call to `setSchedulePosition`. This recursive call prevented `INTERSTITIALS_PRIMARY_RESUMED` from being triggered because the the context of the current (ended) item was lost, leading to `attachPrimary` being called with `fromItem` of `null`. Now the method has two parts, so that when the schedule is changed after ending an interstitial, the next item can advance with the context of the last item to have played. 
Resolves #6911
> Trigger INTERSTITIALS_PRIMARY_RESUMED after ending interstitial with CUE ONCE

- src/controller/audio-stream-controller.ts
- src/controller/base-stream-controller.ts
- src/controller/stream-controller.ts
- src/loader/level-details.ts
- src/remux/passthrough-remuxer.ts
- src/utils/level-helper.ts
- src/utils/rendition-helper.ts
- tests/unit/controller/audio-stream-controller.ts
- tests/unit/controller/level-helper.ts
- Do not adjust initPTS without accurate playlist time offset (when live playlist is out of sync).
- Do not re-emit AUDIO_TRACK_LOADED for track sync as it reruns playlist merge logic.
- Keep audio-stream-controller startPosition within playlist bounds.
- Fix audio-only main <-> track switching buffer flushing issues
- Do not treat live playlists as expired after three "misses" (static responses -> archived live / load segments anyway)
Adjusting initPTS should only be performed for contiguous operations or on switch when expected timestamps differ enough from playlist times that the only way forward is to remap them (these are malformed HLS but we support them since #5235 and #5471).
In this case, when live playlist updates are unable to be delivered frequently enough to stay in sync, …
> Do not adjust initPTS without accurate playlist time offset

- src/utils/fetch-loader.ts
- src/utils/xhr-loader.ts
Replace non-null assertions in xhr-loader and gate evoking of loader callbacks
To close #6359 and avoid exceptions if any in unknown execution contexts. 
- Replaces #6359
> Replace non-null assertions in xhr-loader and gate evoking of loader callbacks

- src/controller/eme-controller.ts
- src/loader/key-loader.ts
- tests/unit/controller/eme-controller.ts
Clean up some assumptions on key request logic in multi-drm scenarios, particularly around PlayReady usage.
There were
Everything was localized to `EmeController::onMediaEncrypted()` and much of the core logic stayed the same, but definitely want some attention while reviewing the implementation decisions, particularly the callout questions/comments (including in github comments) before 👍.
Smoke tested multi-drm case (on demand stream with FairPlay, Widevine, and PlayReady advertised via `EXT-X-KEY` tags and `sinf`/`pssh` mp4 boxes) on:
1. macOS
1. Safari (for FairPlay usage regression testing)
2. Chrome (for Widevine usage regression testing)
3. Windows
1. Edge ("Edgium") with Widevine Enabled and Widevine Disabled (See: https://learn.microsoft.com/en-us/legal/microsoft-edge/privacy#digit …
> fix: assumptions in multi-drm cases where only playready is available for playback.

- api-extractor/report/hls.js.api.md
- src/config.ts
- src/controller/gap-controller.ts
- src/controller/stream-controller.ts
- src/events.ts
- src/hls.ts
- src/types/events.ts
- src/utils/buffer-helper.ts
- tests/unit/controller/gap-controller.ts
- tests/unit/utils/buffer-helper.js
- Improve stall detection and reporting using "waiting" event timing
- Add `config.detectStallWithCurrentTimeMs` with a default of 1250 to configure stall detection when currentTime does not advance while playing without a "waiting" event
- Implement STALL_RESOLVED event - fires after "playing", "seeked", or "ended" event following BUFFER_STALLED_ERROR (Resolves #4273)
- Add BufferInfo to stall-related errors (BUFFER_STALLED_ERROR, BUFFER_NUDGE_ON_STALL, BUFFER_SEEK_OVER_HOLE)
- Add `stalled.start` performance timing to BUFFER_STALLED_ERROR
- Add `buffered` time range array to BufferInfo
- Only perform BUFFER_NUDGE_ON_STALL when needed (multiple buffered time ranges)
- Fix seek on start without play() request (regression in dev)
Stall reporting and resolution requires these enhancements. …
> Gap controller fixes

- src/controller/base-stream-controller.ts
Delay `endOfStream` until playhead is in buffered region.
When `MediaSource.endOfStream()` is called before playback begins, and the SourceBuffer(s) buffered ranges start a little bit past 0 and HLS.js seeks on play to jump this gap, Safari does not emit "ended" event when reaching the end.
Resolves #6890
> Workaround Safari "ended" event not firing when EoS is marked before seek on start

- api-extractor/report/hls.js.api.md
- docs/API.md
- src/config.ts
- src/controller/base-stream-controller.ts
- src/controller/buffer-controller.ts
- src/controller/gap-controller.ts
- src/controller/interstitials-controller.ts
- src/controller/stream-controller.ts
- src/hls.ts
- src/utils/buffer-helper.ts
- src/utils/event-listener-helper.ts
- tests/index.js
- tests/unit/controller/base-stream-controller.ts
- tests/unit/controller/buffer-controller-operations.ts
- tests/unit/controller/buffer-controller.ts
- tests/unit/controller/gap-controller.ts
- tests/unit/controller/stream-controller.ts
- tests/unit/hls.ts
- tests/unit/utils/buffer-helper.js
- tests/unit/utils/mock-media.ts
Flush MSE rendering pipeline when crossing video buffer holes with audio.
Chrome will play past a hole in the video buffer when there is audio, but video will not render and playback will stall one second past the hole. https://issues.chromium.org/issues/40280613#comment10
These changes detect playback traversal of such a gap and issue a seek to flush the pipeline render. This prevents the stall and results in video frames being rendered that would not have otherwise (#5631).
The improvement in stall detection and immediate triggering of "bufferNudgeOnStall" when the media element is "waiting" addresses stalls on audio buffer gaps (#6169).
Are other gap-controller labelled issues addressed?
https://github.com/video-dev/hls.js/issues?q=is%3Aopen+is%3Aissue+label%3Agap-controller
The …
> Flush MSE rendering pipeline when crossing video buffer holes with audio

- api-extractor/report/hls.js.api.md
- docs/API.md
- src/controller/abr-controller.ts
- src/controller/base-stream-controller.ts
- src/controller/error-controller.ts
- src/controller/fragment-tracker.ts
- src/controller/gap-controller.ts
- src/controller/interstitials-controller.ts
- src/controller/level-controller.ts
- src/controller/stream-controller.ts
- src/hls.ts
- src/utils/rendition-helper.ts
- tests/unit/controller/gap-controller.ts
- Fix an issue where the gap-controller would not skip over buffer holes produced by EXT-X-GAP segments.
- Add `hls.loadLevelObj` to API - replaces internal use of `hls.levels[hls.loadLevel]`
`getFwdBufferInfoAtPos` was not properly stepping over EXT-X-GAP segments which prevented them from being re-added to the fragment tracker. `_trySkipBufferHole` in gap-controller depends on being able to step through gap segments in the tracker to skip over large buffer holes.
Additional changes will prevent skipping over a hole when an earlier audio or main segment is being loaded or a variant playlist is being loaded.
Fixes #6814
> Fix seeking into and over multiple EXT-X-GAP segments

- src/controller/buffer-controller.ts
Ignore non-finite MediaSource duration overrides.
Do not set duration to Infinity in `getDurationAndRange` as this can throw when SourceBuffers are updating.
Prevents Interstitial asset players from resetting duration on transferred MediaSource when the schedule duration is `Infinity` for a live primary asset and `liveDurationInfinity` is false.
Duration is already set in `updateMediaSource` between blocking operations and should never be set in `getDurationAndRange`. 
Only applies to live playback with Interstitials with default `liveDurationInfinity` of `false` (set to `true` to workaround this issue).
> Fix live duration override by interstitials

- src/loader/fragment.ts
- tests/unit/utils/discontinuities.ts
Make Fragment.stats enumerable.
Changing `stats` to a getter (#6811) made it non-enumerable. As a results `stats` are not copied by the spread operator or `Object.assign`. The demo app depends on this to display fragment loading progress.
Fragment.stats were changed in favor of lazy instantiation (lower memory usage at playlist parse).
Using ES5 defineProperty after class instantiation expects es6>es5 transpiling. This should have no effect if running the ESM modules (need to verify).
> Make Fragment.stats enumerable

- api-extractor/report/hls.js.api.md
- src/controller/level-controller.ts
- src/hls.ts
Provide a public API to get the list of `pathways`.
1.6.0 introduces a `pathwayPriority` API, but there is no public API to get the list of `pathways` making `pathwayPriority` hard to use. (This is currently only possible with a private `hls.levelController.steering.pathways()` call)
https://github.com/video-dev/hls.js/issues/6996
> feat: pathways getter

- api-extractor/report/hls.js.api.md
- src/controller/audio-stream-controller.ts
- src/controller/base-stream-controller.ts
- src/controller/gap-controller.ts
- src/controller/interstitial-player.ts
- src/controller/interstitials-controller.ts
- src/controller/interstitials-schedule.ts
- src/controller/stream-controller.ts
- Fix streaming primary content over queued assets (base-stream-controller)
- Fix "Main forward buffer length" warning on "seeked" for asset players (stream-controller)
- Fix audio streaming gaps in asset players created after buffer is populated (handles incomplete fragment tracker - audio-stream-controller)
- Fix incorrect interstitial buffering state after flush (interstitials-controller)
- Fix advancing interstitial buffering advancement with append-in-place (interstitials-controller)
- Fix interstitial start/end events at edge (playing last schedule item transitions with new interstitial) (interstitials-controller)
- Fix asset player queue leaks (interstitials-controller `clearAssetPlayer` exits early resulting in `playerQueue` buildup)
- Allow append-in-place at live edge with …
> Interstitial fragment loading and buffering fixes

- src/controller/latency-controller.ts
- tests/unit/controller/latency-controller.ts
- tests/unit/controller/stream-controller.ts
Make latency-controllers getters safe to call after destroyed
Prevents accessors like `hls.targetLatency` from throwing after `hls` instance is destroyed
> Make latency-controllers getters safe to call after destroyed

- src/controller/interstitials-controller.ts
- tests/unit/controller/interstitials-controller.ts
- Advance interstitials-controller timeline position before advancing at the end of an interstitial (#6983)
- Trigger INTERSTITIALS_BUFFERED_TO_BOUNDARY before other interstitial events when program begins
- Do not start interstitials program until media is attached
> Advance interstitials-controller timeline position before advancing at the end of an interstitial (#6983)
Ensures correct resumption time of primary when interstitial uses CUE="ONCE"; Normally when resuming from an interstitial, the primary schedule item start and end time are used update the last known timeline position for the primary player. This wasn't working with interstitials with CUE="ONCE" because the interstitial item is removed from the schedule before resuming, merging the the adjacent primary schedule items into …
> Fix primary resume time when advancing after interstitial with CUE="ONCE"

- api-extractor/report/hls.js.api.md
- src/controller/interstitials-controller.ts
- src/controller/interstitials-schedule.ts
- src/loader/interstitial-event.ts
- tests/unit/controller/interstitials-controller.ts
- Resume primary with a resumption offset of 0 when asset list is empty and no X-RESUME-OFFSET is present
- Avoid aborting in-flight primary segment requests with `startLoad()` when passing over Interstitial with empty asset list
- Clear asset list response before reloading asset-list
- Do not update interstitial duration before assets are resolved
Prior to this change the resumption offset was based on the date range tag DURATION even though there was no interstitial played.
Asset lists that return empty ASSETS are re-requested when media is rebuffered to interstitial start boundary. `assetListResponse` should be set to null prior to requesting the list again.
> Improve handling of empty ASSETS array in X-ASSET-LIST response

- src/controller/interstitials-controller.ts
- src/utils/safe-json-stringify.ts
- tests/index.js
- tests/unit/utils/safe-json-stringify.js
- Fix JSON stringify errors caused by objects having circular references 
References can come from external objects like the media element that have additional properties on them. Eg; When a React reference is passed into `attachMedia`.
A basic React app with interstitials turned on is currently breaking. With this fix it should not break anymore while logging still works.
Broken interstitials.
> fix: json stringify with circular dependencies

- api-extractor/report/hls.js.api.md
- src/controller/abr-controller.ts
Separate the calculation of `next level` into a protected method
I am trying to create a custom abrController by extending hls.js's abrController.
In `public set nextAutoLevel`, I want to calculate value using my own method and assign it to `this._nextAutoLevel`, but since `this._nextAutoLevel` is private, I cannot do that.
It becomes easier for users to implement a custom abrController.
> Separate the calculation of the next level into a protected method

- src/config.ts
- src/controller/abr-controller.ts
- src/controller/buffer-controller.ts
- src/controller/content-steering-controller.ts
- src/controller/eme-controller.ts
- src/controller/gap-controller.ts
- src/controller/id3-track-controller.ts
- src/controller/level-controller.ts
- src/demux/transmuxer-interface.ts
- src/utils/cea-608-parser.ts
- src/utils/level-helper.ts
- src/utils/rendition-helper.ts
- src/utils/safe-json-stringify.ts
- tests/unit/utils/safe-json-stringify.js
Prevent exceptions when circular references are added externally to objects HLS.js serializes or logs using `JSON.stringify`.
Added support for custom replacers since we use on in buffer-controller. I had to choose if the replacer should run before or after the cyclical reference check. I chose before.
Resolves #7036 (Follow up to #7037)
> Replace JSON.stringify with safe stringify module

- src/controller/abr-controller.ts
- src/controller/audio-stream-controller.ts
- src/controller/buffer-controller.ts
- src/controller/error-controller.ts
- src/controller/stream-controller.ts
- src/utils/codecs.ts
- src/utils/mediacapabilities-helper.ts
- src/utils/mp4-tools.ts
- tests/index.js
- tests/unit/utils/mediacapabilities-helper.ts
- Override selection preference and media-capabilities result for HEVC support in Windows Firefox
- Fix handling of BUFFER_ADD_CODEC_ERROR for switch error handling to work
- Fix incorrect caching of media-capabilities results (dev-only regression: codec undefined in `getMediaDecodingInfoKey`)
Functional tests fail for Windows Firefox with HEVC content:
https://github.com/video-dev/hls.js/actions/runs/13503192504/job/37727621627?pr=7045
Resolves #7046
> Override media-capabilities result for HEVC support in Windows Firefox

- .eslintrc.js
- api-extractor/report/hls.js.api.md
- build-config.js
- docs/API.md
- src/config.ts
- src/controller/base-stream-controller.ts
- src/controller/id3-track-controller.ts
- src/controller/interstitial-player.ts
- src/controller/interstitials-controller.ts
- src/controller/stream-controller.ts
- src/define-plugin.d.ts
- src/hls.ts
- src/loader/interstitial-event.ts
- tests/unit/controller/interstitials-controller.ts
- tests/unit/utils/mock-media.ts
- InterstitialsManager changes:
- Add `interstitialPlayer`
- Remove `bufferingPlayer`, `waitingIndex`, and `playout` properties
- Replace `seekTo` method with `currentTime` setter
- Update docs
- Fix and cover expected playback state in interstitial event callbacks (where currentTime is derived from transitional controller state)
- Fix live start in append-in-place interstitial seeking to second start position when primary starts buffering after starting in interstitial
- Simplify playout-limit handling in asset player
- Add padding to flush front buffer call (prevents start of audio segment from being removed in Safari)
- `interstitialsManager.primary.currentTime` should not return mid-interstitial time while appending in place (this will not reflect primary startPosition when starting …
> Interstitials live start, buffering, and manager fixes and docs update

- src/controller/interstitials-controller.ts
- src/controller/interstitials-schedule.ts
- src/loader/interstitial-event.ts
- tests/unit/controller/interstitials-controller.ts
- Reset asset lists after Interstitial has played, unless the interstitial supplements primary.
- Reset errors when seeking back over interstitial start
- Fix gaps in interstital-controller `bufferedPos` and interstitial manager timeline `bufferedEnd` alignment with playback position
- Fix seeking to primary from appendInPlace interstitial when media is help by primary
Asset lists should always be reloaded for late binding.
Interstitial errors are handled by unscheduling the interstitial and falling back to primary. The `error` state on each interstitial is therefor not removed until seeking back
> Reset asset lists after Interstitial has played

- src/controller/stream-controller.ts
Fix an edge-case on webOS 5 (and possible other low power devices), where `synchronizeToLiveEdge()` could seek forward while the first segment was being appended to the buffer.
https://github.com/video-dev/hls.js/issues/6998
> fix: seek during startup on low power devices

- src/controller/abr-controller.ts
- src/controller/base-stream-controller.ts
- src/controller/fragment-tracker.ts
- src/controller/interstitials-controller.ts
- src/controller/stream-controller.ts
When a live playlist update arrives before live start (before media is buffered and client can seek to buffered range), evaluate if the variant should be abandoned, and avoid seeking to catch up to live edge.
The live edge sync (catch up) check was running prior to live start. @grabofus pointed this out in #6998 and provided a fix in #7063. This change follows up by using the estimated playhead position and switching down on slow fragment load.
Resolves #6998
> Improve Live start with slow conditions

- api-extractor/report/hls.js.api.md
- src/controller/base-stream-controller.ts
- src/controller/buffer-controller.ts
- src/controller/interstitial-player.ts
- src/controller/interstitials-controller.ts
- src/controller/interstitials-schedule.ts
- src/controller/subtitle-stream-controller.ts
- src/utils/level-helper.ts
Fixes handling of media element transfer between primary and asset HLS.js instances when abutting interstitials have different strategies for appending media (resetting the media source vs using the primary media source in place) and when the underlying primary content spans multiple discontinuities.
- Avoids loading and queueing primary init segments for discontinuities obscured by interstitials which could lead improper appends and handling of mixed codecs between primary and interstitial.
- Maintains asset player currentTime after media is detached
- Prevent playback from restarting on schedule change after primary media has ended
> Fix Interstitials playback with media source transfer

- src/controller/base-stream-controller.ts
Treat empty segments as gaps even when error handling is signalled on the transmuxer.
This prevents loop loading by immediately marking the empty segment with a gap. Otherwise, the error handling flow must choose to penalize the variant even when there are no alternates to switch to. 
Fixes #7075
> Fix loop loading on empty segment with worker disabled

- api-extractor/report/hls.js.api.md
- src/config.ts
- src/controller/base-playlist-controller.ts
- src/loader/m3u8-parser.ts
- src/loader/playlist-loader.ts
- src/utils/level-helper.ts
- tests/unit/controller/interstitials-controller.ts
- tests/unit/controller/level-helper.ts
- tests/unit/loader/m3u8-parser.ts
Surface errors when parsing invalid Media Playlists. HLS.js will assign an error to `LevelDetails.playlistParsingError` and trigger and parsing error when:
- The Media Playlists does not start with #EXTM3U
- The Media Playlists is missing required #EXT-X-TARGETDURATION tag
- More than one Media Playlist tag is found #EXT-X-(PLAYLIST-TYPE, MEDIA-SEQUENCE, DISCONTINUITY-SEQUENCE, PART-INF, SERVER-CONTROL, ENDLIST)
- More than one  #EXT-X-SKIP or  #EXT-X-VERSION tag is found
- #EXT-X-MEDIA-SEQUENCE or #EXT-X-DISCONTINUITY-SEQUENCE appear _after_ the first segment
- The discontinuity sequence number, media sequence number (or url) changes for a segment between live updates of a playlist
Release note:
Added `config.ignorePlaylistParsingErrors` to ignore playlist parsing errors
These errors …
> Media Playlist parser validation errors

- src/controller/latency-controller.ts
Add debug logging of adjustment to `media.playbackRate` which is useful when debug live streaming playback.
Enhancing engineer experience who debug issues with playback of live stream.s
-
-
> [Debug]: Log playback rate adjustments.

- src/exports-named.ts
This PR exports `M3U8Parser` and makes it available for use outside of this libraries without relying on external packages for parsing playlists. The motivation for this is detailed in https://github.com/video-dev/hls.js/issues/2183. The change follows @robwalch's recommendation from https://github.com/video-dev/hls.js/issues/2183#issuecomment-1836864069.
Is there a need to update any documentation?
Closes https://github.com/video-dev/hls.js/issues/2183.
> Export `M3U8Parser` for external use

- src/controller/eme-controller.ts
- tests/unit/controller/eme-controller.ts
We are going to fix a compatibility issue of `mediaKeysSession.keyStatuses.forEach` on Xbox One devices.
When we debug Xbox One devices, we found an error thrown in the line https://github.com/video-dev/hls.js/blob/master/src/controller/eme-controller.ts#L926
In fact, we noticed the callback arguments are a little different from Chrome. The first argument is the `keyed` object, and the second one is the `status` string. So, I add some special code to switch them. 
it will make Xbox One device work as our epxcted.
> fix: xboxone keyStatuses.forEach callback not work well

- src/controller/stream-controller.ts
Warn when parsed init and media segments contain audio and video tracks but they are expected to only contain video.
HLS.js does not demux fragmented mp4.
Replacing the parsed "audiovideo" result and stripping out audio codecs might get some media to play in Safari, but MSE video SourceBuffers should not be expected to drop audio samples in muxed appends.
Related to #7142
> Warn on muxed mp4 with alt-audio

- src/controller/buffer-controller.ts
- src/controller/level-controller.ts
Ignore alternate audio when audio controller class config options are null
This is already supported via build flags. When the same config changes are made without using build flags, the buffer controller logic should follow.
#7145
> Support disabling alternate audio with config

- src/controller/fragment-tracker.ts
Fix clearing of part loaded status.
Parts that were previously buffered return true when querying `part.loaded` because `elementaryStream` data was not removed. This prevented the reloading of parts that was previously appended and removed from the buffer.
Related to #7165
> Do not skip loading of parts that were previously buffered

- src/utils/mp4-tools.ts
Improve HEVC codec parsing by writing profile compatibility flag in reverse bit order. 
The codec string parsed from hvcC boxes in mp4 init segments contained extra zeros (noticed in #7114). This change fixes the issue:
before `"hvc1.1.60000000.L150"` and after `"hvc1.1.6.L150"`
This does not appear to have impacted support checks or SourceBuffer creation on most platforms. Of the issues where these media parsed codecs were noted, none of the failures were a result of the codec string parsing as far as I know.
> Improve HEVC codec parsing

- MIGRATING.md
Adds a note to the MIGRATING document regarding performance issues on older web engines (for example, Chrome v56/63 on Samsung TV's).
Performance issues discovered when using the ESM (default) version of this library when compiling client applications in `strict` mode. Communicates recommendations to avoid this.
n/a
#7106
> docs: add note regarding ESM use with old browsers

- src/controller/level-controller.ts
- src/utils/codecs.ts
- tests/unit/utils/codecs.ts
Fix modification of codec strings that do not start with "avc1" in `convertAVC1ToAVCOTI`
When a variant has mixed video codecs (Ex: "avc1.64001f,dvh1.05.07"), the non-avc1 codec is modified by `convertAVC1ToAVCOTI`, changing it into something potentially invalid and not supported by the browser.
This change makes sure that the correct codec strings are checked for compatibility in this case, preventing these levels from being removed and manifest incompatible codecs error from firing when all variants contain a similar mix.
> Fix handling of variants with mixed video codecs starting with "avc1"

- api-extractor/report/hls.js.api.md
- src/controller/interstitial-player.ts
Limit append-in-place buffering to playout-limit.
Buffering of interstitial assets was not stopped when the forward buffer past X-PLAYOUT-LIMIT. This is expected when each asset player resets the media source and X-PLAYOUT-LIMIT is enforced by monitoring currentTime.
When all assets are appended in place, sharing a single MediaSource, buffering must stop after reaching or exceeding the playout limit, so that the MediaSource can be transferred to the hls instance responsible for buffering the next scheduled segment.
Fixes #7179
> Fix appending of Interstitials in place that exceed X-PLAYOUT-LIMIT

- api-extractor/report/hls.js.api.md
- src/hls.ts
Add missing type exports (hls.d.mts) for modules exported in hls.mjs (src/exports-named.ts).
The module type exports (hls.d.mts) are simply copied from the default type exports. These only include types explicitly exported in src/hls.ts and not type definitions of the module exports defined in hls.mjs (src/exports-named.ts).
Related to #6707
> Add missing type exports for modules exported in hls.mjs

- api-extractor/report/hls.js.api.md
- src/controller/base-stream-controller.ts
- src/controller/gap-controller.ts
- src/remux/mp4-remuxer.ts
- src/remux/passthrough-remuxer.ts
- src/types/remuxer.ts
- src/utils/mp4-tools.ts
- Parse fmp4 truns to find audio and video base time and sample durations in one place
- Detect missing sync sample at start of fmp4 and error for switch or backtracking
- Use the same track for timestamp offsets with muxed mp4 (base initPTS on audio or video, whichever has the earliest sample times)
- Jump gaps in muxed audio video buffer on stall as long as the gap does not traverse more than one segment boundary
- Ensure that EoS is signaled only once the playhead is in the last buffered range
Prevents decode errors cause by overlapping appends
#7114 (where pipeline error is a result of overlapping appends, not where platform decode error is unavoidable)
- #7114
> Prevent overlapping track appends in muxed fmp4 on discontinuity

- api-extractor/report/hls.js.api.md
- src/controller/interstitial-player.ts
- src/controller/interstitials-controller.ts
- src/hls.ts
- tests/unit/controller/interstitials-controller.ts
Fix incorrect "_HLS_primary_id" value for interstitial asset requests
The asset player session ID was being sent instead of the primary player session ID.
> Fix interstitial "_HLS_primary_id" value in asset requests

- api-extractor/report/hls.js.api.md
- src/controller/interstitial-player.ts
- src/controller/interstitials-controller.ts
- src/loader/interstitial-event.ts
1. Skip asset indexes whose assets have errors when advancing through interstitials in the schedule
2. Reset asset player timeline offset when an earlier asset has errors (delete loaded media playlists with applied offsets)
1. Fixes MediaSource reset playback with asset errors
2. Fixes append-in-place playback with asset errors
I could have simply destroyed asset players whose timelines would be impacted by an error and schedule change, but that would result in the HLS multivariant playlist getting reloaded. Since the `LevelDetails` are delete instead, media playlist will need to be reloaded to generate new offsets. This may no longer be required after timestamp offsets are support #5715, but for now it is a hard requirement.
Fixes #7180
> Skip Interstitial assets that error rather than falling back to primary for entire break

- api-extractor/report/hls.js.api.md
- src/config.ts
- src/controller/error-controller.ts
This PR introduces a new configuration option, `preserveManualLevelOnError`. When this option is set to `true`, hls.js will maintain the manually selected quality level even if network errors (such as `FRAG_LOAD_ERROR`, `FRAG_LOAD_TIMEOUT`, `KEY_LOAD_ERROR`, or `KEY_LOAD_TIMEOUT`) occur. If set to `false` (the default behavior), hls.js will switch back to auto level selection mode (`loadLevel = -1`) upon encountering such errors, attempting to find a rendition that can be loaded successfully.
[Currently](https://github.com/video-dev/hls.js/blob/master/src/controller/error-controller.ts#L345), when a user manually selects a specific quality level, hls.js defaults to switching back to automatic level selection if it encounters fragment loading or key loading errors. This behavior can be …
> feat: preserveManualLevelOnError option

- api-extractor/report/hls.js.api.md
- src/config.ts
- src/controller/base-stream-controller.ts
- src/controller/eme-controller.ts
- src/loader/key-loader.ts
Request key system access based on the eme configuration (with `config.requireKeySystemAccessOnStart`  enabled) and block loading clear content until the media keys are set.
This resolves an issue on Chrome where if clear content is encrypted into the SourceBuffer followed by setting media keys then transitioning to encrypted content, Chrome will die with `PIPELINE_DECODE_ERROR`:
- If the HLS stream starts with clear content only in the manifest, and later transitions to encrypted content
- If the HLS stream starts with mixed content in the manifest, but the first buffered segment is unencrypted. This creates a race-condition today, where the first clear segment might load before the media keys could be set. This has been noticed on MediaTailor live stream with prerolls, where the …
> Add `requireKeySystemAccessOnStart` (fixes Chrome PIPELINE_DECODE_ERROR on clear to encrypted transition)

- tests/functional/auto/setup.js
Update functional test runner to run locally with Safari, Chrome, and Firefox.
Example:
`UA=safari npm run test:func`
Also adds a demo page debug url for each failed test:
```
5) should seek 3s from end and receive video ended event for HLS fMP4...
http://localhost:8000/hls.js/demo/?src=https%3A%2F%...
```
and a summary of asset urls failures:
```
Quitting browser...
Browser quit.
{
"http://example.com/test1.m3u8": 7,
"http://example.com/test2.m3u8": 1
}
121 passing (10m)
8 failing
```
Legacy webdriver configuration is needed for saucelabs, but is unable to locate drivers locally on macos.
> Functional test runner setup changes for running in Safari locally

- api-extractor/report/hls.js.api.md
- src/controller/base-stream-controller.ts
- src/controller/buffer-controller.ts
- src/controller/gap-controller.ts
- src/controller/stream-controller.ts
- src/demux/transmuxer-worker.ts
- src/demux/tsdemuxer.ts
- src/remux/mp4-remuxer.ts
- src/remux/passthrough-remuxer.ts
- src/types/events.ts
- src/types/remuxer.ts
- src/utils/mp4-tools.ts
- tests/test-streams.js
Use SourceBuffer `timestampOffset` rather than modify mp4 decode timestamps.
This is a work-in-progress. Known issues include improper offset of discontinuities with MPEG-TS or muxed content. Additional testing and review is needed to find and fix the application of `initPTS` offsets on append.
- #5715
- #7310 (this is an issue with audio samples starting before video and the base media decode timestamp of audio of the first append being moved forward to 0 to avoid using a signed value for what is expected to be unsigned)
> Use SourceBuffer `timestampOffset`

- src/controller/base-stream-controller.ts
Update next load position if currentTime is not being used on seek
Improves logging for seeking and ensures that media is streamed at the seek position even if there isn't enough buffer for playback.
I wasn't able to reproduce #7327 but deduced that this was the issue based on the logs. This is a reasonable change to make.
Resolves #7327
> Update next load position if currentTime is not being used on seek

- src/controller/buffer-controller.ts
Wait to check if duration and seekable range should be set until any blocking operation is complete.
Ensures that MediaSource duration is not set to a value less than its current value. Doing so invokes buffer ejection and can result in the next append failing because it puts the source in an updating state.
Branched from #7311, these changes should be rebased once that PR is merged.
Fixes #7321
> Fix unnecessary setting of MediaSource duration with stale value

- src/controller/interstitials-controller.ts
- src/demux/transmuxer-worker.ts
Support interstitial schedule navigation on INTERSTITIAL_ASSET_ENDED
Interstitial events are fired synchronously on schedule change. If an app navigates on one of these events, then the `setSchedulePosition` process that fired that event must be exited.
> Support interstitial schedule navigation on INTERSTITIAL_ASSET_ENDED

- src/controller/audio-stream-controller.ts
- src/controller/buffer-controller.ts
- src/controller/content-steering-controller.ts
- src/controller/error-controller.ts
- src/controller/stream-controller.ts
This change ensures that QuotaExceededError is handled properly even after changes proposed in https://github.com/whatwg/webidl/pull/1465 or any other change that would prevent identification of an append error as a "buffer full" (QuotaExceededError) error.
Handles error object with incorrect `code` (!= 22), and always reduces max buffer length on append error.
Prevents first append error that is not a buffer full from being escalated to fatal when there are no other levels (allowing for retries up to `appendErrorMaxRetry`).
Fixes #7367
> Fix QuotaExceededError regression caused by change in Chrome 138

- api-extractor/report/hls.js.api.md
- src/controller/audio-stream-controller.ts
- src/controller/eme-controller.ts
- src/controller/id3-track-controller.ts
- src/loader/level-key.ts
- src/loader/m3u8-parser.ts
- src/utils/hex.ts
- src/utils/mediakeys-helper.ts
- src/utils/mp4-tools.ts
Fix Widevine key management
- Use the Key ID in EXT-X-KEY KEYID when available for Widevine
- Deduplicate key data with the same attributes when parsing media playlists
- Ignore data in "encrypted" event (hls.js can't reliably parse the key id from PSSH without a Widevine protobuf parser)
The Widevine PSSH key id parsing in hls.js (read the 16 bytes 6 bytes back from the end) assumes no optional fields and can't always extract the key id that vendors are including in the playlist (the key id matching tenc box bytes and KEYID attribute value). Since it is difficult to match the "encrypted" event initdata to key tags in the playlist without being able to extract a matching key id, it is better to ignore the event and rely only on key data which is required to be included in HLS media …
> Fix Widevine KEYID parsing

- src/loader/key-loader.ts
Fixes `PIPELINE_ERROR_DECODE` when transitioning from clear to encrypted content when the continuity preceeding the clear content either:
- is clear
- is encrypted but has no `EXT-X-KEY` (as it uses the key from the previous continuity)
This PR allows falling back to using the key system from the config when non of the encrypted fragments are deemed usable from the manifest.
Is there a preference on
> fix: clear to encrypted transition leading to PIPELINE_DECODE_ERROR

- src/demux/tsdemuxer.ts
Reset the MPEG-TS video parser with track changes.
Handles parsing of video tracks in MPEG-TS with AVC and HEVC.
Fixes #7402
> Reset TS video parser with init segment

- src/demux/video/hevc-video-parser.ts
Fix video dimensions computed in HEVC-TS demuxer when SPS default_display_window_flag is present.
#7392
> Ignore offsets related to default_display_window_flag in HEVC-TS demuxer

- renovate.json
Reduce the frequency of PR creation by renovate by scheduling it to run once a month.
Maintainers can create PRs for updated dependencies under "Pending Status Checks" in the renovate dashboard:
https://developer.mend.io/github/video-dev/hls.js
> Schedule renovate to run on the 28th day of the month

- api-extractor/report/hls.js.api.md
- src/controller/audio-stream-controller.ts
- src/controller/base-stream-controller.ts
- src/controller/stream-controller.ts
- src/controller/timeline-controller.ts
- src/demux/audio/base-audio-demuxer.ts
- src/demux/transmuxer-interface.ts
- src/demux/transmuxer.ts
- src/hls.ts
- src/remux/mp4-remuxer.ts
- src/remux/passthrough-remuxer.ts
- src/types/events.ts
- src/types/remuxer.ts
- src/utils/imsc1-ttml-parser.ts
- src/utils/timescale-conversion.ts
- src/utils/webvtt-parser.ts
Fix resetting of initPTS when muxed audiovideo sample start times are inconsistent
When the audio sample start time offsets from playlist times differ between segments or parts, this can cause small changes in initPTS. These changes may cause issues with appending and fragment/part finding.
1. `trackId` is set in stream-controller `this.initPTS[frag.cc]` so that the trackId is maintained between variant switches. This prevents initPTS track and timescale from changing on switch, especially if audio doesn't always start before video in segments or parts.
2. pasthrough-remuxer `initSegment` result remains consistent with initPTS unless `isInvalidInitPts` returns true. This prevents the stream-controller from resetting initPTS when `initSegment.initPTS` changes slightly.
3. initPTS with a …
> Timestamp offset stability fix for muxed audiovideo mp4

- src/controller/buffer-controller.ts
Unblock audio appends when video source buffer is at EoS.
If video reaches end-of-stream first, audio appends should not be blocked.
Blocked audio appends should be unblocked when video reaches end-of-stream.
> Unblock audio appends when video source buffer is at EoS

- api-extractor/report/hls.js.api.md
- src/controller/audio-stream-controller.ts
- src/controller/base-stream-controller.ts
- src/controller/eme-controller.ts
- src/controller/error-controller.ts
- src/controller/stream-controller.ts
- src/remux/passthrough-remuxer.ts
- src/types/buffer.ts
- src/types/remuxer.ts
- src/utils/mp4-tools.ts
Detect unhandled encryption (cbcs) in mp4 init segments and fallback or error when hls.js is not configured to use EME.
No error or fallback is performed if media is detached or media.mediaKeys is set. This is to allow for custom EME integrations.
When hls.js is setup with `emeEnabled: true` this check is skipped because the "encrypted" event handler will error if there is no configured key-system and associated license information. 
This handles improperly packaged HLS carrying encrypted segments without any KEY tags to signal the encryption.
This does not apply to full segment encryption.
> Detect unhandled encryption and fallback or error

- src/controller/interstitial-player.ts
- src/controller/interstitials-controller.ts
- src/controller/interstitials-schedule.ts
- Force schedule update on asset or interstitial error 
- Flush and clear assets when seeking back to earlier asset in interstitial
Forcing an update handles cases where playout duration is not changed by error but schedule update is needed.
Flushing and clearing asset players when seeking back to an earlier asset handles shifts in the timeline cause by faulty assets earlier in the event.
> Force schedule update on asset or interstitial error 

- src/controller/base-stream-controller.ts
Disable part loading for subtitle playlists
Part loading has not been fully implemented in the subtitle-stream-controller, timeline-contoller, fragment-tracker, and other components that deal with tracking part loaded state needed for fragment selection and part loading progression.
This is a stop gap measure for #7460. Rather than allow attempts at part loading which are not handled in sequence successfully (at best the first part is loaded and others skipped), the subtitle-stream-controller will only load complete segments,
> Disable part loading for subtitle playlists

- src/loader/m3u8-parser.ts
- src/utils/level-helper.ts
- tests/unit/controller/level-helper.ts
- Merge new Date Ranges in Playlist Delta Updates when last details have no Date Ranges or previous Date Ranges were removed
- Use program date time carried over to last segment when no segments with `rawProgramDateTime` (#EXT-X-PROGRAM-DATE-TIME references) remain in playlist history  
Handles Live HLS Playlist Delta Updates containing no #EXT-X-PROGRAM-DATE-TIME and periods with no Date Ranges or Date Range turnover (all old tags removed before adding new ones).
Fixes #7461
> Merge new Date Ranges in Delta Update when last details have none

- src/controller/base-stream-controller.ts
Do not treat HTTP status 0 frag load errors as gaps
Last frag load retry should be fatal with http status 0 (offline/CORs/unknown).
Fixes #7410
> Do not treat HTTP status 0 frag load errors as gaps

- docs/API.md
Some minor spello/typo punctuation that triggered me while reading up on config for live streams. Excellent use of the word superior.
Great project, thanks.
> Minor improvements to docs

- docs/API.md
- src/controller/interstitials-controller.ts
- Fix interstitial asset events not firing when attaching primary early for playout-limit change
- Add interstitials-controller logging for timeline position changes, trimming buffered interstitials on schedule updates (with interstitial time range changes), and clearing of schedule state
- Update `config.debug` docs (unrelated)
When a PLAYOUT-LIMIT is added to an interstitial, shortening it's playout duration, if media has been buffered past the playout limit in append-in-place mode, the interstitial controller will re-attach primary to remove the content buffered past the limit and resume primary buffering. A side-effect of this was that the interstitial schedule `timelinePos` state was advanced from the currentTime (mid-interstitial-asset-playback) to the primary start. This prevents …
> Fix interstitial asset events not firing when attaching primary early for playout-limit change

- src/controller/interstitials-controller.ts
Fix exception when seeking to program end
Upon seeking to the end `setSchedulePosition` is called with an index of 1. If there are no interstitials and the schedule contains only one item, this is out of bounds. That is OK. The issue is that `scheduledItem` is undefined rather than null. resulting in `resumePrimary` getting called with an undefined `scheduledItem`. TypeScript always infers that `scheduleItems[index]` will return a result.
> Fix exception when seeking to program end

- api-extractor/report/hls.js.api.md
- src/config.ts
- src/controller/base-stream-controller.ts
- src/controller/eme-controller.ts
- src/controller/error-controller.ts
- src/hls.ts
- src/loader/key-loader.ts
- src/loader/level-details.ts
- src/loader/level-key.ts
- src/types/events.ts
- src/utils/arrays.ts
- src/utils/hex.ts
- src/utils/mediakeys-helper.ts
- src/utils/mp4-tools.ts
- tests/unit/controller/audio-stream-controller.ts
- tests/unit/controller/base-stream-controller.ts
- tests/unit/controller/eme-controller.ts
- tests/unit/controller/subtitle-stream-controller.ts
- Handle EME key status errors such as "internal-error" before appending media
- Ban keys with status "internal-error" so that additional license requests are not made for them when found in other playlists
- Fallback to variants and renditions that have not been loaded or do not contain the key
- Multiple key status changes in a single session are handled based on the session playlist key ID
- Sessions where the playlist key ID changes to status "internal-error" are closed
- Remove levels with unresolved key status errors ("internal-error" or "output-restricted" w/o defined HDCP-LEVEL attributes)
@yajin2021 reported that other variants should be selected when a key error occurs:
- #7401
- #7413
Preventing appends of media with bad keys prevents the CDM from locking up playback. I was not …
> Handle EME key status errors such as "internal-error" and "output-restricted" before appending media

- api-extractor/report/hls.js.api.md
- src/controller/audio-stream-controller.ts
- src/controller/base-stream-controller.ts
- src/controller/stream-controller.ts
- src/utils/error-helper.ts
- Wait to retry fragment request when `navigator.onLine` is false
- Only treat no-alternate segment request failures as gaps in live playlists. Follow up to:
- #7464
- #7410
- Only schedule immediate tick on seeking when buffer is empty and state is idle (add some throttling based on feedback in #7472)
Avoid fatal error and unnecessary retries when offline (temporarily).
Allow skipping of blocked segments in live, but not in VOD where all content should be expected to load eventually.
Fixes #7471
> Defer segment requests when network connection is lost

- .eslintrc.js
- src/controller/abr-controller.ts
- src/controller/buffer-controller.ts
- src/controller/eme-controller.ts
- src/controller/level-controller.ts
- src/controller/stream-controller.ts
- src/demux/sample-aes.ts
- src/utils/mediacapabilities-helper.ts
- tests/unit/controller/eme-controller.ts
- tests/unit/controller/error-controller.ts
Add ESLint syntax rules to restrict async syntax, no-floating-promises, and no-misused-promises
ESlint error messages explain reasoning:
- The async keyword adds a `regenerator` dependency in the hls.js ES5 output not allowed in v1 due to bundle size constraints.
- Use `self` instead of `window` to access the global context everywhere (including workers).
- Usage of Array find methods is restricted for compatibility.
- Usage of Array findIndex methods is restricted for compatibility.
Most of the line changes in files are WS.
> Add ESLint syntax rules to restrict async syntax

- src/utils/error-helper.ts
…adPolicy issue-7420
This PR fixes an inconsistency in the retry policy for timeouts
```
export function isTimeoutError(error: ErrorData): boolean {
switch (error.details) {
case ErrorDetails.FRAG_LOAD_TIMEOUT:
case ErrorDetails.KEY_LOAD_TIMEOUT:
case ErrorDetails.LEVEL_LOAD_TIMEOUT:
case ErrorDetails.MANIFEST_LOAD_TIMEOUT:
case ErrorDetails.AUDIO_TRACK_LOAD_TIMEOUT:
case ErrorDetails.SUBTITLE_TRACK_LOAD_TIMEOUT:
case ErrorDetails.ASSET_LIST_LOAD_TIMEOUT:
return true;
}
return false;
}
```
Timeout events "AUDIO_TRACK_LOAD_TIMEOUT, SUBTITLE_TRACK_LOAD_TIMEOUT, ASSET_LIST_LOAD_TIMEOUT" should consistently follow `timeoutRetry`, not `errorRetry`
> fix: align AUDIO_TRACK_LOAD_TIMEOUT with timeoutRetry policy

- src/loader/level-key.ts
Parse keyId for widevine. PSSH box defines as follows:
```
aligned(8) class ProtectionSystemSpecificHeaderBox extends FullBox('pssh', version, flags=0)
{
unsigned int(8)[16]                SystemID;
if (version > 0)
{
unsigned int(32)              KID_count;
{
unsigned int(8)[16]       KID;
} [KID_count];
}
unsigned int(32)                   DataSize;
unsigned int(8)[DataSize]          Data;
}
```
The length of the DataSize and Data fields is not always 6. For widevine, it is defined in [WidevineCencHeader.proto](https://github.com/alfg/widevine/blob/master/proto/WidevineCencHeader.proto )
Parse KeyId for widevine correctly
> Parse keyid from multi-key widevine PSSH

- api-extractor/report/hls.js.api.md
- demo/main.js
- src/controller/buffer-controller.ts
- src/controller/id3-track-controller.ts
- src/controller/interstitials-controller.ts
- src/controller/subtitle-track-controller.ts
- src/controller/timeline-controller.ts
- src/hls.ts
- src/types/buffer.ts
- src/types/media-playlist.ts
- src/utils/media-option-attributes.ts
- src/utils/texttrack-utils.ts
- tests/index.js
- tests/unit/controller/id3-track-controller.js
- tests/unit/controller/interstitials-controller.ts
- tests/unit/controller/subtitle-track-controller.ts
- tests/unit/controller/timeline-controller.ts
- tests/unit/utils/texttrack-utils.js
Allow removing TextTracks created by hls.js
- use `appendChild` instead of `addTextTrack` to allow reverse operation
- replace track flush and reuse workflow with simple removal
- add `trackNode` field in `MediaPlaylist` to indicate associated `TextTrack`
- fix `MEDIA_DETACHED` event in wrong order and sometimes not triggering
This PR allows video elements to have the same lifecycle as hls.js instances. After detaching, you may attach them to new hls.js instances with nothing to worry about. It also fixed a bug caused by track reuse, where content overlapping occurs if a video contains multiple captions sharing the same language and label. eg: https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8
Yes. Since the changes involve more than one …
> Allow removing TextTracks created by hls.js

- demo/main.js
Add a new the `hlsjsConfig` query param to populate the editor on load. It is added automatically to the permalink whenever a change to the editor is applied.
It makes it easier to share the demo page with the right config (and playback URL).
I have done some QA (e.g. with/without `hlsjsConfig`, with/without peristance), but I don't know if I have covered all the edge cases.
> Add an `hlsjsConfig` query param to populate the demo editor

- src/controller/interstitials-controller.ts
- src/controller/level-controller.ts
- src/loader/playlist-loader.ts
- tests/index.js
- tests/unit/controller/content-steering-controller.ts
- tests/unit/controller/level-controller.ts
- tests/unit/loader/playlist-loader.ts
1. Add `stats.parsing.end` timing prior to emitting `MANIFEST_PARSED` on `MANIFEST_LOADED` and `MANIFEST_PARSING_ERROR`
2. Move unknown codecs handling to playlist-loader
1. Ensures time to parse Multivariant Playlist is measures and available in HLS.js events.
2. Unknown codecs that are supported as audio and video mime times need to be added to parsed levels before parsing media options so that `audioCodec` is set on audio tracks and audio `levelCodec` is set on levels. This ensures creation of SourceBuffers with the full mime type based on the playlists CODECS rather than the incomplete four CC string parse from the segments.
Resolves #7518
> Multivariant Playlist parsing fixes

- .github/workflows/build.yml
- scripts/publish-npm.sh
Use the new release environment and stop providing the npm token. Publishes will then use the OIDC flow which is configured on npm and more secure as we can restrict all publishes to come from this workflow.
Help mitigate against attacks like https://thehackernews.com/2025/09/40-npm-packages-compromised-in-supply.html
> Use GitHub `release` env for npm publish

- src/remux/mp4-remuxer.ts
- src/utils/timescale-conversion.ts
Advance initPTS to accommodate timestamps in earlier segments when starting late in the timeline.
When starting long running live streams without discontinuities, timestamps may have already wrapped in the past. This change anticipates that so that initPTS is not set to a value that would result in earlier segments timestamps getting unwrapped backwards to a value less than zero.
This issue did not occur prior to v1.6.6 with #7311, since in those older versions PTS was always remapped to the timeline. Now that PTS is preserved, it needs to be unwrapped if the timeline is long enough that a low starting "initPTS" would result in negative timestamps when seeking back.
Fixes #7536
> Fix seeking back in live with timestamp wrapping (1.6.6 regression)

- src/controller/abr-controller.ts
- src/controller/cap-level-controller.ts
- src/controller/stream-controller.ts
- tests/unit/controller/cap-level-controller.ts
Use ResizeObserver when available in cap-level-controller.
Improve buffer removal boundary used in fast switch-up to reduce stalling, for in live playback. 
Using `capLevelToPlayerSize` to detect the media element dimensions forces layout. The `ResizeObserver` avoids this speeding up player setup.
Might want to debounce calling `this.detectPlayerSize` in the observer callback to avoid setting the level more than once when the media element size is animated by the browser during transitions like entering and exiting fullscreen.
> Use ResizeObserver to cap level to player size
