src/demux/tsdemuxer.js

This should add support for  NAL units overlapping between PES packets, as discussed in https://github.com/dailymotion/hls.js/issues/6.
Note I haven't been able to test it locally yet as the I haven't been able to get the build to work on windows.

Added support NAL unit overlapping between PES packets

---

package.json

Browserify export name specified in package.json is 'hls', but expected 'Hls' (as specified for watchify, for example).

fix browserify Hls export name

---

demo/index.html

This patch add checkbox on index.html by which it is possible to stop streaming.
Some times it is useful for debug: to edit/prepare stream URL, check logs, etc.

Demo: Allow to globally enable/disable streaming

---

API.md
src/loader/fragment-loader.js
src/loader/playlist-loader.js
src/utils/xhr-loader.js

Added config option 'xhrSetup'. This could be function with single argument of type XMLHttpRequest.
If specified, XhrLoader will call this function before xhr.send(), so that allow user to modify/setup xhr.
There are cases we need just simple XHR tuning. For example, set withCredentials=true to send cookies. IMHO, in such cases it is convenient to implement simple function instead of full featured loader.

XhrLoader: allow custom setup of XMLHttpRequest

---

API.md
README.md
demo/index.html
src/demux/demuxer.js
src/demux/tsdemuxerworker.js
src/events.js
src/remux/mp4-remuxer.js

Fires Events.FRAG_PARSING_METADATA on parsing id3 tags. Event data.samples array contains ID3 PES instances. sample.pts and sample.dts are converted to relative time, values are in seconds.  FIxes #20

Fire Events.FRAG_PARSING_METADATA with id3 samples

---

API.md
src/controller/buffer-controller.js
src/events.js
src/hls.js

- A couple of fixes on detachVideo / destroy
- Added a DESTROYING event, as MSE_DETACHED isn't equivalent in that use case

Fixes for detaching / re-attaching video (for ads support for example)

---

API.md
src/controller/buffer-controller.js
src/events.js
src/helper/level-helper.js

The goal behind these changes is to allow code external to the player to be notified when level details and PTS information have been updated, so they can use the correct fragment timestamps.
I still have one interrogation: should we trigger LEVEL_PTS_UPDATED when drift = 0 ?

Add two new events triggered when level details and PTS information have been updated

---

src/controller/buffer-controller.js

I'm not sure why the `loader` property doesn't exist, but in other places in the file where `abort()` is called you do this check first.

Added missing 'loader' property check

---

README.md

It looks like the method to attach the video stream to the video element is `attachMedia` instead of `attachVideo`.

Update the docs to use attachMedia instead of attachVideo

---

.jshintrc
demo/index.html
src/controller/abr-controller.js
src/controller/mse-media-controller.js
src/loader/playlist-loader.js
src/utils/xhr-loader.js

This makes the measurements more precise & monotonic, eg. avoiding issues when the local system time is adjusted.
Note that the measurements will have an arbitrary base and can't be compared using a regular Date.now(). This is new behavior but doesn't change any of the internal calculations that all rely on deltas.

Use performance timers for stats

---

src/hls.js

In my opinion, triggering DESTROYING should be the first step when destroying the instance of hls.js, even before we call detachMedia. It seems more intuitive to me, I think it's what developers would expect.

Trigger event DESTROYING before detaching media in destroy()

---

src/controller/mse-media-controller.js

saw these index errors when debugging, e.g. for `fragLen` = 1, `Math.round(fragLen / 2)` = 1, not 0.

Fix index error in mse media controller when loading mid-fragment for live playlist

---

src/utils/logger.js

- Adds UTC date and log level to output
- Enables to easily wrap the input to format the output
- Adds support for `debug` and `trace`, when available via console
- Allows to easily hard-disable a level 
- Removes redundancy in code
Example:
```
2015-11-22T14:58:42.255Z | [log] > level 3 loaded [0,63],duration:634.584
logger.js:23 2015-11-22T14:58:42.256Z | [log] > Loading 0 of [0 ,63],level 3, currentTime:0,bufferEnd:0.000
logger.js:23 2015-11-22T14:58:44.199Z | [log] > Demuxing 0 of [0 ,63],level 3
logger.js:23 2015-11-22T14:58:44.233Z | [log] > selected A/V codecs for sourceBuffers:mp4a.40.5,avc1.64001f
logger.js:23 2015-11-22T14:58:44.242Z | [log] > parsed data, type/startPTS/endPTS/startDTS/endDTS/nb:video/0.033/10.033/0.000/10.000/600
logger.js:23 2015-11-22T14:58:44.245Z | [log] > …
```

Slightly improved logging module

---

API.md
src/utils/xhr-loader.js

This allows `withCredentials` to be set depending on the request URL.

Add request url to xhrSetup callback

---

src/demux/exp-golomb.js

This fixes display of videos with non square aspect ratio.
Values are copied from **Table E-1** in the H.264 spec.

Parse and use sample aspect ratio information

---

API.md
src/events.js
tests/functional/multiple/index.html

Per dailymotion/hls.js@6151d5e we're using `MEDIA__{ATTACHED/ATTACHING/DETACH/DETACHING}` instead of `MSE_` prefix. This PR updates this events on some source files.

Update event name prefix from MSE_ to MEDIA_

---

src/controller/mse-media-controller.js

The loose event coupling means that `tick()` can easily be called while processing a `tick()`. This can lead to all sorts of weird behavior.
I am aware of at least one case where this happens: When loading a key which has already been loaded, the `onKeyLoaded` callback is called synchronously while a tick is processing, triggering another `tick()`.

Prevent tick() handler from being entered while already processing

---

package.json
src/loader/playlist-loader.js
src/utils/attr-list.js
tests/unit/utils/attr-list.js

This fixes order dependent parsing of `EXT-X-STREAM-INF` attributes.
This also exposes any stream info attribute for external processing.
Tested to work on a normal and encrypted stream in Chrome.

Add and use generic playlist attribute list parser

---

src/loader/playlist-loader.js
src/utils/attr-list.js
tests/unit/utils/attr-list.js

Any attribute in playlist can be quoted. Changed AttrList to always remove these quotes.

Fixed loading of playlists that contain quoted attribute values

---

src/utils/xhr-loader.js

Previously it was requesting 1 byte too many.
(Fixes #167)

Fix byte range request in XhrLoader

---

API.md

The parameter name is level not levelid (just by looking at https://github.com/dailymotion/hls.js/blob/60e7c82edaa77c7b27b82011dd435c3f63b423cc/src/controller/level-controller.js#L123)

Fixes api documentation for LEVEL_SWITCH

---

src/utils/xhr-loader.js

use XMLHttpRequest `onloadend` instead of `onreadystatechange`.
this should be more performant (Because the statechange function is called many times during the lifetime of a request)

use loadend instead of readystatechange

---

src/utils/url.js
tests/unit/utils/url.js

Also fixed the faulty test and added some more.
(fixes #207)
The issue was that
```javascript
buildAbsolutePath("a/b/c.m3y8", "../d.m3u8");
```
and 
```javascript
buildAbsolutePath("a/b/c.m3y8", "../../d.m3u8");
```
both returned `a/d.m3u8`. `buildAbsolutePath` doesn't handle the base url becoming completely empty.
Now the base url for `buildAbsolutePath` also includes the domain which fixes this.

Fix bug in url util which meant url calculated incorrectly when traversing up to root

---

src/controller/level-controller.js
src/controller/mse-media-controller.js

Tested working on Chrome Canary (v50) and Firefox (v42) on OSX.
Tested by using Big Buck Bunny from demo page and an audio-only stream that I put on pastebin since I could not find any working public audio-only stream: http://pastebin.com/raw/dpXTqA29 (requires disabling web security / CORS checking in browser)
Additional testing using W3C test case: http://w3c-test.org/media-source/mediasource-addsourcebuffer.html. This does not actually play out audio/video, but it queries the browser using isTypeSupported with mime type that starts with `audio/mp4`.
If someone is able to verify this with IE and perhaps other browsers on Windows, this would resolve #203.

Change mimetype for audio sourceBuffers to "audio/mp4"

---

src/demux/aacdemuxer.js

The mp4 remuxer has a parameter for a textTrack. When attempting to use an AAC stream the demuxer passes the timeOffset is into this value. This causes errors when attempting to load an AAC stream, as textTrack.samples will be undefined. Specifically mp4-remuxer.js:53 will fail with a 'cannot call length of undefined' error. 
This PR fixes that by supplying a dummy textTrack object to the remuxer function.

adding empty closed caption object for aac demuxing

---

design.md
src/controller/buffer-controller.js
src/controller/mse-media-controller.js
src/controller/stream-controller.js
src/demux/demuxer-inline.js
src/demux/demuxer-worker.js
src/demux/demuxer.js
src/demux/tsdemuxer.js
src/errors.js
src/events.js
src/hls.js
src/remux/mp4-remuxer.js

refer to https://github.com/dailymotion/hls.js/pull/215

decoupling Streaming and Buffering logic

---

src/demux/exp-golomb.js

I encountered some strange issues with some filmon.tv streams
Since commit 4556b434a0f0e3f8e6d61ba6e45176157518f6f5, I am getting an error from the html5 element, yet no HLS.js ERROR event emitted.
I traced the reason to be getting a sarRatio of `[1280, 1281]`, which causes an irregular 0.999.. sarScale, which makes the width a floating point number.
It seems that when using a floating-point width, an error is emitted (in runtime Electron v0.33.9) without any HLS.js ERROR event. I cannot debug this further to find why the error is emitted, **but since the width reflects pixel-width, I figured that it should be an integer anyway** and I `Math.ceil`'d it.
I also enabled handling of the 1:1 case

Fix readSPS issues

---

README.md

According to https://developer.mozilla.org/en-US/docs/Web/API/MediaSource, the `media.mediasource.whitelist` preference was removed in Firefox 42.
MSE was enabled in Firefox 41 without the preference.

Update Firefox compatibility info

---

package.json
src/index.js

So that this module can bundled with webpack / browserify when installed
from npm.
Should fix #240

Include compiled index.js in npm distribution

---

demo/index.html

Permalinks for the demo page contain the key-value pair ```defaultAudioCodec=undefined``` by default.
When accessing such a permalink, the page interprets it as a string ```"undefined"```, which is not handled properly by [stream-controller.js](https://github.com/dailymotion/hls.js/blob/d2fc84782d50f5bcd4a772b863a4786f817f3f06/src/controller/stream-controller.js#L814)
This change converts the explicit value ```"undefined"``` from and to ```undefined``` in the demo page — I think this is preferable to an empty string but that could work as well.

Fixed conversion from and to "undefined" string in index.html

---

README.md

We've integrated hls.js into Video.js v5 using Source Handler -- new interface suggested by Video.js for easy integration of media engines, so it might be a good mention in README.md.

mentioned another video.js integration in README.md

---

src/utils/xhr-loader.js

When a request is being retried, the timeout handle was not being set.

move timeoutHandle to loadInterval

---

src/controller/buffer-controller.js

When detaching media, `media.src` set to empty string. It doesn't help, because `media.src` evaluates to `location.href` if it's empty string. To fix it, `src` attribute needs to be removed.
I didn't remove `this.media.src = ''` line, I just added `this.media.removeAttribute('src')`
Tell me if you think that `src = ''` should be removed and I will update PR
Issue: https://github.com/dailymotion/hls.js/issues/273

Fix: remove src attr after media detaching (fixes #273)

---

src/loader/fragment-loader.js
src/loader/key-loader.js
src/loader/playlist-loader.js

Make sure we don't try to access a destroyed loader.
If a `loaderror` occurs after `this.loader` has already been set to `null` by `destroy()`, then a `TypeError` exception will be thrown upon encountering `this.loader.abort()`. This PR fixes that by checking to see if `this.loader` is defined.

Undefined loader fix

---

src/controller/stream-controller.js

Prevent `undefined.length` `TypeError` by ensuring that `bufferRange` is actually defined.
This can occur when accessing `currentLevel` too early.
This is an alternative patch to dailymotion/hls.js#290.

Handle `undefined`/`null` `bufferRange` in `getBufferRange`

---

API.md
src/controller/stream-controller.js
src/hls.js

The current way of configuring the target latency is problematic with playlists with variable segment durations, because there's no way to set a consistent latency across playlist: a playlist with 10s segments will have a latency of 30s in hls.js, where the latency will only be 9s if the segments are 3s long.
This PR doesn't aim at replacing the current parameters, but to provide alternate configuration parameters expressed in seconds.
The default still are `liveSyncDurationCount` and `liveMaxLatencyDurationCount`, and those parameters can still be configured.
If set, the new parameters take precedence. 
There's a fail fast if the users tries to mix both type of parameters at initialization.
There's also a fail fast if `liveMaxLatencyDuration` is set but `liveSyncDuration` isn't: there …

Implement alternative params to liveSyncDurationCount and liveMaxLatencyDurationCount

---

src/loader/playlist-loader.js

Fixes support for data-uri encoded playlists.
The only problem was about redirect detection that (in case of data uri) thinks url is "data:application/x-mpegURL," (behavior of xmlhttprequest and responseURL in case of data-uri).
Currently only tested on firefox + chrome without base64 encoding for data-uri.

Small fix for data-uri support

---

src/loader/playlist-loader.js

The current ABR algorithm seems to treat BANDWIDTH like the average bit
rate of the stream. While this is not according to spec which demands
the peak bit rate
https://tools.ietf.org/html/draft-pantos-http-live-streaming-18#section-4.3.4.2
it's probably a realistic assumption for most streams.
To avoid punishing standard compliant streams honor the optional
AVERAGE-BANDWIDTH if present.

Obtain level.bitrate from AVERAGE-BANDWIDTH if present (#334)

---

src/loader/fragment-loader.js

The XMLHttpRequestProgressEvent is very usefull to know the progress of fragment loading
If the player is in buffering state, it allow to display a percentage of loading

Add XMLHttpRequestProgressEvent event in FRAG_LOAD_PROGRESS data

---

src/controller/abr-controller.js
src/controller/level-controller.js

abr-controller: Don't create extra timers. This is notably possible during fast successive seeking where `FRAG_LOADING` will occur repeatedly.
level-controller: Make sure to nullify the timer in `destroy()`.

Controller timer fixes

---

src/loader/fragment-loader.js
src/utils/xhr-loader.js

and keep XHRProgressEvent encapsulated inside xhr-loader
After discussion in PR #320
If event.lengthComputable is false, then the total property on the stats object will be undefined. Is that ok? I guess this is only going to happen if the media server doesn't send back a Content-Length header, which seems highly unlikely to me, especially for video content.
By the way, couldn't this total property be used instead of [expectedLen](https://github.com/dailymotion/hls.js/blob/401ab8c6e0eb37c05b00aa3fbad08ae1bc492f54/src/controller/abr-controller.js#L63) when available?

Add ProgressEvent.total to stats object 

---

src/controller/stream-controller.js

Incase the manifest has a wrong codec, the default one will never be used.
When someone is already using this option its highly likely that he know what he's doing and want to set the codec to this config option

use defaultAudioCodec as first option

---

src/utils/url.js
tests/unit/utils/url.js

And also the case where the base url doesn't contain a protocol.
Fixes #424

URL parser now handles base urls which don't contain a domain (for v0.5.x)

---

src/controller/stream-controller.js

check for pending seek command after having loaded last fragment

Fix possible infinite buffering (for v0.5.x)

---

src/controller/buffer-controller.js
src/controller/stream-controller.js
src/event-handler.js
src/events.js

StreamController: Introduce updateState + destructure doTick
This allows for log lines like
```
[log] > engine state transition from FRAG_LOADING to PARSING
logger.js:47 [log] > Demuxing 44 of [0 ,161],level 0
logger.js:47 [log] > parsed audio,PTS:[234.575,244.986],DTS:[234.575/244.986],nb:488
logger.js:47 [log] > parsed video,PTS:[234.640,244.974],DTS:[234.557/244.974],nb:250
logger.js:47 [log] > engine state transition from PARSING to PARSED
logger.js:47 [log] > media buffered : [10.447333,74.056932][205.028666,244.973599][297.274,330.39031][632.143333,675.681999]
logger.js:47 [log] > engine state transition from PARSED to IDLE
```
So we can track state transitions easily and centralize transition logic if needed (or trigger events/actions on specific transitions).
Also decomposed …

Improve state transitions

---

src/controller/buffer-controller.js

Previously the duration would only be updated automatically to match what was buffered.
Fixes #355

Update mediaelement.duration with duration from manifest

---

API.md
src/controller/abr-controller.js
src/hls.js

Use exponential weighted moving average in keeping the last bandwidth in the ABR controller to smooth out segment load times a bit.

Use EWMA in tracking bandwidth in ABR controller

---

README.md

I just noticed we never updated the README when we added full CEA-708 support. It's cleaned up here.
I deleted my fork and started over, btw, so it'd be clean. I'll learn how to rebase if i need to :)

Updated README.md w/ CEA-708

---

src/controller/abr-controller.js

Resolves https://github.com/dailymotion/hls.js/issues/461 by using playbackRate to adjust starvation delay and next level calculations.

Make the ABR controller take the playback rate into account

---

src/controller/ewma-bandwidth-estimator.js

Make sure that `this.fast_` is defined in `EwmaBandWidthEstimator.getEstimate()` before trying to access it.
Prevents errors from being thrown near the start of playback.

EwmaBandWidthEstimator undefined object fix

---

API.md

* Added missing `Hls.Events.FRAG_PARSING_USERDATA` event docs.
* Fixed and cleaned up formatting of the event args and errors.
* Fixed and cleaned up code snippets.
* Changed multiline code fences (three backticks) to single-line (one backtick) where single-line is expected.

API.md: add FRAG_PARSING_USERDATA, cleanup

---

API.md
design.md
src/controller/abr-controller.js
src/controller/ewma-bandwidth-estimator.js
src/hls.js

ewma-bandwidth-estimator: Make `defaultEstimate` globally-configurable so it's available before `bwEstimator` is initialized
(f9c183d66a89bb1f9c10d1244c50477c6037a98c created this undefined object issue.)
My use case is reading `nextLoadLevel` before playback has started, btw.

EwmaBandWidthEstimator undefined object fix #2

---

API.md

It's `0.5`, not `0.3`.
https://github.com/dailymotion/hls.js/blob/ed2887304ed26f34aa8bc029779c57341fe516a2/src/hls.js#L59

API.md: Fixed default value for maxBufferHole

---

src/utils/xhr-loader.js

... otherwise we might get aborted while having a retry scheduled. unlikely but possible.
also renamed `timeoutHandler` to `requestTimeout` to differentiate between scheduling of request-timeout and retry-timeout calls/handlers.

xhr-loader: store & clear on abort the retry timeout (race cond fix)

---

src/loader/playlist-loader.js
tests/unit/loader/playlist-loader.js

Fixes #555
Also restrict so that all items that go into 'tagList' in the fragment objects start with "EXT", i.e. not general comments. This is because with this change a general comment after `#EXTINF` would not make it to the `tagList` anyway.
A separate issue should the keys in `tagList` contain the EXT prefix?
I.e should the regex be
```javascript
(?:#EXT(.*):(.*))|#(EXT(.*))
```
instead of
```javascript
(?:#(EXT(?:.*)):(.*))|(?:#(EXT(?:.*)))
```
(This PR also reads the `EXT-X-VERSION` as `\d+` like v0.5.x)

Allow comments after #EXTINF before URL

---

src/demux/tsdemuxer.js

There are some cases where the hls.js decoder enters an infinite loop during h.264 decoding, specifically when handling SEI messages. This causes playback to stall, and will completely lock up the browser tab if workers are disabled. In profiling the stall, I've discovered that the decoder can get hung up when parsing SEI payloadType at these lines:
https://github.com/dailymotion/hls.js/blob/3ddaa4c77de1d7be11ec53ef93d7ed5a4367cd40/src/demux/tsdemuxer.js#L378-L382
Presumably this could also happen during payloadSize parsing as well, but I've not experienced it first hand.
Looking at the h.264 spec, the reference implementation, and a few other notable implementations (Exoplayer and ffmpeg), it looks like the current way hls.js parses payloadType and payloadSize is incorrect. Specifically, …

Fix SEI message parsing to match the h.264 spec

---

src/controller/stream-controller.js

Prevents playback failure when calling `stopLoad`/`startLoad` repeatedly on live content
Fixes regression introduced by 582aab08657b6f92feb84de1bb992de7adf0f6c3
---
While bisecting this, I created a version-changeable demo page that pulls from GitHub. It also includes a few extra `console.log` statements and a "500ms reload" button to help reproduce the problem.
Good versions:
http://gigcasters.com/test/hls.js-demo/?v=v0.5.33
http://gigcasters.com/test/hls.js-demo/?v=ef29675128650369013909318da0a48b7a2cb69f
Bad versions:
http://gigcasters.com/test/hls.js-demo/?v=0859f8012bf229aef2fdeb0186ef44bd1adbaafb
http://gigcasters.com/test/hls.js-demo/?v=v0.5.34
Fixed (local) version:
http://gigcasters.com/test/hls.js-demo/?v=v0.5.41-custom
The `dist-proxy.php` the page references is here: …

stream-controller: Ignore startDTS when it is NaN in onFragLoaded

---

src/loader/playlist-loader.js
tests/unit/loader/playlist-loader.js

Previously, an #EXT-IF-BYTERANGE:length[@offset] tag without the optional offset was ignored. This resulted in a get request without range headers causing the download of the full object i.s.o. the desired segment.
Includes a new 'byterange without offset' unit test.

fix capture of byterange tags without offset

---

src/controller/buffer-controller.js

No more media errors (`MEDIA_ERR_SRC_NOT_SUPPORTED`) coming from the `MediaElement` when the `src` attribute is re-initialized.

Detach properly the MediaSource from the media

---

src/demux/tsdemuxer.js
src/remux/mp4-remuxer.js

Resolves https://github.com/dailymotion/hls.js/issues/578 by filling audio gaps at the beginning of a segment with empty audio (when possible).

Actually fill audio gaps at the beginning of a segment with empty audio.

---

package.json

Should fix issue if hls.js is used externally in a project that is built with browserify.
https://github.com/dailymotion/hls.js/issues/265#issuecomment-244400294
refs #265 
This also adds `rimraf lib/*` before babel runs as the babel command doesn't clear the directory itself.

Add browserify derequire plugin

---

src/controller/stream-controller.js

Fix runtime error raised when a live goes offair: `TypeError: Cannot read property 'start' of undefined`.

Do not try to merge fragment details when the playlist is empty for live

---

package.json
tests/functional/auto/hlsjs.js

This works on windows.
(Also requiring chrome driver so loads from node_modules)

Start http-server in functional test instead of separate process

---

tests/functional/auto/hlsjs.html

Should fix sauce labs error when can't find `startStream()` function.

Move functional test html script into head so that it blocks page load

---

.travis.yml
package.json
scripts/travis.sh
tests/functional/auto/hlsjs.js

I've removed the "babel" script as this is now in "buildlib".
Also removed "prebuild" and "postbuild" as the contents of those has now moved into the new "buildlib" and "builddist" scripts. I'm not really sure what the advantage of the pre* and post* scripts are over having the commands in one?
Travis now runs "scripts/travis.sh" which will look at `TRAVIS_MODE` and decide what to do from that.

Speed up travis jobs by only running parts that are necessary

---

src/loader/playlist-loader.js

👋
Test stream: `//playertest.longtailvideo.com/adaptive/bunny/manifest.m3u8`
Codecs are sometimes separated by spaces, causing hls.js to report that there is no audio stream. This results in the buffer-controller expecting to create only one source buffer. This used prevent playback, but https://github.com/dailymotion/hls.js/commit/e56c646177761f8817b27c76fe17ed805752fb07 has fixed that.

Split codecs by space or comma instead of just comma

---

src/utils/cues.js

Test stream: playertest.longtailvideo.com/adaptive/captions/playlist.m3u8
In Firefox, a cue in this stream's caption has its position set to over 100, causing an exception to be thrown. This causes caption processing to freeze (cueStartTime never gets changed). Clamp the value between 0 and 100 to prevent the exception.

Clamp 608 captions position between 0 and 100

---

API.md
src/controller/stream-controller.js
src/hls.js

- Add an extra condition to prevent further playback if we don't have enough segments.

Initial live manifest size

---

src/utils/cea-608-parser.js
src/utils/cues.js

The current code messes up the display of roll-up captions when a new cursor position is set by a PAC caption command. 
You can see the problem in the following stream:
http://player.theplatform.com/p/RIyUFC/t91QYYYzNgwm/select/media/DVYuc3Ngr7iK?form=html&logLevel=debug&pdk=stage
My pull request code clears up the displayedMemory CaptionScreen when a new cursor position is set and it also tries to merge the remaining lines from the previous position into the new position.

Clear out orphaned roll-up captions

---

.travis.yml

Shouldn't do any harm, and wondering if this might fix sauce labs if it uses a more recent docker image. Travis says the image that the previous jobs were running on was created on Thu Feb 5 15:09:33 UTC 2015

use latest stable node version on travis

---

package.json

I accidentally installed it to dependencies.

Move url-toolkit to dev dependency

---

src/loader/playlist-loader.js
src/utils/attr-list.js

Currently if the regex expression was used previously but didn’t run to the end of the string it will resume from where it was previously.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/lastIndex

Reset lastIndex on regex expressions with g flag before use

---

src/controller/abr-controller.js
src/controller/level-controller.js
src/hls.js

Fix for issues #841
When using minAutoBitrate video should start not with the lowest level but with the lowest lewel above minAutoBitrate
Additionally found out that when throttling network to low bandwidh - abandonRulesCheck is forcing to go down to the lowest level

[Addition] minAutoBitrate upgrade #841

---

src/controller/timeline-controller.js

When I have two sources with inline CC, swapping between them causes some CC from the previous source to appear mixed in with the CC of the new source, and continue to update. I am calling detachMedia before swapping to the new source. For VOD to VOD swaps, this mixing lasts only for a couple of fragments. For Live to VOD, I am seeing lingering mixing that lasts for a longer time.
By clearing the cues on the detach media listener in TimelineController, it stops the lingering CC cues. I have tested this with VOD to VOD, live to VOD and VOD to live and it appears to solve the issue.

Pushing fix for CC cues not stopping when switching media

---

src/loader/playlist-loader.js
tests/unit/loader/playlist-loader.js

Problem line: #EXTINF:.640,
Before regex change:
````
Match 1
Full match	0-14	`#EXTINF:.640,
`
Group 27.	0-1	`#`
Group 28.	1-7	`EXTINF`
Group 29.	8-13	`.640,`
````
After regex change:
````
Match 1
Full match	0-14	`#EXTINF:.640,
`
Group 12.	4-7	`INF`
Group 13.	8-12	`.640`
Group 14.	13-13	``
````

Modify regex to capture fragment durations without a leading zero

---

src/controller/buffer-controller.js

Fixes a memory leak of the MediaSource object created in onMediaAttaching
Problem is similar to issue #780, leak was discovered while taking heap snapshots in Chrome

Release MediaSource object URL when media is detached

---

src/controller/timeline-controller.js

The  `new window.Event('addtrack');` line of code throws an exception in IE11. I added a try-catch expression and called `document.createEvent('Event') ` when an exception is caught.

Fix for IE11 not dispatching an addtrack event for 608/708 captions.

---

demo/index.html
src/controller/audio-stream-controller.js
src/controller/audio-track-controller.js
src/controller/buffer-controller.js
src/controller/stream-controller.js
src/demux/aacdemuxer.js
src/demux/demuxer-inline.js
src/demux/demuxer-worker.js
src/demux/demuxer.js
src/demux/tsdemuxer.js
src/events.js
src/loader/playlist-loader.js
src/remux/mp4-remuxer.js

test page : http://streambox.fr/mse/hls.js.alt-audio-live/demo/

alternate audio track support on live stream cowork along with @sergiojm and @fredvb

---

src/controller/stream-controller.js

Previously, backtracking would only occur under specific circumstances, leading to small gaps streams whose fragments don't always start with keyframes but are otherwise fine. This PR changes the stream-controller such that we always backtrack (load the previous fragment) when encountering a dropped frame. 
#855 
I'm having trouble reproducing this (even in 0.6.12) - can I have help verifying? Maybe this isn't needed anymore.
https://content.jwplatform.com/manifests/BHbQYVup.m3u8

Whe loading a fragment with missing frames, backtrack a segment to find the keyframe

---

doc/API.md
src/controller/audio-stream-controller.js
src/controller/stream-controller.js
src/demux/aacdemuxer.js
src/demux/demuxer-inline.js
src/demux/demuxer-worker.js
src/demux/demuxer.js
src/demux/mp4demuxer.js
src/demux/tsdemuxer.js
src/errors.js
src/events.js
src/remux/dummy-remuxer.js
src/remux/mp4-remuxer.js
src/remux/passthrough-remuxer.js

add Fragment object in all events fired by demuxer

---

src/controller/buffer-controller.js

previously, in chrome, the following was displayed:
>[error] > sourceBuffer error:[object Event]

ensure sourceBuffer error is displayed in logs

---

src/utils/cues.js

Small fix for issue #1023.
A SyntaxError was being thrown in IE when creating cues for closed captions that supplied a startTime and endTime of the same value. If they are the same, we now bump the endTime a slight amount.

IE11 - Closed caption rendering fix

---

src/controller/timeline-controller.js

```
details: "internalException"
err: TypeError: self.clearCurrentCues is not a function
at Object.newCue
```

fix incorrect invocation of clearCurrentCues

---

doc/API.md
src/config.js
src/controller/timeline-controller.js

Addresses issue #1019 by adding configuration options for the caption text track label and language code for both generated text tracks. They default to the prior hard-coded values.

Captions - configuration for text tracks

---

src/controller/audio-stream-controller.js

Audio switching independent of buffer.
```
Segment duration: 40s.
maxBufferLength: 90s.
```
The player loads into buffer 120s. For 30 seconds will not change the audio track.

Fix: Switching audio, blocked by buffer.

---

src/helper/level-helper.js
tests/functional/streams.json

A negative frag start time can lead to DTS becoming non-monotonic when remuxed, causing Chrome to throw a SourceBuffer exception and crashing playback.
Test stream (expires in a day or so): https://pubads.g.doubleclick.net/ondemand/hls/content/6698/vid/8f6e0be7-bbdb-4515-b24a-1ae276f08167/CHS/streams/6d0840da-0fb8-4c21-abba-999c73ed78cf/master.m3u8

Do not allow frag.start to be negative

---

doc/API.md

Remove erroneous docs for startFragPrefetch
Reviewing the code that uses `startFragPrefetch` it doesn't appear to do anything with "Max number of append retries". This appears to have been added as part of a23d8cd1b086a2c988a35bd32964997b0b1ed624

Remove erroneous docs for startFragPrefetch

---

doc/design.md
src/controller/id3-track-controller.js
src/controller/subtitle-track-controller.js
src/hls.js

Fix for issue #725.
Added src/controller/id3-track-controller.js to handle creating the id3 metadata text track and adding cues to that track in response to the FRAG_PARSING_METADATA event.

Fix for issue 725: Feed ID3 metadata into textTracks

---

src/controller/timeline-controller.js
src/utils/webvtt-parser.js

Sometimes there are cue overlaps on segmented vtts so the same cue can appear more than once in different vtt files.
This PR adds the ability to avoid showing duplicated cues with same timecode and text.

avoid showing repeated webvtt cues

---

src/hls.js

Some old webkit browsers (the one where I spotted this problem was a stock browser and system webview on Android 4.4.2) have a deprecated MSE API: `WebKitSourceBuffer` there lacks all methods defined by spec and has only `append()` and `abort()`. 
http://caniuse.com/#feat=mediasource states that MSE is supported on Android from 4.4.4 release.
In this browsers `Hls.isSupported` returns `true` (because `WebKitMediaSource` exists and `window.MediaSource.isTypeSupported('video/mp4; codecs="avc1.42E01E,mp4a.40.2"') === true`), but video playback via hls.js breaks. 
In this PR I suggest additional checks to detect a deprecated MSE API.

add SourceBuffer API checks to detect deprecated WebKitMediaSource

---

src/utils/webvtt-parser.js
src/utils/xhr-loader.js

- Replaces `.startsWith` with a function
- Catches `xhr.open`, which throws when trying to access mixed content

Various IE bugfixes

---

src/utils/webvtt-parser.js

Issue https://github.com/video-dev/hls.js/issues/1124

Resolve subtitles desync error

---

src/demux/mp4demuxer.js

The uint32 parsing logic actually produces int32 values, due to use of bitwise operators. This means that negative values can be parsed, which can cause the processing to fail.
I discovered this, when debugging a stream that suddenly stopped working, while spouting negative timestamp values into the debug log. Specifically, it was the parsing of the lower bits of a `version==1` `tfdt` box. I fixed the other instances as well for good measure.

Parse uint32's correctly

---

doc/API.md
src/loader/fragment-loader.js
src/loader/playlist-loader.js
src/utils/xhr-loader.js

This change simply adds the XHR object to the args passed to the loader callbacks for the purpose of getting more details about the request/response.
Specifically we need this at Mux to get the headers of the response, which can tell us:
- Whether or not the file was cached, and at what level
- Which CDN was used in the case of a dns-level CDN switcher like Cedexis
- Which edge node
- CDN internal timing stats

Add XHR object to manifest/frag loader callback args

---

package.json
src/loader/playlist-loader.js
tests/unit/loader/playlist-loader.js

This fixes issue #1179.
For encrypted playlist that use the SN as the initialization vector the content will not play at all.   This is because the playlist regex skips the first N segments and sets the SN to 0 for the Nth segment.
For unencrypted content it simply skips segments.
The problem was with the regex, it does not deal with segment URL that is one character or less.
See checkin/pull comments for why.

Fix issue #1179 with playlist parse

---

doc/API.md
src/controller/cap-level-controller.js
tests/unit/controller/cap-level-controller.js

This PR improves the getMaxLevel, which chooses a level greater than or equal to the current video dimensions, to choose the level with the greatest bandwidth matching the video's dimensions. The current algorithm chooses the first level matching the current dimensions. However, if we have multiple quality levels with the same dimensions yet increasing bandwidths, we do not choose the level with the greatest bandwidth.

Improve cap-level-controller to choose the maximum level by both dimensions and bandwidth

---

src/demux/aacdemuxer.js
src/demux/adts.js
src/demux/demuxer-inline.js
src/demux/mp3demuxer.js
src/demux/mpegaudio.js

https://github.com/video-dev/hls.js/pull/1113 introduces Mpeg audio only support - however in doing so it breaks some audio-only AAC container HLS. It triggers a `[error] > error while trying to add sourceBuffer:Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('audio/mpeg;codecs=mp4a.40.2') is unsupported.` in latest Chrome for Windows 10. 
Example of problematic HLS stream: http://61.63.46.166/vod/_definst_/ibrain/14307/mp4:65v014307004.mp4/playlist.m3u8
(mirror at https://www.rmp-streaming.com/media/hls/issues/1/playlist.m3u8)
This is also documented in https://github.com/video-dev/hls.js/issues/1176 (which was closed using a workaround).
After debugging it appears that the probe for MP3Demuxer returns false positive. This pull request fixes this issue by first …

audio-only-probe-demux-aac-before-mp3

---

src/controller/timeline-controller.js

IE11 and Edge do not allow calls to addTrack with non TextTrackCue objects, so it is necessary to convert the custom WebVTT cues into TextTrackCues.
This partially fixes:
https://github.com/video-dev/hls.js/issues/1054
There is still an additional issue when switching between textTracks, at that point new captions will not display because IE11 and Edge do not fire the textTrack onchange event which triggers the loading of new TextTracks

Fix for VTT subtitles don't show up on IE11 or Edge

---

package.json

The `test` command was failing because `BABEL_ENV=test` does not work for windows. Since `cross-env` is already a dependency I figured it was mistakenly removed from `test` and `test-func` so I added it to those commands.

add cross-env to test so it can be run on windows

---

src/controller/subtitle-track-controller.js

This pull request adds polling for textTrack changes in browsers that don't fire textTrack change events when switching tracks (IE11 and Edge). It is an additional fix for https://github.com/video-dev/hls.js/issues/1054.

Add textTrack polling for browsers that don't have textTrack onchange events

---

src/controller/stream-controller.js

There is an issue when trying to set hls.currentLevel immediately after MANIFEST_LOADED event is fired. StreamController immediateLevelSwitch method is incrementing fragLoadIdx property which is `undefined` at the moment so it becomes `NaN` and breaks further frag loop loading detection inside _loadFragmentOrKey method.

fix frag loading loop detection

---

src/controller/stream-controller.js

This PR will prevent incrementing `nextLoadPos` from the bitrate test frag, which is not appended to the buffer. While this normally does not cause an issue a race condition with start time (as in the case of preloading and autostarting) will cause the first segment to be skipped.

Do not calculate nextLoadPos using bitrate test frag

---

src/controller/level-controller.js
src/loader/playlist-loader.js
src/utils/codecs.js

Fixes issues when eg. a "wvtt" subtitle codec is included in the list. Currently, it breaks in interesting ways, depending on whether the browser advertise support for `'audio/mp4; codecs="wvtt"'` or not.
I created a new `codecs.js` util class that can determine the media type from the codec value. Doing this lookup avoids `"wvtt"` being set to `level.audioCodec`.

Lookup type for codec in mp4ra sample entry code list

---

src/demux/tsdemuxer.js

Allocate avcSample before using it. This occurs when TS contains a NDR before an IDR

fix use of null pointer when SLICE is received before IDR

---

doc/API.md
src/controller/stream-controller.js

Retries for the fragments are honored. Current implementation can retry until buffer is available. With this changes it is not allowed to retry more than specified in the configuration.

Change fragment retry

---

src/utils/vttparser.js

According to https://bugs.chromium.org/p/chromium/issues/detail?id=663797, Chrome now supports "WebVTT: VTTCue.align = 'center'".

Fix comment for VTTCue.align

---

src/controller/level-controller.js

It’s a fix/improvement of current fragment down-shifting logic. If there is an issue with a fragment and we have backup/redundant streams, the library would retry the same level over and over. This change brings Fragment Error concern to Level Controller. It’s part of HLS design, where we need to reload level in order to try fragments.
It’s recommended to adjust fragment retry values to achieve the best retry outcome.

Add fragment errors for level loading

---

demo/index.html

This PR fixes a DOMException that was raised because source buffers in `tracks` were not available from the media source.
```
(index):851 Uncaught DOMException: Failed to read the 'buffered' property from 'SourceBuffer': 
This SourceBuffer has been removed from the parent media source.
at checkBuffer (https://video-dev.github.io/hls.js/demo/:851:79)
```

Demo: Reset tracks when media is detached

---

src/utils/xhr-loader.js

There is an XDomainRequest reference here from https://github.com/video-dev/hls.js/commit/7f772ef86b83972df0c5d8f74e1c5b36fcf4f2f7#diff-5b5ca1c2ac7acf4ca9be5b53329cc1a2 but this only works in IE9 and IE10 which don't have MSE anyway and aren't supported by hls.js
Remove this tidbit of dead code.

Remove dead code XDomainRequest reference

---

src/helper/level-helper.js

nextLevel quality switch is broken since 4a68b557a7f55e1b06c697fc10cdc190fc8c368a
maxStartPTS is never calculated and thus the buffer is not flushed which makes nextLevel switch essentially the same as loadLevel

Fix nextLevel quality switch

---

src/demux/aacdemuxer.js
src/demux/demuxer-inline.js

- Allow AAC demuxing without a timestamp or ID3 data
- Scan entire fragment for ADTS syncword if no ID3 is found
- For AAC streams without ID3, calculate PTS using a default value + time offset
- Probe for TS before AAC because TS demuxing is more accurate (prevents TS streams with AAC audio from being demuxed with the AAC demuxer)
AAC streams do not need to have ID3 data if they don't need to synchronize with a video track, i.e. in audio-only streams.

Allow AAC streams without ID3 to play

---

src/controller/stream-controller.js

With version 0.8.3 some of our streams (LIVE HLS playlist) wouldn't start playing. Fragments were loading but playback never started (black screen, no audio).
After some digging I found the cause of this issue was the commit bc24f55cc51e57128f55e8a9886f2b41b9790fa5. The start position was never set to the first buffered position.
On our streams the buffered start position is always between 1.5 and 2.0 seconds. The player was waiting for a lower position to get buffered which obviously never happened. But I still wondered why the default 2 second maxSeekHole didn't work. Then I saw that "startPositionBuffered" was replaced with "startNotBufferedButClose" and negation in if clause still present which is most certainly not correct.

Fix seek to buffered start position

---

src/utils/webvtt-parser.js

We've started using hls.js in production at France Télévisions but we noticed that on Chrome, certain textTracks were not parsed correctly (ie : 0 cue points when inspecting), no errors were triggered by hls.js, and textTracks were hence not displayed.
This is due to the way vttLines are parsed:
```String.fromCharCode.apply(null, new Uint8Array(vttByteArray))```
-> when vttByteArray is huge and has a length greater than the _theoretical_ maximum number of arguments a javascript function can accept (which varies depending on browser implementation), the call to `apply` fails and raises an error:
**Uncaught RangeError: Maximum call stack size exceeded**
To avoid this quirk, I instead call `reduce` on the array to create the raw string.
To reproduce the error, just open up your console and …

Update vttLines conversion to avoid stack overflow

---

src/controller/buffer-controller.js
src/demux/demuxer.js
src/helper/mediasource-helper.js
src/hls.js

By assigning values to window.MediaSource and window.SourceBuffer
we create properties on the window object which did not necessarily
exist before. On iPhones, for example, window.MediaSource does not
exist, but when we do window.MediaSource = window.MediaSource || window.WebKitMediaSource
we declare the property with an undefined value. This changes the
outcome of an (arguably) common method for checking whether the
browser supports a certain Web API, namely by using the "in" operator
like so:
if ('MediaSource' in window) { ... }
The property declaration was introduced in 66ed87a7
This commit lets window.MediaSource and window.SourceBuffer remain
undeclared on the window object on browsers which do not support
MediaSource/SourceBuffer.

Avoid polluting window object

---

doc/design.md
src/controller/level-controller.js

We are lacking retry constraints for level loading. This change brings level retry configuration in the same way as we have for fragments. Since there is a dependency between fragments and levels by design, level retry management gives an unlimited retry budget for fragments.
Related to https://github.com/video-dev/hls.js/pull/1317

Add level retry constraints

---

doc/API.md
doc/design.md
src/controller/subtitle-stream-controller.js
src/controller/timeline-controller.js
src/events.js

- In the `subtitle-stream-controller`, decrypt subtitle tracks if they are encrypted
- If the fragment has a `frag.decryptdata.uri` that isn't null, trigger `KEY_LOADING` event
- Once `KEY_LOADED` fires, fire `FRAG_LOADING` event
- On `FRAG_LOADED`, decrypt the payload and fire a `FRAG_DECRYPTED` event
- In the `timeline-controller`, do not parse WebVTTs until subtitle frag is decrypted
- On `FRAG_LOADED`, check if frag is encrypted before parsing VTTs
- If encrypted, do nothing and wait for `FRAG_DECRYPTED` event to fire before parsing WebVTTs
I tried to model the changes after patterns followed in other controllers. If you want anything to be modified or moved, let me know and I am happy to make the changes.
Here is an m3u8 with encrypted text tracks that can be used for testing (should …

Subtitle decryption support

---

doc/API.md
src/controller/subtitle-track-controller.js
src/hls.js

We needed to enable subtitles support at France Télévisions and we thought it was cleaner to make it work inside hls.js instead of implementing our own layer on top of this library.
I just rewrote the setSubtitleTrackInternal method to update dom textTracks when needed and to support subtitle disabling.

Rewrite setSubtitleTrackInternal method.

---

karma.conf.js
package.json
tests/tests.webpack.js

**Note**: Closed old PR (#1276) due to bad merge. Pulled latest and cherry-picked changes on top.
This goal of this PR is gain the ability to unit test in a browser environment. 
Example of test that would fail if we ran test with `mocha`:
```
it('should test error handling', (done) => { 
hls.loadSource('https://video-dev.github.io/streams/x36xhzz/x36xhzz.m3u');
hls.attachMedia(video);
hls.on(Hls.Events.ERROR, function(event, data) {
assert.equal(data.networkDetails.status, 404);
done();
});
});
```
The test would complain about `document` being unavailable. For those unfamiliar, `karma` is a test runner which can run the `mocha` tests ( or any other unit tests ) in a browser environment. With the inclusion of `karma-chrome-launcher`, the tests can be run via Headless Chrome which allows …

Add karma test runner

---

doc/API.md
src/demux/demuxer.js

I am using custom loader that stores HLS segments in memory for future use. Transfering ArrayBuffer to Web Worker (demuxer) inside hls.js makes them detached and data not accessible any more. To share data between hls.js Web Workers and custom loader without copying it (i.e. calling ArrayBuffer.slice) it is good idea to add support of SharedArrayBuffer.

Non-transferable SharedArrayBuffer payload support

---

src/utils/webvtt-parser.js

The `hash` function in the webvtt parser requires that the input argument is a string. If not, it will always return the same initial seed (5381). This means that `cue.id` is only based on the cue text and not the timestamps, which breaks the cue de-duplication feature for cues with the same content.
This PR fixes that :)

Fix cue id generation in WebVTT parser

---

tests/functional/streams.json

This was the test stream that would make issue-1331 show up: https://github.com/video-dev/hls.js/issues/1331
Adding the test stream which had the PID discontinuity which would make Safari MSE drop buffers from different PID than initially set up ones

add test stream with dynamic ad-inseration causing codec / PMT/PID discontinuity

---

src/controller/timeline-controller.js
src/utils/cea-608-parser.js
src/utils/output-filter.js
tests/unit/utils/output-filter.js

Update TimelineController for CEA-608 to dispatch VTTCues every time a row finishes updating for Roll-up and Paint-on modes.
**Current Behavior:**
VTTCue is created whenever characters are appended onto the displayed row for Roll-up and Paint-on modes.
**Issue with current behavior:**
Since there are a lot of VTTCue objects that get created with very close start and end times, some of them get ignored by the textTrack and will not dispatch a `cuechange` event. There will be even more dropped VTTCue events when there is load on the browser.
**Resolution:**
I've abstracted out the outputFilter channels into it's own class that will ignore cue creation requests when the line is not complete. This new change will allow VTTCues to be created on a per line bases.
**Results:**
In my environment, …

Add captions OutputFilter

---

src/demux/id3.js
src/utils/webvtt-parser.js

fixes #1417 
webvtt-parser throws an error on certain Japanese (and korean) characters since the ArrayBuffer isn't properly converted into a string. The fix for this was to update and then use the utf8ArrayToStr from id3.js instead of String.fromCharCode to convert the array buffer. Then replace escape() with encodeURIComponent() when encode the text of the current cue in the parser.oncue method

Fix webvtt-parser for Japanese and Korean captions

---

src/utils/webvtt-parser.js

fixed broken merge from master here: ebb2fcc322f90bd0b79feb6df5b2c23660306e4d  which caused captions to break #1422

fix: vtt parser broke after master merge

---

src/demux/mpegaudio.js

Make detection of samples per frame for MPEG audio and fix wrong calculated duration for version 2/2.5 Layer III.
Fix #1356

Fix mpeg audio frame duration

---

src/controller/abr-controller.js

Fix AbrController._nextAutoLevel blocking when fragment aborted.
If the fragment is already loaded, _nextAutoLevel = -1 and level up is possible, but not if the current fragment is still loaded.
This happens if user presses the full screen button and the current fragment is still loaded.

fix nextAutoLevel blocking when fragment aborted

---

src/controller/buffer-controller.js
tests/functional/issues/video-tag-hijack.html

when the video tag is hijacked and initialized with different  `src` by an external script, hls.js will destroy the new object of the hijacker and will stop the playback.
this is an edge case caused by aggressive video ads providers (in this case - Facebook) and poor implementations of hls.js instances management.
nonetheless, in my vision it's a bug worth fixing anyway given the terrible outcome for the user.
this bug is resolved by caching the Object url generated for the local mediaSource and validating that it still the same one when destroying or skipping cleanup otherwise
a test page has been added at `tests/functional/issues/video-tag-hijack.html` that reproduces the problem. reverting the fix in this PR will stop the playback once the video tag has been hijacked.

Don't reset media source if replaced by 3rd party

---

doc/API.md
src/config.js
src/controller/buffer-controller.js

If you are trying to build a player with Native UI capabilities in modern browsers it is not possible to provide proper UI feedback since we override MediaSource duration to duration of the current level. Also, most Native UI implementations do not support DVR. 
We are introducing a new configuration parameter `liveDurationInfinity` which sets duration to `Infinity` thus various MSE implementations can provide corresponding UI to a Live broadcast. The parameter is `false` by default.
Notes:
- resolve https://github.com/video-dev/hls.js/pull/1371

Add Live Duration Infinity config parameter

---

src/helper/is-supported.js
src/helper/issupported.js
src/hls.js

This change is needed for detecting hls.js support without loading full hls.js 
it makes a profit when hls.js imported on page as external script.

Move isSupported method to module

---

package.json
webpack.config.bundle-analyzer.js

this pull request adds the `$ npm run bundle-check` command that will analyze the bundle and spin up a browser with a visual representation of how big are the components of hlsjs:

add `npm run bundle-check` command

---

tests/functional/auto/hlsjs.js

This might be causing connectivity issues
> By default, Sauce routes traffic from some WebDriver browsers (Internet Explorer and Safari) through the Selenium HTTP proxy server so that HTTPS connections with self-signed certificates work everywhere. The Selenium proxy server can cause problems for some users. If that's the case for you, you can configure Sauce to avoid using the proxy server and have browsers communicate directly with your servers.

enable saucelabs avoidProxy option

---

src/crypt/aes-decryptor.js
tests/unit/crypt/aes-decryptor.js

Encrypted segments should end with padding ([PKCS7](https://en.wikipedia.org/wiki/Padding_(cryptography)#PKCS7)), but currently we are not removing these additional bytes, which are all set to the number of padding bytes.
> An encryption method of AES-128 signals that Media Segments are completely encrypted using the Advanced Encryption Standard [AES_128] with a 128-bit key, Cipher Block Chaining, and PKCS7 padding [RFC5652].  CBC is restarted on each segment boundary, using either the IV attribute value or the Media Sequence Number as the IV; see Section 5.2.
https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-4.3.2.4
This PR updates the decryptor so that we remove these bytes.

Remove PKCS7 padding in AESDecryptor

---

doc/design.md
src/crypt/aes-decryptor.js
src/crypt/decrypter.js
src/demux/sample-aes.js

We now explicitly inform the decryptor that pkcs7 padding removal should not happen for sample aes streams. From the documentation it looks like [sample-aes streams should not include this padding](https://developer.apple.com/library/content/documentation/AudioVideo/Conceptual/HLS_Sample_Encryption/Encryption/Encryption.html).
This also disables web crypto, which expects the padding. Currently for sample-aes streams the web decryptor is failing, and then we were falling back to the js decryptor (which previously never removing padding).
fixes https://github.com/video-dev/hls.js/issues/1512

Do not remove padding for sample aes

---

src/remux/mp4-remuxer.js

Fixes issue where line#82 of mp4-remuxer.js was calling remuxVideo with the incorrect number of parameters.  Also moved the next condition statement inside of the same block because it was unnecessary to have the variable and statement outside of the same block.  Added quick check for (inputSamples.length == 0) for remuxVideo just like what remuxAudio has.  Successfully compiled and tested with the default playlist.
- [ x] no commits have been done in dist folder (we will take care of updating it)
- [ x] Travis tests are passing (or test results are not worse than on master branch :))

RemuxVideo method called with incorrect number of parameters; accurateTimeOffset is lost

---

src/loader/playlist-loader.js

This fixes a typo when assigning the loader to the context. We had been previously assigning the loader constructor (capital L), but have been using it as an instance, causing errors. This PR assigns the lowercase l loader to context.
Resolves https://github.com/video-dev/hls.js/issues/1517

Assign the instance of the loader to the context object

---

src/controller/audio-stream-controller.js

This ensures that when maxMaxBufferLength is set to something smaller than,
maxBufferLength the value is respected for both audio and video.
I have a use case where I want to adjust the size of the buffers once the user starts playback. I want to set `maxBufferLength` to the desired length when playback starts. I then set `maxMaxBufferLength` to something extremely small for initial buffering (something like 2 seconds). Then once the action to increase buffer length is taken I can simply update `maxMaxBufferLength` to be something more reasonable (like the default of 600). Without this update the audio stream ends up buffering far more content since it doesn't respect the `maxMaxBufferLength` configuration property.
No docs changes are included since I think this is bringing the code more …

Update audio-stream-controller to respect maxMaxBufferLength.

---

tests/unit/helper/buffer-helper.js

Add tests for  `BufferHelper` .
📝 Notes
I want to improve performance of `BufferHelper.isBuffered` util.
Maybe, current `_checkAppendedParsed` paid unnecessary costs at every time.
(To access `media.buffered` should be cached)
This test is a first step of the refactoring.

test: add BufferHelper tests

---

src/controller/stream-controller.js
src/helper/buffer-helper.js
tests/unit/helper/buffer-helper.js

I've improved `_checkAppendedParsed` function on StreamController.
This method is called high-frequently.
- Cache `media.buffered` during filtering fragments
- It can reduce DOM acesss to `media.buffered`
- macOS: 10.12.5
- Chrome: 63.0.3239.132
- CPU 6x slowdown
I've measured the time of `_checkAppendedParsed` by following simple script.
```diff
diff --git a/src/controller/stream-controller.js b/src/controller/stream-controller.js
index a72758ff..62027855 100644
--- a/src/controller/stream-controller.js
+++ b/src/controller/stream-controller.js
@@ -15,6 +15,7 @@ import {logger} from '../utils/logger';
import { alignDiscontinuities } from '../utils/discontinuities';
import TaskLoop from '../task-loop';
+window.__HLSJS__CheckAppendedParsedPerf = [];
const State = {
STOPPED : 'STOPPED', …
```

Improve `StreamController#_checkAppendedParsed` performance

---

tests/functional/auto/hlsjs.html
tests/functional/auto/hlsjs.js

Pass `config` to HlsJs correctly if the `config` object is defined in `test-streams.js`
Previously, the test does not pass `config` object to hlsJs constructor.
As as result, `angelOneShakaWidevine` stream could not played in the test.
Because, this stream require `widevineLicenseUrl` and `emeEnabled` config.
https://github.com/video-dev/hls.js/blob/6d227c187a2c0ab9fbe90d6d7aadfd49c3176495/tests/test-streams.js#L114-L120

fix angelOneShakaWidevine function test

---

src/events.js
src/hls.js

Currently
- demo and func test does not work
- `npm run test:unit` is failed.
```
HeadlessChrome 0.0.0 (Mac OS X 10.12.6) ERROR
{
"message": "Uncaught ReferenceError: HlsEvents is not defined\nat http://localhost:9877webpack:///src/events.js:5:27 <- tests/tests.webpack.js:75:76\n\nReferenceError: HlsEvents is not defined\n    at Object.defineProperty.value (http://localhost:9877webpack:///src/events.js:5:27 <- tests/tests.webpack.js:75:76)\n    at __webpack_require__ (http://localhost:9877webpack:///webpack/bootstrap%20cd7d57625274bcbcfce8:19:0 <- tests/tests.webpack.js:20:30)\n    at Object.defineProperty.value (http://localhost:9877tests/tests.webpack.js:3560:66)\n    at __webpack_require__ (http://localhost:9877webpack:///webpack/bootstrap%20cd7d57625274bcbcfce8:19:0 <- …
```

fix `events.js` and `hls.js`

---

.travis.yml

This  PR introduce build stage for #1566 
- [Build Stages - Travis CI](https://docs.travis-ci.com/user/build-stages/ "Build Stages - Travis CI")
- Build Stage is enhanced feature of Travis CI's `matrix`
Two stages are **"required"** and **"optional"**.
CI should be passed if **"required"** tests are passed.
In other words, CI allow to fail **"optional"** tests.
As a result, come back GREEN staus 💚 
Refs #1566

fix(travis): introduce build stage

---

tests/test-streams.js

Apply `nudgeMaxRetry: 5` to "Big Buck Bunny - adaptive qualities" func test.
It is a workaround for test failing because of slow seek on Chrome/Win10.
- <https://video-dev.slack.com/archives/C4FC8GGEP/p1519718130000397>
Also, We may need to change the default value of `nudgeMaxRetry`.
(Current `nudgeMaxRetry` is `3` by default)

fix(func-test): add `nudgeMaxRetry` option for slow seek env

---

src/helper/fragment-tracker.js
src/loader/playlist-loader.js
tests/functional/auto/hlsjs.js

context.loader points to constructor of the used loader. getInternalLoader is the right way to get the loader instance.

Fixes handling network error on loading chunklist + Exception on Object.keys in FragmentTracker

---

docs/API.md
src/controller/audio-track-controller.js
src/controller/level-controller.js
src/events.js
tests/unit/controller/level-controller.js

these events have been deprecated for a while, and replaced by `LEVEL_SWITCHING` and `AUDIO_TRACK_SWITCHING`

deprecate LEVEL_SWITCH/AUDIO_TRACK_SWITCH

---

tests/functional/auto/setup.js

try to workaround readyState not being reliable on Saucelabs VM
- [?] Travis tests are passing (or test results are not worse than on master branch :))

functional test / smooth switch : use currentTime instead of readyState as test condition

---

demo/index.html
demo/metrics.html

Removes old references to favicons from the demo HTML pages.  These resources pointed to 404s and were loading on http://, which causes errors in the console on page load.  The favicon could be replaced with a `hls.js`-specific one, if so inclined, but this is a simple fix.

Remove old, insecure (404) favicons in demo HTML pages

---

src/helper/fragment-tracker.js
src/helper/level-helper.js

level-helper: merge initSegment info to avoid requesting it again on each live playlist refresh
related to #1607

avoid repeated request for init segment on live fmp4 playlist and fix regression introduced by FragmentTracker 

---

src/loader/playlist-loader.js

Emitting `loadError`s instead of `loadTimeOut`s when playlist request retries exhaust.

Emit 'loadError' instead of 'loadTimeout' when playlist request retries exhaust

---

src/helper/mediakeys-helper.js

Fix a bug
Version 0.8 was working fine, but now with 0.9 code can no longer be loaded in node environment
allows node code to execute without failing on "window is undefined"

fix: guard case when window is undefined in node environment

---

scripts/travis.sh

Cause the CI build to fail if the module can no longer be required in nodejs without error.
We introduced a regression with the latest release because this was not tested.
Would have caught see https://github.com/video-dev/hls.js/pull/1642
It's easy to test. why not? :)

ensure that module can be required in node without errors

---

demo/index.html
demo/main.js

Description of the Changes
Add limitMetrics option for demo page to limit the total number of metric entries per class; this prevents memory leaks when using the demo player for long periods of time. Default is set to -1; which means Unlimited.

Add limitMetrics option for demo page to limit the total number of metric entries per class

---

src/controller/timeline-controller.js
src/utils/output-filter.js

- Refer to 608/708 captions by name (`textTrack1`) instead of number (`1`)
- Add captions to a new object instead of the timeline-controller prototype
- So that the code is simpler to read and modify. It is much more straightfoward to get the label/language of the captions track via property access rather than string concatenation (`captionsProperties.textTrack1.label` vs ` this.config['captionsTextTrack' + track + 'Label']`). 
- It's easier to read (and statically analyze) a class when all properties to be added to the prototype are initialized in the constructor.
Did I miss any number instances?
General tech debt

Refactor timeline-controller to refer to 608/708 captions via name instead of number

---

src/controller/buffer-controller.js
src/controller/cap-level-controller.js
src/controller/level-controller.js
tests/test-streams.js

This PR allows multiple audio tracks to be set without them being considered alternate audio tracks, which avoids miscalculation of the amount of sourcebuffers needed.
Resolves https://github.com/video-dev/hls.js/issues/1604, https://github.com/video-dev/hls.js/issues/1605
- [] Travis tests are passing (or test results are not worse than on master branch :))

Properly calculate the amount of sourcebuffers needed for streams with multiple non-alternate audio renditions

---

src/controller/stream-controller.js
tests/unit/controller/check-buffer.js

- Break some `_checkBuffer()` functionality into 4 new functions: `_tryFixStall()`, `_reportStall()`, `_tryNudgeBuffer()`, and `_trySkipBufferHole` 
- Unit test each component & control flow through `checkBuffer()` itself
- **Change**: Always emit a stall event when stalling (this was the behavior before fragment tracker; was changed to only trigger on high buffer stalling afterwards)
- `checkBuffer()` is currently large, hard to understand, and not well tested. Refactoring helps readability and allows us to unit test the individual functionality it comprises. Test coverage is up a few percentage points with this PR.
- Not always emitting a stalling event breaks JW's integration. But I think this is also a wider regression. If you hit the edge of a live stream no stall event will be …

Refactor checkbuffer

---

README.md
docs/API.md
docs/html/index.html

In the Getting Started documentation, it initializes a `video` variable inside the `if` block then references that variable in the `else if` block. The `video` variable wouldn't be available in the `else if` block.
Move the `video` variable initialization to outside the `if` block so it can be used in both blocks.

Fix Getting Started Documentation

---

package-lock.json

... to allow reproducible installs with equal flattened dependency tree.
The presence of the lock-file, and committing changes to it, will actually allow us to have install of dependencies that are fixed to a certain flat deps tree. Right now, when running an install of node modules, it may be different from one install to another, as even if we used fixed version numbers in our package file, other packages we depend on may not (but have the `^`), and thus if a new package gets released on the registry, this can modify environment of one and the same code version, which should not be allowed to happen.
Npm's first attempts to fix this issue was the shrinkwrap, but it was a failed design. Package-lock now addresses this properly, in the fashion of the yarn.lock file of the respective …

add package-lock.json 

---

README.md

Change the example code for the case where MSE is not supported to use the `loadedmetadata` event rather than the `canplay` event.
The most likely situation where MSE is not supported but HLS is natively supported is with Safari and, since September 17, Safari only emits the `canplay` event if the URL is in the user-controlled white-list, hence the example code as it stands would not work.
Use of English.
#1686

Change example to use 'loadedmetadata' event rather than 'canplay' event

---

src/demux/tsdemuxer.js

Fix RemuxerTrackIdConfig as per iso/iec 14496-12 spec
ISO/IEC 14496-12 (ISO base media file format)
"track_ID is an integer that uniquely identifies this track over the entire life-time of this presentation.
Track IDs are never re-used and cannot be zero. "
But RemuxerTrackIdConfig.video is 0. So we should use properly track Id.
I'm not sure, but I think it will be reviewed by developers involved in remux.
https://github.com/video-dev/hls.js/issues/1687

Fix RemuxerTrackIdConfig as per iso/iec 14496-12 spec

---

src/controller/abr-controller.js
src/controller/audio-stream-controller.js
src/controller/stream-controller.js
src/controller/subtitle-stream-controller.js
src/loader/fragment.js
tests/unit/controller/stream-controller.js
tests/unit/loader/fragment.js

- Load partial frags which have already been loaded once before
- Set currentFrag before arming abr check timer
- Implement `frag.encrypted` getter
- Add unit tests
- So that partial frags which have been loaded once are allowed to load again. This can happen when seeking backwards into a region which requires that fragment to be loaded again. Without this change, that fragment continuously loads until `checkBuffer()` intervenes by nudging `currentTime`.
For example:
1) The stream begins loading in order: `1506, 1507, 1508, 1509, 1510`
2) `1509` is a partial fragment. After backtracking it appends with the gap
3) For whatever reason (in this case seeking or a forced reparse from the demuxer), Hls.js wants to load `1509` again
4) `1509` is selected but not loaded because it's fragState is …

Resolve partial frag loop loading

---

src/controller/fragment-tracker.js

Prevent FragmentTracker from tracking a fragment that was used for bitrate testing
The bug caused the StreamController to go into an endless loading loop because
the bitrateTest fragment was being treated by the FragmentTracker as buffered
when it wasn't and thus if the StreamController tried to fetch that fragment
again it was blocked because the FragmentTracker told the StreamController
it was already loaded.
This worked fine in 0.8.9.
No

Fixed FragmentTracker causing endless loading

---

tests/functional/auto/setup.js

From https://github.com/video-dev/hls.js/pull/1693 it was reported that this was an issue. This should fix it.
The thing with the var has probably been working anyway, because before it was using var hoisting, meaning that this worked anyhow since the variable had been declared "somewhere" further down, even though it was a nested scope. Of course it is "nicer" to only work with let and const as this is also much more readable, but I don't think the stream var was actually undefined ever?

Test setup: Fix `stream` var not defined in top scope

---

.travis.yml
README.md
package.json
scripts/check-already-published.js
scripts/set-canary-version.js
scripts/travis.sh

make travis publish an npm package on every commit merged to master of the form
```
[current version]-canary.[first 8 characters of commit]
```
e.g. 0.9.1-canary.9d7e9af9
Because it allows people to easily grab builds of master.
They can:
```
npm install hls.js@canary
```
or use
```
https://cdn.jsdelivr.net/npm/hls.js@canary
```
_which will sometimes be slightly behind due to cdn caching_
or
```
https://cdn.jsdelivr.net/npm/hls.js@0.9.1-canary.9d7e9af9
```

publish canary package on master commits

---

README.md
scripts/set-canary-version.js

bump the patch version for canary releases, and use the commit number as the prerelease string instead of commit hash.
I did some more reading around npm/semver and the current canary version is incorrect. The canary version should be higher than the current stable version. Also the prerelease string should ascend between versions.
This allows someone to specify
```
^0.9.5-canary.3810
```
in their package.json, which will always resolve to the latest canary, until >= 0.9.5 has been released, at which point they will automatically switch to the stable releases.

Ensure canary version is higher than stable version

---

src/controller/fragment-finders.js
src/controller/stream-controller.js
tests/mocks/data.js
tests/test-streams.js
tests/unit/controller/fragment-finders.js
tests/unit/controller/stream-controller.js

- Fall back to `findFragBySN` if `findFragByPDT` returns a frag which fails the `fragmentWithinToleranceTest`
- Break `findFragmentByPDT` and `findFragmentBySN` into a `fragment-finders.js` module
- Default `bufferEnd` to 0 in `fragmentWithinToleranceTest`
- Unit test & unit test & unit test
- Add 4 functional test streams with different PDT scenarios 
So that streams with discontinuities which have huge gaps inbetween PDT values play properly. Test stream: http://playertest.longtailvideo.com/adaptive/boxee/playlist.m3u8
```
#EXTM3U
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-MEDIA-SEQUENCE:1
#EXT-X-ALLOW-CACHE:YES
#EXT-X-TARGETDURATION:8
#EXT-X-VERSION:3
#EXT-X-PROGRAM-DATE-TIME:2012-12-06T19:10:03+00:00
#EXT-X-DISCONTINUITY
#EXT-X-PROGRAM-DATE-TIME:2012-12-06T19:10:03+00:00
#EXTINF:6.006,{} …
```

Fall back to frag finding by SN if PDT search does not return a good fragment

---

README.md
demo/index.html
scripts/travis.sh

Allow people to access the demo page with the canary build of hls.js at http://video-dev.github.io/hls.js/demo?canary=true
It also clears the jsdelivr cache after a new canary release is publishes, so that new requests should get the new version immediately.
So that people can easily test the canary version.

Add ability to load demo page with canary build

---

src/controller/stream-controller.js

So that `lastCurrentTime` is updated frequently enough to avoid stalls. If the playback rate is set > 1, a small gap can causes this check never to pass:
```
if (currentTime !== this.lastCurrentTime) {
// The playhead is now moving, but was previously stalled
if (this.stallReported) {
logger.warn(`playback not stuck anymore @${currentTime}, after ${Math.round(tnow - this.stalled)}ms`);
this.stallReported = false;
}
```
Because the difference between `currentTime` and `lastCurrentTime` is not large enough to re-set `lastCurrentTime`.
No
https://github.com/video-dev/hls.js/issues/1505
From https://github.com/jwplayer/hls.js/pull/118

Remove playbackRate factor for setting lastCurrentTime

---

src/loader/m3u8-parser.js

The original code need a an regex to handle other type of suffix.
Fixed old "FIXME".

Add a regex to check different mp4 suffix.

---

src/controller/audio-stream-controller.js
src/controller/stream-controller.js

Fixed `AudioStreamController` & `StreamController` not being cleaned up
- `onHandlerDestroying()` is overriden by said controllers but doesn't call
`super.onHandlerDestroying()` which cases the tick interval to never stop
Because hls.js is leaking memory after `destroy()`
no

Fix memory leak

---

src/demux/adts.js

Event.ERROR is undefined if don't import Event object.

---

src/remux/mp4-generator.js
src/utils/make-array-from-array-like.js

Use `Array.from` instead of `Array.prototype.slice.call`.
This PR is to use better function than `Array.prototype.slice.call`.

Use `Array.from` instead of `Array.prototype.slice.call`

---

docs/API.md
src/hls.js

Expose observer.once to public API.
It simplifies hls.js events subscription code in some cases - instead of writing something like
```js
function onManifestParsedOnce() {
hls.off(Hls.Events.MANIFEST_PARSED, onManifestParsedOnce);
video.play();
})
hls.on(Hls.Events.MANIFEST_PARSED, onManifestParsedOnce);
```
you can just do
```js
hls.once(Hls.Events.MANIFEST_PARSED, function () {
video.play();
}));
```
if you need a single event call subscription.
no
no
I could not find any tests for on/off API, please point if I should add some.

expose observer.once to public api

---

.eslintrc.js
package.json
scripts/travis.sh
src/controller/abr-controller.js
src/controller/audio-stream-controller.js
src/controller/buffer-controller.js
src/controller/cap-level-controller.js
src/controller/eme-controller.js
src/controller/fps-controller.js
src/controller/level-controller.js
src/controller/stream-controller.js
src/controller/subtitle-stream-controller.js
src/crypt/decrypter.js
src/demux/adts.js
src/demux/demuxer-inline.js
src/demux/demuxer.js
src/events.js
src/loader/playlist-loader.js
src/utils/codecs.js
src/utils/fetch-loader.js
src/utils/get-self-scope.js
src/utils/logger.js
src/utils/xhr-loader.js
tests/unit/controller/check-buffer.js
tests/unit/demuxer/demuxer.js

Acknowledged the issue that was addressed here: https://github.com/video-dev/hls.js/pull/1755 ...
* Fix a few false positives of linter browser-env globals for `Event`, which is supposed to be our event enum, but linter thought was the DOM Event constructor.
* For code safety measure, remove all preset and custom globals from our eslint config
* Only access window globals explicitely everyhwere (yes), since this is the only way to write (almost) safe code in the end
* Add a `lint:quiet` script to only show fatal errors in eslint output 
* Mask the `window` global explicitely with self for transparent use of that scope in modules that are imported by both worker and main threads.
`Event` not defined in `decryptor` and `adts` demuxer, which was causing error events not to be triggered in …

Fix DOM `Event` lint global false positive and access all window props explicitely

---

src/controller/stream-controller.js

Trigger BUFFER_NUDGE_ON_STALL error first before updating the currentTime of the video tag.
Anytime we set the video tag's currentTime value, it triggers a pair of 'seek' and 'seeked' events. By triggering the error first, users of HLSjs can better decide how to deal with these events.
None.
Buffering on slower internet connections. (100kbps or less)

Trigger BUFFER_NUDGE_ON_STALL before updating currentTime

---

src/loader/m3u8-parser.js
tests/unit/loader/playlist-loader.js

Updated regular expression to use first colon as tag name divider, rather than last.
If passing a JSON object in a custom tag, the tag name contains part of json object, and value is broken.
The regex could be validated.
#1814

Updated LEVEL_PLAYLIST_REGEX_SLOW in m3u8-parser.js to use first colon as tag end

---

src/controller/cap-level-controller.js

So that when the current media is detached, and new media with fewer levels is attached, `maxAutoLevel` does not represent an index out-of-bounds with respect to the new array of levels.
From the reported issue:
1. load a source with multiple levels with large video tag size to make `autoLevelCapping` > 0, let say `autoLevelCapping = 1`
2. detach (`autoLevelCapping  = 1`)
3. load source with a single level (`autoLevelCapping  = 1`)
4. ABR controller reads `maxAutoLevel` (which equals `autoLevelCapping = 1`) and traverses all levels from `minAutoLevel` to `maxAutoLevel` and breaks up because `minAutoLevel = 0`, `maxAutoLevel = 1` and `levels.length === 1` (we are getting out of range error)
Does re-attaching guarantee that `onManifestParsed` will be called again? I'm wondering if it could …

Stop level capping on media detaching

---

tests/test-streams.js

Replace `http` to `https` for avoiding mixed content in demo page
All resource should be playable on demo pages(https page).
- can play all demo on https page
fix #1589

fix(demo): update http to https

---

scripts/travis.sh
webpack.config.js

Add a guard against the global `window` object (not present for Node.js), in order to avoid errors when loading hls.js into Node.js with `require()` (including using `import` statements via bundlers or transpilers).
Instead of throwing an error it will export an empty object `{}`. In effect this is making it possible to load the module and not get any error, so the error handling can be deferred, if need be.
The guard can alternatively be added to the hls.js source code, to each file containing references to the DOM. This is less optimal imo. One of the maintainers seems to think the same (see: https://github.com/video-dev/hls.js/pull/1642#discussion_r177874988)
Hls.js doesn't support ES6 modules that can be imported in Node.js (`.mjs`-files), if this is changed in the future, then this …

Support universal builds ("SSR")

---

src/demux/aacdemuxer.js

Our current code will compute an AAC timestamp based on the current stream time (timeoffset) if the ID3 timestamp is not found; we use a falsy check to verify this. However, the timestamp of a segment following a discontinuity may be 0. The timeoffset-computed timestamp will allow that segment to buffer, but will cause the remuxer to misscalculate the base PTS for the new discontinuous range. This miscalculation causes the remuxer to detect fragments subsequent to the first discontinuous fragment as overlapping.
This is what should happen:
10 -> 20 -> 30 -> **D** -> 0 -> 10
But this is what actually happens:
10 -> 20 -> 30 -> **D** -> 40 -> 10
Is `isNaN` fine here? We aren't in danger of accidentally casting a string (and this tricking `isNaN`) but I know it's not the best practice.

Only compute PTS using timeoffset when the ID3 timestamp is NaN

---

src/controller/abr-controller.js
src/controller/audio-stream-controller.js
src/controller/buffer-controller.js
src/controller/fragment-finders.js
src/controller/fragment-tracker.js
src/controller/level-helper.js
src/controller/stream-controller.js
src/demux/demuxer.js
src/loader/fragment-loader.js
src/loader/fragment.js
src/loader/level.js
src/loader/m3u8-parser.js
src/loader/playlist-loader.js
src/polyfills/number-isFinite.js
src/utils/discontinuities.js
src/utils/webvtt-parser.js
tests/mocks/data.js
tests/unit/controller/fragment-finders.js
tests/unit/controller/stream-controller.js
tests/unit/loader/fragment.js
tests/unit/loader/level.js
tests/unit/loader/playlist-loader.js
tests/unit/utils/discontinuities.js
webpack.config.js

- Stop searching for fragments via PDT when PTS is known
- Backfill PDT values in cases when the first PDT tag does not correspond to the first fragment
- Remove `programDateTime` property from `level.details`; PDT can change between discontinuities within a level. `hasProgramDateTime` has been added to `details` so that code can easily infer if PDT is available for use; if true, all fragments will have `pdt` set.
- Lazy compute `endPdt` since it changes based on duration; duration may change after frags are demuxed
- Avoid assigning pdt to the level or frag if it is NaN
- Apply search tolerances to finding frags via PDT 
- Replace `isNaN` with `Number.isFinite`
- Polyfill `Number.isFinite` via webpack replacement
- Clean up redundant code
- Add tests
- Searching for fragments via PDT …

Improve fragment searching via PDT

---

src/controller/audio-track-controller.js
tests/unit/controller/audio-track-controller.js

solve issue #1833 
Currently if manifest contains default audio track attribute and application tries to set audio track on manifest parsed event then the logic will override the application selection.
The current change adds a state flag to indicate an audio was selected via API, e.g. selected by application, and it is then used when `_selectInitialAudioTrack` is called.
If the application didn't select an audio track then run with current logic(select track with default attribute in manifest). if the application did chose audio track then try to find an appropriate track from all available tracks.
resolve #1833

fix initial audio track selection

---

src/controller/audio-track-controller.js
src/controller/level-controller.js
src/demux/aacdemuxer.js
src/demux/demuxer-inline.js
src/loader/playlist-loader.js

- Reassign audio track ids after filtering
- Unassign level property from audio tracks and captions
- Fix performance now usage typo
- The audio track`id` property is used as an index to the audio track array. If the ID is not reassigned after filtering, it will no longer correspond to the correct array location. This can causes exceptions or the wrong track to be loaded.
- The level property was previously left undefined for audio tracks and captions. This allowed a unique id to be set in https://github.com/video-dev/hls.js/blob/master/src/loader/playlist-loader.js#L343. When changed to 0, it resulted in all audio tracks having the id of 0, which caused the `audioStreamController` to fail to signal the level switch, which caused AAC remuxing to break.
- Trying to access …

v0.11.0 regression fixes

---

.travis.yml

When `draft: true` is set, incorrect commit/tag information is sent to
Github. Override tag/target fields for correct behavior.
Ref. travis-ci/travis-ci#9852
workaround a travis bug so that when the release is created it is assigned to the tag.

add work around tagging issue in Travis CI deployment

---

README.md
demo/basic-usage.html
demo/index.html

Update the links in the readme to the new location of hosted api docs and update the demo to use the build from the repo instead of the cdn.
The one breaking thing in here is that `?canary=true` no longer works on the demo, which instead will be located at "http://video-dev.github.io/hls.js/latest/demo". "http://video-dev.github.io/hls.js/latest/demo" will still exist and point to the demo for the latest tag.
Also the api docs will now be at http://video-dev.github.io/hls.js/latest/api-docs instead of http://video-dev.github.io/hls.js/docs/html

Update readme and demo for gh pages

---

package.json
src/hls.js
src/polyfills/number.js
webpack.config.js

* Make the Number.isFinite polyfill be injected in local scopes where it is used (or where Number is used in fact)
* The polyfill adresses Number as a whole (but that is just a conceptual detail, doesn't change the result)
* Remove the String endsWith polyfill that was modifying globals (we don't need it anywhere)
We don't want to touch global env with our bundle

Inject polyfills via webpack provide (not modifying global env)

---

src/loader/key-loader.js

Set maxRetry to 0 in `key-loader`.
Instead of retrying the same key on the same variant multiple times, key-loader will trigger an error and rely on stream-controller to handle retry logic. This will also align retry logic with `fragment-loader`
If someone can provide a test stream with different keys across variants
Solve #1836.

key-loader: set maxRetry to 0

---

src/controller/timeline-controller.js
tests/unit/controller/timeline-controller.js

enable reusing text tracks even if they are not in same order between manifests
If two manifests have same text tracks in different order then the current logic, which is index based, will not be able to reuse the text tracks
closes #1868

fix(timeline-controller): reuse text tracks when not in same order

---

src/loader/m3u8-parser.js
tests/unit/loader/playlist-loader.js

Allow fragment files to contain spaces
Safari allows spaces in their fragment files, many encoders all them. They are expected to work.
Perhaps if there is a space at the end of the .ts fragment, it would be included. I'm not certain if that is handled.
#1439 
- [x ] new unit / functional tests have been added (whenever applicable)

fix-1439: allow spaces in fragment files

---

src/loader/playlist-loader.js

fix playback of streams for which fragment URL looks like mp4 fragment (ie match with this [regex](https://github.com/video-dev/hls.js/blob/d6d83b1066e25c6925bfef308d418bc4beb42a32/src/loader/m3u8-parser.js#L30)), but which are not mp4
related to #1919
regression introduced in [v0.9.0](https://github.com/video-dev/hls.js/releases/tag/v0.9.0)

playlist-loader: handle mp4 streams without sidx ranges in map

---

src/controller/buffer-controller.js

Fix the issue with stuck stream on chrome while seeking. This fix augments this commit https://github.com/nochev/hls.js/commit/2737c71b8bf7377f01be69cce14c5594de6e8e2d. Essentially, player gets stuck when it goes not to the `onSBUpdateEnd` method but to the first branch in `if` statement (https://github.com/video-dev/hls.js/blob/master/src/controller/buffer-controller.js#L478) when an abort error happens in chrome (https://github.com/video-dev/hls.js/blob/master/src/controller/buffer-controller.js#L70). As a result it doesn't pickup `this.audioTimestampOffset` and gets stuck
We are using hls.js and cannot ship features in production without chrome working with `audio/mpeg` streams while seeking. Also there are issues related to this problem
#1924 also some issues with seeking opened may …

fix chrome stream hang up when seeking

---

docs/design.md

ewma-bandwidth-estimator.js is moved to utils folder, the current link is broken.
no.
no.

Fix ewma-bandwidth-estimator.js link in design doc

---

README.md
demo/index.html

Follow on from https://github.com/video-dev/hls.js/pull/1940
The change there wouldn't work when the demo was accessed on `/latest`, `/stable`, or `/<commit hash>`
Also `/demo` only existed by mistake. I removed it 37246e6d51eb88a6c91b46aee5c759019d6a5026
If people are actually loading the demo on `/demo` we will need to add a redirect

fix api link on demo page

---

index.html

^
so that by default people see the docs for the latest stable release

redirect to /stable instead of /latest

---

docs/API.md
src/controller/buffer-controller.js
tests/unit/controller/buffer-controller.js

- Only schedule flushes on `LEVEL_UPDATED` events
- Refactor
- Improve unit tests
In the interest of time (and better code) I refactored https://github.com/video-dev/hls.js/pull/1845 to match Hls.js' design patterns.
* There already exists code to flush arbitrary buffer ranges. It is preferable to use this code because it handles edge cases around flushing sourcebuffers, and ensures that flushes are scheduled for the future if blocked by a current append operation.
* Always flushing on sourcebuffer update end harms performance - that event can be triggered several times per second. It's not critical to *immediately* clear the back buffer on append; the `LEVEL_UPDATED` event triggers frequently enough for this use case.
* There were some minor nitpicks over code style. In the interest of …

Refactor backbuffer cleanup PR

---

src/event-handler.js

So that browsers which do not support Sets (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set#Browser_compatibility) do not throw an exception & prevent Hls.js from functioning. Converting Set to a plain object is preferable to a polyfill because it results in less code - polyfills have a price.
No
https://github.com/video-dev/hls.js/issues/1859

Remove es6 set to fix compatibility issues in old browsers

---

src/loader/playlist-loader.js

Restore `response` in MANIFEST_LOAD_ERROR/LEVEL_LOAD_ERROR/AUDIO_TRACK_LOAD_ERROR event data.
`response` was accidentally removed in 5b25906bf7a18ee1df3d6fea3b875e94971b9060. The API docs state that it should contain the status code and status text from the XHR response.
No.

Restore `response` data in playlist loader error events

---

src/controller/stream-controller.js
tests/unit/controller/stream-controller.js

Check what the SourceBuffer reports as start time for the first fragment appended and If within the threshold of maxBufferHole, adjust this.startPosition for _seekToStartPos. This happens on the first tick in checkBuffer. 
Fixes an issue with Edge where it will not start (when autoStartLoad is false) if seek at start position is only set to the value we calculate for the live + latency position. 
E.g.
media seeked to 6.000 VS media seeking to 6.014
In v8.9 and previously, hls.js looked at buffer.start value on first tick in checkBuffer method,  but that was lost in subsequent releases.  
With this PR,  it restores it in the new code base to get live streams on Edge with non zero pts playing again.  
Would like to know if there was a solid reason for removing this in 0.9.0 in order to …

Fix for issue 1978.  

---

src/controller/level-helper.js
src/controller/stream-controller.js
src/remux/mp4-remuxer.js
tests/test-streams.js
tests/unit/controller/level-helper.js
tests/unit/utils/discontinuities.js

- In the case that a/v PTS values intersect:
- Set frag.startPTS to the min of audio/video startPTS values
- Set frag.endPTS to the max of audio/video endPTS values
- If the frag is the last of a VOD stream, set the end PTS/DTS to the max end PTS/DTS
- Otherwise, the start/end PTS values will be determined by the existing behavior (min start/max end)
- Always skip startup gaps, regardless of size @dsparacio 
- Add tests and comments
According to the MSE spec, the start/end time for a buffered range is the intersection of the sourceBuffer start/end times for that range (https://www.w3.org/TR/media-source/#htmlmediaelement-extensions), and not the min of the starts and max of the ends as we have previously assumed. This assumption causes Hls.js' internal representation of a fragments …

Calculate fragment start/end based on the intersection of audio/video PTS

---

src/controller/buffer-controller.js
src/controller/cap-level-controller.js
src/controller/level-controller.js
tests/mocks/hls.mock.js
tests/test-streams.js
tests/unit/controller/buffer-controller.js
tests/unit/controller/cap-level-controller.js
tests/unit/controller/level-controller.js

- Change the definition of `altAudio` in the `MANIFEST_PARSED` event to reflect whether any audioTracks contain a URI
- Calculate the number of sourceBuffers based solely on whether altAudio is signaled or not. There are two expected sourceBuffers with altAudio, and 1 otherwise
- Remove assumption in `cap-level-controller` which starts capping if levels and altAudio are signaled
- Refactor, add unit tests, and test streams
- This reflects how Hls.js actually determines whether to load a track via the `stream-controller`. https://github.com/video-dev/hls.js/blob/master/src/controller/stream-controller.js#L1161-L1162
- Even if there are levels and alt audio signaled, the stream can still be audio-only. Hls.js must not cap if there is no video. If video *is* signaled, capping will start in …

Refactor sourceBuffer estimation to reflect how Hls.js intends to use the parsed manifest

---

src/controller/buffer-controller.js
src/controller/timeline-controller.js
tests/unit/controller/buffer-controller.js

- Create sourceBuffers if the max of 2 tracks has been reached, regardless of buffer codec events received
- Replace `Object.values` with `[].slice.call` when checking textTrack reuse
- So that if a stream throws a `FRAG_PARSING_ERROR` during demuxing of the first segment (and therefore will not emit a BUFFER_CODEC event) is allowed to play if the expected number of tracks has already been received. See `//playertest.longtailvideo.com/hls/NBCR_Production_-_OCS/809/468/master.m3u8` for a test case.
- There seems to be a bug with ChromeHeadless/Ubuntu's `Object.values` function when called on the textTracks array-like object. The call always returns `[]`, causing tracks to never be reused. `[].slice.call` is also preferable because we don't have to polyfill it, resulting in less code.
No …

Fix 0.11.1 Regressions

---

src/controller/stream-controller.js
src/demux/demuxer.js
src/remux/mp4-remuxer.js
tests/unit/controller/stream-controller.js
tests/unit/demuxer/demuxer.js

- Normalize PTS relative to `initPTS` instead of `initDTS`
- Determine contiguity according to `initPTS`
- Provide `startPTS` instead of `startDTS` as a timeoffset when available
- Remove fix provided in https://github.com/video-dev/hls.js/pull/1992
So that all streams begin at their intended start position. This PR ensures that audio/video elementary streams begin at the same time by fixing starting video at `initPTS` , and flushing audio to video by inserting silent audio or dropping extra frames. Since all video now starts at the expected start time, we don't need to set `this.startPosition = buffered.start(0)`.
@dsparacio Tomorrow I'll do some testing on Edge to make sure that the bug you fixed is still OK.
Looking back through the annotations, the original reason for this work was to …

Remux according to initial PTS so that streams start at 0

---

src/utils/webvtt-parser.js

Live streams which start with an initial negative PTS do not show cues.
Test stream: http://playertest.longtailvideo.com/adaptive/live-webvtt/webvttTest/playlist.m3u8
No. I know we have an open issue with regards to PTS wrapping; however, I believe the best solution here is to revert to known working code instead of attempting to address it in a hotfix.
0.12.0 regression

Revert PTS wrapping code which produces incorrect cue times

---

src/controller/subtitle-stream-controller.js
src/utils/webvtt-parser.js

-  Subtracts the timeOffset applied in the demuxer from the syncPTS before determining if it has wrapped
- Fixed a typo accessing the frag buffered array, which caused vtt segments to load too late & miss cues
In the mp4 remuxer, we apply a timeOffset to PTS:
`initPTS = Math.min(initPTS, videoSamples[0].pts - inputTimeScale * timeOffset);`
Which may make the initPTS negative after a discontinuity. The webvtt parser always assumes that a negativePTS is one which has wrapped around; however, this is not always true. By applying the original offset we can correctly apply the wrapping value.
Test streams:
https://mtoczko.github.io/hls-test-streams/test-vtt/playlist.m3u8
http://playertest.longtailvideo.com/adaptive/live-webvtt/webvttTest/playlist.m3u8
I didn't pass the time base to the initPTS …

Check if PTS has wrapped after applying PTS time offset

---

src/controller/timeline-controller.js

In a stream with no discontinuities, the `vttCCs` array for `cc 0` is not created until the time subtitles are enabled. This causes `vttCCs[0].start` to be set to the current time, which causes cue times to be doubled; the start for `cc 0` is always 0 and not the cue's start time. Therefore we should initialize this property to 0 from the start.
Kind of hacky, but I think it's fine for a hotfix.
#2046

Intialize vttCCs map with cc 0

---

scripts/build-deploy-netlify.sh

It's better than using the tag because it actually matches what's deployed

use the version from package.json when deploying

---

package-lock.json
package.json
webpack.config.js

This fixes an issue where light-dist / light defined their own resolve property causing them to not get the base config resolve for extensions, etc.
Includes a few minor lint fixes that popped in my editor as well.
Before:
After:

Update light build targets to include Typescript extensions

---

docs/API.md

In the explanations of how abrBandWidthFactor and abrBandWidthUpFactor work the example calculation uses less than, but it should be greater than(?).
Currently the docs have: `abrBandWidthUpFactor * bandwidth average < level.bitrate`
Should it should read `abrBandWidthUpFactor * bandwidth average > level.bitrate`?
The abr-controller has it as: `adjustedbw > bitrate` 
https://github.com/video-dev/hls.js/blob/master/src/controller/abr-controller.js#L303

Docs: abrBandWidthFactor and abrBandWidthUpFactor

---

karma.conf.js
package-lock.json
package.json
src/controller/buffer-controller.ts
src/types/segment.ts
src/types/track.ts
src/utils/logger.js
tests/unit/controller/buffer-controller.js
tsconfig.json

This adds TypeScript definitions to the buffer controller to help migrate the internals of hls.js over to TypeScript.
I wasn't sure what controller or file should "own" the types for Segment / Track types so I created a types folder and added them there for the purpose of moving forward. If a better location or file for ownership is known can move it there.
One additional change I made was I changed the functions that were bound as event listeners to become instance methods using the `name = () => { }` definition style, rather than bind the prototype function to the instance and keep track of the reference. This is why variables such as `this.onmse` were removed and not defined.

Buffer Controller TypeScript

---

docs/API.md
src/hls.js
tests/unit/controller/abr-controller.js
tests/unit/hls.js

create getter for HLS to extract bandwidth estimate
To load most appropriate chunks based on bandwidth as it's the most accurate estimate
No
https://github.com/video-dev/hls.js/issues/1904

Make bandwidth estimate public API

---

tests/unit/utils/buffer-helper.js

Add more tests for BufferHelper.
In order to increase test coverage, here are the results:
before:
```bash
--------------------------------|----------|----------|----------|----------|----------------|
File                            |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
--------------------------------|----------|----------|----------|----------|----------------|
All files                       |    28.29 |    21.71 |    39.84 |    28.24 |                |
src/utils                      |    26.47 |    20.28 |    27.57 |    26.37 |                |
buffer-helper.js              |    92.68 |    77.27 |      100 |     92.5 |       64,80,81 |
--------------------------------|----------|----------|----------|----------|----------------|
```
after:
```bash …
```

Increase BufferHelper test coverage to 100%

---

src/demux/adts.js
tests/unit/demuxer/adts.js

Add tests for adts.js.
There is no test case for adts.js, this PR will change its test coverage from:
```bash
--------------------------------|----------|----------|----------|----------|----------------|
File                            |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
--------------------------------|----------|----------|----------|----------|----------------|
All files                       |    28.29 |    21.71 |    39.84 |    28.24 |                |
src/demux                      |     6.18 |     3.96 |     5.51 |     6.29 |                |
aacdemuxer.js                 |        0 |        0 |        0 |        0 |... 70,71,74,78 |
adts.js                       |        0 |        0 |        0 |        0 |... 231,233,236 | …
```

Increase adts.js test coverage to 100%

---

docs/API.md
src/utils/ewma-bandwidth-estimator.js

fix docs for `hls.bandwidthEstimate`
to understand what unit is used for `bandwidth`
No
[PR](https://github.com/video-dev/hls.js/pull/2086) fix

Choose bitrate in Bps

---

.eslintrc.js
src/controller/eme-controller.ts

This adds TypeScript definitions to the eme controller to help migrate the internals of hls.js over to TypeScript.
I added the browser environment to .eslintrc so that XMLHttpRequest is defined globally because there was a fight between eslint and typescript. TypeScript doesn't define XMLHttpRequest off the `Window` type. It defines it as a global interface that can be used.
I left the `onManifestParsed` event handler untyped because I know @johnBartos is planning on overhauling the manifest parsing types so this can wait to be typed when those are in master.
The other double-check part is a change in `_attemptKeySystemAccess`. The function `getSupportedMediaKeySystemConfigurations` will never return null. It either throws or returns a keysystem config. So the `if (!` never would be …

EME Controller TypeScript

---

src/loader/m3u8-parser.js

This fixes some lint warnings. 
I did this separately from the TS conversion so that the changes required for doing TypeScript conversion will be limited to adding typing information.
No.
None. Works toward TS migration

Fix lint warnings in m3u8-parser.js in prep for TS conversion.

---

src/utils/vttcue.js

... remove IE8 specific handling in VTT/Cue related code. It's essentially dead because we don't support Internet Explorer 8, minimum supported version is 11.
No need for it to stay within the distributable bundle
`hls.min.js` before:
`225,970` bytes 
`hls.min.js` after:
`225,822` bytes
Total: `-148` bytes ⬇️ 
Not that I'm aware of
None in particular
- ~[ ] new unit / functional tests have been added (whenever applicable)~ N/A
- ~[ ] API or design changes are documented in API.md~ N/A

(misc) Removing IE8-specific (dead) vtt/cue code

---

src/event-handler.ts

This adds simple type definitions to the event handler base class. This makes it so all classes that expand upon this base class can be typed before having to go through and type all the event data.
`npm run type-check` fails without as `this.hls` is undefined for any classes that extend.
Don't worry too much about the `any` types here. These will be piece-mealed out for better definitions as the events class becomes incrementally more typed.

Basic typescript of event handler.

---

src/demux/adts.js
src/demux/mpegaudio.js
src/demux/tsdemuxer.js
src/remux/mp4-remuxer.js
tests/unit/demuxer/adts.js

- recompute audio mdat size by summing the size of all  audio samples, instead of trusting track.len
- get rid of track.len
- this fixes the RangeError exception
we might want to clone the problematic stream and add it to the test suite. if fine with the owner. thought ?
#2063 
- [?] new unit / functional tests have been added (whenever applicable)

mp4-remuxer / remuxAudio() : recompute mdatSize / dont rely on audioTrack.len

---

src/controller/audio-stream-controller.js
src/controller/base-stream-controller.js
src/controller/fragment-tracker.js
src/controller/level-controller.js
src/controller/level-helper.js
src/controller/stream-controller.js
src/controller/subtitle-stream-controller.js
src/controller/subtitle-track-controller.js
src/controller/timeline-controller.js
src/hls.js
tests/unit/controller/level-helper.js
tests/unit/controller/subtitle-stream-controller.js
tests/unit/controller/subtitle-track-controller.js

- Start and stop subtitle loading in sync with `startLoad()/stopLoad()` API calls
- Compute sliding & merge subtitle playlists during live playback
- Fix shared references between `subtitle-track-controller` and `subtitle-stream-controller`
- Refactoring:
- Extend `subtitle-stream-controller` from `base-stream-controller`
- Move more shared logic into `base-stream-controller`
- Move live reload interval calculation into a shared function & import into `subtitle-track-controller`
- Remove the `trackId` from subtitle fragments, and refer to them by their `level` property
- Several other minor refactorings (flipped conditionals, destructuring args, organizing functions)
- Add a bunch of unit tests
Live subtitle playback is not functioning correctly - on first glance, it appears that sliding …

Implement live VTT subtitle loading

---

demo/metrics.html

This utilizes the DOM APIs to utilize user data, this prevents innerHTML or jQuery html issues that enable XSS as found in #2161.
Some could craft a metrics page and pass it to create XSS. It was worse because it was jsonpack'd so it wouldn't even look out of the ordinary until the XSS had been performed.
Closes #2161.

Fix XSS on metrics page

---

src/controller/stream-controller.js

Fix the calculation for `maxBufLen`
The code doesn't seem to match the comment. If `don't buffer more than 60 MB and more than 30s` is the wanted behavior, then here it should be `min`.
The expected behavior should be double checked.

stream-controller: fix maxBufLen calculation

---

scripts/deploy-netlify.sh

Only deploy the latest build when we are actually on the most recent master commit
Otherwise if we tag something which is not the latest commit, we still overwrite the latest build.

only deploy hlsjs-latest when we are on newest master commit

---

src/controller/fragment-tracker.js

This PR will fix error on destroying the instance of `Hls`.
The following is error detail (hls.js@0.12.3).
1. Visit [hls.js demo page](https://hls-js.netlify.com/demo/)
1. Change playlist file to [Shaka-packager Widevine DRM (EME) HLS-fMP4 - Angel One Demo](https://storage.googleapis.com/shaka-demo-assets/angel-one-widevine-hls/hls.m3u8)
1. Change playlist file to [Big Buck Bunny - adaptive qualities](https://video-dev.github.io/streams/x36xhzz/x36xhzz.m3u8)
This PR needed to change playlist file.

Fixed error on destroying the instance of `Hls`

---

package-lock.json
package.json

update [webworkify-webpack](https://github.com/borisirota/webworkify-webpack) to 2.1.5 which fixes the issue which is causing hls.js to crash when used with create-react-app.
So that hls.js works with create-react-app.
fixes #2064

update webworkify-webpack to 2.1.5

---

src/controller/audio-stream-controller.js
src/controller/stream-controller.js

Init segment shouldn't be considered as a requested start fragment.
We are preparing to switch some streams from HLS TS to HLS MP4 (to use with Widevine/Playready). While doing this I noticed that hls.js didn't start LIVE streams with first video segment (0.m4s) but instead requested the last video segment in playlist first (2.m4s). After some debugging I found out that due to init segment being requested first, the `this.startFragRequested = true;` flag has been set. This caused the `_ensureFragmentAtLivePoint ` trying to find the correct fragment without having any previous fragment as reference. By not setting the `startFragRequested` for initSegment this issue is fixed.
Does it break anything?
Wrong start video fragment requested in LIVE MP4 HLS streams.

Init segment should not be treated as start segment

---

src/controller/buffer-controller.ts
tests/unit/controller/buffer-controller.js

Make it so buffer flush events without a type flush both audio and video.
This makes it act like the expected behaviour from a comment in the stream controller stating that a event without type flushes both. See the linked issue for related code.
See issue.
Are there any other unit tests that should be added?
Resolves #2143.

GH-2143: Fix flush buffer not accepting undefined types 

---

docs/API.md

Fix incorrect information in the "default config object" shown in API.md
To fix incorrect information in the documentation, differences were found by looking at the default config in the source code: https://github.com/video-dev/hls.js/blob/master/src/config.js#L23
Nope, but another pass at the default values would be welcome incase I missed something
None in particular
- ~[ ] new unit / functional tests have been added (whenever applicable)~ N/A

(misc) fixing incorrect default config values in API.md

---

demo/main.js

Fix a persistence issue in the demo page, where a config might not become persisted under certain conditions.
If loading the demo page with a persisted config, effectively "restoring" that config, the demo page isn't implicitly enabling persistence - even though the persistence user input checkbox is being `checked`
This effectively made persistence work only on a clean slate (e.g. no pre-existing persisted config)
Steps to reproduce the issue:
1. Persist a config. For clarity, add some custom fields to the JSON prior to applying
2. Reload the page. Observe the persisted config was restored as expected, and that the persist user input checkbox is `checked`
3. Change the config JSON in some way (but otherwise be syntactically valid)
4. Apply the changed config, observe that the config does …

(misc) Fix - Demo hls.js config persistence issue

---

src/controller/audio-stream-controller.js

Fix AudioStreamController for streams with subtitles if media is not attached
Fixes audioSwitch and logging in AudioStreamController
Reproduce example:
```html
<video id="video" controls></video>
<button onclick="attach()">Attach media</button>
<script>
var video = document.getElementById('video');
var hls = new Hls({
startFragPrefetch: true,
debug: true,
});
// attach();
hls.loadSource('https://faked-multiple-audio-tracks-qdyvgxaayi.now.sh/index.m3u8');
hls.startLoad();
function attach () {
hls.attachMedia(video);
}
</script>
```
on master branch stream will not play after attach

fix AudioStreamController when media is not attached

---

.github/stale.yml

So that we give developers more time to respond to inquires, and so that we don't close questions which have not been answered

Bump stale time to close from 7 days to 60, add more exempt labels

---

scripts/deploy-netlify.sh

so that the sites are created under the new team that has the open source account policy
https://open-api.netlify.com/#/default/createSiteInTeam

create netlify sites under new team

---

package-lock.json
src/demux/id3.js
tests/unit/demuxer/id3.js

Enable null delimiter parsing on TXXX labels, per http://id3.org/id3v2.4.0-frames section 4.2.6
This is achieved by passing `true` to the already existing `existOnNull` parameter of `utf8ArrayToStr(array, exitOnNull = false)` if a TXXX field is detected.
ID3 TXXX parsing was broken, merging info and description fields
Shouldn't be, this is a one line change. 
#2215

fix parsing of TXXX ID3 frames

---

src/utils/cues.js

Remove IMO unnecessary cue position alignment.
Cues are wrongly positioned in current Firefox. Why we use const (50) for Firefox?
Yes, if we keep backward compatibility, maybe this is still needed on older Firefoxes.

Remove cue position alignment by adding 50 for Firefox

---

src/controller/buffer-controller.ts
src/types/track.ts

Fix rolling dvr cmaf streams
On conversion to typescript this.tracks was passed to buffer created event which has less properties than the actual tracks. One property that was missing was track.id which is necessary in onBufferCreated method in stream-controller.js in order to find the main track which is needed to scheduled main fragment loading. This was causing the rolling dvr cmaf stream to not seek to the live point and play the video.
#2265

Add id prop back to track in buffer controler

---

docs/release-process.md
scripts/get-version-tag.js
scripts/set-package-version.js
scripts/travis.sh
scripts/version-parser.js

Update the deployment scripts so that pushing a preprelase git tag will trigger an npm publish on a separate tag automatically, similarly to how the stable releases work.
It makes it possible for prereleases to go through the same build process and publish in a clean environment as the stable ones do. It would also create a draft github release that could be published and marked as a prerelease.
After this we could consider removing publishing rights from all users except the CI user to help [protect against malicious publishes](https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident).
- `git tag -a -v1.2.3` will result in `1.2.3` being published with the `latest` npm tag.
- `git tag -a -v1.2.3-beta` will result in `1.2.3-beta` being published with the `beta` npm …

support preprelease publishes from git tag

---

src/event-handler.ts
src/task-loop.ts

Convert `TaskLoop` to TypeScript
#2070
I changed `setTimeout` to `self.setTimeout`, `clearTimeout` to `self.clearTimeout` and the same for `setInterval` and `clearInterval`.
This made typescript use the correct type, and using `self` instead of `window` means it should also work in a worker.
https://stackoverflow.com/a/11237259
>While the main thread window self points to the Window object, in worker threads self points to a separate WorkerGlobalScope object.
I wonder why we don't use `self` everywhere in place of `window`, and then we wouldn't need `getSelfScope()` 🤔

convert TaskLoop to TypeScript

---

src/controller/buffer-controller.ts
src/demux/demuxer.js
src/is-supported.ts
src/utils/mediasource-helper.ts

To prevent exceptions from being thrown when Hls.js is loaded into envs without MSE support (i.e. iOS)
Addresses feedback in https://github.com/video-dev/hls.js/pull/2263
https://github.com/video-dev/hls.js/issues/2262

Guard against undefined errors when accessing MediaSource

---

src/controller/eme-controller.ts
src/errors.ts
src/utils/cea-608-parser.ts

- Guard against null `initData`, and add new error details for missing init data
- Apply the non-null operator to `this.cueStartTime`
- I don't know the side effects of defaulting this value, so I think this is the best option given the limited scope of the PR
So that our build passes without TS errors
Sure
N/A

Fix TS errors

---

scripts/deploy-netlify.sh

Handle `git rev-parse master` failing
Without this the pipeline fails when publishing a prerelease. It was failing because it was never fetched. It looks like when using `--branch` with `git fetch` git only pulls the reference to that tag/branch.
Now we explicitly fetch the pointer to `origin/master`.

ensure we fetch master before getting the latest commit

---

src/controller/fragment-finders.ts
src/loader/fragment.ts
tests/unit/loader/playlist-loader.js

~Seperate fragment class from Initialization Segments.~
~Some code changes that will likely conflict with the open m3u8-parser PR, so one will have to be updated after one is merged.~
Just added types to fragment-finders, and instead type-asserted `frag.sn` to number.
Progress towards #2070
~Separation of Initialization Segments from Fragments.~
This broke some of the MP4 demuxing the code path in the demuxer-worker, so I pulled it out.
N/A

Fragment Finders Typescriptify

---

src/remux/mp4-remuxer.js
src/utils/timescale-conversion.ts

Remove a misplaced scale normalization in a timestamp delta compuation in the mp4-remuxer when checking for sample gaps and overlapping.
Currently we will simply compute the wrong value which obviously is an issue.
https://github.com/video-dev/hls.js/issues/2336

Fix for issue #2336: Remove misplaced timescale normalizing in delta computation

---

src/loader/key-loader.ts

Revert the conditional which decides whether to return the cached key to it's pre-TS state. The current logic causes the cached key to be returned for segments of different levels, which causes AES decryption to fail.
So that AES decryption works
No

Fix bad conditional in key loader causing the wrong key to be loaded

---

package.json
scripts/travis.sh

Make the webpack output less verbose on CI and attempt to build the docs on travis.
Netlify has been failing sometimes and one of the reasons (docs failing to build) wasn't obvious because the webpack output took so long that netlify never shipped the end of the logs before it was terminated, which contained the error from `npm run docs`.
If there is an error building docs again it should now be visible on netlify, but also the build job on travis should fail.

Less verbose webpack output on CI, and attempt to build docs on travis

---

src/controller/buffer-controller.ts
tests/test-streams.js

Log an error rather than throwing an exception when `flushLiveBackBuffer` is called for a live stream without media attached.
Fixes an edge-case where the exception prevents a live stream starting.
Fixes #2333
- N/A new unit / functional tests have been added (whenever applicable)
- N/A API or design changes are documented in API.md

Bugfix: Uncaught exception trying to flush back buffer when starting live stream

---

scripts/travis.sh

Use `npm ci` instead of `npm install` on CI.
This is quicker, but also validates that the package-lock is in sync with the package.json
Without this anything in the package.json that is out of sync with the package-lock gets silently updated and the integrity is not checked

use `npm ci` instead of `npm install`

---

src/controller/audio-stream-controller.js
src/controller/buffer-controller.ts
src/controller/stream-controller.js
src/controller/subtitle-stream-controller.js
src/controller/subtitle-track-controller.js
tests/unit/controller/subtitle-stream-controller.js

Fix the detach-attach workflow when using a media with alternative audio tracks
On re-attch the context of altAudio is not saved in buffer control so it doesn't know to create two source buffers.
Also, in context of stream controller it doesn't reset the `altAudio` flag.
I also noticed that stream controller is reloading the entire frags it has in `fragmentTracker` and it seems it needs to be reset on detach, otherwise there's a very long start delay where unnecessary buffering occurs. Unfortunately I'm not too sure what are the side effects.
I think there's a bigger issue here(and some smaller ones).
Big issue:
The logic seems problematic in general.
For stream with altAudio we first get the the main init segment in `stream-controller` and it will usually contain muxed video and audio. …

fix: calling detatchMedia() followed by attachMedia() causes audio to not play

---

src/config.ts
src/controller/audio-stream-controller.ts
src/controller/audio-track-controller.ts
src/controller/base-stream-controller.ts
src/controller/level-controller.ts
src/controller/stream-controller.ts
src/crypt/aes-decryptor.ts
src/crypt/decrypter.ts
src/demux/base-audio-demuxer.ts
src/demux/transmuxer-worker.ts
src/demux/transmuxer.ts
src/demux/tsdemuxer.ts
src/hls.ts
src/loader/fragment-loader.ts
src/performance/performance-monitor.ts
src/utils/fetch-loader.ts
src/utils/logger.js
src/utils/mp4-tools.ts

- Push streamed data to the transmuter in roughly one second payloads based on level bitrate
- Prevent the transmux-worker from posting empty "transmuxComplete" messages (Don't create empty ArrayBuffers)
- Cleanup and optimize logging
- Only log frag loading message when fragment changes
- Remove performance monitor logger (this can be implemented externally)
- Bind console method in `consolePrintFn` for direct logging 
- Reduce the amount empty array buffers created and prevent unnecessary copying
- Load audio track on level loading event rather than level loaded (tracks load at the same time)
- Remove `STARTING` state which was only used in the audio stream controller to wait a tick
- Load first audio fragment while waiting for initPTS (similar to the solution in master using …

Performance improvements for v1.0

---

package.json
scripts/precommit.sh
scripts/travis.sh
src/controller/audio-track-controller.js
src/controller/timeline-controller.ts
src/loader/m3u8-parser.ts
tests/unit/controller/ewma-bandwidth-estimator.js

- Add "sanity-check" package script
- Run docs in travis build ~and precommit~
- Fix type check errors
- Fix bandwidth estimator tests that fail on Mac desktop because of float precision 
These changes are to help ensure we don't break netlify builds when making changes, and are necessary to generate a release with a demo page.
The sanity-check target is one I run a lot locally so I made a shortcut for it.
These changes have already been made in feature/v1.0.0.
- N/A new unit / functional tests have been added (whenever applicable)
- N/A API or design changes are documented in API.md

Fix netlify build in master and add build checks

---

.eslintrc.js
src/controller/level-controller.ts
src/remux/mp4-remuxer.ts
src/remux/passthrough-remuxer.ts
tests/unit/controller/buffer-operation-queue.ts

Prevent `<string>` style type assertion (not to be confused with generic type definitions) in the code.
Rob mentioned that these type assertions were making the docs fail.
`as any as Type` - If you want to have a partial type for "quick assertions" like with unit tests, this is the way you do it, you don't need a eslint disable rule.

Eslint type assertion rule

---

.github/stale.yml

Adds Needs Triage to the exempt list for stale tickets.
Too many tickets were being closed that had streams that could be used to make hls.js more bullet-proof.

Adds Needs Triage to be a staleness exempt label.

---

src/controller/subtitle-track-controller.js

The timeline-controller previously did this but the subtitle controller
did not. What this PR does is clear subtitle cues during the process of
detaching the media, and also disables subtitle tracks on the video
element it is detached from.
This fixes odd behaviour I noticed on the demo page where when switching
between Angel-One and Multiple Text Tracks content. If you detach and
reattach to the same video element between two pieces of content that do
not share text tracks, the track elements from the previous content will
be visible in the default video controls. By setting subtitleTrack to -1
we trigger our internal setter logic which goes through and disables all
tracks which hides them from user-agent controls.
Additionally, before disabling them, clearing the cues from the text …

Cleaning Text Tracks cues on media detachment.

---

src/controller/buffer-controller.ts
src/controller/id3-track-controller.js
src/events.js
src/utils/texttrack-utils.ts

Implement flushing of the TextTrackCueList in accordance with the liveBackBufferLength config option, for live mode only. 
This means that the id3 cues relevant to the current live buffer will still be maintained. However, we avoid the continuous growth that eventually consumes all the memory.
VTT cues are not cleaned up until a stream is destroyed.
Long Live streams lead to a memory leak, as the TextTrackList continues growing with Cues until the browser runs out of memory and becomes un-responsive.

VTT cues are never cleaned up. Fix memory leak in live.

---

src/controller/stream-controller.js

when the video is paused the currentTime should not be updated. 
fixes #2417
and by that will not update the current time of the video if it paused
#2417
I am only wondering whether the `!medi.paused` should be before, i.e with the line 
```js
if (bufferEnd < Math.max(start - config.maxFragLookUpTolerance, end - maxLatency)) {
```
#2417

fix: consider paused state

---

demo/main.js
src/controller/buffer-controller.ts
src/controller/id3-track-controller.js

Follow up on https://github.com/video-dev/hls.js/pull/2309 by @JordanPawlett with a few enhancements:
1. Set `liveBackBufferLength` to 15 minutes in the demo (the default is `Infinity`)
1. Only emit `LIVE_BACK_BUFFER_REACHED` when `SourceBuffer.remove` does not throw
1. Optimize id3-track-controller `onLiveBackBufferReached`
1. Test back buffer removal in the demo by default.
1. Only fire `LIVE_BACK_BUFFER_REACHED` when the back buffer actually is flushed (if the method throws the last sourceBuffer request is still being processed)
1. Reduce code complexity 
1. To introduce the new event in 0.13.0 rather than a later patch
We don't have any tests for `liveBackBufferLength`. Adding it to the demo is just a stop-gap to provide some coverage for folks testing live streams in the demo app. …

Follow up clear-vtt-cues-with-live-back-buffer-length

---

src/config.ts
src/controller/audio-track-controller.js
src/controller/gap-controller.js
src/controller/stream-controller.js
tests/test-streams.js
tests/unit/controller/gap-controller.js

* Fix the previous logic to actually work for startup-stalls of livestreams (see explanations given in https://github.com/video-dev/hls.js/pull/2290)
* Design logic to make sense, we will provide comments inline the diff to explain this in more detail (see also some explanations given in first shot PR at these issues here https://github.com/video-dev/hls.js/pull/2290)
* Use native HTML5 media-element API `waiting` and `stalled` events additionnaly for stall detection (covering cases that will otherwise not be caught)
* EDIT: Fix false-positive buffer-stalled error on *all* seeks into unbuffered region in current version
* EDIT: Adds the `hasPlayed` flag to properly handle startup cases and isolate them properly from mid-play paused case (where the browser might not indicate the pause …

Fix for issue #2323: gap-controller: fix logic and improve behavior in edge cases

---

src/config.ts
src/controller/eme-controller.ts
src/controller/gap-controller.js
src/controller/stream-controller.js
src/controller/subtitle-stream-controller.js
src/utils/buffer-helper.ts
tests/functional/auto/setup.js
tests/test-streams.js
tests/unit/controller/gap-controller.js

Align the gap-controller with changes from https://github.com/video-dev/hls.js/pull/2359 and https://github.com/video-dev/hls.js/pull/2370 (https://github.com/video-dev/hls.js/compare/68fb4010c8c8632f9abeaf03cdaded0acb27fc74...c7c0e132e0bbead453ff53dad5928e8f77d79fa8)
1. Jump start gaps (fixes).
2. Do not report stalls before playback has started or when seeking.
https://playertest.longtailvideo.com/adaptive/short/short.m3u8 (start gap and partial)
https://playertest.longtailvideo.com/adaptive/sintel_aes/playlist.m3u8
https://dapian.video-yongjiu.com/20190901/9943_6699ca5d/index.m3u8 (Safari)
Fixes #2323
Fixes #2381
Fixes #2436

Follow up gap controller fixes

---

src/demux/tsdemuxer.js

Prevent `RangeError` exception when parsing incomplete PES.
Remove exceptions in the critical path.
I'm sure if the issue is that the PES causing this are incomplete, empty or simply mishandled further up in the TS demuxer. I think the issue is related to #2109 and will look into whether those changes would fill in the missing data that results in this case.
Fixes #2415
Relates to #2109

Prevent RangeError exception when parsing incomplete PES

---

src/controller/stream-controller.js

Prevent seeking to 0 when startPosition is -1
Unnecessary seeking on start will result in fragment loading being aborted if there is a small start gap and `maxBufferHole` is set to 0.
`onMediaSeeking` in base-stream-controller will do a `bufferInfo` check, and without any tolerance, the start gap results in `bufferInfo.len === 0` so the  controller thinks we're seeking outside the buffer and cancels the next fragment load:
https://github.com/video-dev/hls.js/blob/63efbc035a119de9c83bf36e273a2aa047fa7ea8/src/controller/base-stream-controller.js#L80
I think preventing the root cause is a good fix to include now in 0.13.0. More time and consideration needs to go into improving the stream controllers' `onMediaSeeking` handler. 
Fixes #2438

Prevent seeking to 0 when startPosition is -1

---

.travis.yml

update the travis config to only include ".js" and ".js.map" files in the github release. Since we started generating type definitions these ".d.ts" files at the top level were also included, which I don't think is useful for anyone in a github release.
Prevents all the ".d.ts" files at the top level being included in the github release.

only include js files in release

---

src/controller/timeline-controller.ts

fix #2400 for example LG SDK 2 has bug on their addCue method with different structure it won't addCue, check if the added cue is entered otherwise try the fallback structure.
enable captions on problematic OS such as LG SDK 2
#2400

fix #2400 issue - cues doesn't show up on browsers which addCue doesn't throw error with invalid structure

---

scripts/travis.sh

This makes it so until we are ready to flip the switch on adding types, there won't be conflicting Typescript definitions for users that are using `@types/hls.js`.
Currently, the types even without a type root are being found by various language servers, and confusing typecheckers with projects that pull in the DefinitelyTyped version of hls.js
Closes #2474

Remove TypeScript types build step

---

.eslintrc.js
package-lock.json
package.json
src/is-supported.ts

- Fix `isSupported` check in browsers missing `SourceBuffer` global.
- Add a eslint rule to prevent `SourceBuffer` global usage.
- Update TypeScript and run `npm audit fix`
JavaScript... no exceptions.
No
resolves #2430
resolves #2476
- N/A new unit / functional tests have been added (whenever applicable)
- N/A API or design changes are documented in API.md

Fix `isSupported` check in browsers missing `SourceBuffer` global

---

src/demux/tsdemuxer.js

attempt to fix #1469
we are currently dropping any PES packet without PTS/DTS
this was introduced by https://github.com/video-dev/hls.js/commit/9a80c9804dbfdf939bdd3c4056c7ac9e3bcfed42. this filtering was added as we were previously providing AVC samples with undefined PTS/DTS to mp4-remuxer.
the mp4-remuxer isnt resilient to that and is generating corrupted video fmp4 in that case.
let's try to be more resilient and fallback on last AVC sample PTS/DTS (PTS/DTS are optional fields of PES headers)
we need to test against streams with PES not signalling PTS/DTS.
#1469

tsdemuxer: if PES does not contain PTS/DTS, use last PES PTS/DTS instead

---

src/demux/tsdemuxer.js

Fixes an issue where incomplete AAC frames at the end of PES packets are skipped.
Fixes loss of data and corruption of certain media streams. (#2528)
No.
Fixes #2528

Improve PES ACC overflow handling

---

src/controller/eme-controller.ts
tests/unit/controller/eme-controller.js

Fix `"Fatal: Media is encrypted but no CDM access or no keys have been obtained yet"` error by using a mediaKeys promise in the `"encrypted"` event callback.
EME API is async, but our handling of the 'encrypted' media event is not which causes functional tests to fail.

Fix EME controller async errors

---

demo/main.js
docs/API.md
src/controller/cap-level-controller.js
src/controller/fragment-tracker.js
src/controller/level-controller.js
src/controller/stream-controller.js
src/errors.ts
src/events.js
src/hls.ts
src/loader/playlist-loader.ts

- Add a new API method `removeLevel(index, urlIndex)`
- Add a new events `LEVELS_UPDATED` fired after a level is removed
- Add a new error `LEVEL_EMPTY_ERROR` fired when a playlist is loaded/parsed and does not contain any fragments
- Add level removal for level error handling to the demo
- Update documentation to cover new API features
These features allow developers to filter out problematic levels, as well as redundant level urls. The demo provides an example of how to implement this.
These features are present in the feature/v1.0.0 branch, but have remained undocumented. These changes will introduce the features and documentation in v0.14.0, which will help ensure they are properly documented in v1.0, and make switching between the upcoming releases and pre-releases easier.
The 180p …

Feature: `removeLevel()` API method

---

src/controller/audio-stream-controller.js
src/controller/stream-controller.js

Ensure that live streams start at the determined or specified `startPosition`.
Live streams with audio tracks sometimes start in the middle rather than the `startPosition` determined by `computeLivePosition`. That "middle" segment might not even align between the main playlist and the track playlist complicating playback and start position.
These changes are based on a PR in the JW player fork that addressed this issue:
https://github.com/jwplayer/hls.js/pull/259

Improve seek to start position for live streams

---

docs/API.md
src/config.ts
src/controller/stream-controller.js
tests/unit/controller/stream-controller.js

The `testBandwidth` config option defaults to `true` maintaining existing ABR behavior which samples a low quality segment to improve the bandwidth estimate before selecting a start level. This option can be set to `false` when you'd like to provide your own estimate or use the default `abrEwmaDefaultEstimate` to speed up start times.
This feature is already implemented in feature/v1.0.0, and is being added in v0.14 to aid in testing and the transition to v1.
#2407 
#2433

Add `testBandwidth` config option

---

src/loader/m3u8-parser.ts
tests/unit/loader/playlist-loader.js

Prevent trying to load a com.apple.streamingkeydelivery format `skd://...` and warn the integrator this isn't supported out-of-the-box by hls.js
I am working on playing HLS fMP4 w/ Fairplay encryption `com.apple.fps.2_0` with hls.js and it was creating an error while trying to load `skd://` over HTTP.
Preventing it allows segments to be added to Buffer/MediaSource and therefore trigger the `webkitneedkey` and `webkitkeymessage` events that I need to get a license from our DRM provider 
Any other KEYFORMAT should work

Prevent loading com.apple.streamingkeydelivery key format

---

src/controller/id3-track-controller.js
src/remux/mp4-remuxer.js

Add defensive handling to ID3 cue time parsing to prevent exceptions constructing cues from incomplete fragments or samples.
I've found streams that have fragments at the end of stream with only id3 data. The lack of media results in invalid end time. These changes fix that.
These changes are already present in feature/v1.0.0. Including them in v0.14.0 will help make a smoother transition to v1.

Prevent internal exceptions with bad fragments

---

README.md

Make it so copying and pasting the example from the README will work right out of the box. It just take the README back to the previous behavior where the example was the same as what shows by default on the test-streams page.
Because I copy and paste the example all the time (shh) and it gets me every time when it doesn't work at first.
Well I did refactor the source URL to be a variable because I also find myself having to edit that in two places every time 😇 
Very, very small onboarding pain.

Make the readme example work out of the box again

---

package.json

Currently the NPM module packs all files in the repo, but only a handful of them are necessary to run. Adding [files key to package.json](https://docs.npmjs.com/files/package.json#files) with the ones we want to keep will exclude all unnecessary ones and doing so will greatly reduce the NPM module size.
This will help with speed, bandwidth and so on and so forth.

Remove all unnecessary files form the NPM distribution

---

src/controller/stream-controller.js
src/controller/timeline-controller.ts
src/loader/playlist-loader.ts
src/utils/cea-608-parser.ts
tests/unit/controller/stream-controller.js

1. Apply `config.renderTextTracksNatively` to 608 captions
2. Fix CEA 608 channel indexes (1 based)
3. Parse CLOSED-CAPTIONS manifest attributes to apply language, label and `default` to (non-native) tracks 
4. Only log that we're loading keys and fragments when we're actually starting to load them
1. When `renderTextTracksNatively` is `false` hls.js should not create textTracks for 608 captions. Instead it should trigger `NON_NATIVE_TEXT_TRACKS_FOUND` with track information.
2. CEA 608 channel output was off by -1
3. Now we apply the correct language properties from manifest CLOSED-CAPTIONS to 608 output
4. Prevent console spam `Loading ${frag.sn} of [${levelDetails.startSN} ...`

CC channel and CLOSED-CAPTIONS fixes

---

src/demux/adts.js
tests/unit/demuxer/adts.js

fix a bug: false positive ADTS probe in MP3 stream (may happen in any data stream).
To fix the bug.
I removed the check whether a frame ends at the end of the data supplied to probe(). Instead probe() only returns true if there are at least three valid headers and two valid frames in between. I think this makes sense because every HLS chunk should have at least three full frames in it.
The main point of the bug fix is the check against zero sized frames. And to fix the header length check which was broken as I think.

Fix false positive ADTS probes

---

tests/functional/auto/setup.js
tests/functional/auto/testbench.js

- Not attempt to switch levels until playback starts on a different level in the "smooth switch" test
- Differentiate test logs from player logs with `[test] >` prefix
- Fail test and return early when `!Hls.isSupported()`
The "smooth switch" function test fails when `switchToHighestLevel` is called before playback begins because `LEVEL_SWITCHED` is never triggered. `LEVEL_SWITCHED` is only triggered when `FRAG_CHANGED` has already been fired for a fragment on a different level. That, or playback isn't starting on certain streams and it's unclear from the logs why...

Fix smooth switch test

---

src/demux/tsdemuxer.js

Improve logging for streams with with unknown or unsupported elementary stream types.
An unknown elementary stream type can result in hundreds of the same log statement every segment. These changes reduce that to one log statement per PMT type, per segment.
I observed severe browser performance degradation with dev tools open in Firefox when verifying #2684. By reducing the number of log statements, the dev tools can be used without stalling the browser / page.
#2684

Reduce log output for unknown elementary stream types

---

src/utils/fetch-loader.js
src/utils/xhr-loader.js

in case they are patched by a different library after hls.js is loaded
Update the xhr/fetch loaders to directly use the native globals from the `window.`, without caching their reference at the top of the modules.
Some sites/libraries modify the native globals.
When hls.js is loaded before such libraries, hls.js will not use the patched ones because it has already cached the native ones.
Not really, pretty simple change

don't cache native globals

---

src/controller/audio-stream-controller.js
src/controller/stream-controller.js
tests/functional/auto/setup.js
tests/functional/auto/testbench.js

Prevent the first two segments from being reloaded at the start of a stream with a start gap larger than `maxBufferHole` but smaller than `MAX_START_GAP_JUMP`.
The audio and main stream controller depend on `BufferHelper.bufferInfo` to determine the end of the buffer relevant to `currentTime` used to find which fragment it will load next. In a gap or hole this buffer end would be for a range before `currentTime`. `maxBufferHole` is used to look past a gap or hole that `currentTime` is in. At the start of the stream, when playback starts, hls.js can jump up to 2 seconds (`MAX_START_GAP_JUMP`) or `maxBufferHole`, whichever is larger, so this change uses that to prevent the stream controller logic from getting stuck picking the first two segments for loading because `BufferHelper.bufferInfo` …

Improve handling of large start gaps

---

src/controller/cap-level-controller.js

With firefox 75.0 64bit on MacOS 10.13.6 aka HighSierra we noticed that `capLevelToPlayerSize: true` would not work: The player would always select the lowest level even at player sizes way above the highest available level's resolution.
Adding debug output to `CapLevelController.mediaWidth()` / `.mediaHeight()` gave us the following values (example):
```
[log] > media.width 89 clientWidth 963 offsetWidth 963 logger.js:40:11
[log] > media.height 0 clientHeight 543 offsetHeight 543 logger.js:40:11
[log] > set autoLevelCapping:0
```
So it seems we should prefer `media.clientWidth` over `media.width` in accordance with
https://developer.mozilla.org/en-US/docs/Web/API/CSS_Object_Model/Determining_the_dimensions_of_elements
fix `capLevelToPlayerSize: true` on MacOS
To make …

prefer media.client{Width,Height} over media.{width,height}

---

package-lock.json
package.json
src/observer.ts

Update eventemitter3 to 4.0.3 and remove the workaround that was added (6f98604319bcb09f72438483ae1b7ad4477e5013) to make 4.0.1 work. The issue was fixed in https://github.com/primus/eventemitter3/pull/223 and https://github.com/primus/eventemitter3/pull/224

update eventemitter3 to 4.0.3

---

src/controller/cap-level-controller.js
tests/unit/controller/cap-level-controller.js

Use `getBoundingClientRect()` in cap-level-controller to get media element width and height
The cap-level-controller should calculate media element width and height at once when calling `getMaxLevel`. It should only use the video element's `width` and `height` attributes, when the client width and height are unavailable (for example when the media element is not in the DOM or is scaled to 0).
Improvement relates to #2659

Use getBoundingClientRect in cap-level-controller

---

docs/API.md
src/config.ts
src/controller/eme-controller.ts
tests/unit/controller/eme-controller.js

Add a new Hls config option `drmSystemOptions` to be able to customize `audioRobustness` and `videoRobustness` in EMEController.
Robustness is required in more and more devices, for example, we need to specify robustness to be `HW_SECURE_CRYPTO` in order to support HDCP on FireTV Stick 4K and gen 2.
And there is also a robustness warning in Chrome if not specified:
> It is recommended that a robustness level be specified. Not specifying the robustness level could result in unexpected behavior in the future, potentially including failure to play
N/A
N/A

Support drm system options

---

package-lock.json
src/controller/audio-stream-controller.ts
src/controller/stream-controller.ts
src/loader/fragment.ts
src/loader/level-key.ts
src/loader/m3u8-parser.ts
src/utils/attr-list.ts
tests/unit/loader/fragment.js

When fragments are signalled from the manifest they are encrypted we
need to be able to detect this fact. Currently we use the boolean
"encrypted" on Fragment to support this. So I've added some tests that
cover the current behaviour for AES-128 encryption, and some ~skipped~
tests that cover the future usecase.
Additionally, this change includes a tiny change to the LevelKey class.
It now has a private constructor, and two static methods to create
itself. `fromURL` and `fromURI`, one supports the current usecase for
absolute or relative URLs, and the other is for supporting the future
use-case of URI keys.
As the meaning of the `encrypted` getter on Fragment has been changed
to mean that a fragment has a `EXT-X-KEY` associated with it, locations where it was used
currently for …

Add fragment.encrypted unit tests for manifest signalled DRM (PlayReady and Widevine)

---

src/controller/eme-controller.ts
tests/unit/controller/eme-controller.js

Close media key sessions and clear media keys when media detached.
When we tested Hls.js on Android Webview on FireTV, we found that the player failed to play DRM titles after finishing 5 or 6 titles. After investigation, the root cause is:
> whenever we create a new Hls.js instance for a DRM title, it will set new media key and open a new key session to decrypt DRM media data, but it doesn’t release them when the Hls.js instance destroys. Looks like there is a maximum limitation on FireTV platform for opening key sessions, once we reach it, no new session could be created any more.
Related adb logs:
```bash
29063 10-30 03:49:57.719   295 13552 I WVCdm   : CdmEngine::QueryStatus …
```

Close media key sessions and clear media keys when media detached

---

src/controller/fragment-finders.ts
tests/test-streams.js
tests/unit/controller/fragment-finders.js

Improve `findFragmentByPTS` and `fragmentWithinToleranceTest` with regards to selecting the next fragment and handling of tiny fragments.
The binary search in`findFragmentByPTS` fails to find tiny segments that are smaller than the difference or gap between the end of audio and video in the previous segment. These tiny segments are often created with digital ad insertion or stitching.
The image below illustrates issue #2776  where sn 12 is never loaded and playback stalls near the end of sn 11, because `findFragmentByPTS` consistently returns `null`:
I've kept the original intention and priority of `findFragmentByPTS` in tact as much as possible. Now, it only skips `BinarySearch.search` for the very first segment where it was always being called. And, if `BinarySearch.search` fails but an …

Fix: playback stops on short segment

---

netlify.toml

Follow up for https://github.com/video-dev/hls.js/pull/2818. Currently it fails to build for 'master' because `TRAVIS_MODE` is not set on the 'production' environment. I thought 'master' would still fall under 'branch-deploy' like the other branches but it appears it doesn't.
It doesn't work otherwise for `master`.

default TRAVIS_MODE to netlifyBranch on netlify

---

.github/ISSUE_TEMPLATE/bug_report.md
README.md
scripts/deploy-netlify.sh

- Stop deploying to netlify-latest because hls-js-dev now automatically builds master.
- Update links.
hls-js-latest now just redirects to hls-js-dev so old links should still work.

Do not deploy to netlify-latest and update links to netlify-dev

---

src/controller/base-stream-controller.ts
src/controller/buffer-controller.ts
src/controller/buffer-operation-queue.ts
src/controller/fragment-tracker.ts
src/controller/subtitle-stream-controller.ts
src/loader/fragment-loader.ts
src/loader/fragment.ts
src/loader/m3u8-parser.ts
src/types/buffer.ts
src/utils/mp4-tools.ts

Init segments are currently not decrypted if EXT-X-KEY applies to them, this causes the initialization segment to not work.
Turns out this media also contains multiple `trun` boxes. Which is something we previously haven't dealt with, and was causing issues with our parsing the duration of the media. This is likely due to a restriction in CMAF. That limits you to only one `trun`. But MSE targets a BMFF bytestream, which doesn't have this restriction.
On the test stream in #2259 (https://t2.qluv.io/test-aes-enc-init/master.m3u8), ~I'm seeing gaps~ fixed with the `trun` changes. Regression testing still needs to be done.
~Additionally, I'm wondering if we should add some kind of "decrypted" boolean to Fragment and store the result.~ Answered.
Closes #2259.

Support for encrypted initialization segments for fMP4

---

src/controller/timeline-controller.ts
src/utils/cea-608-parser.ts
src/utils/output-filter.ts

Fix simultaneous parsing of CEA-608 captions in multiple channels.
A regression was introduced after v0.13.2 when incorporating cea-608-parser changes from the feature/v1.0.0 branch.
The changes attempted to parse both channel 1 and 3 caption fields simultaneously, and in some cases this appeared to work. But when the `currChNr` property was updated for one field, it could impact the other, causing CC content to get dropped.
These changes track the current channel independently for each field removing the interference.

CEA-608 captions fix

---

src/controller/timeline-controller.ts
src/utils/cea-608-parser.ts
src/utils/output-filter.ts

Assign separate `cueRanges` to each CEA-608 output filter for merging rollup captions text without destroying cue ranges in other channels.
Some captions were being dropped because a single `cueRanges`  time range was shared in timeline-controller across CC 1 and 3 rollup captions.
The last round of fixes (#2834) took care of content (whole words and lines of text) that was being dropped. These changes fix the timing of the content and cues in either channel overlap.

CEA-608 captions fix (part II)

---

src/demux/mp3demuxer.js

Fix the problem of discontinuity of mp3 fragment where first fragment have timestamp == 0.
Right now playlist like this:
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TARGETDURATION:2
#EXTINF:2,
fragA000.mp3
#EXTINF:2,
fragA001.mp3
#EXTINF:2,
fragA002.mp3
#EXT-X-DISCONTINUITY
#EXTINF:2,
fragB000.mp3
#EXTINF:2,
fragB001.mp3
#EXTINF:2,
fragB002.mp3
#EXT-X-ENDLIST
will be played incorrectly. fragB000 have timestamp equal to 0 and will have discontinuity flag internally, but PTS will be calculated as 6 * 90000. This will break playback badly.
It fixes a bug.
Don't think so.

Fixed incorrect calculation of PTS for mp3/ID3 timestamp equal to zero (important in case of discontinuity)

---

scripts/set-package-version.js
scripts/version-parser.js

Update the fix in https://github.com/video-dev/hls.js/commit/90cf214d1a0d8be659784c0b20290a6e46421e02 to prevent accidentally publishing older versions.
I noticed the fix in https://github.com/video-dev/hls.js/commit/90cf214d1a0d8be659784c0b20290a6e46421e02. Minor thing but I think it would be better to still check all the time, but allow the current version. With the current fix it's still possible to accidentally publish a tag earlier than the current one.

always check version is greater than previous

---

src/controller/stream-controller.js
src/remux/mp4-remuxer.js

1. Fix segment duration calculation when first and last PTS do not match min and max (fixes #2873)
1. Fix rounding errors in initPTS calculation:
Actual 😞  `90000 * 16.4 === 1475999.9999999998`
Expected ` 90000 * 16.4 === 1476000`
1. Limit how frequently the position of video frames are adjusted based on estimated next DTS, maintaining composition time when possible
1. Clamp DTS to 0 after timecode hole/overlap check and Safari frame duration calculation (prevents incorrect `nextDTS delta` adjustment from being applied)
1. Adjust timecode hole tolerance to account for 59.94 and 29.97 frame rate variance (prevents adjustment from being applied with 0-2 dts sample duration variance)
1. When backtracking because of dropped video frames, reset the demuxer so that we don't use next DTS based …

Fix dropped frames caused by AVC min/max PTS not matching first/last PTS

---

src/polyfills/number.js
src/remux/mp4-remuxer.js
webpack.config.js

- Replace `Number.MAX_SAFE_INTEGER` with an import the same way we replace `Number.isFinite` for IE11.
- Use `Number.POSITIVE_INFINITY` and `Number.NEGATIVE_INFINITY` for default min/max values in `remuxVideo`.
- Cleanup use of `inputSamples.length` in `remuxVideo`
Fixes playback on IE11.

Fix for IE11 missing Number.MAX_SAFE_INTEGER

---

src/remux/mp4-remuxer.js

- Fix estimated DTS timeoffset between segments
- Prevent gaps caused by writing over the previous frame assumed to be a hole
> - Prevent gaps caused by writing over the previous frame assumed to be a hole
Fix gaps in buffer for streams with variable framerate or other PTS/DTS inconsistencies that caused the "Video: PTS/DTS adjusted" workaround to kick in when it should not.
hls.js was shifting the start of the first frame of some segments back about a frame's duration, which cleared the previous frame from the buffer causing buffer gaps. I don't see how we could accurately estimate the last AVC frame duration (`lastFrameDuration` or `mp4SampleDuration`) to get the estimated `nextAvcDts` to be spot on - not sure it can always be. So to prevent these overwrites, ignore assumed AVC DTS …

Fix gaps introduced in video buffer by remuxer work-around

---

src/demux/demuxer-inline.js

Probe segments in order of transmux configs on discontinuities and track switch, to avoid false positives when existing AAC demuxer probes TS files.
Maintain the same demuxer and remuxer as long as the type hasn't changed.
DAI inserts TS audio segments in audio tracks with AAC segments, and `AACDemuxer.probe` returns `true` when passed the TS data. 
Throwing away the remuxer when the audio demuxer changes drops audio because the last appended timecode is lost.
#2887

Fix demuxer switching on level switch and discontinuities

---

demo/chart/timeline-chart.ts
demo/main.js
src/controller/level-helper.js
src/controller/stream-controller.js
src/remux/mp4-remuxer.js
tests/test-streams.js

- Fix Safari playback by removing Safari workarounds in mp4-remuxer.
- Fix remuxer (PTS based) time-offset `nextAvcDts` estimation to avoid false hole/overlap detection.
- Fix forward fragment start overestimation by adding `fragment.minEndPTS`
- Avoid removing overlapping media in the forward buffer when flushing future segments after setting `nextLevel` (prevents gaps when adapting fmp4 and the previous segment's media extends past the target segment's start in "HLS fMP4 by Bitmovin")
- Use minimum segment PTS when calculating `initPTS` and TS AV time-offset in remuxer (since the first sample PTS is not always the fragment start)
These changes also help make fragment DTS and PTS updates more stable on adaptations, when reloading previously parsed fragments, and when simply forward …

Fix Safari video playback, and fragment timing

---

src/controller/base-stream-controller.js
src/controller/stream-controller.js
tests/unit/controller/stream-controller.js

Seek into buffer start when starting a live stream.
This avoids a video rendering bug in IE11 and Edge where video is not rendered when seeking into an unbuffered range to start playback.
It also avoids requiring the gap-controller to step forward playback and potentially reporting stalls.
#2498
#2507

Seek once into buffer start when starting live

---

src/controller/audio-stream-controller.js

Solves initial AV desync for fMP4.
It seems that there are cases when initPTS handling is faulty and it results in misaligned offsets for A/V.
I suspect that audio demuxing can start here without knowing the video's initPTS: [https://github.com/video-dev/hls.js/blob/master/src/controller/audio-stream-controller.js#L526](https://github.com/video-dev/hls.js/blob/master/src/controller/audio-stream-controller.js#L526)
Might be the same issue: https://github.com/video-dev/hls.js/issues/2545

Fix initial audio video desync for fMP4

---

src/controller/audio-stream-controller.js

Improve the handling of audio-stream-controller `waitingFrag` by:
- Always removing the waiting fragment from the fragment tracker when clearing it before it's appended
- Use fragment-finders `fragmentWithinToleranceTest` in audio-stream-controller
- Parse waiting fragment when fragment cc initPTS is known (so that we establish sync with video)
- Drop waiting fragment when:
- video cc has changed since waiting fragment was set but not to the cc needed to parse waiting cc 
- The waiting fragment is no longer the audio fragment that needs to be buffered
The audio-stream-controller got stuck on discontinuities for because the waiting was not used when it should be and it's status was not managed correctly: 
1. `videoTrackCC` is only updated once `initPTS[waitingFragCC]` is available, which …

Fix stalling on discontinuity with audio track

---

.travis.yml
demo/main.js
tests/functional/auto/setup.js
tests/functional/auto/testbench.js

- Fix IE11 Selenium execute async JavaScript exceptions
- Update Safari version from 9.1 to 10.1 for a better chance at webdriver running tests in Safari
- Omit logs from logging of result JSON
- Fail "seek to end -5" early `onprogress` if more than 2 `buffered` ranges are found (If have an unexpected gap, the test should fail)
Improve test run stability required and optional browser configurations.
This PR was originally for troubleshooting test failures that I was having difficulty reproducing locally. If you're interested in the temporary changes I made to troubleshoot test runs both locally and in the travis runs, let me know and I can move the stashed changes into a branch. Disabling the worker and shortening the list of test stream to the problem stream are the first steps.
When …

Debug functional test failure

---

src/remux/mp4-remuxer.js

Update lastDTS after realigning samples in case firstDTS set to a higher value
See #2905

Prevent negative DTS time ranges in fragments

---

src/remux/mp4-remuxer.js

Compare set sort and shift flags after PTSNormalize is applied.
- Fixes false positive on the `sortSamples` flag when the last sample's dts was normalized but the current was not.
- Fixes false positive on the `ptsDtsShift` flag when `sample.pts` is less than `sample.dts` before `PTSNormalize` is applied.
Relates to #1796

Fix regression in streams with PTS wrapping prior to DTS

---

src/controller/level-helper.js

Do not use shorter track duration when updating fragment timing at a discontinuity.
The first of audio and video tracks to end is used to determine the start of the next segment - but this should only be done when segments are contiguous and we expect the same track to start sooner. In the case of a discontinuity, we want the next segment to start after both tracks in the previous segment have ended.
In earlier releases and in Safari, this stream has a duration of ~40 seconds. These changes restore that duration which was being cut short by always using `minEndPTS` in the changes below.
http://playertest.longtailvideo.com/adaptive/boxee/playlist.m3u8

Fix stream duration update regression with discontinuities and misaligned AV

---

demo/chart/timeline-chart.ts
demo/index.html
demo/main.js
src/controller/audio-stream-controller.js
src/controller/stream-controller.js
tests/functional/auto/setup.js
tests/test-streams.js

- Do not flush audio on audio track switch when both tracks are main variant streams
- Clean up test streams and test `abr` properties
- Add a "Next video" button in "Playback" to quickly cycle through streams in the drop-down
- Update the drop-down on page load to match the permalink video when a match is found
- Clean up some console logging around segment loading
When playing a stream with variants whose audio is described in MEDIA tracks (with no alt audio), the audio-stream-controller will trigger track change events on level switch. This has the unintended side-effect of making the stream-controller flush all audio in `onAudioTrackSwitching`. Unfortunately this flush command may prevent the init segment for the new audio variant from being appended. In the case where the audio …

Fix edge-case in main audio-only with track descriptions 

---

package-lock.json
src/demux/tsdemuxer.js
src/remux/mp4-remuxer.js
tests/functional/auto/setup.js

When a rollover was occuring the timeoffset value was incorrectly calculated due to taking the minimum PTS from the new set of rollovers, this lead to a very large timeOffset delta on the audio and led to incorrect PTS values after running through PTSNormalize function.
This happened to be fixed by the silent gap code just below, which set the sample pts and dts to be the expected next value, but this now makes it so on well-formed media, the else branch is essentially a no-op because the delta is zero.
https://github.com/video-dev/hls.js/blob/ff2646a3db04803d52668dbce8c4e5ca750bf35d/src/remux/mp4-remuxer.js#L540-L548
Investigating #1796.
Did this against your branch @robwalch since your change fixed the time duration, this now resolves an internal issue with the PTS value because of the …

Fix PTS calculation on rollover.

---

src/controller/id3-track-controller.js

Update the id3 parser to ensure cues have a duration of at least `0.25s`
We are seeing missing `TextTrack` `change` events in cases where the cue exists at the end of a segment due to the previous `0.0001` adjustment not providing a long enough duration to fire when the playhead plays over the cue.
All of it, I'm new
JW8-11282

Require min cue duration of 0.25

---

src/controller/buffer-controller.ts
src/controller/gap-controller.js
src/controller/stream-controller.js

- Set live seekable range when `liveDurationInfinity` is enabled
- Skip large start gaps (target duration * 2)  in live streams 
When level loading in a live stream fails, and we perform an immediate switch the buffer is flushed. This also removes all `seekable` ranges and when the media's duration is `Infinity` this prevents seeking when setting `currentTime`. Since updating `currentTime` and seeking is essential to catchup to the live playlist so that buffering can resume, setting the seekable range with `setLiveSeekableRange` fixes this.
With these changes, when `liveDurationInfinity` is set to `true` the media element's `duration` and `seekable` properties should match those of Safari when buffering live content. `duration` will be `Infinity` and `seekable` TimeRange will match the …

Set live seekable range when `liveDurationInfinity` is enabled

---

demo/main.js
src/controller/audio-track-controller.js
src/controller/stream-controller.js
src/hls.ts

Support the use of `loadSource()` after loading or playing another stream.
This is a work in progress. Right now it's just a small set of changes to get the ball rolling and discuss what other changes are required. So far it will:
- Stop network controllers before loading a new stream
- Reset the selected audio track so that the audio-track-controller will call `_selectInitialAudioTrack` in `_selectAudioGroup` to load the media playlist and begin buffering alt-audio
We get a lot of issues where folks expect to be able to call `loadSource()` to load a new video after already playing or starting to load another one. The canned answer is, it is always best to start with a new player instance when loading a new stream. I don't think this should be the case. We should know the internals, and …

Stop loading and reset selected audio track when reloading streams

---

README.md

Update README for checking browser HLS support.
Before Safari supported MSE then this recommendation in the README worked well because `Hls.isSupported()` would return `false`. Now that changed and it returns `true`.
I typically think it's a best practice to use the browser's native HLS support if it's available, otherwise fallback to `hls.js`
n/a - only a README update

README: Swap logic for checking Hls.isSupported()

---

src/remux/mp4-remuxer.js

Fix a regression introduced in v0.14.1, in the audio remuxer, where bad samples mid fragment were not being dropped.
Appending out of order samples results in stretching of audio track duration.
Test stream (4 second segment with one out of sequence audio sample) https://playertest.longtailvideo.com/adaptive/audio-sample-out-of-sequence/main.m3u8
The video duration becomes 27 hours:
https://hls-js.netlify.app/demo/?src=https%3A%2F%2Fplayertest.longtailvideo.com%2Fadaptive%2Faudio-sample-out-of-sequence%2Fmain.m3u8&demoConfig=eyJlbmFibGVTdHJlYW1pbmciOnRydWUsImF1dG9SZWNvdmVyRXJyb3IiOnRydWUsImR1bXBmTVA0IjpmYWxzZSwibGV2ZWxDYXBwaW5nIjotMSwibGltaXRNZXRyaWNzIjotMX0=
#2959

Fix audio remuxer out of sequence sample drop regression 

---

src/controller/id3-track-controller.js

Only apply minimum ID3 cue duration when cue does not have a valid duration.
ID3 cues found on the last sample of an ID3 track or cues in tracks with out-of-order PTS will have an end time that is equal or less than their start time, which is not valid.
This fixes a regression introduced in v0.14.8 with  #2951 where we applied a minimum duration 0.25s to all metadata cues, to ensure change events always fire, without considering the need to maintain the duration of cues intended to provide data relative to video frames (where the duration is more likely to be ~0.008-0.04s).
#2963

Only apply minimum ID3 cue duration when cue has none

---

src/controller/stream-controller.js

Use the combined buffer in gap controller and to signal when to seek to start position
So that when we seek to the start position we can adjust for any difference between the start of audio and video buffers that offsets the combined buffer.
This will prevent stalls, but may cause the audio-stream-controller to load segments based on currentTime 0 after loading it's start segment, but before this check results in `_seekToStartPos()` being called. The problem is that each stream controller has its own rules for setting its `loadedmetadata` flag which determines if the search for the next fragment to be loaded should start from `currentTime` or `nextLoadPosition`.

Check combined buffer before start seek

---

src/remux/mp4-remuxer.js

Fix mp4-remuxer `CHUNK_DEMUXER_ERROR_APPEND_FAILED` in Chrome 74 and lower, as well as Chromium based browsers like Opera 58.
Older versions of Chrome error when appending mp4 fragments with negative base decode times. Using these values works in other browsers and allows us to append video as close to `0` and the first audio sample as possible, reducing start gaps at the beginning of video with large composition times (pts-dts delta).
> The video playback was aborted due to a corruption problem or because the video used features your browser did not support - CHUNK_DEMUXER_ERROR_APPEND_FAILED: video frame with PTS 40000us has negative DTS -40000us after applying timestampOffset, handling any discontinuity, and filtering against append window
Negative DTS were allows in v0.14.4 which …

Chrome 74 and lower mp4-remuxer fix

---

src/demux/id3.js

Merge changes from v0.14.x into master
Includes a fix for ID3 parsing, splitting `WXXX` info and value on NULL delimiter to extract URL.
As a result TextTrack metadata cues added by hls.js for these ID3 tags should match those added by Safari using the same stream with video.src=m3u8 playback.

Fix ID3 WXXX URL parsing

---

.travis.yml
package-lock.json
package.json
scripts/travis.sh
src/remux/mp4-remuxer.js
tests/functional/auto/setup.js

Fix handling of AVC sample where sample contain PTS that is less than DTS and the PTS does not always increase like the DTS:
```js
0: {key: true, pts: 0, dts: 0, units: Array(4), debug: "", …}
1: {key: false, pts: 12003, dts: 3003, units: Array(1), debug: "", …}
2: {key: false, pts: 6006, dts: 6006, units: Array(1), debug: "", …}
3: {key: false, pts: 2979, dts: 9009, units: Array(1), debug: "", …} // PTS < DTS and < previous PTS
4: {key: false, pts: 9042, dts: 12012, units: Array(1), debug: "", …} // PTS < DTS
5: {key: false, pts: 24015, dts: 15015, units: Array(1), debug: "", …}
6: {key: false, pts: 18018, dts: 18018, units: Array(1), debug: "", …}
7: {key: false, pts: 14991, dts: 21021, units: Array(1), debug: "", …} // PTS < DTS and < previous PTS
8: {key: false, pts: 21054, dts: …
```

Fix remuxing of AVC with bad PTS

---

src/controller/level-controller.js
src/controller/stream-controller.js
src/controller/subtitle-track-controller.js
tests/unit/controller/subtitle-track-controller.js

- Fix resuming of live streams after calling `stopLoad()` and `startLoad()`
- Stop loading subtitle track playlists after `stopLoad()`  is called
- Do not adjust for live playlist sliding twice
- Reverse 6a3f6a8 which requires audio, subtitle and main stream controllers to use the same startPosition logic
We should be able to resume live stream loading after stopping it.
All live playlist reloading should stop after `stopLoad()`  is called.
#2994
Audio tracks continue to load after `stopLoad()` is called because the implementation was changes to a taskLoop. This is fixed in feature/v1.0.0 and will not be addressed here.

Fix resuming of live streams after calling stopLoad() and startLoad()

---

src/controller/audio-stream-controller.js
src/controller/buffer-controller.ts
src/controller/gap-controller.js
src/controller/stream-controller.js
src/utils/buffer-helper.ts
tests/unit/utils/buffer-helper.js

Fix posible SourceBuffer related error `Failed to read the 'buffered' property from 'SourceBuffer': This SourceBuffer has been removed from the parent media source.`
This error has been reported several times https://github.com/video-dev/hls.js/issues/1787
This error is handled in some places but not everywhere. This PR adds a wrappers that makes reading this property safe.
https://github.com/video-dev/hls.js/issues/1787

Adds BufferHelper.getBuffered()

---

src/utils/cues.ts

Add VTTCues with matching start time in reverse order for correct CSS layout.
Chrome will display cues with identical time ranges from the bottom up when controls overlap lines.
#3070

Display 608 captions in correct order

---

src/controller/subtitle-stream-controller.js

- fix the subtitle controller to work after `hls.stopLoad()` and `hls.startLoad()` was used #3053 
- fix an incorrect subtitle file loading order after initial seek in some very rare cases #3053 
The german tv-station ZDF uses the api `hls.stopLoad()`and `hls.startLoad()` in their player and needs to provide WebVTT for their clips. This also fixes the example code to work where `hls.loadSource` is called inside the `MEDIA_ATTACHED` event: https://github.com/video-dev/hls.js/blob/master/docs/API.md#third-step-load-a-manifest
- #3053

Bugfix for subtitle loading after hls.stopload() was used

---

src/remux/mp4-remuxer.js

Normalize first audio and video PTS/DTS when comparing the two and determining initPTS to ensure elementary media streams are aligned on start.
In a stream where the first video PTS is a wrapped unsigned integer as seen below, we don't want to base initPTS on this value and attempt to align audio to it.
```
videoTrack.samples
0: {key: true, pts: 8589933243, dts: 8589933243, units: Array(3), debug: "", …}
1: {key: false, pts: 1711, dts: 1711, units: Array(1), debug: "", …}
2: {key: false, pts: 4681, dts: 4681, units: Array(1), debug: "", …}
3: {key: false, pts: 7651, dts: 7651, units: Array(1), debug: "", …}
4: {key: false, pts: 10711, dts: 10711, units: Array(1), debug: "", …}
5: {key: false, pts: 13681, dts: 13681, units: Array(1), debug: "", …}
6: {key: false, pts: 16651, dts: 16651, …
```

Handle PTS rollover on initial sample of video or audio

---

src/remux/mp4-remuxer.js

Correct calculation of initPTS.
Changes in #3083 affected how initPTS was calculated in streams that should have had any correction.
Fix for changes in #3083 for #3082

Improve handling of PTS rollover initPTS calculation

---

src/utils/cues.ts

Fix sorting of appended VTT cues with line numbers for Chrome's handling of overlapping cues.
Adjacent WebVTT cues rendered in Chrome tend to overlap by default, or don't fit in the viewport - at least when controls are displayed, which can lead to a cue with a greater line number being moved above one with a lower line number near the bottom of the screen.
To account for this, cues with a line number of 8 or higher are appended in reverse order. This makes them render in the correct order, unless the styling of cues is changed such that the cues no longer overlap (at which point they would be very small and difficult to read).
Lines at the top of the media element viewport must be appended in order, otherwise with snapToLine, the first line can be moved below the second, and so on. …

Bugfix: 608 captions displayed in reverse order

---

src/utils/xhr-loader.ts

Add the missing `onprogress` event listener to the `XMLHttpRequest` object inside the `xhr-loader`, and update `stats.loaded` & `stats.total` accordingly.
The ABR controller [relies](https://github.com/video-dev/hls.js/blob/feature/v1.0.0/src/controller/abr-controller.ts#L122) on the `.loaded` property of the `ProgressEvent` for accurate estimation of the remaining bytes to download.

Add onprogress listener to xhr-loader

---

docs/API.md
src/controller/audio-track-controller.ts
src/controller/base-playlist-controller.ts
src/controller/level-controller.ts
src/controller/subtitle-track-controller.ts
src/types/events.ts
src/types/level.ts
src/types/media-playlist.ts
tests/unit/controller/subtitle-track-controller.js

- Use RENDITION-REPORT details to make blocking reload requests when switching level/audio/subtitle playlists
- Add `type` and `url` to "hlsSubtitleTrackSwitch" events switching to a track
- Subtitle disabling switches to index `-1` continue to only contain `{ id }`
These changes allow us to make blocking playlist requests for variants that should be (close to) the latest already available on the origin and edge.
These changes use the previous playlist report's LAST-MSN and LAST-PART attributes for the variant being switched to as parameters in the request for that playlist.
Improvements to low-latency switching like playlist/segment prefetching or variant latency/under-buffer estimates using these reports are not included in this change-set.

LL-HLS RENDITION-REPORT playlist variant switching

---

src/demux/sample-aes.js

Nals <= 48 go through decryption phase
Nothing is decrypted (too few data), but discardEPB is performed, which corrupts bitstream, which results in artifacts in playback, depending on target machine + browser this may also freeze the tab/browser, as corrupt data is fed to decoder
This error looks like a typo.
No
#3102

Sample AES decryption with 48 AVC Closes: #3102

---

.dependabot/config.yml
.github/dependabot.yml
.github/workflows/automerge.yml

Switch to the stable version of dependabot which is managed by GitHub and configures an [auto merge action](https://github.com/tjenkinson/gh-action-auto-merge-dependency-updates) (disclaimer: I wrote it) to merge the dependency update PRs which don't contain major bumps.
Because the current dependabot is going away eventually. The auto merge action isn't needed, but if we make the travis step required, then it could be helpful if we have enough confidence in that to merge. The new dependabot doesn't support auto merging after an approval anymore.

Switch to stable dependabot

---

demo/style.css

Add dark-mode styles to demo page applied with system/browser preferred color scheme.
It's easier on my eyes. 
With these new styles, and General > Appearance: "Dark" enabled on my mac, the demo looks like this:

Demo Dark-Mode

---

.github/workflows/build.yml
.travis.yml
scripts/travis.sh
tests/functional/auto/setup.js

Setup GitHub actions to do everything but the building and publishing of releases. I'll look into that later.
The functional tests are removed from travis. The rest remains for now.
Keeping it inside GitHub should be faster and more reliable. Previously we _needed_ to use travis because it seemed to be the only place that let forks work with SauceLabs because of some JWT mechanism, but it seems that has been shut down now.
- On travis we set the concurrency limit to 8, because this is the maximum number of sauce labs tunnels we're allowed at once. Unfortunately this applies to every type of job, not just the function test one. Now many more jobs can run at once, and we only throttle the functional test ones. This means the build and unit test jobs should always run pretty instantly.
- …

Switch to GitHub actions for PR checks

---

.github/workflows/build.yml

Make it so that the `test_functional_optional` workflow always passes. The individual jobs can still fail.
Means the owner won't get an email showing a failure on the overall check run if only an optional test fails.

do not fail test_functional_optional workflow

---

package.json

fix the following issue on running `npm start` with the current combo of webpack vs webpack-dev-server versions in deps:
```
> webpack-dev-server --progress --env.debug --env.demo --port 8000
internal/modules/cjs/loader.js:800
throw err;
^
Error: Cannot find module 'webpack-cli/bin/config-yargs'
```
As stated here: https://github.com/webpack/webpack-dev-server/issues/2759#issuecomment-706668920
> webpack-dev-server does not work with webpack-cli v4
fix the bug which probably was induced from an automatic update of deps.
in order to do that, we need to invoke the dev-server via `webpack serve ...`. 
this patch will also fix the `--env` arg usage. the dot-syntax is not supported anymore, but instead values are passed as in other standard CLI argument syntax.
described above.

fix webpack CLI usage (current scripts are not compatible with webpack versions in current package deps)

---

demo/main.js
docs/API.md
src/config.ts
src/controller/audio-stream-controller.ts
src/controller/base-stream-controller.ts
src/controller/fps-controller.ts
src/controller/latency-controller.ts
src/controller/level-helper.ts
src/controller/stream-controller.ts
src/controller/subtitle-stream-controller.ts
src/hls.ts
src/loader/level-details.ts
src/loader/m3u8-parser.ts
src/loader/playlist-loader.ts
tests/mocks/data.js
tests/unit/controller/latency-controller.ts
tests/unit/controller/stream-controller.ts

Adjust playbackRate (1/2-2x) to maintain target latency
- Adds `latency` getter to API
- Adds `targetLatency ` getter to API
- Adds `maxLatency ` getter to API
- Moves responsibility for `liveSync...` options from stream-controller to latency-controller
- Show "Max Latency", "Target Latency", "Latency", "Edge Stall" and "Playback rate" in Buffer and statistics demo tab
- Adds `minLiveSyncPlaybackRate` and `maxLiveSyncPlaybackRate` config bounds to `playbackRate` adjustment
Target latency is determined by:
1. User defined configuration option `liveSyncDuration` or `liveSyncDurationCount`
2. HOLD-BACK (not Low-Latency) or PART-HOLD-BACK (LL-HLS) in v9+ HLS playlist
3. Default is TARGETDURATION * 3 (`DefaultConfig.liveSyncDurationCount`)
This controller will be responsible for hls.js's live …

Latency controller

---

.github/dependabot.yml

Prefix dependabot commits with [skip ci]
Should stop netlify builds for dependabot PR's, which are using build minutes.

prefix dependabot commits with [skip ci]

---

src/remux/mp4-remuxer.js

Prevent us from using negative DTS values in AVC moof atoms in old webkit browsers.
Fixes a decode errors in 2017 Tizen Smart TVs in streams where we try to minimizing video start gaps by aligning video and audio as close to 0 as possible without changing initial CTS.
Fixes #3211

Include old WebKit based browsers in positive DTS gate 

---

src/utils/mp4-tools.ts

Fix playback of streams using fMP4 where the sample duration is stored in the `trex` box.
To successfully play more streams.
No.

Apply default flags and duration from trex box

---

.github/workflows/automerge.yml

Use the hls.js personal access token for auto merge.
Because otherwise after the merge the actions don't run on master, because the `secrets.GITHUB_TOKEN` is not allowed to trigger other actions, which is why canary's and netlify builds aren't being published from the auto merges.

use the hlsjs PAT for auto merge

---

src/utils/cues.ts

Calculate cue position for CEA-608 caption cues according to the PAC indent code table at https://dvcs.w3.org/hg/text-tracks/raw-file/default/608toVTT/608toVTT.html#positioning-in-cea-608
Improve rendering of 608 captions (multiline and left aligned).
Also a small optimization on whitespace check using RegEx.test rather than String.match.
Test streams:
https://playertest.longtailvideo.com/adaptive/captions/playlist.m3u8
https://playertest.longtailvideo.com/adaptive/cpcweb/cpcdemo.m3u8

Improve CEA-608 column to VTT position

---

src/controller/audio-stream-controller.ts
src/controller/base-stream-controller.ts
src/controller/stream-controller.ts

Only trigger stream controller `config.autoStartLoad` behavior in stream controllers' `onMediaAttached` callback, when the controller's state is `STOPPED`.
When loading has already been started based on `config.autoStartLoad` or `streamController.forceStartLoad` in a `levelController.onParsedComplete` callback in the `Hls` constructor, each controller should not interrupt and restart its initial playlist request on attach.
Moved common attach/detach callback code to base-stream-controller.

Prevent reloading of the initial playlist on media attach

---

src/remux/passthrough-remuxer.ts
src/utils/mp4-tools.ts
tests/test-streams.js

Add support for AVC fmp4 fragments found in Apple Advanced HEVC/H.264 stream
Playback of https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_adv_example_hevc/master.m3u8 without JavaScript exceptions.
When playing this stream, mp4-tool functions such as `getStartDTS`, `offsetStartDTS `, and `getDuration` would throw exceptions when encountering track fragment boxes for unknown track types* not accounted for in the init data (`initData[id]` is `undefined`).
These changes ignore those track fragments so that we only deal with the audio and video fragments we're parsing time/duration for.
*Track types added to init data:
```
const type: HdlrType = { soun: ElementaryStreamTypes.AUDIO, vide: ElementaryStreamTypes.VIDEO }[hdlrType];
if (type) {
```
Replaced some array methods …

Add support for AVC fmp4 fragments found in Apple Advanced HEVC/H.264 stream

---

src/demux/id3.js

This PR updates our ID3 tag parsing to ensure that we always parse and surface the ID3 tags as long as the `type` is present on the frame.
Certain users, such as Yospace, have custom ID3 tags, like `YMID`, that were previously being dropped in the parsing step as they did not follow any of the expected patterns.
For an example, see the following test stream: http://playertest.longtailvideo.com/adaptive/yospace-id3/index.m3u8
I don't believe so, but as this is my first contribution here, possibly!

Always parse ID3 tags if type is present on the ID3 Frame

---

.github/workflows/build.yml

Updates the sauce connection action to a [version that retries](https://github.com/saucelabs/sauce-connect-action/pull/20) and will actually error if the connection fails.
Current version does not error if connection fails or concurrent limit reached, meaning the build then fails at the integration test stage. With retries hitting the concurrent execution limit shouldn't cause a failure anymore, because we will keep retrying until there's room available.

update sauce-connect action to a version with retries

---

.github/workflows/automerge.yml

Not run the automerge action on forks, where the secret is not available.
Currently it runs and fails on forks.

do not run automerge action if secret not available

---

src/config.ts
src/controller/base-stream-controller.ts
src/controller/buffer-controller.ts
src/controller/fragment-tracker.ts
src/controller/level-helper.ts
src/controller/stream-controller.ts
src/demux/transmuxer.ts
src/loader/fragment.ts
src/remux/mp4-remuxer.ts
src/types/events.ts
src/types/fragment-tracker.ts
src/types/remuxer.ts
tests/unit/controller/audio-track-controller.js
tests/unit/controller/base-stream-controller.js
tests/unit/controller/buffer-controller-operations.ts
tests/unit/controller/gap-controller.js
tests/unit/controller/stream-controller.ts

- Load all previous segments until a keyframe is found when non-independent video segments are found in a new transmux session (backtracking after a seek or stream start).
- Loaded segment data that requires backtracking is kept in the fragment-tracker so that the segment is not reloaded after previous segments are.
- Segment duration and timeline are not modified when frames are dropped from segments containing but not starting with a keyframe.
- The back buffer is flushed when backtracking and when appending partial (dropped frames) segments. This ensures partially appended fragments are reloaded and buffered completely in sequence when necessary.
- Segments whose frames are dropped before being appended are always reported as `PARTIAL` by the fragment-tracker
- Changed default …

Improve remuxing of non-independent segments and backtracking

---

docs/API.md
src/controller/stream-controller.ts
tests/unit/controller/stream-controller.ts

- Remove pause and nudge on immediate level switch
- Immediate level switch simply aborts current frag and flushed the entire buffer
Prevents hls.js behavior (emergency down switch) and manual quality selection implementations from triggering a "pause". Hls.js may stall as a result when implementing a manual switch with `hls.currentLevel`. This can be addressed by toggling playback rate `video.playbackRate = 0` or pause before setting `hls.currentLevel`, and after the forward buffer is full.
Fixes #3336

Do not pause on immediate switch

---

src/controller/timeline-controller.ts
src/remux/mp4-remuxer.ts
src/utils/webvtt-parser.ts

- Fix WebVTT X-TIMESTAMP-MAP handling 
- handle PTS rollover in VTT cues
WebVTT with timestamp maps were not being parsed correctly. This stream, for example, has three cues:
https://playertest.longtailvideo.com/adaptive/live-webvtt/webvttTest/playlist.m3u8
In Safari, the first cue starts at 4.96s. The cue time calculation in v0.14.x was off because this code mistook the difference between the MPEGTS map time of 0 and the cue local time as a wrapped value when it has nothing to do with that.
```
// Calculate subtitle offset in milliseconds.	
if (Math.abs(syncPTS - (vttCCs[cc].start * 90000 || 0)) > 4294967296) {	
syncPTS += 8589934592;	
}
```
These changes rename the timestamp map variables and handle all calculations in `parser.oncue`. `PTSNormalize` is used on the final cue start time, …

Fix WebVTT X-TIMESTAMP-MAP handling and handle PTS rollover in cues

---

src/controller/audio-stream-controller.ts
src/controller/audio-track-controller.ts
src/controller/stream-controller.ts
src/controller/subtitle-stream-controller.ts
src/controller/subtitle-track-controller.ts
src/demux/transmuxer-interface.ts
src/demux/transmuxer.ts
src/remux/mp4-remuxer.ts
src/remux/passthrough-remuxer.ts
src/types/remuxer.ts

- Fix remuxing of TS segments with audio elementary streams (PID) but no audio samples 
- Do not create empty `initSegment` arrays
- Improve audio and subtitle tracks update and change logging
This line was meant to wait for expected AV samples from the TS demuxer to be present before remuxing when streaming progressively.
```
const canRemuxAvc =
((!hasAudio || enoughAudioSamples) && (!hasVideo || enoughVideoSamples)) || this.ISGenerated;
```
In [this stream](https://playertest.longtailvideo.com/adaptive/eleph-audio/playlist.m3u8), that never happens because while the TS segments describe an audio track in the program map table, there are no audio samples in the TS segments (audio is delivered in AAC tracks). As a result, we are stuck with a remux result containing no context. The player …

Unblock remuxer on flush

---

src/demux/base-audio-demuxer.ts
src/demux/mp4demuxer.ts
src/demux/tsdemuxer.ts
src/remux/mp4-remuxer.ts
src/remux/passthrough-remuxer.ts
src/types/demuxer.ts
src/types/remuxer.ts

- Remux audio-only stream contiguously without dropping samples or inserting silence
- Strongly type demuxer and remuxer track input and output
Fixes support for audio-only playlist with ACC segments containing ID3 "com.apple.streaming.transportStreamTimestamp" that should be ignored:
https://playertest.longtailvideo.com/adaptive/id3/playlist.m3u8

Remux audio-only streams contiguously

---

src/controller/base-stream-controller.ts
src/controller/fragment-tracker.ts
src/controller/stream-controller.ts

Prevent playback from getting stuck when seeking to the start of a segment containing keyframe(s) after the start. 
Seeking to duration - 3 of https://playertest.longtailvideo.com/adaptive/artbeats/manifest.m3u8 reproduces the issue / fails functional tests:
```
should seek 3s from end and receive video ended event for Stream with duplicate sequential PDT values with 2 or less buffered ranges:
Error: Timeout of 40000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. 
```

Backtrack partial segments

---

src/controller/audio-stream-controller.ts
src/controller/stream-controller.ts
src/controller/subtitle-track-controller.ts

1. Improve init buffer codecs logging so that it logs:
- the manifest audio codec even when a different one is selected.
- the manifest CODECS when buffering muxed "audiovideo" segments.
- before BUFFER_CODECS is triggered and buffer-controller logs `"creating sourceBuffer"` message.
2. Tidy up "Swapping audio codec" logs
Closes #3069
Resolves #3068 (TrackSet includes "audiovideo")

Log parsed codec details before BUFFER_CODECS is triggered

---

src/controller/audio-stream-controller.ts
src/controller/buffer-controller.ts
src/controller/buffer-operation-queue.ts

- Fix buffer flush when `media.duration` is `NaN`
- Set `complete` flag on audio-stream-controller `waitingData` to process fragment completely on INIT_PTS
Fixes a case where the audio-stream-controller gets stuck in a `PARSED` state after loading the first audio segment in Safari because `media.duration` is still `NaN` after setting `mediaSource.duration`.
Reproducible by loading fmp4 stream in Safari in v1.0.0-beta.2:
https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s-fmp4/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8

Fix audio track buffering in Safari

---

demo/main.js
demo/style.css
src/controller/abr-controller.ts
src/controller/base-stream-controller.ts
src/loader/m3u8-parser.ts
src/types/level.ts
tests/unit/controller/level-controller.js

Prevent ABR level switching to different codec sets that would break playback.
Improves support for streams with mixed codecs in browsers where MSE supports multiple audio and video codecs.
Example:
Apple's [Advanced stream (HEVC/H.264)](https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_adv_example_hevc/master.m3u8 ) example contains AVC and HEVC video. It also contains AAC, AC-3, and  EC-3 audio. Since we do not yet support [codec changing on source buffers](https://googlechrome.github.io/samples/media/sourcebuffer-changetype.html), appending one type of video or audio after another can cause either an append or media error. This can still occur after a manual switch but should not in auto mode, where experiencing error recovery would disrupt the viewing experience. …

Limit ABR level selection to current codec set

---

src/controller/audio-stream-controller.ts
src/controller/base-stream-controller.ts
src/controller/buffer-controller.ts
src/controller/stream-controller.ts
src/is-supported.ts
src/types/buffer.ts
src/types/events.ts

- Update audio/mpeg SourceBuffer timestampOffset before appending first fragment/part bytes
- Include frag in Level PTS Updated event
- Add `MediaSource.changeType` support
MP3 chunks were being dropped on LEVEL_PTS_UPDATED when it fires before the last segment is completely appended. Also, the expectation was that it fires before any append, but that is no longer the case since bytes are always appended on loading progress (even if there is only one progress event). LEVEL_PTS_UPDATED happens after loading is complete. Including the fragment object in LEVEL_PTS_UPDATED helps make it clearer why the event was fired.
`MediaSource.changeType` support allows for transitions between AAC with and without SBR, as well as audio and video codec changes in the latest version of Chrome and Safari. …

MediaSource.changeType Support and MP3 Buffering Fixed

---

src/demux/base-audio-demuxer.ts
src/demux/mp4demuxer.ts
src/demux/sample-aes.ts
src/demux/transmuxer.ts
src/demux/tsdemuxer.ts
src/types/demuxer.ts

Convert sample-aes.js to typescript, and improve typescript types in tsdemuxer.ts.
`decryptData` in demuxer code was of type `Uint8Array`, which was incorrect - this should have been a LevelKey.  But, LevelKey has a `key` and `iv` which can be null, and all of this code in demuxer will break if these are null.  So, I created a new type `KeyData` which is essentially a limited subset of [`LevelKey`](https://github.com/video-dev/hls.js/blob/master/src/loader/level-key.ts#L3) but where values can't be null, and with only the data that the demuxers need to do their job.  `transmuxer.ts#getEncryptionType()` was already checking to verify that the `key` was set on the LevelKey, but didn't bother to check if `iv` was set (even though we'll crash later when we try to dereference it, if it is not) …

Convert sample-aes.js to typescript. Improve typescript types in tsdemuxer.

---

src/crypt/decrypter.ts
src/demux/sample-aes.ts
src/demux/transmuxer.ts
src/demux/tsdemuxer.ts
src/types/demuxer.ts

- Fixes SAMPLE-AES streaming. Fix developed and tested against sample stream from https://demo.unified-streaming.com/keyrotation/
- MPEG-TS Demuxer PES timestamp TypeScript cleanup; ID3 and MP3 PES with no PTS are dropped. AVC and AVC samples use previous PTS where available.
Follow up from #3384
Fixes a regression introduced in 6836ef3e40ee2ed72553856cc1bd6f35f806bf1d
Adds more type safety to `TSDemuxer`

Fix SAMPLE-AES MPEG-TS streaming

---

src/controller/abr-controller.ts
src/controller/audio-stream-controller.ts
src/controller/base-stream-controller.ts
src/controller/level-controller.ts
src/controller/stream-controller.ts
src/controller/subtitle-stream-controller.ts
src/controller/timeline-controller.ts
src/loader/m3u8-parser.ts
src/types/level.ts
src/utils/codecs.ts
tests/functional/auto/setup.js
tests/unit/controller/level-controller.js

- Allow fragment loading error retries to run before level recovery
- If level recovery fails for all levels, then make the fragment loading error fatal
- Fix the audio stream controller error handler (missing event type and object input parameters)
Fixes a conflict between stream-controller and level-controller fragment loading error handling. Any live stream in auto ABR mode would stall after a single fragment load timeout, waiting for a level update that never comes, and skipping fragment reload logic because of that level change.
To reproduce the issue, I used the following config with a multi variant live stream and throttled network performance after (or before) playback starts:
```js
{
"debug": true,
"enableWorker": false,
"lowLatencyMode": false,
"fragLoadingTimeOut": 1000, …
```

Allow fragment loading error retries to run before level recovery

---

src/controller/timeline-controller.ts
src/utils/cues.ts
src/utils/webvtt-parser.js

fix duplicate 608 lines
On rendition switching the liones may get duplicated
Reuse the hash function when creating the 608/708 VTTCues to assign them a unique id.
Extract the webvtt-parser callback function that adds text track cues and reuse it for adding the 608/708 cues.
Wasn't sure what is the best way to use the hash function - if to leave it in webvtt-aprser and expose or extract it to a seperate vtt utils function and import in both parser and cues modules.
I ended up exposing it from webvtt-parser and adding the id in timeline-controller, but it makes more sense to keep the logic near where VTTCue is created.
Let me know if you want to change this in anyway- open for comments.
In addition, added text field to VTTCue interface.

fix: duplicate 608/708 VTT lines

---

.github/workflows/automerge.yml
.github/workflows/build.yml

Use full commit hashes in the workflows.
GitHub is gong to deprecate using the short hashes.
See: https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions

use full commit hashes in workflows

---

demo/main.js
src/controller/audio-track-controller.ts
src/controller/id3-track-controller.ts
src/controller/subtitle-stream-controller.ts
src/controller/subtitle-track-controller.ts
src/controller/timeline-controller.ts
src/utils/cues.ts
src/utils/imsc1-ttml-parser.ts
src/utils/texttrack-utils.ts
src/utils/webvtt-parser.ts

- Do not append 608/WebVTT/IMSC cues that have already been appended (merges changes from #3321 into master, while maintaining that `config.cueHandler` must append cues to their supplied TextTrack)
- Fix 608 CC continuity when seeking and while its track is disabled
- Clear tracks when levels text group-id changes
- Update group-id on level switch, not just on level loading
- Remove 608 CC cues from the live back buffer
- Exit early after parsing duplicate 608 cues (reduce cue creation on level switch)
- Demo replaces the video element when playing a new source to remove subtitle and captions tracks that cannot be removed (🎻 no `removeTrack` 🎶  )
- Clear demo video event handlers (fixes demo performance/leak)
- Prevents the user from seeing duplicate cues (especially with multi-level …

Cleanup cues and track group switching

---

src/controller/timeline-controller.ts

Fix 608 parsing continuity regression introduced in #3423.
The 608 parsers must be reset when fragment loading continuity ends. This was handled on FRAG_LOADED, but with v1, that event can and mostly does fire before FRAG_PARSING_USERDATA where 608 samples are received. I moved that logic to FRAG_PARSING_USERDATA but didn't realize that event fires twice for each fragment (once per transmuxer push and once again on flush). While I hope to address some of these details prior to v1.0.0 going GA, resetting on FRAG_LOADING gets the job done for now.

Fix 608 parsing continuity

---

src/utils/webvtt-parser.ts

fix duplicate vtt lines for segmented vtt
When vtt file is sliced it sometimes may contain same caption line in both slices of the vtt file as the time range of it is crossing the slicing border.
If the line has a trailing whitespace it will be treated differently if it is in the end of the vtt slice or at the start(or middle) as we trim the entire vtt fragment we get but not the individual time blocks.
Example:
```
Frag1.vtt
WEB VTT
1
00:00:00.360 --> 00:00:01.520 
first line
2
00:00:01.600 --> 00:00:02.680 
second line ending with trailing whitespace 
```
```
Frag2.vtt
WEB VTT
3
00:00:01.600 --> 00:00:02.680 
second line ending with trailing whitespace 
4
00:00:03.400 --> 00:00:04.000
third line
```
In the first fragment we will clip the trailing whitespace cause we do it in …

fix: duplicate segmented vtt lines

---

api-extractor/report/hls.js.api.md
docs/API.md
src/controller/audio-stream-controller.ts
src/controller/base-stream-controller.ts
src/controller/buffer-controller.ts
src/controller/stream-controller.ts
src/demux/tsdemuxer.ts
src/remux/mp4-remuxer.ts
src/types/events.ts
tests/unit/controller/buffer-controller-operations.ts
tests/unit/controller/fragment-tracker.ts

- Only perform one append per segment per MPEG-2 TS elementary stream (in non-progressive mode)
- Normalize buffer append event properties
- Assume audio contiguity in the mp4-remuxer after remuxing has begun
The "progressive" refactor introduced a regression in the number of appends when in non-progressive mode. The transmuxer performs two appends for each elementary stream for each segment (one on loading-progress > push and one on loading-complete > flush). This happens because the ts-demuxer leaves unparsed PES packets until flush.
This change skips the demuxing of TS data on push and processes it all on flush. This removes a performance bottle-neck caused by the additional SourceBuffer blocking, controller state changes, and events all resulting from these additional appends. This …

Perform one append per segment per MPEG-2 TS elementary stream

---

src/demux/tsdemuxer.ts

Fix MPEG-2 TS part loading regression
#3489 introduced a regression in LL-HLS part loading. The tsdemuxer depends on data to be demuxed on push. Moving this to flush prevented all parts except the last from being transmuxed.
While this change means that FRAG_LOADED will be dispatched after parse and append events when the worker is disabled, this is expected in progressive mode and with parts.

Fix MPEG-2 TS part loading regression

---

demo/chart/timeline-chart.ts
demo/main.js
src/controller/audio-stream-controller.ts
src/controller/base-stream-controller.ts
src/controller/latency-controller.ts
src/controller/stream-controller.ts
src/loader/m3u8-parser.ts
tests/functional/auto/setup.js
tests/test-streams.js
tests/unit/controller/audio-track-controller.js
tests/unit/controller/latency-controller.ts

- Set audio-track playlist start position after syncing with main playlist in live streams
(Fixes intermittent playback failure of Live  CMAF streams)
- Fix `getInitialLiveFragment` in scenarios where program-date-time was expected, but missing:
- Do not set `fragPrevious` to the  "initSegment" as a sequence number is expected
- Assign a PDT value to the level `fragmentHint` (the fragment object for LL parts in the playlist that do not yet form a complete segment)
- Fallback to target SN if PDT is missing in live start frag lookup
- Reset start position for live streams when the first fragment request errors or transmuxing finished after the fragment was removed from the sliding window
- Fix demo timeline setup and updates of LL-HLS streams with query params
- Improve live stream start …

Live start robustness with tracks and short sliding windows

---

src/controller/base-stream-controller.ts
src/controller/buffer-controller.ts

- Unblock fragment loading when stream controller cannot leave the PARSED state
- Exit early when flushing the back buffer when source buffers have not been created  
As a follow up to #3504, puts the stream controller back into an IDLE state if it changed to PARSED before source buffers were created, blocking live streams from starting under very constrained conditions
#3473

Workaround stream-controller stuck in PARSED state

---

api-extractor/report/hls.js.api.md
docs/API.md
src/config.ts
src/controller/eme-controller.ts

- Set license `xhr.responseType` and `onreadystatechange` before running ``licenseXhrSetup`
- Document `licenseXhrSetup` config option
- Add `licenseResponseCallback` to eme-controller config options
- Apply hls.js API instance context to eme-controller pre and post processor function calls
These options allow for pre and post-processing of WideVine license requests.
#2016
#3494

DRM license request and response handlers

---

src/controller/base-stream-controller.ts
src/controller/buffer-controller.ts
src/controller/fragment-tracker.ts
src/controller/stream-controller.ts
tests/unit/controller/fragment-tracker.ts

- Prevent new backtracking logic from clearing the buffer at `currentTime`.
- When clearing the forward buffer for `nextLevel` only remove the buffer starting at the end of the upcoming segment we want to replace, this way we don't have to backtrack if the loaded media does not begin with a keyframe but still has one before the end of the segment.
- Only evict part of the forward buffer if there is a gap. The larger gap will allow rebuffering or backtracking to fill the gap.
Clearing the entire buffer up to a non-independent or partial segment (`this.flushMainBuffer(0, frag.start);`) allows the player to backtrack all the way to the first segment with a keyframe, but it can interrupt playback if the play head is in range.

Improve backtracking on level switch and repair gaps

---

src/controller/fragment-tracker.ts

Fix `FRAG_CHANGED` and `LEVEL_SWITCHED` events being skipped and `currentLevel` not changing when playing at the edge of an LL-HLS stream.
App integrations depend on these events to determine the current playback quality among other things.
#3530

Fix LL-HLS FRAG_CHANGED, LEVEL_SWITCHED and currentLevel

---

src/controller/base-stream-controller.ts
src/controller/fragment-finders.ts
src/controller/latency-controller.ts
tests/unit/controller/stream-controller.ts

- Fix a regression that replaced the live start position of `0` with the midway mark of a live playlist
- Made `latencyController.liveSyncPosition` min/max clamping a little easier to read and debug
- Added more `getInitialLiveFragment` unit tests
To start live playback at the correct position.
#3528

Fix live fragment finder logic

---

src/controller/audio-stream-controller.ts
src/controller/base-stream-controller.ts
src/controller/buffer-controller.ts
src/controller/fragment-tracker.ts
src/controller/stream-controller.ts
src/hls.ts
tests/test-streams.js
tests/unit/controller/buffer-controller-operations.ts

- Prevent back-buffer `BUFFER_FLUSHED` callbacks from resetting stream state to `IDLE` while fragments are loading
- Set stream controller state to `IDLE` when the current fragment loading/parsing/appending is aborted or fails (not after it's replaced)
- Evict back-buffer on `FRAG_CHANGED` at target duration intervals making fewer MSE remove requests
- Emit `FRAG_CHANGED` where parts were loaded and fix other methods relying on `getAppendedFrag` for ranges where only parts were buffered (Resolves #3530)
- Only emit `LIVE_BACK_BUFFER_REACHED` in live streams
After uninterrupted playback for longer than 90 seconds (the default back-buffer length) hls.js starts clearing the back-buffer. `onBufferFlushed` stream controller callbacks will reset the loading state and begin fetching a new …

Prevent back-buffer eviction callback from resetting active segment requests 

---

src/controller/level-helper.ts
src/loader/m3u8-parser.ts
src/utils/discontinuities.ts

Fix an issue that causes DISCONTINUITY values to be reassigned incorrectly.
`level.fragmentHint` should only be set on playlists with LL-HLS parts, and should not be used to detect "discontinuity sliding from playlist" in `mergeDetails` on live playlist update, as they could have a different discontinuity sequence number than the matching fragment in the next update. This results in a `ccOffset` that adjusts segments discontinuity sequence numbers incorrectly. We don't want that because then audio and video playlist alignment shifts things around, and it's a bad time for everyone.

Fix issue that causes DISCONTINUITY values to be reassigned incorrectly

---

src/loader/fragment.ts
tests/unit/loader/playlist-loader.js

Fix the parsing of the `INDEPENDENT` attribute to match the spec: https://tools.ietf.org/html/draft-pantos-hls-rfc8216bis-08#section-4.4.4.9
A missing `INDEPENDENT` attribute is incorrectly assigned the value `true`.
No

Fix part INDEPENDENT parsing to match spec

---

src/controller/abr-controller.ts
src/controller/base-stream-controller.ts
src/controller/stream-controller.ts

Perform bitrate test when `bitrateTest` is set in the config.
Frag event changes led to a regression in performing the bitrate test in streams.
Resolves #3582

Fix stream start with `bitrateTest` config option

---

src/controller/level-controller.ts

Filter out audio-only codec signaled stream when others have a resolution but no codecs attribute
hls.js does not support switching between variants with and without audio and video, so it filters out audio-only variants when variants with video and audio are detected. I've encountered streams with CODECS on the audio-only variants, but only RESOLUTION on the ones with video and audio.
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",NAME="English",FORCED=NO,AUTOSELECT=YES,URI="subtitlelist_leng_b174000.m3u8",LANGUAGE="eng"
#EXT-X-STREAM-INF:BANDWIDTH=174000,RESOLUTION=320x180,SUBTITLES="subs"
chunklist_b174000.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=64000,CODECS="mp4a.40.2",SUBTITLES="subs"
chunklist_b64000.m3u8 …
```

Filter out audio-only codec signaled stream when others have a resolution but no codecs attribute

---

docs/API.md
src/hls.ts

- Return NaN with custom abrController that does not have bwEstimator property
- Add note to API docs on supplying a custom estimate
Resolves #3562

Fix `hls.bandwidthEstimate()` with custom `abrController`

---

.github/workflows/automerge.yml

Switch the auto merge action to `pull_request_target` instead of `pull_request`, which is still a trigger when a PR is changed, but the context is set to the base branch and secrets are always provided. The context change doesn't make a difference in our case given we're not checking out or running any code from the PR head commit.
[Triggers from dependabot no longer get the secrets](https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/) meaning the current updates aren't being merged.

switch auto merge to pull_request_target

---

src/controller/base-stream-controller.ts
src/controller/latency-controller.ts

Only resync playback with live streams if the buffer is starved or playback is behind `liveMaxLatencyDuration` or `liveMaxLatencyDurationCount`.
A regression is causing hls.js to seek forwards to the start of the live sliding window on level update whenever playback is behind the sliding start (by more than `maxFragLookUpTolerance`, which is very small). This ignores the `liveMaxLatencyDuration` or `liveMaxLatencyDurationCount` options that should allow playback to fall behind up to that amount, as long as media is buffered.
These changes ensure that whenever playback is outside the sliding window, and the buffer is starved, _or_ playback is behind the configured max latency, the player will resync with the stream.

Live stream sync fixes and imrovements

---

src/controller/fragment-tracker.ts
src/types/fragment-tracker.ts

Only track `activeFragment` and `activeParts` in fragment-tracker for "main" playlist segments. And, only use these in calls to `getAppendedFrag` for the "main" `levelType`.
`getAppendedFrag` is used to determine `hls.currentLevel`. Matching "audio" type fragments or parts resulted in `currentLevel` being returned as `0`.
> 1. Ignores `levelType`
#3602

Fix `currentLevel` and `getAppendedFrag` with alt-audio streams

---

api-extractor/report/hls.js.api.md
demo/chart/timeline-chart.ts
demo/main.js
src/controller/abr-controller.ts
src/controller/audio-stream-controller.ts
src/controller/audio-track-controller.ts
src/controller/base-playlist-controller.ts
src/controller/base-stream-controller.ts
src/controller/buffer-controller.ts
src/controller/cap-level-controller.ts
src/controller/eme-controller.ts
src/controller/fragment-tracker.ts
src/controller/gap-controller.ts
src/controller/latency-controller.ts
src/controller/level-controller.ts
src/controller/stream-controller.ts
src/controller/subtitle-stream-controller.ts
src/controller/subtitle-track-controller.ts
src/controller/timeline-controller.ts
src/crypt/decrypter.ts
src/hls.ts
src/loader/fragment-loader.ts
src/utils/xhr-loader.ts
tests/unit/controller/cap-level-controller.js

Free up references when destroying player to prevent memory leaks and improve GC.
Also made a couple of small optimizations to the Timeline chart on the demo page after observing that it can impact player performance with very active streams (LL-HLS CMAF 0.5s parts). Panning the chart or keeping it running for long periods impacts page performance that hls.js needs to handle requests and MSE appends.
A new player should be created and the previous destroyed for each HLS stream played. The previous player should be completely destroyed and not retain (cyclical) references that the browser cannot garbage collect.
Resolves #2104
Relates to #3605 and possibly #3606

Cleanup hls.destroy()

---

karma.conf.js
package.json
src/controller/level-controller.ts
tests/unit/controller/stream-controller.ts

Ignore out-of-range level indexes as in previous major version.
Also adds a script for running unit tests in debug mode without coverage instrumentation in Chrome.
So that playback starts even with an invalid `startLevel`.
Fixes #3618

Ignore out-of-range level indexes as in previous major version

---

src/controller/audio-stream-controller.ts
src/controller/base-stream-controller.ts
src/controller/stream-controller.ts

Update nextLoadPosition right before loading a fragment or part.
`nextLoadPosition` is set too far ahead when LL-HLS part loading. In most cases, this doesn't matter, but it could potentially lead to skipped parts or gaps in some cases when starting a CMAF stream.

Update nextLoadPosition right before loading a fragment or part

---

MIGRATING.md
api-extractor/report/hls.js.api.md
demo/main.js
docs/API.md
docs/design.md
src/controller/buffer-controller.ts
src/demux/transmuxer-interface.ts
src/demux/transmuxer.ts
src/errors.ts
src/remux/passthrough-remuxer.ts
src/utils/codecs.ts
src/utils/mp4-tools.ts
src/utils/xhr-loader.ts
tests/functional/auto/testbench.js
tests/unit/controller/buffer-controller.js

1. - Fallback to mp4 passthough when probing fails (not mp3 transmux)
2. - Add 'av01' to video codecs lookup table
3. - Parse codec box with TODO
4. - Added fatal `BUFFER_INCOMPATIBLE_CODECS_ERROR` media error when all attempts to add SourceBuffers fail.
And `BUFFER_CREATED` no longer fires right after `BUFFER_ADD_CODEC_ERROR`.
1. Prevents hls.js from treating mp4 segments as audio/mpeg when probing fails.
2. Recognizes AV1 "av01" codec strings as video in manifest CODEC attributes.
3. Took the next step in parsing codecs from fmp4 data. Added better codec defaults for when hls.js only parses"hvc1" or "av01" from an init segment and manifest CODECS are missing.
4. A fatal error should be expected when all attempts to add SourceBuffers fail, and these failures should not trigger …

Improve handling of fmp4 streams when probing fails or codecs are unknown

---

src/loader/playlist-loader.ts
src/utils/xhr-loader.ts

This PR will...
Fix Refused to get unsafe header "age" console error in Chrome
Why is this Pull Request needed?
Resolves issues:
Resolves #3680

Fix Refused to get unsafe header "age" console error in Chrome

---

api-extractor/report/hls.js.api.md
demo/main.js
src/controller/base-playlist-controller.ts
src/controller/latency-controller.ts
src/controller/level-helper.ts
src/loader/level-details.ts

- Calculate drift (live edge advance rate) 
- Display live program date time in demo stats
Live streams do not always update at a steady rate. Drift reveals when a live stream's edge has not advanced as much as time has passed since it first advanced.
Displaying program date time in the demo and its distance from local date-time provides a second latency estimate, as well as get a rough idea of how accurate the stream PDT is.
Viewing drift for a live stream helps to explain why the latency metric may be artificially low or high, do to the rate at which the edge is advancing. At the same time the "seconds ago" PDT value can provide a sense of what time the encoder is assigning to the start of each segment, and how well it aligns with the edge update-based latency estimate.

Calculate Live Drift

---

demo/basic-usage.html

The basic usage example contains a bug in which, if HLS is not supported, the `video` variable will never be initialized. Yet the `else if` branch assumes that `video` contains a reference to the `<video>` element.

Fix uninitialized variable in basic usage example

---

src/controller/buffer-controller.ts
tests/functional/auto/setup.js
tests/functional/auto/testbench.js

Improve end-of-stream handling in Firefox and Safari with multi-track streams
Playback can stall when seeking to the end of streams. This is often why our functional tests fail in Safari and Firefox. These changes help the case where these tests would timeout completely because both 'seeked' and 'ended' events never fire.
HLS.js now calls `mediaSource.endOfStream()` **only once** after both audio and video tracks have appended their final segment, and both SourceBuffers are marked `ended` prevents playback from stalling while seeking to the end. The 'ended' event still may not fire in cases where audio and video are not aligned near the end.
Before, each call to `mediaSource.endOfStream()` triggered a "durationchange" on the video element. This was happening twice, once for each track, …

Improve end-of-stream handling

---

src/demux/adts.ts
src/demux/base-audio-demuxer.ts
src/demux/mpegaudio.ts
src/remux/mp4-remuxer.ts

Fix ADTS `canParse` (last sample), typos, and logging.
Fixes `PIPELINE_ERROR_DECODE` errors in certain streams with acc file segments.

Fix PIPELINE_ERROR_DECODE error streams with AAC segments

---

README.md
api-extractor/report/hls.js.api.md
demo/chart/timeline-chart.ts
demo/main.js
docs/API.md
package.json
src/controller/base-stream-controller.ts
src/controller/buffer-controller.ts
src/controller/stream-controller.ts
src/hls.ts
tests/functional/auto/.eslintrc.js
tests/functional/auto/index-light.html
tests/functional/auto/index.html
tests/functional/auto/setup.js
tests/test-streams.js

- Update README for v1
- Add [`drift`](https://github.com/video-dev/hls.js/pull/3690) to public API
- Include Promise polyfill in functional tests for IE11 and legacy Edge browsers
- Fix IE11 smooth switch stuck in PARSING state
- Fix demo Timeline media buffers in IE11
- Do not allow object-shorthand and remove destructuring in functional test scripts (not supported by IE11)

IE11, README v1, and Functional Test Fixes

---

src/controller/level-controller.js

Fix used `firstLevel` if `hls.startLevel` & `config.startLevel` are not defined
If master playlist not have BANDWIDTH then used `firstLevel`.  At the moment `firstLevel` not defined in constructor so have this error:
`Error while trying to switch to level NaN` 
This problem only in 0.x.x versions in 1.0.0 [already fixed ](https://github.com/video-dev/hls.js/blob/03226bc1c9dcf8f8385b9960afed69f8469b2efe/src/controller/level-controller.ts#L31)
Examples (the playlist opens in the CIS, ues VPN if need): 
0.14.17: https://hls-js-76506a25-92a4-462c-aa38-cc2cd20ce706.netlify.app/demo/?src=https%3A%2F%2Fcdn-volta.wasd.tv%2Flive%2F5774%2Findex-1616129555-5132.m3u8&demoConfig=eyJlbmFibGVTdHJlYW1pbmciOnRydWUsImF1dG9SZWNvdmVyRXJyb3IiOnRydWUsImR1bXBmTVA0IjpmYWxzZSwibGV2ZWxDYXBwaW5nIjotMSwibGltaXRNZXRya …

fix play without BANDWIDTH in master playlist

---

api-extractor/report/hls.js.api.md
src/loader/playlist-loader.ts
src/types/loader.ts
src/utils/fetch-loader.ts
src/utils/xhr-loader.ts
tests/unit/loader/fragment-loader.ts

Loader has a function called getResponseHeader() (added in 1.0.0), which returns the value of a response header. It's used to find the "age" header to see if a request has been in a proxy for a while, when playing live.
But, this API is way too broad - first it assumes the underlying transport is HTTP based. If the underlying transport is something else, like WebRTC or websocket, what should getResponseHeader() return? Or, in my case, I have a caching loader which caches playlists locally, and my HTTP headers are long gone (and if I wanted to save them explicitly for the loader, it wouldn't even be useful, because the "age" header would be out of date by the time my loader fetches them).
You could argue it should just return undefined for WebRTC and websocket, and maybe in my local cache …

fix: Replace Loader.getResponseHeader() with Loader.getCacheAge().

---

api-extractor/report/hls.js.api.md
package-lock.json
src/types/loader.ts
src/utils/fetch-loader.ts
src/utils/xhr-loader.ts
tests/unit/loader/fragment-loader.ts

(This is the non-breaking part of https://github.com/video-dev/hls.js/pull/3707).
The `Loader` interface has a property named `loader` of type `any`.  This property is not read by any hls.js code.  The two implementations of loader (xhr-loader and fetch-loader) set this to an XMLHttpRequest and a fetch Response, respectively.
I'm writing a loader that loads data from a local cache - I don't even have an HTTP request involved in my loader, so I have nothing to put here.  But, since no one reads from it anyways, easiest just to remove it, and then I don't have to set it to `undefined`.  The existing `MockXhr` loader is an example of a loader, used in fragment loading tests, is another example of a loader that never defines this.
I'm not sure why this property was here in the first place - …

fix(types): Remove unused Loader.loader property.

---

src/hls.ts
tests/unit/hls.js

This is a super minor fix.  I was getting the very unhelpful error: `TypeError: Cannot read property 'forEach' of null`.  It turns out I was calling `stopLoad()` after calling `destroy()`, and was running into:
```ts
this.networkControllers.forEach(...
```
but `this.networkControllers` had been set to `null` in the `destroy()` function.
So this change:
* Makes it so `networkControllers` is defined as an array or undefined.
* Handles the case where you call `stopLoad()` when `networkControllers` is undefined (this is a no-op now).
* Throws a slightly more user friendly "Cannot call `startLoad()` on destroyed instance of hls" when you call `startLoad()` after calling `destroy()`.
No
None.

fix: stopLoad() after destroy() becomes no-op, startLoad() after destroy() throws nicer error message.

---

api-extractor/report/hls.js.api.md
demo/chart/timeline-chart.ts
src/controller/audio-track-controller.ts
src/controller/subtitle-track-controller.ts
src/types/events.ts
tests/unit/controller/subtitle-track-controller.js

- Use track name over track index, fixes unordered track group switching
- Adds 'name' property to audio and subtitle track switching events
- Sets `selectDefaultTrack` to `false` so that track name matching works when indexes are not aligned / there's a default track and no manual track selection to disable first
Fixes an exception when switching levels that use audio groups with inconsistent track order (and a default track) 
Resolves #3729

Use track name over track index, fixes unordered track group switching

---

demo/chart/timeline-chart.ts
src/controller/base-stream-controller.ts
src/controller/stream-controller.ts
tests/unit/controller/stream-controller.ts

1. Honor `config.startPosition` and `hls.startLoad(startPosition)` with live streams
2. Do not sync with the live edge when playback is within sliding window and `liveMaxLatencyDuration` or `liveMaxLatencyDurationCount`
1. `startPosition` was ignored when selecting the first fragment to load in a live stream so that we could use `getInitialLiveFragment`. This is in part because we could not tell if `startPosition` was specified by the user or set internally. By not setting it internally until after `getInitialLiveFragment` for default behavior when not set, we can honor the user's intent when it is.
2. Fixes a regression where `synchronizeToLiveEdge` would seek to the live sync position when underbuffered (on start) even though playback was within an acceptable range.
Fixes #3736

Honor startPosition from config/startLoad with live streams

---

api-extractor/report/hls.js.api.md
src/controller/audio-stream-controller.ts
src/controller/audio-track-controller.ts
src/controller/base-stream-controller.ts
src/controller/stream-controller.ts
src/controller/subtitle-stream-controller.ts
src/controller/subtitle-track-controller.ts
src/types/events.ts
tests/unit/controller/subtitle-track-controller.js

- Reset transmuxer on audio-tracks-updated to handle audio group track switching
- Added `groupId` to `AudioTrackSwitchingData` and `SubtitleTrackSwitchData` (just added `name` recently and in light of this issue, `groupId` is also something you'd want to know about an upcoming track change)
The transmuxer doesn't see audio groups so tracks in different groups with the same index appear as contiguous segments. Resetting the transmuxer on audio track update deals with this type of discontinuity resetting where audio is appended when the active group is changed.
https://github.com/video-dev/hls.js/blob/072ef4b15e011d5194dbc7e7ad8782dd88ffd0b5/src/demux/transmuxer-interface.ts#L159-L163
I considered adding groupId or original track id indexes (across groups) to the transmux pipeline but that …

Fix fmp4 segmented audio group switching

---

src/loader/m3u8-parser.ts
tests/unit/loader/playlist-loader.js

Use the parse in `UrlToolkit` to extract just the path and use that for checking for the '.mp4' extension.
Currently if there's a query string the check fails.
fixes https://github.com/video-dev/hls.js/issues/3756

ignore query when checking for mp4 url extension

---

src/controller/buffer-controller.ts
src/hls.ts

Do not detach and reattach media in `loadSource` when in an hls.js event loop. 
When `loadSource` is called, only detach and reattach media if URL has changed, and source buffer types are set.
Prevents recursive calls when `loadSource` is called in an event handler such as `MEDIA_ATTACHED`, or any prior to `BUFFER_CODECS`. This is where the `BufferController`'s `SourceBuffer` configuration is set. Loading a new stream prior to that can be performed without reattaching. After that, reattaching is necessary to reset the source buffers.
Resolves #3732

Fix MEDIA_ATTACHED > `loadSource` recursive calls

---

src/utils/xhr-loader.ts

Use RegEx to match "age" header in `XMLHttpRequest.getAllResponseHeaders()`, skipping the CDN Tune-In "age" header check in live streams with no "age" in the playlist response header.
Fixes regression introduced in #3685 in response to #3680 that turns up the `Refused to get unsafe header "age"'` errors "to 11".
The solution that used `getAllResponseHeaders().indexOf('age')` matched the word "age" anywhere in the headers as in "max-age" as part of:
```
cache-control: max-age=2
content-length: 283
content-type: application/vnd.apple.mpegurl
date: Mon, 12 Apr 2021 20:39:28 GMT
expires: Mon, 12 Apr 2021 20:39:30 GMT
last-modified: Mon, 12 Apr 2021 20:39:28 GMT
```
Resolves #3680

Fix "age" header check in XHR loader

---

src/controller/audio-stream-controller.ts
src/controller/base-stream-controller.ts
src/controller/stream-controller.ts

Reset stream controller ENDED state after flushing the buffer
Resumes streaming after level or track switch after the last segment has been appended

Reset stream controller ENDED state after flushing the buffer

---

src/controller/stream-controller.ts

Reset stream controller ENDED state after flushing the buffer for main audio-only streams
The fix in #3774 did not cover audio-only streams handled by the stream-controller. That change only reset the loading state in stream-controller after removing media from the video source buffer.
Completes #3774

Reset stream controller ENDED state pt.2

---

src/controller/audio-track-controller.ts
tests/unit/controller/audio-track-controller.ts

Fix alt-audio switching to track after the track has been loaded.
Fixes a change (https://github.com/video-dev/hls.js/pull/3731/files#diff-fce83d85205f6441ddd410c5aca54bf4215dcbe6c16b6184af98ae438f930626R175-R176) that prevents switching to audio-tracks that have already been loaded.
Bug introduces in dev after merging #3731 (this issue is not present in v1.0.0)

Fix switching to track after track has been loaded

---

src/controller/subtitle-track-controller.ts

Ensure that the default track is selected after playback.
Subtitle groups were not respected prior to v1, and now that they are, there was just this tiny gap in the implementation.
By moving when the tracks in the group are populated, the functions work as intended, selecting the default track.
Impact analysis on the change.
Closes #3780

bugfix: DEFAULT=YES on caption tracks was not being respected.

---

src/controller/audio-stream-controller.ts
src/controller/base-stream-controller.ts
src/controller/stream-controller.ts
tests/test-streams.js

Fix a regression in AES key loading that causes the main and audio stream controllers to load each others' fragments on KEY_LOADED.
Prior to v1.0, `onKeyLoaded` would set the stream controllers' state to IDLE (even if it was the other controller/level/track fragment's key that was loaded), but this wasn't a show stopper (at worst I guess it would result in keys being requested more than once).
In v1.0 the fragment is requested as soon as the key is loaded and parsed, rather than waiting for the next tick. This was done in an effort to improve the performance of AES streams. Our test samples do not include an encrypted stream with separate tracks like the one found in #3772 so this one slipped through.
Fixes #3772

Fix AES-128 in streams with alt-audio tracks

---

src/controller/base-playlist-controller.ts

- Request LL-HLS playlists with the `_HLS_part` param set to `0` and `_HLS_msn` incremented when the last sn matches the segment of the last part.
- Fix blocking playlist requests with `lowLatencyMode` set to `false`.
The current implementation always requests the last part index + 1, which depends on servers responding with part 0 for `_HLS_msn + 1`. This also results in additional caching on the edge. By detecting the last part and last segment match we can send the correct indexes resolving #3571 and #3771.
For blocking playlist requests when `lowLatencyMode` is set to `false`, the playlist will be refreshed for each part until the last part index is found, and then `_HLS_msn + 1` with the same `_HLS_part` (last part index) will be requested one PART-TARGET (or 1 second) ahead of the …

Request LL-HLS playlists with _HLS_part param starting at 0 for next sn

---

src/types/level.ts

- Set the ```SearchParams``` directly on ```URL``` instead of  set to ```url.search```.
- Remove sort ```SearChParams```.
Through set ```url.search``` to add SearchParams that will cause the url isn't equal origin url even if doesn't have any parameter set to. I think the ```url.toString()``` will do encode and server side check the url by string type not equal origin url, so response 403 forbidden. 
Please help to check my thoughts correctly.
https://github.com/video-dev/hls.js/issues/3786

Direct set SearchParams on URL and remove sort.

---

src/controller/base-playlist-controller.ts

Fix blocking playlist requests with `lowLatencyMode` set to `false`.
For blocking playlist requests when `lowLatencyMode` is set to `false`, the playlist will be refreshed for each part until the last part index is found, and then `_HLS_msn + 1` with the same `_HLS_part` (last part index) will be requested one PART-TARGET (or 1 second) ahead of the expected TARGETDURATION refresh time. This will make a blocking request for the next segment update without making it so early that it fails.
Resolves #3566

Fix blocking playlist requests with `lowLatencyMode` is set to `false`

---

src/controller/fps-controller.ts

Fix a regression introduced in #3072 that changed the fps-controller 's repeating interval to a timer that only fires once.
So that fps-controller's `checkFPS` is called continuously when `config.capLevelOnFPSDrop` is set to `true`.
Fixes #3790

Fix setInterval/Timer regression in fps-controller

---

src/controller/audio-stream-controller.ts
src/controller/base-stream-controller.ts
src/controller/fragment-tracker.ts
src/controller/stream-controller.ts

Evict unbuffered audio and main fragments from the tracker on `BUFFER_FLUSHED`.
Fixes intermittent (mostly Firefox) audio-buffer stall with frequent audio group switching.
Resolves #3770

Fix audio-buffer stall with frequent audio group switching

---

src/utils/fetch-loader.ts

Fix fetch loader stats marked as aborted after loaded
Loader instances are destroyed after each use. The fetch loader was flipping on an `aborted` flag when destroyed even when complete.
Fixes #3789

Fix fetch loader stats marked as aborted after loaded

---

demo/chart/timeline-chart.ts
demo/index.html
package-lock.json
package.json

Replace the Timeline Chart.js zoom plugin with more performant implementation.
'chartjs-plugin-zoom'  added wheel listeners on every update. The panning hander also forced updates on every mousemove event hogging cycles needed by hls.js on the main event loop to handle network and worker messages.
The custom pointer listeners updating pan and zoom setting while only rendering chart updates on animation frame. Gesture events handle pinch-zoom on iPad.
Pinch-zoom does not work on Android, and pointer events are canceled after panning one pointer move event. This isn't any worse than 'chartjs-plugin-zoom' but could be better if the timeline is supposed to be more usable on Android.

Demo Timeline optimizations
